### PR TITLE
startDevWorker Milestone 1 - Reboot

### LINKED ISSUE #4165: 🐛 BUG: `wrangler dev --remote` no longer logs?
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.13.0

### What version of Node are you using?

18

### What operating system are you using?

Mac

### Describe the Bug

I cloned https://github.com/joshthoward/d1-tutorial/tree/main

Updated to wrangler 3.13.0, and now logs don't show up in the console when running `wrangler dev --remote`

Instead I see:
```
[wrangler:inf] GET /cdn-cgi/ProxyWorker/pause 204 No Content (3ms)
[wrangler:inf] GET /cdn-cgi/ProxyWorker/pause 204 No Content (0ms)
[wrangler:inf] GET /cdn-cgi/ProxyWorker/pause 204 No Content (1ms)
Total Upload: 3.03 KiB / gzip: 1.13 KiB
[wrangler:inf] GET /cdn-cgi/ProxyWorker/play 204 No Content (0ms)
✘ [ERROR] {

    message: 'Uncaught TypeError: Failed to establish the WebSocket connection: expected server to
  reply with HTTP status code 101 (switching protocols), but received 404 instead.',
    cause: {}
  }


[wrangler:inf] GET /cdn-cgi/ProxyWorker/pause 204 No Content (0ms)
```

### Please provide a link to a minimal reproduction

https://github.com/joshthoward/d1-tutorial/tree/main

### Please provide any relevant error logs

_No response_

### LINKED ISSUE #4168: 🐛 BUG: ProxyWorker request logs
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.13.0

### What version of Node are you using?

18.18.0

### What operating system are you using?

Windows 10

### Describe the Bug

With wrangler 3.13.0, I'm now seeing the following in my logs regularly when developing:
```
[wrangler:inf] GET /cdn-cgi/ProxyWorker/pause 204 No Content (0ms)
[wrangler:inf] GET /cdn-cgi/ProxyWorker/pause 204 No Content (12ms)
[wrangler:inf] GET /cdn-cgi/ProxyWorker/pause 204 No Content (1ms)
[wrangler:inf] GET /cdn-cgi/ProxyWorker/play 204 No Content (1ms)
```

Is this intended? Should these be debug logs instead? These logs do not appear in 3.12.0 or prior.

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by RamIdeas**
**What this PR solves / how to test:**

This PR is for all changes made since Milestone 1 was first merged in #3960

Notable commits:
- bedbe4eb fix: don't show logs to ProxyWorker(s) unless log level is debug
  - fixes #4168 
- 76f90edf fix: show console.log's in remote mode remote inspector websocket upgrade request required auth headers so use `fetch` with `Upgrade: websocket` header instead of `new WebSocket`
  - fixes #4165 
- 1271a1ae use miniflare verbose mode only if debug log level
  - should reduce "scary logs" noise
- 7198a81b register ProxyWorker with DevRegistry instead of UserWorker
- f09c51dc Revert "register ProxyWorker with DevRegistry"
  - this commit has been applied+reverted and will be reapplied in Milestone 2 due to its dependence on the new `bindings` shape
  - it is an optimisation for the devregistry and functionally behaves the same
- 1a9e2f54 use single Miniflare instance for (Inspector)ProxyWorker
  - fixes [DEVX-929](https://jira.cfdata.org/browse/DEVX-929)
- 997d77db port: clear remote runtime logs upon UserWorker restarts
  - this forward-ports [this change](https://github.com/cloudflare/workers-sdk/pull/4235)
- 6129d965 default unstable_dev inspectorPort to 0
  - this is a more sane default for unstable_dev which is used most in test suites and therefore most likely run in parallel
- 7ac5efd7 parallelise cleanup to minimise chance of hanging
  - previously, sequential cleanups fail to fully cleanup if earlier steps in the sequence fail
- 974216e2 ensure InspectorProxyWorker unsafeDirectPort is set
  - `undefined` disables the inspector – we should implement a separate option to explicitly enable/disable the inspector in Miniflare
- 001c542d don't use file-system for (Inspector)ProxyWorker DOs
  - the DOs don't use storage so we can tell Miniflare to not bother setting up the tmp dirs
- 3fea2685 prevent eviction of the Durable Objects with (Inspector)ProxyWorker
  - Durable Object eviction was implemented and shipped during this work which caused the in-memory state to disappear across requests (interferring with pause/play control messages) – since these DOs are for local development, we can disable eviction entirely
- 183db24c ready event should await proxyWorker.setOptions
  - workaround for miniflare bug
- 7f768e6d remove miniflare workaround for parallel requests
  - removes a previous workaround
- f72497e6 considerations for race between control messages and user fetches
  - this guarantees the order of requests for control messages and `worker.fetch` requests which are more likely to run into a race condition over the async http boundary than eye-ball requests
- 0845c9df use port: undefined vs 0 for UserWorker to force different port across reloads to workaround workerd bug on Windows
  - this is a workaround for https://github.com/cloudflare/workerd/issues/1376
- 217d8ba5 Don't try to parse node internals
  - this fixes an issue with devtools not working introduced by https://github.com/cloudflare/workerd/pull/1294
- a49cc8a0 only proxy consoleAPICalled events in remote mode
- a1d5afa2 enable consoleAPICalled events proxying if local mode AND service-worker format
  - these 2 commits account for workerd now printing console.log's itself since https://github.com/cloudflare/workerd/pull/1294

**Author has addressed the following:**

- Tests
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] Included
  - [ ] Not necessary because:
- Associated docs
  - [x] Issue(s)/PR(s): linked above
  - [ ] Not necessary because:

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

File: packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts [hunk 1]
```diff
@@ -125,6 +134,37 @@ export class InspectorProxyWorker implements DurableObject {
...
+
+		const message: InspectorProxyWorkerIncomingWebSocketMessage = JSON.parse(
+			event.data
+		);
+
+		this.sendDebugLog("handleProxyControllerIncomingMessage", event.data);
+
+		switch (message.type) {
+			case "reloadStart": {
+				this.sendRuntimeDiscardConsoleEntries();
```
Comment (mrbbot) [inline packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts:151]: Does this get triggered on the initial worker load? I'm assuming it does, in which case this would hide startup logs in remote mode when starting `wrangler dev`, regressing on #4235?

File: packages/wrangler/src/dev/dev.tsx [hunk 2]
```diff
@@ -277,6 +277,10 @@ function DevSession(props: DevSessionProps) {
 				inspector: {
 					port: props.inspectorPort,
 				},
+				urlOverrides: {
+					secure: props.localProtocol === "https",
+					hostname: props.localUpstream,
```
Comment (mrbbot) [inline packages/wrangler/src/dev/dev.tsx:282]: Looks like you're missing `props.localUpstream` from this hook's deps array.

File: packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts [hunk 3]
```diff
@@ -212,47 +259,48 @@ export class InspectorProxyWorker implements DurableObject {
...
-
-				break;
-			}
-			default: {
-				assertNever(message.type);
-			}
-		}
-	};
-
+	runtimeAbortController = new AbortController();
```
Comment (mrbbot) [inline packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts:262]: A comment explaining what aborting this controller does would be nice.

File: packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts [hunk 4]
```diff
@@ -212,47 +259,48 @@ export class InspectorProxyWorker implements DurableObject {
...
 	runtimeKeepAliveInterval: number | null = null;
-	reconnectRuntimeWebSocket() {
+	async reconnectRuntimeWebSocket() {
 		assert(this.proxyData, "Expected this.proxyData to be defined");
 
 		this.sendDebugLog("reconnectRuntimeWebSocket");
 
+		this.runtimeAbortController.abort();
+		this.runtimeAbortController = new AbortController();
 		this.websockets.runtimeDeferred = createDeferred<WebSocket>(
```
Comment (mrbbot) [inline packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts:271]: Should we be closing the old runtime WebSocket here, or are we assuming it's already closed at this point/will be closed by `workerd` when we reconnect?

File: packages/wrangler/templates/startDevWorker/ProxyWorker.ts [hunk 5]
```diff
@@ -101,25 +101,17 @@ export class ProxyWorker implements DurableObject {
...
-			if (
-				proxyData.userWorkerInnerUrlOverrides &&
-				proxyData.userWorkerInnerUrlOverrides.port === undefined
-			) {
-				// if userWorkerInnerUrlOverrides is set but port is not, remove port from innerUrl
-				// eg. if userWorkerInnerUrlOverrides is { hostname: 'example.com' }, then innerUrl will be http://example.com/... not http://example.com:8787/...
-				innerUrl.port = "";
-			}
 			headers.set("MF-Original-URL", innerUrl.href);
+			headers.set("MF-Disable-Pretty-Error", "true");
```
Comment (mrbbot) [inline packages/wrangler/templates/startDevWorker/ProxyWorker.ts:114]: I'd add a comment here explaining this isn't actually disabling the pretty error page for users, since we're running in Miniflare here, the proxy Miniflare instance will prettify errors.

File: packages/wrangler/src/api/startDevWorker/ProxyController.ts [hunk 6]
```diff
@@ -204,18 +188,27 @@ export class ProxyController extends EventEmitter {
...
 		} catch (cause) {
 			if (this._torndown) return;
 
 			const error = castErrorCause(cause);
 
 			this.inspectorProxyWorkerWebSocket?.reject(error);
-			this.emitErrorEvent("Could not connect to InspectorProxyWorker", error);
+			this.emitErrorEvent(
+				"Could not connect to InspectorProxyWorker " +
+					JSON.stringify({ webSocket, readyState: webSocket?.readyState }),
```
[the remark this answers is not in the document]
Comment (RamIdeas) [reply packages/wrangler/src/api/startDevWorker/ProxyController.ts:209]: This was a local-only debugging thing – should've removed it

File: packages/wrangler/src/api/startDevWorker/ProxyController.ts [hunk 7]
```diff
@@ -283,14 +283,14 @@ export class ProxyController extends EventEmitter {
...
+			let websocket = await this.inspectorProxyWorkerWebSocket?.promise;
 			assert(websocket);
 
 			if (websocket.readyState >= WebSocket.READY_STATE_CLOSING) {
-				await this.reconnectInspectorProxyWorker();
+				websocket = await this.reconnectInspectorProxyWorker();
 			}
 
-			websocket.send(JSON.stringify(message));
+			websocket?.send(JSON.stringify(message));
```
[the remark this answers is not in the document]
Comment (RamIdeas) [reply packages/wrangler/src/api/startDevWorker/ProxyController.ts:293]: It also reset in the if statement to a possibly undefined. In fact, I can reconnect no matter what and assert after that

File: packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts (hunk 4 above)
Comment (RamIdeas) [reply packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts:271]: Assuming it will be closed when the runtime is terminated

File: packages/wrangler/src/dev/local.tsx [hunk 8]
```diff
@@ -174,9 +174,13 @@ function useLocalWorker(props: LocalProps) {
 					userWorkerInnerUrlOverrides: {
 						protocol: props.localProtocol,
 						hostname: props.localUpstream,
+						port: props.localUpstream ? "" : undefined, // `localUpstream` was essentially `host`, not `hostname`, so if it was set delete the `port`
```
Comment (penalosa) [inline packages/wrangler/src/dev/local.tsx:177]: What does an empty string mean for a port?

File: packages/wrangler/src/dev/start-server.ts [hunk 9]
```diff
@@ -413,9 +410,13 @@ export async function startLocalServer(
 				userWorkerInnerUrlOverrides: {
 					protocol: props.localProtocol,
 					hostname: props.localUpstream,
+					port: props.localUpstream ? "" : undefined, // `localUpstream` was essentially `host`, not `hostname`, so if it was set delete the `port`
```
Comment (penalosa) [inline packages/wrangler/src/dev/start-server.ts:413]: As above

File: packages/wrangler/src/dev/local.tsx (hunk 8 above)
Comment (RamIdeas) [reply packages/wrangler/src/dev/local.tsx:177]:
```ts
url = new URL('http://localhost:8787');
console.log(url); // http://localhost:8787
url.port = "";
console.log(url); // http://localhost
```

File: fixtures/worker-ts/src/index.ts [hunk 10]
```diff
@@ -29,6 +29,6 @@ export default {
 	): Promise<Response> {
 		const url = new URL(request.url);
 		if (url.pathname === "/error") throw new Error("Hello Error");
-		return new Response("Hello World!");
+		return new Response("Hi9 World!");
```
[the remark this answers is not in the document]
Comment (RamIdeas) [reply fixtures/worker-ts/src/index.ts:32]: Nope lol

File: packages/wrangler/src/api/startDevWorker/ProxyController.ts [hunk 11]
```diff
@@ -60,135 +57,122 @@ export class ProxyController extends EventEmitter {
...
+				.then(() => {
+					this.emitReadyEvent(proxyWorker);
+				})
+				.catch((error) => {
+					this.emitErrorEvent(
+						"Failed to start ProxyWorker or InspectorProxyWorker",
+						error
+					);
+				});
+		}
```
[the remark this answers is not in the document]
Comment (RamIdeas) [reply packages/wrangler/src/api/startDevWorker/ProxyController.ts:175]: Nope ready event only need to be fired when the promise resolves which is exactly what this if-block guards

File: packages/wrangler/src/api/dev.ts [hunk 12]
```diff
@@ -169,7 +169,7 @@ export async function unstable_dev(
 		compatibilityDate: options?.compatibilityDate,
 		compatibilityFlags: options?.compatibilityFlags,
 		ip: options?.ip,
-		inspectorPort: options?.inspectorPort,
+		inspectorPort: options?.inspectorPort ?? 0,
```
Comment (1000hz) [inline packages/wrangler/src/api/dev.ts:172]: would it make sense to have this fallback to the default inspector port of `9222`?

**Review by 1000hz — APPROVED** [review]

File: packages/wrangler/src/api/dev.ts (hunk 12 above)
Comment (RamIdeas) [reply packages/wrangler/src/api/dev.ts:172]: No the CLI can makes those decisions for the default value but the default in the general case should be 0 (random port)

File: packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts (hunk 1 above)
Comment (mrbbot) [reply packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts:151]: Wouldn't `sendRuntimeDiscardConsoleEntries()` call `sendRuntimeMessage()` which `await`s the runtime `WebSocket` promise before sending the message?

https://github.com/cloudflare/workers-sdk/blob/78c0b2280b1e2fc15551f4436ed072fd95e130da/packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts#L393

Essentially, would calling this method here queue a message to be sent to the runtime as soon as we'd connected the WebSocket which then cleared logs?

File: fixtures/worker-ts/src/index.ts [hunk 13]
```diff
@@ -29,6 +29,6 @@ export default {
 	): Promise<Response> {
 		const url = new URL(request.url);
 		if (url.pathname === "/error") throw new Error("Hello Error");
-		return new Response("Hello World!");
+		return new Response("Hello World 3!");
```
Comment (mrbbot) [inline fixtures/worker-ts/src/index.ts:32]: Guessing this was introduced during manual testing?
```suggestion
		return new Response("Hello World!");
```

File: packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts (hunk 1 above)
Comment (RamIdeas) [reply packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts:151]: Good point! Let me have a think

Comment (RamIdeas) [reply packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts:151]: Thinking we can call `sendRuntimeMessage()` (within `sendRuntimeDiscardConsoleEntries()`) with the websocket in the 2nd param, not the websocket promise, but also need to account for undefined triggering the default value (websocket promise)

File: packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts (hunk 4 above)
Comment (RamIdeas) [reply packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts:271]: In fact, it was being closed further down after the next connection had been established. I'm mentioning it here because, to address your other comment, I am changing it to close here as you suggested in this comment

File: packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts (hunk 1 above)
Comment (RamIdeas) [reply packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts:151]: Fixed in https://github.com/cloudflare/workers-sdk/pull/4413/commits/7506c8f7b30e749fe54f59f064c573647f381d84

**Review by mrbbot — APPROVED** [review]
