### PR TITLE
[wrangler] fix: ensure dev server doesn't change request URLs

### LINKED ISSUE #4743: 🐛 BUG: 3.19.0 changed URL normalization
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

- affected versions: 3.19.0 - 3.22.4
- last working version: 3.18.0

### What version of Node are you using?

20.9.0

### What operating system are you using?

WSL Ubuntu 22.04.3 LTS

### Describe the Bug

Version 3.19.0  changed the  URL normalization (changing double slashes to the single slash) of the `request.url` string which is a BREAKING CHANGE.

Visiting `http://localhost:8787//test`:

 - v3.19.0: `http://localhost:8787/test`
 - v3.18.0: `http://localhost:8787//test`

Created simple "Hello world" app using `npx create-cloudflare@2.9.0`:

`wrangler.toml`:
```toml
name = "super-dew-c60b"
main = "src/index.js"
compatibility_date = "2023-07-17"
```

`src/index.js`:
```js
export default {
	async fetch(request) {
		return new Response(request.url);
	},
};
```

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by mrbbot**
Fixes #4743.

**What this PR solves / how to test:**

This PR ensures URLs aren't modified when requests pass through Wrangler's proxy server. Specifically, it ensures this `DurableObjectStub#fetch()`...

https://github.com/cloudflare/workers-sdk/blob/54ea6a53bd1f222308135ed96bbb16a019302382/packages/wrangler/templates/startDevWorker/ProxyWorker.ts#L31

...preserves the URL, by enabling the `durable_object_fetch_requires_full_url` compatibility flag in the proxy workers. This flag disables `workerd`'s legacy behaviour of resolving this URL relative to `http://fake-host` and leaves the URL untouched. To test this, run `wrangler dev` against a worker that logs its incoming URL, e.g.

```js
export default {
  async fetch(request, env, ctx) {
    console.log(request.url);
    return new Response("body");
  }
}
```

...then run `curl http://localhost:8787//test`. You should see `http://localhost:8787//test` in the `wrangler dev` session's output, including the `//`.

**Author has addressed the following:**

- Tests
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [x] Not necessary because: fixing a regression

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

File: packages/wrangler/src/api/startDevWorker/ProxyController.ts [hunk 1]
```diff
@@ -67,8 +76,7 @@ export class ProxyController extends EventEmitter {
 			workers: [
 				{
 					name: "ProxyWorker",
-					// `url_standard` required to parse IPv6 hostnames correctly
-					compatibilityFlags: ["nodejs_compat", "url_standard"],
+					compatibilityFlags,
```
Comment (penalosa) [inline packages/wrangler/src/api/startDevWorker/ProxyController.ts:79]: Why does this worker have an old compatibility date? Would it be possible to update it to a more recent compatibility date and avoid the need for some of these flags?

File: fixtures/worker-app/tests/index.test.ts [hunk 2]
```diff
@@ -76,4 +76,13 @@ describe("'wrangler dev' correctly renders pages", () => {
 		const text = await response.text();
 		expect(text).toMatch(/[0-9a-f]{16}/); // 8 hex bytes
 	});
+
+	it("passes through URL unchanged", async ({ expect }) => {
+		const url = `http://${ip}:${port}//thing`;
```
Comment (penalosa) [inline fixtures/worker-app/tests/index.test.ts:81]: It wasn't a problem in the linked issue, but it might be worth adding a query string and a fragment here, just in case

File: packages/wrangler/src/api/startDevWorker/ProxyController.ts (hunk 1 above)
Comment (mrbbot) [reply packages/wrangler/src/api/startDevWorker/ProxyController.ts]: aabf927

File: fixtures/worker-app/tests/index.test.ts (hunk 2 above)
Comment (mrbbot) [reply fixtures/worker-app/tests/index.test.ts]: 4752878, fragments aren't preserved here, so just added a query string.

File: packages/wrangler/src/api/startDevWorker/ProxyController.ts [hunk 3]
```diff
@@ -67,8 +67,8 @@ export class ProxyController extends EventEmitter {
 			workers: [
 				{
 					name: "ProxyWorker",
-					// `url_standard` required to parse IPv6 hostnames correctly
-					compatibilityFlags: ["nodejs_compat", "url_standard"],
+					compatibilityDate: "2023-12-18",
```
Comment (RamIdeas) [inline packages/wrangler/src/api/startDevWorker/ProxyController.ts:70]: 🤦

**Review by RamIdeas — APPROVED** [review]

File: packages/wrangler/src/api/startDevWorker/ProxyController.ts [hunk 4]
```diff
@@ -67,8 +67,8 @@ export class ProxyController extends EventEmitter {
 			workers: [
 				{
 					name: "ProxyWorker",
-					// `url_standard` required to parse IPv6 hostnames correctly
```
Comment (petebacondarwin) [inline packages/wrangler/src/api/startDevWorker/ProxyController.ts:70]: Without this do we still work with IPv6 hostnames?

Comment (mrbbot) [reply packages/wrangler/src/api/startDevWorker/ProxyController.ts:70]: Yep, the default-on date for [`url_standard` is `2022-10-31`](https://developers.cloudflare.com/workers/configuration/compatibility-dates/#new-url-parser-implementation). Given `2023-12-18` is after that, the flag will still be enabled. 👍

Comment (petebacondarwin) [reply packages/wrangler/src/api/startDevWorker/ProxyController.ts:70]: Oh right. So the fix is actually adding a compatibility date, not ther removal of the compatibility flag?

Comment (mrbbot) [reply packages/wrangler/src/api/startDevWorker/ProxyController.ts:70]: Yep! 🙂
