### PR TITLE
[vitest-pool-workers] Support `@voidzero-dev/vite-plus-test` as vitest alternative

### LINKED ISSUE #13001: Support vite plus for `@cloudflare/vitest-pool-workers`
### Describe the solution

@cloudflare/vitest-pool-workers bundles vitest/worker in order to run the Vitest runner inside workerd, but @voidzero-dev/vite-plus-test does not expose that subpath, so at runtime it fails with No such module "vitest/worker".`

> Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
Error: [vitest-pool]: Failed to start cloudflare-pool worker for test files /Users/yoshikawatakumi/dev/amitoco/apps/api/src/index.test.ts.
 ❯ ../../node_modules/.pnpm/@voidzero-dev+vite-plus-test@0.1.13_@opentelemetry+api@1.9.0_@types+node@24.12.0_esbuil_d56179fe1baeee4f5c79fc70199bbcdf/node_modules/@voidzero-dev/vite-plus-test/dist/chunks/cli-api.DuT9iuvY.js:3454:98
 ❯ processTicksAndRejections node:internal/process/task_queues:104:5
 ❯ Pool.schedule ../../node_modules/.pnpm/@voidzero-dev+vite-plus-test@0.1.13_@opentelemetry+api@1.9.0_@types+node@24.12.0_esbuil_d56179fe1baeee4f5c79fc70199bbcdf/node_modules/@voidzero-dev/vite-plus-test/dist/chunks/cli-api.DuT9iuvY.js:3454:9
Caused by: Error: No such module "vitest/worker".
 ❯ ProxyServer.fetch ../../node_modules/.pnpm/miniflare@4.20260317.1/node_modules/miniflare/src/workers/core/proxy.worker.ts:174:11

### PR DESCRIPTION
**Pull request by penalosa**
Fixes #13001.

When users run tests via [Vite+](https://github.com/voidzero-dev/vite-plus) (`@voidzero-dev/vite-plus-test`) with the [recommended pnpm overrides](https://github.com/voidzero-dev/vite-plus/blob/main/packages/test/BUNDLING.md), two things break:

1. **Version check rejects `0.1.14`** — `assertCompatibleVitestVersion` compares the distribution's own version (`0.1.14`) against our `peerDependencies.vitest` constraint (`^4.1.0`). Fix: read the `bundledVersions.vitest` field from the distribution's `package.json` to get the real upstream version (e.g. `4.1.1`).

2. **`Disallowed operation called within global scope`** — vite-plus-test eagerly initialises `@sinonjs/fake-timers` during module loading, which calls `setTimeout`. Our `monkeypatchedSetTimeout` guard blocks this because the call originates from `@voidzero-dev/vite-plus-test` rather than `vitest`. Fix: add `@voidzero-dev/vite-plus-test` to the `fromVitest` allowlist regex.

### Setup required by users

Per [vite-plus's bundling docs](https://github.com/voidzero-dev/vite-plus/blob/main/packages/test/BUNDLING.md), users must configure pnpm overrides to alias `vitest` to `@voidzero-dev/vite-plus-test`:

```json
{
  "pnpm": {
    "overrides": {
      "vitest": "npm:@voidzero-dev/vite-plus-test@0.1.14",
      "@vitest/runner": "npm:@voidzero-dev/vite-plus-test@0.1.14",
      "@vitest/snapshot": "npm:@voidzero-dev/vite-plus-test@0.1.14"
    }
  }
}
```

Verified end-to-end in an isolated reproduction project outside the monorepo.

---

- Tests
  - [ ] Tests included/updated
  - [ ] Automated tests not possible - manual testing has been completed as follows:
  - [x] Additional testing not necessary because: verified in an isolated reproduction project outside the monorepo with `vite-plus@0.1.14` + pnpm overrides. Cannot add a CI fixture because vite-plus requires the recommended pnpm overrides setup, which would mess up the rest of workers-sdk 
- Public documentation
  - [ ] Cloudflare docs PR(s):
  - [x] Documentation not necessary because: follows vite-plus's existing setup guide

---

<a href="https://app.devin.ai/review/cloudflare/workers-sdk/pull/13075" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

File: packages/vitest-pool-workers/src/pool/index.ts [hunk 1]
```diff
@@ -742,11 +753,19 @@ export function assertCompatibleVitestVersion(ctx: Vitest) {
...
-	const actualVitestVersion = vitestPkgJson.version;
 	assert(
 		expectedVitestVersion !== undefined,
 		"Expected to find `@cloudflare/vitest-pool-workers`'s `vitest` version constraint"
 	);
+
+	// For alternative vitest distributions (e.g. @voidzero-dev/vite-plus-test),
+	// the package version (0.x) doesn't correspond to the upstream vitest
+	// version. Instead, extract the real vitest version from the @vitest/*
+	// dependencies declared in the distribution's package.json.
```
Comment (penalosa) [inline packages/vitest-pool-workers/src/pool/index.ts]:
```suggestion
```

**Comment by workers-devprod** [comment]
Codeowners approval required for this PR:
- ✅ @cloudflare/wrangler

<details><summary>Show detailed file reviewers</summary>


</details>

File: packages/vitest-pool-workers/src/pool/index.ts [hunk 2]
```diff
@@ -727,6 +729,15 @@ function getPackageJson(dirPath: string): PackageJson | undefined {
 	}
 }
 
+/**
+ * Extract the upstream vitest version from an alternative distribution's
+ * package.json. Distributions like `@voidzero-dev/vite-plus-test` declare
+ * the bundled vitest version in `bundledVersions.vitest`.
+ */
+function getUpstreamVitestVersion(pkgJson: PackageJson): string | undefined {
+	return pkgJson.bundledVersions?.vitest;
```
Comment (edmundhung) [inline packages/vitest-pool-workers/src/pool/index.ts:738]: Is this documented by vite+? Do we need to confirm with the team on whether it is safe to rely on this?

Comment (penalosa) [reply packages/vitest-pool-workers/src/pool/index.ts:738]: It is documented, yes: https://github.com/voidzero-dev/vite-plus/blob/a3c80d5d57f3af862d9e4df99aa6e48ce1352384/packages/core/BUNDLING.md?plain=1#L313
