### PR TITLE
fix: generate command with running cross-device

### LINKED ISSUE #2850: 🐛 BUG: `wrangler generate` sometimes fails due to cross-device renaming
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2

### What operating system are you using?

Windows

### Describe the Bug

Run `wrangler generate` with any template. It will fail.

The solution is to switch from `fs.renameSync` to a `copy` and `unlink` approach in `git-client.ts`

### PR DESCRIPTION
**Pull request by Cherry**
Fixes #2850

**What this PR solves / how to test:**

When using Windows (and maybe other operating systems), a `renameSync` can throw a `Error: EXDEV: cross-device link not permitted` error when renaming across drives. This is very common on Windows installs that may have Windows on `C:/`, but their user files on another drive like `E:/`.

This PR resolves that by first trying the `renameSync` (will be much faster than copying files on the same device, so worth doing first), but then catching the `EXDEV` error and handling it specifically afterwards.

For tests, I don't really know how to properly approach testing this cross-device behaviour if I'm honest - it'd need another filesystem (maybe mocked?) on some other virtual device - and most `generate` tests appear to be skipped right now anyway. If that's something folks would like to see, I'm going to need some guidance/examples on how best to do that testing. I ran manual tests locally on my Windows 10 machine using `generate project-name https://github.com/cloudflare/workers-sdk/templates/experimental/worker-rust`, as well as in WSL and on my Macbook just to ensure the previous behaviour wasn't impacted across a few OSes, and all worked well.

**Author has included the following, where applicable:**

- [ ] Tests
- [x] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer is to perform the following, as applicable:**

- Checked for inclusion of relevant tests
- Checked for inclusion of a relevant changeset
- Checked for creation of associated docs updates
- Manually pulled down the changes and spot-tested

### CODE REVIEW

**Comment by Cherry** [comment]
It seems like `fs.cp` is used in other places in the codebase, so it should be safe to use here too. I've gone ahead and removed the original dependency on `fs-extra`.

File: packages/wrangler/src/git-client.ts [hunk 1]
```diff
@@ -125,8 +127,24 @@ export async function cloneIntoDirectory(
 	// cleanup: move the template to the target directory and delete `.git`
 	try {
 		fs.renameSync(templatePath, targetDirectory);
-	} catch {
-		throw new Error(`Failed to find "${subdirectory}" in ${remote}`);
+	} catch (err) {
+		// @ts-expect-error non standard property on Error
+		if (err.code !== "EXDEV") {
+			logger.debug(err);
+			throw new Error(`Failed to find "${subdirectory}" in ${remote}`);
```
Comment (petebacondarwin) [inline packages/wrangler/src/git-client.ts:134]: Perhaps include the original `err` in the new Error?

Comment (Cherry) [reply packages/wrangler/src/git-client.ts:134]: I'm happy to do this - the original code doesn't, so I assumed that was intentional, but if you think it's safe to just pass it through, can do!

**Review by petebacondarwin — COMMENTED** [review]
I note that you are skipping the two unit tests. Do they not work?

I know you said that it was hard to create a real world test for this.
I wonder if we could create a network mapped drive that points to a local folder?
https://support.microsoft.com/en-us/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d#ID0EBD=Windows_11

File: packages/wrangler/src/git-client.ts (hunk 1 above)
Comment (petebacondarwin) [reply packages/wrangler/src/git-client.ts:134]: Hmm. Oh I see. OK let's leave it as-is.
(Aside, I note that `subdirectory` could actually be `undefined` that would be a weird message!)

Comment (Cherry) [reply packages/wrangler/src/git-client.ts:134]: > (Aside, I note that subdirectory could actually be undefined that would be a weird message!)

Yeah, it could for sure. The error handling here is pretty bare-bones. If you think it's worth refactoring here, let me know.

**Comment by Cherry** [comment]
> I note that you are skipping the two unit tests. Do they not work?

Yeah I attempted a _very_ dumb test by temporarily mocking `renameSync` to always through the `EXDEV` error so the `fs.cp` codepath would be hit, but it didn't seem to stick. I'm not sure if `runWrangler` in tests is spawning a brand new process and therefore doesn't have the mocks? I'm really not sure.

> I wonder if we could create a network mapped drive that points to a local folder?
[support.microsoft.com/en-us/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d#ID0EBD=Windows_11](https://support.microsoft.com/en-us/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d#ID0EBD=Windows_11)

This might work 🤔 I've never had to test anything like this in CI before. Prior libraries that have solved this seem to just handle it by naively mocking: https://github.com/andrewrk/node-mv/blob/645d8f4c783abf84204be704098fdd41f36ab195/test/test.js#L14

File: packages/wrangler/src/git-client.ts [hunk 2]
```diff
@@ -125,8 +127,24 @@ export async function cloneIntoDirectory(
...
+		}
+		// likely on a different filesystem, so we need to copy instead of rename
+		// and then remove the original directory
+		try {
+			fs.cpSync(templatePath, targetDirectory);
```
Comment (petebacondarwin) [inline packages/wrangler/src/git-client.ts:139]: We actually need a `recursive` option on this command too, which is why the tests were failing.
I have fixed this up and rebased.

**Review by petebacondarwin — APPROVED** [review]
Assuming CI is happy, I am happy.

**Comment by Cherry** [comment]
Thanks Pete! 🎉
