### PR TITLE
[vitest-pool-workers] Reject V8 coverage provider with a clear error

### LINKED ISSUE #5266: 🐛 BUG: Vitest code coverage does not work when using `@cloudflare/vitest-pool-workers`
### Which Cloudflare product(s) does this pertain to?

Workers Vitest Integration

### What version(s) of the tool(s) are you using?

0.1.2

### What version of Node are you using?

20.5.1

### What operating system and version are you using?

macOS Sonoma 14.1.1

### Observed behavior
Following the basic example from [your announcement blog post](https://blog.cloudflare.com/workers-vitest-integration/) I created a basic project with it & attempted to enable code coverage by adding the `@vitest/coverage-v8` package & added `coverage: { enabled: true }` property to my Vitest config.

### Expected behavior
When running Vitest you get the following error:
```bash
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: No such module "node:inspector".
  imported from "Users/nuro/Desktop/vitest-test/node_modules/.pnpm/@vitest+coverage-v8@1.4.0_vitest@1.3.0/node_modules/@vitest/coverage-v8/dist/index.js"
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
```

### Steps to reproduce

- Follow [the announcement post ](https://blog.cloudflare.com/workers-vitest-integration/) to set up a basic Vitest project
```
      1 .
      2 ├── src
      3 │   └── index.ts
      4 ├── tests
      5 │   └── basic.test.ts
      6 ├── package.json
      7 ├── pnpm-lock.yaml
      8 ├── tsconfig.json
      9 └── vitest.config.ts
```
 - Add the `@vitest/coverage-v8` package
 - Add the following to the `test` object to enable code coverage
```ts
    coverage: {
      enabled: true,
    },
```

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by penalosa**
Fixes #5266.

V8 native coverage (`@vitest/coverage-v8`) requires `node:inspector` to collect profiling data from V8's runtime. workerd provides `node:inspector` as a non-functional stub — methods are no-ops, `url()` returns undefined — so V8 coverage silently fails or crashes with a confusing `No such module "node:inspector"` error.

This adds early detection in the Vite plugin `config` hook, which runs before Vitest attempts to resolve the `@vitest/coverage-v8` package. When coverage is enabled with the `v8` provider (or no provider, since v8 is the default), the plugin throws a clear error directing users to use Istanbul coverage instead.

Istanbul works by instrumenting source code at build time and doesn't need `node:inspector`, so it runs on any JavaScript runtime including workerd.

---

- Tests
  - [x] Tests included/updated
  - [ ] Automated tests not possible - manual testing has been completed as follows:
  - [ ] Additional testing not necessary because:
- Public documentation
  - [ ] Cloudflare docs PR(s):
  - [x] Documentation not necessary because: the error message itself serves as inline documentation, and Istanbul coverage is already documented in Vitest's coverage guide

---

<a href="https://app.devin.ai/review/cloudflare/workers-sdk/pull/13095" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

**Comment by workers-devprod** [comment]
Codeowners approval required for this PR:
- @cloudflare/wrangler

<details><summary>Show detailed file reviewers</summary>

- packages/vitest-pool-workers/src/pool/plugin.ts: [@cloudflare/wrangler]
- packages/vitest-pool-workers/test/validation.test.ts: [@cloudflare/wrangler]

</details>

File: packages/vitest-pool-workers/src/pool/plugin.ts [hunk 1]
```diff
@@ -71,6 +71,35 @@ export function cloudflareTest(
...
+			// V8 coverage requires `node:inspector` to collect coverage data from
+			// V8's profiler. workerd provides `node:inspector` as a non-functional
+			// stub, so V8 coverage silently fails or crashes. Istanbul works because
+			// it instruments source code at build time without needing V8 access.
+			// See: https://github.com/cloudflare/workers-sdk/issues/5266
+			const coverage = config.test.coverage;
+			if (
+				coverage &&
+				typeof coverage === "object" &&
+				!Array.isArray(coverage) &&
```
Comment (edmundhung) [inline packages/vitest-pool-workers/src/pool/plugin.ts]: Are these checks needed? I checked out the branch and the IDE seems to know the coverage is always an object already.

File: packages/vitest-pool-workers/src/pool/plugin.ts [hunk 2]
```diff
@@ -71,6 +71,35 @@ export function cloudflareTest(
...
+			) {
+				const provider = "provider" in coverage ? coverage.provider : undefined;
+				if (provider === "v8" || provider === undefined) {
+					const lines = [
+						`Coverage provider "v8" is not supported by \`@cloudflare/vitest-pool-workers\`.`,
+						"V8 native coverage requires \`node:inspector\` which is not functional in the Workers runtime.",
+						"",
+						"Use Istanbul instead — it works by instrumenting source code and runs on any JavaScript runtime:",
+						"",
+						"  1. Install: pnpm add -D @vitest/coverage-istanbul",
```
Comment (edmundhung) [inline packages/vitest-pool-workers/src/pool/plugin.ts]: Nit: Not every users use pnpm, would it be better to use `npm` here? We can also detect the package manager they use but probably an overkill.

Comment (dario-piotrowicz) [reply packages/vitest-pool-workers/src/pool/plugin.ts]: I totally agree, I think we should either mention the current package manager being used or be generic

File: packages/vitest-pool-workers/test/validation.test.ts [hunk 3]
```diff
@@ -107,3 +108,76 @@ test(
 		expect(result.stderr).toMatch(expected);
 	}
 );
+
+describe("coverage provider validation", () => {
+	test(
+		"rejects v8 coverage provider with a clear error",
+		{ timeout: 45_000 },
```
Comment (dario-piotrowicz) [inline packages/vitest-pool-workers/test/validation.test.ts:115]: are these super long timeouts necessary? 🥹

Comment (penalosa) [reply packages/vitest-pool-workers/test/validation.test.ts:115]: Unfortunately yes, these run a full Vitest process from scratch, which can be slow in CI

**Comment by workers-devprod** [comment]
Codeowners approval required for this PR:
- ✅ @cloudflare/wrangler

<details><summary>Show detailed file reviewers</summary>


</details>
