### PR TITLE
fix: log successful execution of D1 commands locally

### LINKED ISSUE #6938: 🐛 BUG: Wrangler d1 execute command don't show success message when using local file on local database
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

10.8.2 [Wrangler]

### What version of Node are you using?

20.18.0

### What operating system and version are you using?

Mac Sonoma 15.0.1

### Observed behavior
When executing a local sql file on local database, I don't get status of command. Did it execute the sql file correctly or did it failed?

Sample output:

```
➜  d1-tutorial git:(main) ✗ npx wrangler d1 execute prod-d1-tutorial --local --file=./schema.sql                

 ⛅️ wrangler 3.80.2
-------------------

🌀 Executing on local database prod-d1-tutorial (8e1192dc-7d2a-4628-9e6e-44b14bb976fd) from .wrangler/state/v3/d1:
🌀 To execute on your remote database, add a --remote flag to your wrangler command.

➜  d1-tutorial git:(main) ✗ 
```

### Expected behavior
Even though my sql file don't have any select query, the command itself should indicate that it was able to run the sql file successfully.

### Steps to reproduce
To reproduce, run the following command:

`npx wrangler d1 execute prod-d1-tutorial --local --file=./schema.sql`

schema.sql file:

```sql
DROP TABLE IF EXISTS Customers;
CREATE TABLE IF NOT EXISTS Customers (CustomerId INTEGER PRIMARY KEY, CompanyName TEXT, ContactName TEXT);
INSERT INTO Customers (CustomerID, CompanyName, ContactName) VALUES (1, 'Alfreds Futterkiste', 'Maria Anders'), (4, 'Around the Horn', 'Thomas Hardy'), (11, 'Bs Beverages', 'Victoria Ashworth'), (13, 'Bs Beverages', 'Random Name');
```

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by emily-shen**
## What this PR solves / how to test

Fixes #6938 
Already does this for remote, just logs a bit of feedback to the user for local as well.

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [x] Tests included
  - [ ] Tests not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [x] Required
  - [ ] Not required because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [x] Changeset included
  - [ ] Changeset not necessary because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: trivial logging change

### CODE REVIEW

File: packages/wrangler/src/d1/execute.tsx [hunk 1]
```diff
@@ -332,6 +332,12 @@ async function executeLocally({
 		success: result.success,
 		meta: { duration: result.meta?.duration },
 	}));
+	if (allResults.every((r) => r.success)) {
+		logger.log(
+			`🚣 ${allResults.length} command${allResults.length === 1 ? "" : "s"} executed successfully.`
```
Comment (CarmenPopoviciu) [inline packages/wrangler/src/d1/execute.tsx:337]: do we really need that emoji here?

**Review by CarmenPopoviciu — APPROVED** [review]

File: packages/wrangler/src/d1/execute.tsx (hunk 1 above)
Comment (emily-shen) [reply packages/wrangler/src/d1/execute.tsx:337]: Haha I'm just mimicking what gets logged out when something is executed in remote mode. That seems to throw a random canoe in there, so why not in local too ¯\\\_(ツ)_/¯
