### PR TITLE
Intercept workerd logs + write all debug logs to a hidden file

### LINKED ISSUE #3631: 🐛 BUG: "warning: Not symbolizing stack traces because $LLVM_SYMBOLIZER is not set"
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.2.0

### What version of Node are you using?

_No response_

### What operating system are you using?

Ubuntu 22.04.2 LTS

### Describe the Bug

Anytime the application reports an error, the first error is prepended with this:

```
workerd/util/symbolizer.c++:99: warning: Not symbolizing stack traces because $LLVM_SYMBOLIZER is not set. To symbolize stack traces, set $LLVM_SYMBOLIZER to the location of the llvm-symbolizer binary. When running tests under bazel, use `--test_env=LLVM_SYMBOLIZER=<path>`.
```

Stack traces that follow are squished and hard to read.

This has also been reported in comments at the bottom of #3262 and #3457, and appears to affect multiple operating systems.

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by RamIdeas**
Fixes #3631 

**What this PR solves / how to test:**

- fixes a bug where Miniflare's Log class rethrew the error when the log level meant the error wouldn't be logged
- exposes a new Miniflare option: `handleRuntimeStdio` which allows intercepting workerd `stdout`/`stderr`
- wrangler now intercepts workerd logs using the above option
- wrangler now writes all ~~debug~~ logs to `.wrangler/debug-logs/wrangler-debug-<TIMESTAMP>.log` (superseding [this PR](https://github.com/cloudflare/workers-sdk/pull/2712))

Implementation notes:
- Logs with log level `debug` are now never sent to the terminal so the terminal remains clean but the extra observability is provided via the log file
- The default debug log filepath can be overridden using the new `WRANGLER_LOG_DIR` env var
  - which allows you to specify a directory path or a specific `.log` filepath
  - the default value for this env var is `<package>/.wrangler/debug-logs`
  - the filename will contain a timestamp, unless the `WRANGLER_LOG_DIR` value ends in `.log`
- The e2e test workflow will upload the debug-log file as an artefact for inspection upon failures (primarily, but also available on successful runs too)
- The logger level `debug` is what triggers the use of the log file but *all* logs are appended to the log file so that the order amongst other log-level logs (`info`, `error`, `warn`, etc) is preserved

Exposing a `handleRuntimeStdio` option, instead of hooks for each readline interface of the current implementation, should also satisfy https://github.com/cloudflare/workers-sdk/issues/4357

**Author has addressed the following:**

- Tests
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [ ] Not necessary because:

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

File: packages/wrangler/src/utils/debug-log-file.ts [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+	appendFile(debugLogFilepath, entry).catch((err) => {
+		if (hasLoggedError) return;
+		hasLoggedError = true;
+		logger.error(`Failed to write to debug log file`, err);
+	});
+
+	if (hasLoggedLocation) return;
+	hasLoggedLocation = true;
+	logger.info(`🐛 Writing debug logs to "${debugLogFilepath}"`);
+	// TODO: move this into an exit hook so it isn't the first thing logged
```
Comment (RamIdeas) [inline packages/wrangler/src/utils/debug-log-file.ts:49]: TODO before this PR is merged

File: packages/wrangler/src/dev/miniflare.ts [hunk 2]
```diff
@@ -418,6 +418,17 @@ async function buildMiniflareOptions(
...
+			stdout.on("data", (chunk) => {
+				// TODO: with some conditional heuristic, call log.debug instead of log.info
+				log.info(chunk.toString());
+			});
+
+			stderr.on("data", (chunk) => {
+				// TODO: with some conditional heuristic, call log.debug instead of log.error
+				log.error(chunk.toString());
+			});
+		},
```
Comment (RamIdeas) [inline packages/wrangler/src/dev/miniflare.ts:431]: Instead of log.debug like these comments mention, instead we could directly call `appendToDebugLogFile`

File: packages/wrangler/src/utils/debug-log-file.ts [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+	const entry = `
+--- ${new Date().toISOString()}
+${format(...args)}
+---
+`;
+
+	appendFile(debugLogFilepath, entry).catch((err) => {
+		if (hasLoggedError) return;
+		hasLoggedError = true;
+		logger.error(`Failed to write to debug log file`, err);
```
Comment (RamIdeas) [inline packages/wrangler/src/utils/debug-log-file.ts:43]: In addition to logging this error, we could also log the `entry` to the terminal rather than lose it entirely

**Comment by admah** [comment]
@RamIdeas are users notified somewhere that this new file exists?

File: packages/wrangler/src/utils/debug-log-file.ts (hunk 1 above)
Comment (RamIdeas) [reply packages/wrangler/src/utils/debug-log-file.ts:49]: @admah currently this line is logged upon the first entry to the log file but as mentioned in the comment, it might be better to log this line when the process exits

File: packages/wrangler/src/dev/miniflare.ts [hunk 4]
```diff
@@ -381,6 +382,82 @@ function buildSitesOptions({ assetPaths }: ConfigBundle) {
...
+
+			// CLEANABLE:
+			// known case to cleanup: Address in use errors
+			if (classifiers.isAddressInUse(chunk)) {
+				const address = chunk.match(
+					/Address already in use; toString\(\) = (.+)\n/
+				)?.[1];
+
+				logger.error(
+					`Address (${address}) already in use. Please check that you are not already running a server on this address or specify a different port with --port.`
```
Comment (Skye-31) [inline packages/wrangler/src/dev/miniflare.ts:443]: Would `--port` actually do anything here? I was under the assumption that `--port` was wrangler's port, not workerd's

Comment (RamIdeas) [reply packages/wrangler/src/dev/miniflare.ts:443]: Wrangler passes the port arg to workerd via miniflare – workerd is the process that actually binds to the port

**Review by mrbbot — COMMENTED** [review]
Miniflare changes look good! I've added some comments to some of the Wrangler ones... 👍

File: packages/wrangler/src/dev/miniflare.ts [hunk 5]
```diff
@@ -381,6 +382,82 @@ function buildSitesOptions({ assetPaths }: ConfigBundle) {
...
+			const containsLlvmSymbolizerWarning = chunk.includes(
+				"Not symbolizing stack traces because $LLVM_SYMBOLIZER is not set"
+			);
+			const containsHexStack = /stack:( [a-f\d]{9}){3,}/.test(chunk);
+
+			return containsLlvmSymbolizerWarning || containsHexStack;
+		},
+		// Is this chunk an Address In Use error?
+		isAddressInUse(chunk: string) {
+			return chunk.includes("Address already in use; toString() = ");
```
[the remark this answers is not in the document]
Comment (RamIdeas) [reply packages/wrangler/src/dev/miniflare.ts:402]: We'll find out when the e2e tests run

File: packages/wrangler/src/dev/miniflare.ts [hunk 6]
```diff
@@ -381,6 +382,82 @@ function buildSitesOptions({ assetPaths }: ConfigBundle) {
...
+			// IGNORABLE:
+			// anything else not handled above is considered ignorable
+			// so send it to the debug logs which are discarded unless
+			// the user explicitly sets a logLevel indicating they care
+			logger.debug(chunk);
+		}
+
+		// anything not exlicitly handled above should be logged as info (via stdout)
+		else {
+			logger.info(chunk);
```
[the remark this answers is not in the document]
Comment (RamIdeas) [reply packages/wrangler/src/dev/miniflare.ts:425]: I was aware of this because miniflare's previous implementation used `readline` which stripped the newline chars before using console.log/error but adding .trim() to the chunk values didn't change anything

File: packages/wrangler/src/utils/debug-log-file.ts [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+			.replace("T", "_")
+			.replace("Z", "");
+		const absoluteFilepath = path.join(
+			getBasePath(),
+			".wrangler",
+			`wrangler-debug-${date}.log`
+		);
+		const relativeFilepath = path.relative(process.cwd(), absoluteFilepath);
+
+		return relativeFilepath;
```
[the remark this answers is not in the document]
Comment (RamIdeas) [reply packages/wrangler/src/utils/debug-log-file.ts:24]: They're not going to be that big but I guess the number of files will grow quickly. I was thinking I can put them in a `.wrangler/debug-logs/` directory so the `.wrangler` directory isn't directly affected

File: packages/wrangler/src/dev/miniflare.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (RamIdeas) [reply packages/wrangler/src/dev/miniflare.ts:409]: Looks like it works on all platforms 😄

File: packages/miniflare/src/shared/log.ts [hunk 8]
```diff
@@ -78,8 +78,7 @@ export class Log {
 
 	error(message: Error): void {
 		if (this.level < LogLevel.ERROR) {
-			// Rethrow message if it won't get logged
-			throw message;
+			// Ignore message if it won't get logged
```
Comment (mrbbot) [inline packages/miniflare/src/shared/log.ts:81]: We should update `NoOpLog` below too.

File: packages/wrangler/src/logger.ts [hunk 9]
```diff
@@ -73,7 +74,22 @@ export class Logger {
...
+			// unless in unit-tests, if logLevel >= debug, send ALL logs to the debug log file (even non-debug logs for context & order)
+			if (
+				!inUnitTests &&
+				LOGGER_LEVELS[this.loggerLevel] >= LOGGER_LEVELS.debug
+			) {
+				void appendToDebugLogFile(messageLevel, message);
+			}
+			// unless in unit-tests, if the current message is a debug log, do not pollute the terminal with it (it's now in the debug log file)
+			if (!inUnitTests && LOGGER_LEVELS[messageLevel] === LOGGER_LEVELS.debug) {
+				return;
```
Comment (mrbbot) [inline packages/wrangler/src/logger.ts:89]: If the user has explicitly configured a debug log level, I feel like we should be logging debug logs to the terminal too? 🤔

File: packages/wrangler/src/utils/debug-log-file.ts [hunk 10]
```diff
@@ -0,0 +1,85 @@
...
+import { getBasePath } from "../paths";
+import type { LoggerLevel } from "../logger";
+
+const getDebugFileDir = getEnvironmentVariableFactory({
+	variableName: "WRANGLER_LOG_DIR",
+});
+
+function getDebugFilepath() {
+	const dir =
+		getDebugFileDir() ?? path.join(getBasePath(), ".wrangler", "debug-logs");
```
Comment (mrbbot) [inline packages/wrangler/src/utils/debug-log-file.ts:15]: Are we keeping this relative to the package, or should we make it relative to the project root like other uses of `.wrangler`?

File: packages/wrangler/src/utils/debug-log-file.ts [hunk 11]
```diff
@@ -0,0 +1,85 @@
...
+		}
+	});
+}
+
+/**
+ * Reads the current log file after waiting for all pending writes
+ */
+export function readDebugLogFile(): Promise<string> {
+	return mutex.runWith(() => readFile(debugLogFilepath, "utf-8"));
+}
```
Comment (mrbbot) [inline packages/wrangler/src/utils/debug-log-file.ts:85]: Is this function used anywhere?

File: packages/wrangler/src/logger.ts (hunk 9 above)
Comment (RamIdeas) [reply packages/wrangler/src/logger.ts:89]: This was the original plan but then you highlighted [Glen's PR](https://github.com/cloudflare/workers-sdk/pull/2712) which pointed out the debug logs in the terminal become too noisy and hard to follow. Sending all logs to the debug log file keeps the terminal clean but enables the extra observability.

Is this a breaking change? Do we want to keep the debug logs in the terminal until the next major?

File: packages/wrangler/src/utils/debug-log-file.ts (hunk 10 above)
Comment (RamIdeas) [reply packages/wrangler/src/utils/debug-log-file.ts:15]: The project root is probably better – how do I get the path to the project root?

File: packages/wrangler/src/logger.ts (hunk 9 above)
Comment (RamIdeas) [reply packages/wrangler/src/logger.ts:89]: Are you suggesting we write debug logs to the file unconditionally and write them to the terminal when the user has explicitly configured a debug log level?

Comment (mrbbot) [reply packages/wrangler/src/logger.ts:89]: Yep exactly. The default would be just write them to the debug log file, and don't log them to the terminal as we do today. Then if `--log-level=debug` or `WRANGLER_LOG=debug` (I think those are right 😅 ), are set, debug logs should go the terminal too.

File: packages/wrangler/src/utils/debug-log-file.ts (hunk 10 above)
Comment (mrbbot) [reply packages/wrangler/src/utils/debug-log-file.ts:15]: Replied internally.

File: packages/wrangler/src/logger.ts (hunk 9 above)
Comment (RamIdeas) [reply packages/wrangler/src/logger.ts:89]: 1. Is writing to a file on all runs of wrangler unnecessary overhead? Shouldn't it be opt-in
2. If we write logs to a file on every run, do we print the location every time too? Seems like noise unless they opt-in

Comment (mrbbot) [reply packages/wrangler/src/logger.ts:89]: > 1. Is writing to a file on all runs of wrangler unnecessary overhead? Shouldn't it be opt-in?

I don't think so. The idea is if something goes wrong, debug logs will already be there. You don't have to re-run with debug logging enabled and try reproduce it again.

> 2. If we write logs to a file on every run, do we print the location every time too? Seems like noise unless they opt-in

I don't think so. If they're in a known location, users should be able to get them from there for issue reports. We should point this location out in the report template.

File: packages/wrangler/src/utils/debug-log-file.ts [hunk 12]
```diff
@@ -2,17 +2,23 @@ import { appendFile, mkdir, readFile } from "node:fs/promises";
...
+import { logger, type LoggerLevel } from "../logger";
 import { getBasePath } from "../paths";
-import type { LoggerLevel } from "../logger";
 
 const getDebugFileDir = getEnvironmentVariableFactory({
-	variableName: "WRANGLER_LOG_DIR",
+	variableName: "WRNALGER_LOG_PATH",
+	defaultValue() {
+		const configPath = findWranglerToml();
+		const configDir = configPath ? path.dirname(configPath) : getBasePath();
```
Comment (mrbbot) [inline packages/wrangler/src/utils/debug-log-file.ts:14]: Shouldn't this fallback to `process.cwd()`?

Comment (mrbbot) [reply packages/wrangler/src/utils/debug-log-file.ts:14]: I think that's what we do already. If you run `wrangler dev` and then try cache something with the Cache API for example?

**Review by mrbbot — APPROVED** [review]

File: .github/workflows/e2e.yml [hunk 13]
```diff
@@ -82,3 +82,11 @@ jobs:
           CLOUDFLARE_ACCOUNT_ID: ${{ secrets.TEST_CLOUDFLARE_ACCOUNT_ID }}
           WRANGLER: pnpm --silent --package ${{ steps.find-wrangler.outputs.dir}} dlx wrangler
           NODE_OPTIONS: "--max_old_space_size=8192"
+          WRNALGER_LOG_PATH: ${{ runner.temp }}/wrangler-debug-logs/
```
Comment (1000hz) [inline .github/workflows/e2e.yml:85]:
```suggestion
          WRANGLER_LOG_PATH: ${{ runner.temp }}/wrangler-debug-logs/
```

File: .github/workflows/pullrequests.yml [hunk 14]
```diff
@@ -115,6 +115,14 @@ jobs:
           TMP_CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
           TMP_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
           NODE_OPTIONS: "--max_old_space_size=8192"
+          WRNALGER_LOG_PATH: ${{ runner.temp }}/wrangler-debug-logs/
```
Comment (1000hz) [inline .github/workflows/pullrequests.yml:118]:
```suggestion
          WRANGLER_LOG_PATH: ${{ runner.temp }}/wrangler-debug-logs/
```

**Review by 1000hz — CHANGES_REQUESTED** [review]

File: .github/workflows/pullrequests.yml (hunk 14 above)
Comment (RamIdeas) [reply .github/workflows/pullrequests.yml]: argh good catch!

Comment (1000hz) [reply .github/workflows/pullrequests.yml]: looks like the typo survived the most recent commits

**Review by 1000hz — APPROVED** [review]
