### PR TITLE
C3: Validate project name

### LINKED ISSUE #3222: 🐛 BUG: c3 project name input is not correctly validated
### Which Cloudflare product(s) does this pertain to?

C3

### What version of `Wrangler` are you using?

c3@2.0.0-next.2

### What operating system are you using?

Mac

### Describe the Bug

If I specify `foo.com` as my project name in C3, C3 happily accepts it just to fail during deployment:

```
npm create cloudflare@next     

using create-cloudflare version 2.0.0-next.1

╭ Create an application with Cloudflare Step 1 of 3
│ 
├ Where do you want to create your application?
│ dir ilovejavascript.net
│
├ What type of application do you want to create?
│ type webFramework
│
├ Which development framework do you want to use?
│ framework Angular
│
╰ Continue with Angular Creating your application via `npx @angular/cli@next new ilovejavascript.net --standalone`

? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? CSS
            Standalone application structure is new and not yet supported by many existing 'ng add' and 'ng update' integrations with community libraries.
CREATE ilovejavascript.net/README.md (1072 bytes)
CREATE ilovejavascript.net/.editorconfig (274 bytes)
CREATE ilovejavascript.net/.gitignore (548 bytes)
CREATE ilovejavascript.net/angular.json (3015 bytes)
CREATE ilovejavascript.net/package.json (1050 bytes)
CREATE ilovejavascript.net/tsconfig.json (901 bytes)
CREATE ilovejavascript.net/tsconfig.app.json (263 bytes)
CREATE ilovejavascript.net/tsconfig.spec.json (273 bytes)
CREATE ilovejavascript.net/.vscode/extensions.json (130 bytes)
CREATE ilovejavascript.net/.vscode/launch.json (470 bytes)
CREATE ilovejavascript.net/.vscode/tasks.json (938 bytes)
CREATE ilovejavascript.net/src/main.ts (250 bytes)
CREATE ilovejavascript.net/src/favicon.ico (1642 bytes)
CREATE ilovejavascript.net/src/index.html (304 bytes)
CREATE ilovejavascript.net/src/styles.css (80 bytes)
CREATE ilovejavascript.net/src/app/app.component.css (0 bytes)
CREATE ilovejavascript.net/src/app/app.component.html (23083 bytes)
CREATE ilovejavascript.net/src/app/app.component.spec.ts (927 bytes)
CREATE ilovejavascript.net/src/app/app.component.ts (318 bytes)
CREATE ilovejavascript.net/src/app/app.config.ts (117 bytes)
CREATE ilovejavascript.net/src/assets/.gitkeep (0 bytes)
✔ Packages installed successfully.
    Successfully initialized git.
╭ Configuring your application for Cloudflare Step 2 of 3
│ 
├ Installing Angular SSR 
│ installed
│ 
├ Adding Cloudflare Pages adaptor code 
│ added Cloudflare Pages adaptor code`
│ 
├ Installing adaptor dependencies 
│ Installed
│ 
├ Updating application code 
│ Done updating application code
│ 
├ Updating angular.json config 
│ Updated angular.json config
│ 
├ Adding command scripts for development and deployment
│ added commands to `package.json`
│ 
╰ Application configured 

╭ Deploy with Cloudflare Step 3 of 3
│ 
├ Do you want to deploy your application?
│ yes deploying via `npm run deploy`
│
┐ Creating Pages project 

✘ [ERROR] A request to the Cloudflare API (/accounts/d61d1e4d1ab4db4f5dbcf0a11cf90a5e/pages/projects) failed.

  You have entered an invalid project name. Project names can be 1-58 lowercase characters with dashes, but cannot start/end with a dash (/). [code: 8000003]
  
  If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose
````

In the short term we should validate the C3 input.

In the mid-term/long-term we should reconsider what kind of validation constraints we want to put on the project name as `foo.com` project names that match the target domain seem like a perfectly valid choice we should support somehow (e.g. by converting the name to foo-com when deploying onto `.pages.dev` subdomain).

### PR DESCRIPTION
**Pull request by jculvey**
Fixes #3222

**What this PR solves / how to test:**

This change ensures that project names are also valid pages project names to prevent crashes during the deploy step. 

**Associated docs issue(s)/PR(s):**

- [insert associated docs issue(s)/PR(s)]

**Author has included the following, where applicable:**

- [ x ] Tests
- [ x ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer is to perform the following, as applicable:**

- Checked for inclusion of relevant tests
- Checked for inclusion of a relevant changeset
- Checked for creation of associated docs updates
- Manually pulled down the changes and spot-tested

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

File: packages/create-cloudflare/src/common.ts [hunk 1]
```diff
@@ -34,13 +34,31 @@ import type { C3Args, PagesGeneratorContext } from "types";
 const { name, npm } = detectPackageManager();
 
 export const validateProjectDirectory = (relativePath: string) => {
+	// Validate that the directory is non-existant or empty
```
Comment (petebacondarwin) [inline packages/create-cloudflare/src/common.ts:37]:
```suggestion
	// Validate that the directory is non-existent or empty
```

**Review by petebacondarwin — APPROVED** [review]

File: packages/create-cloudflare/src/common.ts [hunk 2]
```diff
@@ -34,13 +34,31 @@ import type { C3Args, PagesGeneratorContext } from "types";
...
 	const existsAlready = existsSync(path);
 	const isEmpty = existsAlready && readdirSync(path).length === 0; // allow existing dirs _if empty_ to ensure c3 is non-destructive
 
 	if (existsAlready && !isEmpty) {
 		return `Directory \`${relativePath}\` already exists and is not empty. Please choose a new name.`;
 	}
+
+	// Ensure the name is valid per the pages schema
+	const projectName = basename(path);
+	const invalidChars = /^- | -$|[^a-z0-9-]/;
```
Comment (dario-piotrowicz) [inline packages/create-cloudflare/src/common.ts:48]: are the `/^- | -$|` here necessary? aren't you checking that in the next regex?
```suggestion
	const invalidChars = /[^a-z0-9-]/;
```

Comment (jculvey) [reply packages/create-cloudflare/src/common.ts:48]: Woops, missed this in the refactor. You're correct

**Review by dario-piotrowicz — APPROVED** [review]

**Review by petebacondarwin — APPROVED** [review]
LGTM - waiting on e2e tests to pass though...

**Comment by petebacondarwin** [comment]
E2E test failures seem to be legit?

**Comment by jculvey** [comment]
> E2E test failures seem to be legit?

Turns out it was `chatgptPlugin`. Pages have stricter name requirements than do workers and was failing under the new validation despite previously working as a workers name. It would be nice if we could validate the name depending on the project type, but because of the dialog sequence that isn't really possible.
