### PR TITLE
[vitest-pool-workers] Add `adminSecretsStore()` to `cloudflare:test`

### LINKED ISSUE #12778: vitest-pool-workers silently ignores secretsStorePersist — secrets store bindings always empty in tests
### Which Cloudflare product(s) does this pertain to?

vitest-pool-workers

### What versions & operating system are you using?

- `@cloudflare/vitest-pool-workers@0.12.20` (latest, verified — also reproduced on 0.12.19)
- `miniflare@4.20260301.1`
- `wrangler@4.71.0`
- macOS, Node 22

### Describe the Bug

When a worker uses `secrets_store_secrets` in `wrangler.jsonc`, vitest-pool-workers correctly reads the config and creates the service bindings (with `.get()`), but the backing secrets store is always empty. Calling `env.SECRET.get()` throws `Error: Secret "..." not found`.

**Root cause:** `secretsStorePersist` is a shared Miniflare option, but vitest-pool-workers only passes a fixed set of shared options:

```js
// pool/index.mjs line 7518
var SHARED_MINIFLARE_OPTIONS = {
  log: mfLog,
  verbose: true,
  handleRuntimeStdio,
  unsafeStickyBlobs: true
};
```

`secretsStorePersist` is not included. Even when specified in the vitest config's `miniflare` block, it's parsed as a per-worker option and silently ignored. Without it, Miniflare falls back to a fresh temporary directory, so the backing KV is always empty.

This is different from `d1Persist`, `kvPersist`, `r2Persist`, etc., which also aren't in `SHARED_MINIFLARE_OPTIONS` — but those are typically seeded in test setup (e.g., `applyD1Migrations`). There's no equivalent API to seed the secrets store from within a test.

### Expected behavior

Either:
1. `secretsStorePersist` should be forwarded to the Miniflare constructor (like other persist options), OR
2. There should be a `cloudflare:test` API to seed secrets store values (analogous to `applyD1Migrations`), OR
3. The docs should mention this limitation under [known issues](https://developers.cloudflare.com/workers/testing/vitest-integration/known-issues/)

### Workaround

Use a wrangler environment that omits `secrets_store_secrets`, provide the secret as a plain string binding via `miniflare.bindings`, and handle both types in application code:

```jsonc
// wrangler.jsonc
{
  "secrets_store_secrets": [
    { "binding": "MY_SECRET", "secret_name": "MY_SECRET", "store_id": "..." }
  ],
  "env": {
    "test": {
      "d1_databases": [...]  // must re-declare — not inherited
      // secrets_store_secrets intentionally omitted
    }
  }
}
```

```ts
// vitest.config.ts
wrangler: { configPath: "./wrangler.jsonc", environment: "test" },
miniflare: {
  bindings: { MY_SECRET: "test-value" },
},
```

```ts
// application code — handle both binding types
const secret = typeof env.MY_SECRET === "string"
  ? env.MY_SECRET
  : await env.MY_SECRET.get();
```

### Related issues

- #9006 — same symptom in `@cloudflare/vite-plugin`
- #9369 — secrets not found in local mode (includes community workaround with same `typeof` pattern)

### Please provide any relevant error logs

```
Error: Secret "BETTER_AUTH_SECRET" not found
 ❯ getAuth src/lib/auth.ts:47:45
```

### PR DESCRIPTION
**Pull request by penalosa**
Fixes #12778.

Secrets store bindings only expose a read-only `.get()` method, so there was previously no way to seed secret values from within a test. This adds `adminSecretsStore()` to `cloudflare:test` — a thin wrapper that returns Miniflare's existing admin API for a secrets store binding, giving tests full control over create/update/delete operations.

```ts
import { adminSecretsStore } from "cloudflare:test";
import { env } from "cloudflare:workers";

const admin = adminSecretsStore(env.MY_SECRET);
await admin.create("test-value");

const value = await env.MY_SECRET.get(); // "test-value"
```

---

- Tests
  - [x] Tests included/updated
  - [ ] Automated tests not possible - manual testing has been completed as follows:
  - [ ] Additional testing not necessary because:
- Public documentation
  - [x] Cloudflare docs PR(s): https://github.com/cloudflare/cloudflare-docs/issues/29388
  - [ ] Documentation not necessary because:

### CODE REVIEW

File: packages/vitest-pool-workers/src/worker/secrets-store.ts [hunk 1]
```diff
@@ -0,0 +1,39 @@
+// The admin API key used by Miniflare's emulated secrets store binding.
+// This must match the value in miniflare/src/workers/secrets-store/constants.ts.
+const ADMIN_API = "SecretsStoreSecret::admin_api";
```
Comment (penalosa) [inline packages/vitest-pool-workers/src/worker/secrets-store.ts]: Make this an exported constant from Miniflare, if possible

File: packages/vitest-pool-workers/src/worker/secrets-store.ts [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+			"Failed to execute 'adminSecretsStore': parameter 1 is not a secrets store binding."
+		);
+	}
+
+	return (binding as Record<string, (...args: unknown[]) => unknown>)[
+		ADMIN_API
+	]() as SecretsStoreSecretAdmin;
+}
+
+interface SecretsStoreSecretAdmin {
```
Comment (penalosa) [inline packages/vitest-pool-workers/src/worker/secrets-store.ts]: Can this be an exported type from Miniflare?

File: packages/vitest-pool-workers/test/bindings.test.ts [hunk 3]
```diff
@@ -51,3 +51,44 @@ test("hello_world support", async ({ expect, seed, vitestRun }) => {
...
+		"index.test.ts": dedent`
+				import { adminSecretsStore } from "cloudflare:test";
+				import { env } from "cloudflare:workers";
+				import { it } from "vitest";
+
+				it("seeds and retrieves a secret", async ({ expect }) => {
+					const admin = adminSecretsStore(env.MY_SECRET);
+					await admin.create("test-value");
+					const value = await env.MY_SECRET.get();
+					expect(value).toBe("test-value");
```
Comment (penalosa) [inline packages/vitest-pool-workers/test/bindings.test.ts]: Exercise some more admin operations here please

**Comment by workers-devprod** [comment]
Codeowners approval required for this PR:
- ✅ @cloudflare/wrangler

<details><summary>Show detailed file reviewers</summary>


</details>
