### PR TITLE
[miniflare/wrangler] Bump undici to v7.24.8 and remove pnpm patch

### LINKED ISSUE #13013: POST requests returning non-2xx status crash with "fetch failed"
When using @cloudflare/vite-plugin with Vite dev server, any POST request handler that returns a non-2xx HTTP status code (e.g. 401, 400, 403, 404) causes the Miniflare proxy to crash with a generic fetch failed error. The actual response from the worker is lost and Vite returns a 500 to the client.

GET requests with the same non-2xx status codes work correctly.

NOTE: this is only on DEV (via vite)

## Minimal reproduction:

```
  // app.ts (Hono, but framework doesn't matter)
  import { Hono } from 'hono';

  const app = new Hono();

  // ✅ Works — GET + 401
  app.get('/test-get-401', (c) => c.json({ error: 'Unauthorized' }, 401));

  // ✅ Works — POST + 200
  app.post('/test-post-200', (c) => c.json({ ok: true }, 200));

  // ✅ Works — POST + 201
  app.post('/test-post-201', (c) => c.json({ ok: true }, 201));

  // ❌ Crashes — POST + 401
  app.post('/test-post-401', (c) => c.json({ error: 'Unauthorized' }, 401));
```

## Test commands:

```
  curl -v http://localhost:5173/test-get-401      # ✅ 401
  curl -v -X POST http://localhost:5173/test-post-200   # ✅ 200
  curl -v -X POST http://localhost:5173/test-post-201   # ✅ 201
  curl -v -X POST http://localhost:5173/test-post-401   # ❌ 500 (should be 401)
```

  Error output in Vite terminal:
```
  [vite] Internal server error: fetch failed
      at Object.processResponse (node_modules/undici/lib/web/fetch/index.js:237:16)
      ...
      at async _Miniflare.dispatchFetch (node_modules/miniflare/dist/src/index.js:86755:22)
      at async file:///node_modules/@cloudflare/vite-plugin/dist/index.mjs:1601:19
```

##  Versions:
  - vite: 8.0.1
  - @cloudflare/vite-plugin: 1.30.0
  - miniflare: 4.20260317.1
  - wrangler: 4.75.0
  - OS: macOS

Pinning Miniflare to this version fixes the issue:
```
"overrides": {
	  "miniflare": "4.20251217.0"
	},
````

### PR DESCRIPTION
**Pull request by petebacondarwin**
Fixes #13013.

Bumps undici from 7.24.4 to 7.24.8, which includes the upstream fix ([nodejs/undici#5006](https://github.com/nodejs/undici/pull/5006)) for `isTraversableNavigable()` returning `true` unconditionally. This caused POST/PUT requests with non-2xx responses (e.g. 401) to throw `TypeError: fetch failed` because undici entered the 401 credential-retry block and failed on stream-backed request bodies.

Since the fix is now included upstream, this PR removes the pnpm patch we applied in #13058 as a workaround.

#### Changes

- Bump `undici` and `undici-types` from 7.24.4 → 7.24.8 in the pnpm catalog
- Remove `undici@7.24.4` from `patchedDependencies` and delete `patches/undici@7.24.4.patch`
- Remove now-unused `@ts-expect-error` directives on the `clone()` overrides in `src/http/request.ts` and `src/http/response.ts` (undici 7.24.8 types no longer error on these)
- Fix `SpecIterableIterator` type incompatibility in R2 tests — use structural types for `keys`/`delimitedPrefixes` helpers instead of `R2Objects` from `@cloudflare/workers-types` (removes unused `R2Objects` import)
- Fix `SpecIterableIterator` type incompatibility in vite-plugin `websockets.ts` — convert `@remix-run/node-fetch-server` `Headers` to `Record<string, string>` before passing to `miniflare.dispatchFetch`
- Add regression test covering GET/POST/PUT × various non-2xx status codes via `dispatchFetch`

#### Reviewer notes

- `undici@7.24.4` (unpatched) still appears in the lockfile as a transitive dependency of an older bundled miniflare version — this is expected and harmless since workspace packages now resolve to 7.24.8.
- The test exercises `dispatchFetch` which routes through undici's `fetch()` to workerd, covering the exact code path that was broken.
- The `@ts-ignore` comments on the `super.clone()` calls are intentionally kept — only the outer `@ts-expect-error` directives (which suppressed the method-override error) became unused with the new types.
- undici 7.24.8 changed `Headers.keys()` to return `SpecIterableIterator<string>` instead of `IterableIterator<string>`. This causes type mismatches wherever third-party `Headers` types (e.g. `@cloudflare/workers-types`, `@remix-run/node-fetch-server`) are passed to undici-typed APIs. The fixes in this PR work around these at the call sites.

#### ⚠️ Human review checklist

- [ ] Verify the `@ts-expect-error` removals are safe — confirm that `clone()` and `status` overrides still compile correctly with undici 7.24.8 types (CI build will confirm this)
- [ ] Confirm no other `@ts-expect-error` directives in miniflare reference undici types that may have changed
- [ ] Review `websockets.ts` `Record<string, string>` conversion — `headers.forEach` collapses multi-value headers to a single value per key; verify this is acceptable for WebSocket upgrade requests
- [ ] Check if there are other places in the monorepo where `Headers` objects cross the undici / workers-types boundary that may also need fixing

---

- Tests
  - [x] Tests included/updated
  - [ ] Automated tests not possible - manual testing has been completed as follows:
  - [ ] Additional testing not necessary because:
- Public documentation
  - [ ] Cloudflare docs PR(s):
  - [x] Documentation not necessary because: this is a dependency bump with no user-facing API changes

Link to Devin session: https://app.devin.ai/sessions/fea4cbb20470478ca29d0c117e41896d
Requested by: @petebacondarwin

### CODE REVIEW

**Comment by workers-devprod** [comment]
Codeowners approval required for this PR:
- ✅ @cloudflare/wrangler

<details><summary>Show detailed file reviewers</summary>


</details>

**Review by penalosa — APPROVED** [review]

**Review by workers-devprod — APPROVED** [review]
Codeowners reviews satisfied

File: packages/vite-plugin-cloudflare/src/websockets.ts [hunk 1]
```diff
@@ -38,7 +37,16 @@ export function handleWebSocket(
...
+			const headers = new Headers();
+			const rawHeaders = request.rawHeaders;
+			for (let i = 0; i < rawHeaders.length; i += 2) {
+				// oxlint-disable-next-line typescript/no-non-null-assertion
+				if (rawHeaders[i]!.startsWith(":")) {
+					continue;
+				}
+				// oxlint-disable-next-line typescript/no-non-null-assertion
+				headers.append(rawHeaders[i]!, rawHeaders[i + 1]!);
+			}
```
Comment (jamesopstad) [inline packages/vite-plugin-cloudflare/src/websockets.ts]: Please can we try reverting these changes and just casting the type? The runtime types should already be compatible.

**Review by jamesopstad — CHANGES_REQUESTED** [review]

File: packages/vite-plugin-cloudflare/src/websockets.ts (hunk 1 above)
Comment (petebacondarwin) [reply packages/vite-plugin-cloudflare/src/websockets.ts]: Sure. I'll give it a go

**Review by jamesopstad — APPROVED** [review]
