### PR TITLE
fix: add better error for user binding called ASSETS in pages projects

### LINKED ISSUE #6266: 🐛 BUG: No error handling for failed deploy due to binding with the name 'assets'.
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

Wrangler 3.64.0

### What version of Node are you using?

20.10.0

### What operating system and version are you using?

Windows 11

### Observed behavior
When deploying a Hono application in Wrangler, if a binding uses the name 'ASSETS' the application will fail to deploy.

### Expected behavior
The application failing to deploy is expected as assets is a reserved keyword, however no error message is provided to explain that this is the cause of the failed deployment. An error message that explains that a binding with the name assets exists and that the name needs to be changed is the expected behavior.

### Steps to reproduce
Please provide the following:
- Create a Hono application
- Add a binding with the name 'ASSETS'
- Attempt deploying the application

### PR DESCRIPTION
**Pull request by emily-shen**
Fixes #6266 
The binding name "ASSETS" is used internally by pages projects. If a user had a binding with this name (totally sensible binding name for an r2 bucket for example) it would fail cryptically (see linked issue). 

---

- Tests
  - [ ] TODO (before merge)
  - [x] Tests included
  - [ ] Tests not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [ ] Required
  - [x] Not required because: no changes to e2es
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: error message fix

### CODE REVIEW

**Comment by emily-shen** [comment]
a binding named ASSETS is allowed in workers projects though, and there are plenty of existing tests using that so that case should already be covered

File: packages/wrangler/src/config/validation.ts [hunk 1]
```diff
@@ -2773,6 +2773,12 @@ const validateBindingsHaveUniqueNames = (
 				bindingsGroupedByName[bindingName] = [];
 			}
 
+			if (bindingName.toUpperCase() === "ASSETS" && isPagesConfig(config)) {
+				diagnostics.errors.push(
+					`The name 'ASSETS' is reserved in Pages projects. Please use a different name for your ${bindingType} binding.`
```
Comment (edmundhung) [inline packages/wrangler/src/config/validation.ts:2778]: Nit: Is binding name is case sensitive? Might be better to show the original name user provided.
```suggestion
					`The name '${bindingName}' is reserved in Pages projects. Please use a different name for your ${bindingType} binding.`
```

Comment (emily-shen) [reply packages/wrangler/src/config/validation.ts:2778]: turns out it is case sensitive, so you totally can deploy with 'assets' (lowercase) no issues
