### PR TITLE
wrangler: feat: wrangler preview_urls default to workers_dev

### LINKED ISSUE #10722: Invoking `wrangler deploy` w/o config forcibly resets preview URLs
### What versions & operating system are you using?

Workers Builds. `pnpx wrangler@latest`

### Please provide a link to a minimal reproduction

_No response_

### Describe the Bug

When running `pnpx wrangler@latest deploy --assets build --compatibility-date 2025-01-01` as a minimal way to deploy a static assets worker, this now forcibly disables the preview URLs functionality of Cloudflare Workers, even if it was enabled in the dashboard.

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by danielrs**
Fixes #10722.

Also tracked internally: https://jira.cfdata.org/browse/WC-4085.

_Describe your change..._

Originally, we were defaulting config.preview_urls to `true`, but we were accidentally enabling Preview URLs for users that only had config.workers_dev=false.

Then, we set the default value of config.preview_urls to `false`, but we were accidentally disabling Preview URLs for users that only had config.workers_dev=true.

Rather than defaulting config.preview_urls to `true` or `false`, we default to the resolved value of config.workers_dev. Should result in a clearer user experience.

---

- Tests
  - [x] Tests included
  - [ ] Tests not necessary because:
- Public documentation
  - [x] Cloudflare docs PR(s): https://github.com/cloudflare/cloudflare-docs/pull/25766
  - [ ] Documentation not necessary because:
- Wrangler V3 Backport
  - [ ] Wrangler PR: 
  - [x] Not necessary because: Not a patch change.

### CODE REVIEW

**Comment by danielrs** [comment]
- [x] Wait for API changes before merging.

**Comment by danielrs** [comment]
- [x] Also tested manually using local build.

File: packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts [hunk 1]
```diff
@@ -1,7 +1,13 @@
 import { http, HttpResponse } from "msw";
 import { ParseError } from "../../parse";
-import { getSubdomainValues } from "../../triggers/deploy";
-import { mockGetWorkerSubdomain } from "./mock-workers-subdomain";
+import {
+	getSubdomainValues,
+	getSubdomainValuesAPIMock,
```
Comment (petebacondarwin) [inline packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts:5]: I was deeply confused by this being called a Mock while existing in the production code. Now I read through I see that we are simulating the backend logic within Wrangler so that we can do diffing, right?
I see there is a comment in there that we should be able to get this from the API. Is that on the roadmap?

Comment (danielrs) [reply packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts:5]: Yeah that's the main purpose for this function, act as a placeholder of the defaults computed at the API-level. Once the API has an endpoint that lets Wrangler know the defaults, we should be able to stop using this function in production code. Gonna create an internal ticket for this.
