### PR TITLE
Fix execution freezing on `debugger` statements when DevTools is not attached

### LINKED ISSUE #7956: 🐛 BUG: execution freezes on `debugger` statements when no inspector is open
### Which Cloudflare product(s) does this pertain to?

Wrangler, Miniflare

### What versions are you using?

wrangler@3.106.0

### What operating system and version are you using?

macOS Sequoia 15.2

### Please provide a link to a minimal reproduction

https://github.com/dario-piotrowicz/my-create-cloudflare-worker-29-01-2025

### Describe the Bug

Just adding a single debugger statement to a worker causes the whole process to freeze and not serve responses anymore, the only way to unblock execution is to open a devtools inspector

The way I reproduced this was by simply creating a worker using C3 (https://github.com/dario-piotrowicz/my-create-cloudflare-worker-29-01-2025/commit/399695478a0434a3a283070d6966a46bb2c313d5), adding a debugger statement to my worker (https://github.com/dario-piotrowicz/my-create-cloudflare-worker-29-01-2025/commit/95c7bb7790ee7ced5f284ef12f5717c27037b4ec) and running `npm start`, in such case requests don't get processed until I open an inspector that lets me hit the debugger.

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
Fixes #7956 

Previously, `wrangler` always tried to connect to an inspector debugger, even when DevTools wasn't open. This caused scripts to freeze on `debugger` statements. Now the connection is only made when DevTools is actually attached.

---

- Tests
  - [ ] Tests included/updated
  - [x] Automated tests not possible - manual testing has been completed as follows:
     - pull down the issue's [minimal reproduction](https://github.com/dario-piotrowicz/my-create-cloudflare-worker-29-01-2025)
     - run `npm i` and `npm start`, try fetching/visiting the worker's url and notice its execution being blocked
     - install this PR's prerelease (`npm i https://pkg.pr.new/wrangler@12835`)
     - try `npm start` again and see that the execution is no longer blocked
     - press the `d` hotkey and fetch from the worker again, see that debugging still works as expected
     - try to run `npm start` in a vscode debugger terminal and see that debugging still works as expected
     - run again the command normally and try to debug via chome's `chrome://inspect` page, see that debugging still works as expected
  - [ ] Additional testing not necessary because:
- Public documentation
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: bugfix

*A picture of a cute animal (not mandatory, but encouraged)*

---

<a href="https://app.devin.ai/review/cloudflare/workers-sdk/pull/12835" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

**Comment by workers-devprod** [comment]
Codeowners approval required for this PR:
- ✅ @cloudflare/wrangler

<details><summary>Show detailed file reviewers</summary>


</details>

File: packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts [hunk 1]
```diff
@@ -398,10 +398,18 @@ export class InspectorProxyWorker implements DurableObject {
...
-		this.sendRuntimeMessage(
-			{ method: "Debugger.enable", id: this.nextCounter() },
-			runtime
-		);
+		// Only send Debugger.enable if DevTools is already attached.
+		// When DevTools first connects, it sends its own Debugger.enable message.
+		// However, on runtime reconnect (e.g., after worker reload), DevTools won't
+		// re-send Debugger.enable since it considers the session still active.
+		// Without this, Debugger.scriptParsed events won't be emitted on the new
+		// runtime connection, breaking source maps, breakpoints, and debugger pausing.
```
Comment (petebacondarwin) [inline packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts:406]: So what you're saying is that don't need to send this message when devtools first connect but it will be needed if we are reconnecting to it, e.g. it is already open for one reason or another.

Comment (dario-piotrowicz) [reply packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts:406]: yes 🙂

**Comment by dario-piotrowicz** [comment]
Thanks a lot @petebacondarwin 😄 

Yeah I didn't consider the devtools closing situation! 😓 I'll quickly look into it now 🙏

**Comment by workers-devprod** [comment]
Codeowners approval required for this PR:
- ✅ @cloudflare/wrangler

<details><summary>Show detailed file reviewers</summary>


</details>

**Comment by dario-piotrowicz** [comment]
@petebacondarwin https://github.com/cloudflare/workers-sdk/pull/12835/commits/50944aadcb123c6481bdc14d25bec6aee2f978c1 should address the client closing concern 😄 (again, thanks a lot for surfacing the issue! 🙏)

Please have another look 🙂🙏
