### PR TITLE
[wrangler] Handle multi-module workers when downloading scripts

### LINKED ISSUE #2866: 🐛 BUG: keep_vars in wrangler.toml is not respected
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.12.0

### What operating system are you using?

Linux

### Describe the Bug

With keep_vars set on wrangler.toml, variables are still removed from Worker, using command `wrangler publish`.
In other hand, when using command `wrangler publish --keep-vars`, it's working correctly and manually configured variables are not removed.

### LINKED ISSUE #2886: 🐛 BUG: `wrangler --from-dash` doesn't support multi-module workers
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.12

### What operating system are you using?

Mac

### Describe the Bug

- Create a multi-module worker
- Run `wrangler --from-dash`
- Not all modules are downloaded

### PR DESCRIPTION
**Pull request by RamIdeas**
Fixes #2886 

This PR adds support for downloading multi-module scripts from the API. The API endpoint already returns formdata, and the previous implementation in wrangler `throw`s when that formdata contains more than one entry. Therefore, this is not a breaking change requiring a major version bump (maybe a minor?).

Unfortunately, that block of code was not tested. The mocked API response was only ever a text response inferred to be one file with the filename hardcoded.

Regarding tests, since MSW does not support the `Response#formData` method and there's no (easy/understandable) way to hook into MSW's response (it's all functional objects, no class instances), **I've added an `if` statement to the runtime code** which turns the MSW MockedResponse into a undici Response. **This won't effect non-test execution** since the response will already be an undici Response returned from fetch.

### CODE REVIEW

File: packages/wrangler/src/cfetch/internal.ts [hunk 1]
```diff
@@ -242,17 +242,16 @@ export async function fetchDashboardScript(
 	if (usesModules) {
 		// Response from edge contains generic "name = worker.js" for dashboard created scripts
 		const form = await response.formData();
-		const entries = Array.from(form.entries());
-		if (entries.length > 1)
-			throw new RangeError("Expected only one entry in multipart response");
-		const [_, file] = entries[0];
+		const files = Array.from(form.entries())
+			.filter(([_, file]) => file instanceof File)
```
Comment (penalosa) [inline packages/wrangler/src/cfetch/internal.ts:246]: What is this filter checking? Are there items in the response that aren't parsed as Files?

File: packages/wrangler/src/cfetch/internal.ts [hunk 2]
```diff
@@ -242,17 +242,16 @@ export async function fetchDashboardScript(
...
-		if (file instanceof File) {
-			return await file.text();
-		}
-
-		return file ?? "";
+		return files;
 	} else {
-		return response.text();
+		const contents = await response.text();
+		const filename = response.headers.get("cf-entrypoint") ?? "index.js";
```
Comment (penalosa) [inline packages/wrangler/src/cfetch/internal.ts:252]: A service worker syntax worker won't have an entry point (sorry, I think I gave you a different answer in person!)

File: packages/wrangler/src/init.ts [hunk 3]
```diff
@@ -485,10 +486,12 @@ export async function initHandler(args: InitArgs) {
 					`/accounts/${accountId}/workers/services/${fromDashScriptName}/environments/${defaultEnvironment}/content`
 				);
 
-				await writeFile(
-					path.join(creationDirectory, "./src/index.ts"),
-					dashScript
-				);
+				for (const file of dashScript) {
+					await writeFile(
+						path.join(creationDirectory, `./src/${file.name}`),
```
Comment (penalosa) [inline packages/wrangler/src/init.ts:491]: This will probably need a recursive mkdir on the dirname before doing a file write to work with nested files

File: packages/wrangler/src/init.ts [hunk 4]
```diff
@@ -591,10 +594,12 @@ export async function initHandler(args: InitArgs) {
 					`/accounts/${accountId}/workers/services/${fromDashScriptName}/environments/${defaultEnvironment}/content`
 				);
 
-				await writeFile(
-					path.join(creationDirectory, "./src/index.js"),
-					dashScript
-				);
+				for (const file of dashScript) {
+					await writeFile(
```
Comment (penalosa) [inline packages/wrangler/src/init.ts:598]: Doing this in parallel (i.e. with await Promise.all()) might be a nice optimisation

File: packages/wrangler/src/init.ts [hunk 5]
```diff
@@ -591,10 +594,12 @@ export async function initHandler(args: InitArgs) {
...
+						path.join(creationDirectory, `./src/${file.name}`),
+						file.stream() as ReadableStream
```
Comment (penalosa) [inline packages/wrangler/src/init.ts:600]: Why is this typecast needed? Does Node FS take web streams?

**Review by penalosa — CHANGES_REQUESTED** [review]
Mostly questions-main thing that needs changed is the addition of a mkdir on the file path for writeFile to work.

File: packages/wrangler/src/cfetch/internal.ts (hunk 1 above)
Comment (RamIdeas) [reply packages/wrangler/src/cfetch/internal.ts:246]: I'm not sure if there will be any non-files or even if that's possible. I was keeping the existing check from L250

File: packages/wrangler/src/cfetch/internal.ts (hunk 2 above)
Comment (RamIdeas) [reply packages/wrangler/src/cfetch/internal.ts:252]: Ok so shall I hardcode 'index.js' instead?

Comment (penalosa) [reply packages/wrangler/src/cfetch/internal.ts:252]: I think we've generally tended to use `worker.js` for service workers on the dashboard, but `index.js` probably fits more with Wrangler, so yeah

Comment (RamIdeas) [reply packages/wrangler/src/cfetch/internal.ts:257]: I kept `index.js` to match the existing wrangler functionality and the existing tests

File: packages/wrangler/src/init.ts [hunk 6]
```diff
@@ -485,9 +486,17 @@ export async function initHandler(args: InitArgs) {
...
+				await Promise.all(
+					dashScript.map(async (file) => {
+						const filepath = path
+							.join(creationDirectory, `./src/${file.name}`)
+							.replace(/\.js$/, ".ts"); // change javascript extension to typescript extension
+						const directory = dirname(filepath);
+
+						await mkdir(directory, { recursive: true });
+						await writeFile(filepath, file.stream() as ReadableStream);
+					})
```
Comment (JacobMGEvans) [inline packages/wrangler/src/init.ts:499]: So something like this maybe? 
```suggestion
function chunk(array, size) {
  const result = [];
  let i = 0;

  while (i < array.length) {
    result.push(array.slice(i, i + size));
    i += size;
  }

  return result;
}

const batchSize = 10;
const batches = chunk(dashScript, batchSize);

await Promise.all(
  batches.map(async (batch) => {
    await Promise.all(
      batch.map(async (file) => {
        const filepath = path
          .join(creationDirectory, `./src/${file.name}`)
          .replace(/\.js$/, ".ts"); // change javascript extension to typescript extension
        const directory = dirname(filepath);

        await mkdir(directory, { recursive: true });
        await writeFile(filepath, file.stream() as ReadableStream);
      })
    );
  })
);
```

**Review by JacobMGEvans — APPROVED** [review]
