### PR TITLE
C3: Relax empty directory check

### LINKED ISSUE #4212: 🐛 BUG: C3 empty project folder validation is too aggressive
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

2.6.0

### What version of Node are you using?

20.8.0

### What operating system are you using?

macOS

### Describe the Bug

When creating a project with C3, the project directory validation is overly aggressive. It doesn't allow creation of a project if the target directory already contains
- .DS_Store file (if directory was created in Finder on macOS)
- .git folder (if directory is a git repo already)
- .idea folder (if directory has been opened in a JetBrains IDE)

I hit this every time I use C3 to create a project in the root of an existing repo, specifying `.` as the project folder (or `cd ..` and specify the folder name, it's the same).

I believe the root cause is this line:
https://github.com/cloudflare/workers-sdk/blob/c2457cb484f9e09752403116f137ab1bc40ae322/packages/create-cloudflare/src/common.ts#L43

To improve this workflow (create & clone repo, open in IDE, init via c3), I believe a whitelist would be useful. Similar create- tools have one, here's Astro for an example:
https://github.com/withastro/astro/blob/main/packages/create-astro/src/actions/shared.ts

Sure, create-astro can be more confident in Astro templates not containing x or y file, but even a _smaller_ whitelist will be helpful in a lot of cases.

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by jculvey**
Fixes #4212.

**What this PR solves / how to test:**

This relaxes the existing directory check to allow files such as `.git`, `.hg`, and `.DS_Store` that are created by IDEs, the OS, or are benign config files. These don't conflict with c3 and the existing check impedes the workflow of users who create folders via their IDE.

**Associated docs issue(s)/PR(s):**

- [insert associated docs issue(s)/PR(s)]

**Author has included the following, where applicable:**

- [ ] Tests
- [ x ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer is to perform the following, as applicable:**

- Checked for inclusion of relevant tests
- Checked for inclusion of a relevant changeset
- Checked for creation of associated docs updates
- Manually pulled down the changes and spot-tested

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

**Review by dario-piotrowicz — COMMENTED** [review]
I'm really not sure about this approach, it seems rather brittle and requiring lots of maintenance tweaking in the long run 😕 

for example, I can see `LICENSE`, what about `LICENSE.md`, `licence.md`? `README`? `README.md`? `readme.md`?  `.gitkeep`? `.vscode`?

I think the list can go on and on and be rather long etc...

Could we instead do something like showing a warning telling the user `this directory is not empty, the process might fail, do you want to proceed? Y/n`? or something along those lines?

Maybe instead of listing what we allow, we could list all the files that we have in our templates and just error on conflicts for those? and let the process continue otherwise (meaning that the framework clis would do whatever checks they do for webFrameworks hopefully covering that for us?)

**Comment by jculvey** [comment]
> I'm really not sure about this approach, it seems rather brittle and requiring lots of maintenance tweaking in the long run 😕
> 
> for example, I can see `LICENSE`, what about `LICENSE.md`, `licence.md`? `README`? `README.md`? `readme.md`? `.gitkeep`? `.vscode`?
> 
> I think the list can go on and on and be rather long etc...

You're not wrong 😄 . The list does seem hit or miss, and does seem like the type of thing that will need to be tweaked to no end. FWIW [astro](https://github.com/withastro/astro/blob/main/packages/create-astro/src/actions/shared.ts) and [next](https://github.com/vercel/next.js/blob/canary/packages/create-next-app/helpers/is-folder-empty.ts#L6) use the same technique in their scaffolding tools, as do others. I don't think we should maintain the list ourselves, but rather use the union of all files allowed by framework creators.

> Maybe instead of listing what we allow, we could list all the files that we have in our templates and just error on conflicts for those? and let the process continue otherwise (meaning that the framework clis would do whatever checks they do for webFrameworks hopefully covering that for us?)

I think the block list turns out to be a hard problem. If we wanted to do this, we'd have to generate permutations of every possible c3 run with each option, and then collect a set of all the possible files to check against. This too will change over time, so we'd have to automate the process to happen on PRs (possibly just of new templates).

Then, if we let framework clis just do whatever checks just handle the validation, it means that instead of failing during the first step like this PR would do, they will fail during the scaffolding step as we call the framework cli.

> Could we instead do something like showing a warning telling the user `this directory is not empty, the process might fail, do you want to proceed? Y/n`? or something along those lines?

This sounds like a better option, but I think we want to strongly avoid destructive operations. If we confirm and let them despite the file being non-empty this is possible in a way that it's not today. I think we should still crash in scenarios where we think this could happen, but just exempt a few simple corner cases where this commonly pops up for users -- like when they create a directory via an IDE or some OS utility that creates a couple hidden files.

**Review by dario-piotrowicz — APPROVED** [review]

**Comment by dario-piotrowicz** [comment]
@jculvey I see, well thanks for the reply, I'm still not convinced about this but:
 - it's better then the current situation
 - it doesn't seem like we have clearly better alternatives
 
 So I am fine to proceed with this if you feel strongly about it 🙂
 
One minor thing (kinda alluded in my previous comment) I would suggest adding logic for having the checks case insensitive and potentially ignoring file extensions (so that you can match match `LICENCE` if the user has a `LICENCE.md`) or something similar to increase the range we can cover 🙂

File: packages/create-cloudflare/src/cli.ts [hunk 1]
```diff
@@ -78,6 +80,21 @@ export const runCli = async (args: Partial<C3Args>) => {
 		format: (val) => `./${val}`,
 	});
 
+	// If the directory already exists, confirm overwrite or abort
+	const path = resolve(projectName);
+	if (existsSync(path)) {
```
Comment (dario-piotrowicz) [inline packages/create-cloudflare/src/cli.ts:85]: if the directory exists but it is empty, couldn't/shouldn't we just go ahead without asking the user?

File: packages/create-cloudflare/src/helpers/args.ts [hunk 2]
```diff
@@ -39,6 +39,10 @@ export const parseArgs = async (argv: string[]): Promise<Partial<C3Args>> => {
 			alias: "y",
 			type: "boolean",
 		})
+		.option("overwrite", {
+			type: "boolean",
+			description: "Overwrite files if target directory exists.",
```
Comment (dario-piotrowicz) [inline packages/create-cloudflare/src/helpers/args.ts:44]:
```suggestion
			description: "Overwrite files if target directory exists",
```
(the other descriptions don't end with a full stop)

**Review by dario-piotrowicz — APPROVED** [review]

**Review by IgorMinar — APPROVED** [review]
LGTM - c3 only changes

**Comment by DaniFoldi** [comment]
Hi 👋 

I've been following this PR, thanks for the quick turnaround @jculvey. Am I right saying that the newest implementation fails if the directory is non-empty, but allows the user to overwrite, which deletes **everything** from the target directory?

If so, I'd be cautious about proceeding - this approach doesn't actually solve my main issue, rather it sets everything on fire and hides in the smoke. For the most part, there shouldn't be anything wrong deleting everything when I'm setting up a project, but what if I created a repo on GitHub that included a 
LICENSE` file? Now if that's deleted, do I have to recreate? With `.git` gone, do I have to clone again? What about other template files..

For the most part, I'd say there's actually nothing c3 should validate here; create-{framework} (this is for pages/website templates only) already validates for files it considers safe, and as far as my understanding goes c3 doesn't usually create new files for the Pages deployment configuration. For workers, I'd keep the whitelist like other projects do, maybe expanding by the case insensitivity or some other files, but judging by the number of issues they've had I'd say their approach is just fine.

File: packages/create-cloudflare/src/common.ts [hunk 3]
```diff
@@ -36,49 +36,44 @@ export const validateProjectDirectory = (
...
-	// Crash if the directory already exists
 	const path = resolve(args.projectName);
 	const err = validateProjectDirectory(path, args);
 	if (err) {
 		crash(err);
 	}
 
+	// Delete the target directory path. At this point, the
+	// user has already confirmed the overwrite, if it exists
+	rmSync(path, { recursive: true, force: true });
```
Comment (Cherry) [inline packages/create-cloudflare/src/common.ts:71]: I'm not super familiar with this code, so this is a drive-by review, but this feels very dangerous to me. Someone could run this in `/`, or `C:/` with `--overwrite` and then end up with a bunch of their filesystem being wiped.

Comment (jculvey) [reply packages/create-cloudflare/src/common.ts:71]: I'm going to change it back to the previous strategy of failing on non-empty directories with the exception of an allow list, but for posterity: 

> Someone could run this in /, or C:/ with --overwrite and then end up with a bunch of their filesystem being wiped if I'm understanding correctly?

Correct, if you ran `npm create cloudflare / -- --overwrite, it would wipe the filesystem. Just as it would if you ran `rm -rf /`. Does this seem like a common, realistic use case that we should account for? 

> Even with a confirmation, that feels very heavy-handed and not something I've personally experienced with other tooling.

Here's a couple of examples of similar tools that do the same thing:
- [create-solid](https://github.com/solidjs/solid-start/blob/main/packages/create-solid/cli/index.js#L300)
- [create-vue](https://github.com/vuejs/create-vue/blob/main/index.ts#L316 )

Comment (Cherry) [reply packages/create-cloudflare/src/common.ts:71]: Thanks for the insight @jculvey. I think the previous strategy makes the most sense.

As for those other packages, if I'm reading them correctly from a very brief investigation:

- `create-solid` seems to only remove the `tempTemplate` dir inside your current working directory, which they define as `path.join(target, ".solid-start")`.
- and `create-vue` seems to explicitly check if they enter a `.`, requires a `--force`, and even re-prompts them that they're about to remove everything in that directory

**Comment by jculvey** [comment]
> Am I right saying that the newest implementation fails if the directory is non-empty, but allows the user to overwrite, which deletes **everything** from the target directory?
> If so, I'd be cautious about proceeding - this approach doesn't actually solve my main issue, rather it sets everything on fire and hides in the smoke. For the most part, there shouldn't be anything wrong deleting everything when I'm setting up a project, but what if I created a repo on GitHub that included a LICENSE`file? Now if that's deleted, do I have to recreate? With`.git` gone, do I have to clone again? 

That's fair. I'm going to change it back to the previous implementation of failing on non-empty directories but exempting files in an allow-list.

> What about other template files..

What are other template files?  

> For the most part, I'd say there's actually nothing c3 should validate here; create-{framework} (this is for pages/website templates only) already validates for files it considers safe, and as far as my understanding goes c3 doesn't usually create new files for the Pages deployment configuration. For workers, I'd keep the whitelist like other projects do, maybe expanding by the case insensitivity or some other files, but judging by the number of issues they've had I'd say their approach is just fine.

I don't think we want to drop validation entirely. `create-cloudflare` isn't designed to be run in existing projects, and we can't provide guarantees around that experience. Each framework creator will validate what files it considers safe, but it won't check for files that could potentially conflict with pages or workers itself. Additionally, we want to protect against scenarios where the user accidentally runs c3 in an existing directory where they didn't intend to.
