### PR TITLE
Change dev registry and inspector server to use 127.0.0.1 instead of all interfaces

### LINKED ISSUE #4430: 🐛 BUG: Wrangler is still listening on the wildcard address even with --ip localhost
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.15.0

### What version of Node are you using?

21.1.0

### What operating system are you using?

Mac

### Describe the Bug

When running `wrangler dev`, a lot of services are listening on the wildcard address. On machines without a firewall that could cause unnecessarily exposure.

Ports in question:

* node: port 9229 and 6284 and a random port (56547),
* workerd: port 8787
```
$ lsof -nPiTCP -sTCP:LISTEN
COMMAND   PID USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
node    51399  pwu   33u  IPv6 0xe8478a1f17ba37f      0t0  TCP *:9229 (LISTEN)
node    51399  pwu   37u  IPv4 0xe8478b51682305f      0t0  TCP *:56781 (LISTEN)
node    51399  pwu   38u  IPv6 0xe8478a1f17bab7f      0t0  TCP *:6284 (LISTEN)
workerd 51401  pwu   11u  IPv4 0xe8478b515f2f98f      0t0  TCP 127.0.0.1:56779 (LISTEN)
workerd 51401  pwu   12u  IPv6 0xe8478a1f17bb37f      0t0  TCP [::1]:56779 (LISTEN)
workerd 51401  pwu   14u  IPv4 0xe8478b5166e64ff      0t0  TCP *:8787 (LISTEN)
```

With `wrangler dev --ip localhost`, this improves such that workerd is no longer listening on the wildcard address:
```
$ lsof -nPiTCP -sTCP:LISTEN
COMMAND   PID USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
node    51416  pwu   36u  IPv6 0xe8478a1e7bdd37f      0t0  TCP *:9229 (LISTEN)
node    51416  pwu   37u  IPv6 0xe8478a1f161c37f      0t0  TCP [::1]:56788 (LISTEN)
node    51416  pwu   38u  IPv6 0xe8478a1e7bddb7f      0t0  TCP *:6284 (LISTEN)
workerd 51418  pwu   11u  IPv4 0xe8478b515f2f98f      0t0  TCP 127.0.0.1:56786 (LISTEN)
workerd 51418  pwu   12u  IPv6 0xe8478a1f17f5b7f      0t0  TCP [::1]:56786 (LISTEN)
workerd 51418  pwu   14u  IPv4 0xe8478b51682305f      0t0  TCP 127.0.0.1:8787 (LISTEN)
workerd 51418  pwu   15u  IPv6 0xe8478a1f17f537f      0t0  TCP [::1]:8787 (LISTEN)
```

Ports are defined here:
https://github.com/cloudflare/workers-sdk/blob/3637d97a99c9d5e8d0d2b5f3adaf4bd9993265f0/packages/wrangler/src/index.ts#L62-L63

Port 9229 is used for the inspector here:
https://github.com/cloudflare/workers-sdk/blob/3637d97a99c9d5e8d0d2b5f3adaf4bd9993265f0/packages/wrangler/src/dev/inspect.ts#L859-L865
https://github.com/cloudflare/workers-sdk/blob/3637d97a99c9d5e8d0d2b5f3adaf4bd9993265f0/packages/wrangler/src/dev/inspect.ts#L255

As you can see there is no reason it should listen on the wildcard given that it is only used locally. Let's change that to listen on localhost, https://nodejs.org/api/net.html#serverlisten
```diff
- server.listen(props.port);
+ server.listen(props.port, 'localhost');
```

Port 6284 appears to be used for a "service registry":
https://github.com/cloudflare/workers-sdk/blob/3637d97a99c9d5e8d0d2b5f3adaf4bd9993265f0/packages/wrangler/src/dev-registry.ts#L13-L14
https://github.com/cloudflare/workers-sdk/blob/3637d97a99c9d5e8d0d2b5f3adaf4bd9993265f0/packages/wrangler/src/dev-registry.ts#L83-L85

Again, it only appears to be used on localhost, so we should be able to change that as well?

Note that for those running `wrangler` in Docker with port-forwarding, it should probably still listen on the wildcard in that special case. Maybe the `--ip` option can be used to influence the above listen options?

Historical note: the dev server used to listen on localhost, but this was changed to listen on wildcard in #1605 which also added the `--ip` option.

Also related: security concerns about listening on external interfaces, #2036 (closed in favor of #4239).

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by jspspike**
Fixes #4430

The dev registry and inspector server listen on all interfaces when running `wrangler dev`, this might not be desired by users who use `--ip` to prevent listening beyond `localhost`. This PR will will make the dev registry and inspector server use `127.0.0.1`

- Tests
  - [ ] Included
  - [ ] Not necessary because: 
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [x] Not necessary because: Not a change that is user facing or affects user behavior

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

File: packages/wrangler/src/dev/inspect.ts [hunk 1]
```diff
@@ -252,19 +253,25 @@ export default function useInspector(props: InspectorProps) {
...
-			server.close();
+			//server.close();
 			// Also disconnect any open websockets/devtools connections
 			wsServer.clients.forEach((ws) => ws.close());
 			wsServer.close();
 			abortController.abort();
+			createHttpTerminator({
+				server,
+				gracefulTerminationTimeout: 0,
+			})
```
Comment (mrbbot) [inline packages/wrangler/src/dev/inspect.ts:272]: `createHttpTerminator()` internally [registers a listener](https://github.com/gajus/http-terminator/blob/aabca4751552e983f8a59ba896b7fb58ce3b4087/src/factories/createInternalHttpTerminator.ts#L39) for incoming connections on the `server`, so it can close the sockets when you call `terminate()`. This means you need to call `createHttpTerminator()` before any clients connect. See the dev registry code for the correct order:

```js
server = createServer(app);
terminator = createHttpTerminator({ server });
server.listen(DEV_REGISTRY_PORT, "127.0.0.1");
```

File: packages/wrangler/src/dev/inspect.ts [hunk 2]
```diff
@@ -252,19 +253,25 @@ export default function useInspector(props: InspectorProps) {
...
+			server.listen(props.port, "127.0.0.1");
 		}
 		startInspectorProxy().catch((err) => {
 			if ((err as { code: string }).code !== "ABORT_ERR") {
 				logger.error("Failed to start inspector:", err);
 			}
 		});
 		return () => {
-			server.close();
+			//server.close();
```
Comment (Lekensteyn) [inline packages/wrangler/src/dev/inspect.ts:264]: Should this be completely removed if you replace it with the graceful terminator below?

File: packages/wrangler/src/dev-registry.ts [hunk 3]
```diff
@@ -48,7 +48,7 @@ async function isPortAvailable() {
 				netServer.close();
 				resolve(true);
 			});
-		netServer.listen(DEV_REGISTRY_PORT);
+		netServer.listen(DEV_REGISTRY_PORT, "127.0.0.1");
```
Comment (Lekensteyn) [inline packages/wrangler/src/dev-registry.ts:51]: This seems to work just fine:
```suggestion
		netServer.listen(DEV_REGISTRY_PORT, "localhost");
```

Can we change 127.0.0.1 everywhere to `localhost` for IPv6(-only) support?

Comment (mrbbot) [reply packages/wrangler/src/dev-registry.ts:51]: Hmmm, if we did this, we wouldn't listen on the IPv4 interface (at least on my laptop 🙂).

```js
import http from "node:http";
const server = http.createServer((req, res) => res.end("body"));
server.listen(9999, "localhost")
```

```shell
$ curl http://localhost:9999
body
$ curl "http://[::1]:9999"
body
$ curl http://127.0.0.1:9999
curl: (7) Failed to connect to 127.0.0.1 port 9999 after 5 ms: Couldn't connect to server
```

Node will only listen on the first hostname resolved from DNS, which in this case is `[::1]`. The default resolution order was [changed in Node 17](https://github.com/nodejs/node/pull/39987), so Node versions before then would've listened on `127.0.0.1` instead.

**Review by mrbbot — APPROVED** [review]
