### PR TITLE
fix: better errors for workers commands in pages projects

### LINKED ISSUE #6793: 🐛 BUG: Throw an actionable error if we detect a Pages project using Workers commands
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

v3.78.7

### What version of Node are you using?

_No response_

### What operating system and version are you using?

Macos 14.6.1 (23G93)

### Observed behavior

When running commands such as `wrangler secrets list` or `wrangler deploy` we should be detecting if the project a user is in is a Pages project (has pages output dir in wrangler.toml) and throw an actionable error for the user pointing them to the command needed for Pages.
Currently, running these commands will do Worker actions and cause confusion for users.

For example, running `wrangler secrets list` currently outputs:
```
$ npx wrangler@latest secret list

✘ [ERROR] A request to the Cloudflare API (/accounts/4e599df4216133509abaac54b109a647/workers/scripts/pages-example/secrets) failed.

  This Worker does not exist on your account. [code: 10007]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

which is very confusing for a user - they know the Pages Worker exists but it says it doesn't.

Instead, we should do an output like:
```
$ npx wrangler@latest secret list

✘ [ERROR] This command is for Workers, for Pages please run `wrangler pages secret list`
```

Another example is deploy where it'll error about `main` not being set - if a user sets that, they're now gonna deploy a Worker which will not be what they want and will not work like they expect. This should also link to `wrangler pages deploy`.

---

I think for non-wrangler.toml projects, we cannot nicely handle this today but we can at least improve it for those with the toml file.

### Steps to reproduce

* Create a Pages project with wrangler.toml
* Attempt to do `wrangler secret list`

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by emily-shen**
## What this PR solves / how to test

Fixes #6793 

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [x] Tests included
  - [ ] Tests not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [ ] Required
  - [x] Not required because: covered adequately by unit tests
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [x] Changeset included
  - [ ] Changeset not necessary because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: just some better errors

### CODE REVIEW

File: packages/wrangler/src/deploy/index.ts [hunk 1]
```diff
@@ -254,6 +254,12 @@ export async function deployHandler(args: DeployArgs) {
 		args.config || (args.script && findWranglerToml(path.dirname(args.script)));
 	const projectRoot = configPath && path.dirname(configPath);
 	const config = readConfig(configPath, args);
+	if (config.pages_build_output_dir) {
+		throw new UserError(
+			"This command is for Workers, for Pages please run `wrangler pages deploy`."
```
Comment (CarmenPopoviciu) [inline packages/wrangler/src/deploy/index.ts:259]:
```suggestion
			"You are attempting to run a Workers specific command in a Pages project. Please use `wrangler pages deploy` instead."
```

or alternatively

```suggestion
			"You are attempting to run `wrangler deploy` in a Pages project. `wrangler deploy` is meant to deploy Workers to Cloudflare. For Pages, please use `wrangler pages deploy` instead."
```

or something along those lines

Comment (CarmenPopoviciu) [reply packages/wrangler/src/deploy/index.ts:259]: same for all the other errors

**Review by CarmenPopoviciu — APPROVED** [review]

**Comment by irvinebroque** [comment]
Love this!
