### PR TITLE
fix: ensure upstream_protocol is passed to the Worker

### LINKED ISSUE #4539: 🐛 BUG: `upstream_protocol` is ignored in the codebase
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.18.0

### What version of Node are you using?

18.17.1

### What operating system are you using?

Mac

### Describe the Bug

As visible from [the code search](https://github.com/search?q=repo%3Acloudflare%2Fworkers-sdk%20upstreamProtocol&type=code) the `upstream_protocol` option gets parsed and verified but never used.

Steps to reproduce
* define `upstream_protocol = "https"`
* make a request to the `wrangler dev` server
* see the outgoing requests being `http`
* also, see the upstream server redirecting to `https` as it should in 2024 :)

Expected
* outgoing requests use `https`

Thanks for the great work on the tool, awesome stuff!

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

No errors.

### PR DESCRIPTION
**Pull request by petebacondarwin**
**What this PR solves:**

In `wrangler dev` it is possible to set the `upstream_protocol`, which is the protocol under which the User Worker believes it has been requested, as recorded in the `request.url` that can be used for forwarding on requests to the origin.

This setting defaults to `https`. Previously, it was not being passed to `wrangler dev` in local mode. Instead it was always set to `http`.

Note that setting `upstream_protocol` to `http` is not supported in `wrangler dev` remote mode, which is the case since Wrangler v2.0.

Fixes #4539

**How to test:**

Using the build of Wrangler from this PR run `wrangler dev` on a simple worker as follows:

```ts
export default {
  fetch(request: Request) {
    return new Response(request.url);
  }
}
```

Note that the response will be a URL that has `https` as its protocol (e.g. `https://localhost:8787`).

Then run the same worker with `wrangler dev --upstream-protocol=http`. Now the response will have a URL that has `http` as the protocol.

**Author has addressed the following:**

- Tests
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [x] Not necessary because: bug fix - no docs changes needed.

### CODE REVIEW

File: packages/wrangler/src/dev/local.tsx [hunk 1]
```diff
@@ -172,7 +174,7 @@ function useLocalWorker(props: LocalProps) {
 						pathname: `/core:user:${props.name ?? DEFAULT_WORKER_NAME}`,
 					},
 					userWorkerInnerUrlOverrides: {
-						protocol: props.localProtocol,
+						protocol: props.upstreamProtocol,
```
Comment (petebacondarwin) [inline packages/wrangler/src/dev/local.tsx:177]: This is the key line in this PR.

File: packages/wrangler/src/dev/miniflare.ts [hunk 2]
```diff
@@ -530,7 +531,9 @@ async function buildMiniflareOptions(
 
 	const upstream =
 		typeof config.localUpstream === "string"
-			? `${config.localProtocol}://${config.localUpstream}`
+			? `${config.upstreamProtocol ?? config.localProtocol}://${
```
Comment (petebacondarwin) [inline packages/wrangler/src/dev/miniflare.ts:534]: And possibly this too!

File: packages/wrangler/src/dev/start-server.ts [hunk 3]
```diff
@@ -95,7 +95,7 @@ export async function startDevServer(
 				port: props.inspectorPort,
 			},
 			urlOverrides: {
-				secure: props.localProtocol === "https",
+				secure: props.upstreamProtocol === "https",
```
Comment (petebacondarwin) [inline packages/wrangler/src/dev/start-server.ts:98]: Currently `urlOverrides` is not used in the codebase but is expected to be used once we land the next phase of the startDev work, so this fix is needed here too.

**Comment by RamIdeas** [comment]
It's surprising to me that it defaults to https. In my opinion, request.url should be the actual url to reach the user worker by default. If there are config overrides to opt-in to change request.url, fine. But by default, it shouldn't be different from the eyeball.

**Comment by petebacondarwin** [comment]
> It's surprising to me that it defaults to https. In my opinion, request.url should be the actual url to reach the user worker by default. If there are config overrides to opt-in to change request.url, fine. But by default, it shouldn't be different from the eyeball.

Yes, ideally the URL the user hits and the upstream URL should be equivalent by default, but this is the current defaults, which I think are a legacy of the fact that it is easier for the remote preview worker to be HTTPS and it is easier for the local proxy server to be HTTP.

I think it is a breaking change to swap that default which has been like that since Wrangler 1.

**Comment by petebacondarwin** [comment]
> > It's surprising to me that it defaults to https. In my opinion, request.url should be the actual url to reach the user worker by default. If there are config overrides to opt-in to change request.url, fine. But by default, it shouldn't be different from the eyeball.
> 
> Yes, ideally the URL the user hits and the upstream URL should be equivalent by default, but this is the current defaults, which I think are a legacy of the fact that it is easier for the remote preview worker to be HTTPS and it is easier for the local proxy server to be HTTP.
> 
> I think it is a breaking change to swap that default which has been like that since Wrangler 1.

Actually, thinking about this more... Given that the current behaviour was not to send this through at all in local mode, then it is probably not a breaking change to change the default for local mode. For remote mode, https is the only possible value anyway, so that would have to stay the same.

**Comment by RamIdeas** [comment]
> Actually, thinking about this more... Given that the current behaviour was not to send this through at all in local mode, then it is probably not a breaking change to change the default for local mode. For remote mode, https is the only possible value anyway, so that would have to stay the same.

Yep that was my thinking too

File: packages/wrangler/src/config/validation.ts [hunk 4]
```diff
@@ -400,8 +401,13 @@ function normalizeAndValidateDev(
 		ip = process.platform === "win32" ? "127.0.0.1" : "localhost",
 		port,
 		inspector_port,
-		local_protocol = "http",
-		upstream_protocol = "https",
+		local_protocol = (args as { localProtocol: "http" | "https" })
+			.localProtocol ?? "http",
+		// In remote mode upstream_protocol must be https, otherwise it defaults to local_protocol.
+		upstream_protocol = (args as { upstreamProtocol: boolean })
```
Comment (mrbbot) [inline packages/wrangler/src/config/validation.ts:407]: Should `upstreamProtocol` be typed `"http" | "https"` too? Is there a way to avoid the `as`s here?

**Review by mrbbot — APPROVED** [review]
Looks good, one minor comment. Agree the default should be `http` for local mode. 👍

File: packages/wrangler/src/config/validation.ts (hunk 4 above)
Comment (mrbbot) [reply packages/wrangler/src/config/validation.ts:407]: > We need the cast here because `args` is typed as `unknown`.

If you're sure these will be "http" or "https", could you use a runtime assertion instead to narrow the types? Or change the type of `args` to encode this restriction?

Comment (petebacondarwin) [reply packages/wrangler/src/config/validation.ts]: Added some asserts

**Review by mrbbot — APPROVED** [review]
