### PR TITLE
write to output file on command failure

### LINKED ISSUE #10965: Check if a version upload will fail due to a DO migration
### Describe the solution

`wrangler versions upload` will fail if a change contains a durable object migration. Afaict, the only reliable way to check if a pending change contains a durable object migration is to run a `versions upload` and grep through the output, making scripting in CI difficult.

Since API calls are needed to validate this ([wrangler/src/durable.ts#L64C5-L68C58](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/durable.ts#L64C5-L68C58)) we can't update `--dry-run` to show pending DO migrations.

Instead, would it be possible to add a command such as `wrangler versions check` that validates if a worker version can be successfully uploaded?

```
✘ [ERROR] A request to the Cloudflare API (/accounts/2d755c260322537ff250be4cc2718320/workers/scripts/durable-object-migrations/versions) failed.

  Version upload failed. You attempted to upload a version of a Worker that includes a Durable
  Object migration, but migrations must be fully applied by running "wrangler deploy". See
  https://developers.cloudflare.com/workers/configuration/versions-and-deployments/gradual-deployments/#gradual-deployments-for-durable-objects
  for more information. [code: 10211]
  To learn more about this error, visit:
  https://developers.cloudflare.com/workers/configuration/versions-and-deployments/gradual-deployments/#gradual-deployments-for-durable-objects
```

### PR DESCRIPTION
**Pull request by nikitassharma**
Fixes #10965

When either WRANGLER_OUTPUT_FILE_PATH or WRANGLER_OUTPUT_FILE_DIRECTORY are set
in the environment, then command failures will append a line to the output file
encoding the error code and message, if present.

With issue #10965, a DO migration can be identified as follows
```bash
if [ "$(tail -1 ${WRANGLER_OUTPUT_FILE_PATH} | jq .code)" = "10211" ]; then
    # DO migration, handle as needed
fi
```

- Tests
  - [X] Tests included
  - [ ] Tests not necessary because:
- Public documentation
  - [ ] Cloudflare docs PR(s): 
  - [X] Documentation not necessary because: not documented
- Wrangler V3 Backport
  - [ ] Wrangler PR: 
  - [X] Not necessary because: not in v3

### CODE REVIEW

File: packages/wrangler/src/core/register-yargs-command.ts [hunk 1]
```diff
@@ -198,6 +199,18 @@ function createHandler(def: CommandDefinition, commandName: string) {
 			// TODO(telemetry): send command completed event
 		} catch (err) {
 			// TODO(telemetry): send command errored event
+
+			// Write handler failure to output file if one exists
+			const error = err as Error;
```
Comment (petebacondarwin) [inline packages/wrangler/src/core/register-yargs-command.ts]: Rather than a cast, how about doing:


```suggestion
			if (error instanceof Error) {
```

Comment (petebacondarwin) [reply packages/wrangler/src/core/register-yargs-command.ts]: Or further you could consider `error instanceof ApiError`
