### PR TITLE
Fix potential EBADF error when restarting workerd process in Miniflare

### LINKED ISSUE #11675: EBADF thrown when restarting workerd on vite server restart
### What versions & operating system are you using?

```
System:
  OS: macOS 26.1
  CPU: (14) arm64 Apple M4 Pro
  Memory: 1.30 GB / 48.00 GB
  Shell: 5.9 - /opt/homebrew/bin/zsh
Binaries:
  Node: 22.12.0 - /Users/spencer.alger/.local/state/fnm_multishells/96545_1765904624516/bin/node
  Yarn: 4.12.0 - /Users/spencer.alger/.local/state/fnm_multishells/96545_1765904624516/bin/yarn
  npm: 10.9.0 - /Users/spencer.alger/.local/state/fnm_multishells/96545_1765904624516/bin/npm
  bun: 1.2.19 - /Users/spencer.alger/Developer/ramp/web/.devbox/nix/profile/default/bin/bun
npmPackages:
  @cloudflare/vite-plugin: 1.13.7 => 1.13.7 
  wrangler: 4.40.2 => 4.55.0 
```

### Please provide a link to a minimal reproduction

I was unable to produce a repro outside of our proprietary repo unfortunately, definitely tried, open to ideas about what I might need to replicate.

### Describe the Bug

We're seeing a consistent issue when we change our vite config and the cloudflare plugin tries to restart the workerd process. When [this code](https://github.com/cloudflare/workers-sdk/blob/3483b841bedb78d67048cc8b9846e0598ec5fa6c/packages/miniflare/src/runtime/index.ts#L228-L231) runs at startup everything is fine, but when we update our vite config and this code runs again it throws an `EBADF` error that I can't quite wrap my head around.

I'm not 100% sure this is actually a workerd issue, but the error is definitely coming from the workerd library and I'm really hoping that someone might have a brilliant idea that helps explain why this is happening. If nothing else, it was surprising that nobody has filed such an issue yet.

`command`
```
"@@/node_modules/@cloudflare/workerd-darwin-arm64/bin/workerd"
```

`args`
```
[
  "serve",
  "--binary",
  "--experimental",
  "--socket-addr=entry=127.0.0.1:0",
  "--external-addr=loopback=127.0.0.1:51001",
  "--control-fd=3",
  "-",
  "--inspector-addr=localhost:9229",
]
```

and the error thrown:
```
{
  errno: -9,
  code: "EBADF",
  syscall: "spawn",
  stack: `Error: spawn EBADF
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at Object.spawn (node:child_process:753:9)
    at Runtime.updateConfig (@@/node_modules/miniflare/dist/src/index.js:49746:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async #assembleAndUpdateConfig (@@/node_modules/miniflare/dist/src/index.js:61776:30)
    at async #setOptions (@@/node_modules/miniflare/dist/src/index.js:62026:5)
    at async Mutex.runWith (@@/node_modules/miniflare/dist/src/index.js:38857:48)
    at async BasicMinimalPluginContext.configureServer (file://@@/node_modules/@cloudflare/vite-plugin/dist/index.js:17540:11)
    at async _createServer (file://@@/node_modules/vite/dist/node/chunks/node.js:26521:86)
    at async restartServer (file://@@/node_modules/vite/dist/node/chunks/node.js:26686:16)`
}
```

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by petebacondarwin**
Explicitly destroy all stdio streams (stdin, stdout, stderr, and control pipe) before killing the workerd process in Runtime#dispose(). This ensures file descriptors are properly released before spawning a new process, preventing EBADF errors during rapid restarts.

_The original issue was not able to provide a reproduction that we could test so this PR is speculative._

Fixes #11675

---

- Tests
  - [x] Tests included/updated
  - [ ] Automated tests not possible - manual testing has been completed as follows:
  - [ ] Additional testing not necessary because:
- Public documentation
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: bug fix

*A picture of a cute animal (not mandatory, but encouraged)*

---

<a href="https://app.devin.ai/review/cloudflare/workers-sdk/pull/12025">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

File: packages/miniflare/src/runtime/index.ts [hunk 1]
```diff
@@ -315,13 +315,35 @@ export class Runtime {
...
+		this.#process = undefined;
+
+		// Explicitly destroy all stdio streams to ensure file descriptors are
+		// properly released. This prevents EBADF errors when spawning a new
+		// process after restart.
+		// See https://github.com/cloudflare/workers-sdk/issues/11675
+		runtimeProcess.stdin?.destroy();
+		runtimeProcess.stdout?.destroy();
+		runtimeProcess.stderr?.destroy();
+		// The control pipe at stdio[3] is a Readable stream
```
Comment (vicb) [inline packages/miniflare/src/runtime/index.ts]: That's not consistent with l335?

File: packages/miniflare/src/runtime/index.ts [hunk 2]
```diff
@@ -315,13 +315,35 @@ export class Runtime {
...
+		const controlPipe = runtimeProcess.stdio[3];
+		if (controlPipe instanceof Readable) {
+			controlPipe.destroy();
+		}
+
 		// `kill()` uses `SIGTERM` by default. In `workerd`, this waits for HTTP
 		// connections to close before exiting. Notably, Chrome sometimes keeps
```
Comment (vicb) [inline packages/miniflare/src/runtime/index.ts:340]: Chrome?

Comment (vicb) [reply packages/miniflare/src/runtime/index.ts:340]: Oh I see, I think it was still std stuff, nvm

File: packages/miniflare/test/index.spec.ts [hunk 3]
```diff
@@ -3401,6 +3401,46 @@ test("Miniflare: custom Node outbound service", async () => {
 	);
 });
 
+test("Miniflare: setOptions: can restart workerd multiple times in succession", async () => {
+	// Regression test for https://github.com/cloudflare/workers-sdk/issues/11675
```
Comment (vicb) [inline packages/miniflare/test/index.spec.ts:3552]: annotate ?

as in https://vitest.dev/guide/test-annotations

Comment (petebacondarwin) [reply packages/miniflare/test/index.spec.ts:3552]: I think annotations are too noisy for this sort of thing. We don't need this to be displayed in every test run report.

File: packages/miniflare/src/runtime/index.ts (hunk 1 above)
Comment (petebacondarwin) [reply packages/miniflare/src/runtime/index.ts]: I guess this could be:


```suggestion
		// The control pipe at stdio[3] could be a Readable stream. If so also destroy it
```

File: packages/miniflare/test/index.spec.ts (hunk 3 above)
Comment (vicb) [reply packages/miniflare/test/index.spec.ts:3552]: https://vitest.dev/guide/test-annotations.html#built-in-reporters
The default reporter prints annotations only if the test has failed

Comment (petebacondarwin) [reply packages/miniflare/test/index.spec.ts:3552]: Yes but I regularly use verbose reporter.

Comment (petebacondarwin) [reply packages/miniflare/test/index.spec.ts:3552]: And more importantly, this link to the original issue is not needed in the reporter outpiut. If the test fails it is because something has broken that needs fixing. The original issue is only one of the sources for looking into what could be the cause.
