### PR TITLE
[vite-plugin] Fix crash when plugins send HMR events before runner initialization

### LINKED ISSUE #11063: Vite plugin fails with vite-plugin-vue-devtools and remote bindings enabled
### What versions & operating system are you using?

- node 24.3.0
- @cloudflare/vite-plugin 1.13.14
- vite 7.1.11
- vite-plugin-vue-devtools 8.0.3
- wrangler 4.44.0

### Please provide a link to a minimal reproduction

_No response_

### Describe the Bug

When we enable remote binding for our D1 database `npm run dev` fails when we have `vite-plugin-vue-devtools` plugin enabled as well.

When I remove `vueDevTools()` from `vite.config.js` `npm run dev` works just fine.

## Error log
```
$ npm run dev

> vite

node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

AssertionError [ERR_ASSERTION]: The WebSocket is undefined
    at Object.send (file:///Users/vojtadrbohlav/dev/sl/go-slideslive/node_modules/@cloudflare/vite-plugin/dist/index.js:6946:4)
    at Object.send (file:///Users/vojtadrbohlav/dev/sl/go-slideslive/node_modules/vite/dist/node/chunks/config.js:28501:149)
    at hmr (file:///Users/vojtadrbohlav/dev/sl/go-slideslive/node_modules/vite/dist/node/chunks/config.js:28659:20)
    at file:///Users/vojtadrbohlav/dev/sl/go-slideslive/node_modules/vite/dist/node/chunks/config.js:28666:80
    at Array.map (<anonymous>)
    at file:///Users/vojtadrbohlav/dev/sl/go-slideslive/node_modules/vite/dist/node/chunks/config.js:28666:59
    at handleHMRUpdate (file:///Users/vojtadrbohlav/dev/sl/go-slideslive/node_modules/vite/dist/node/chunks/config.js:28667:5)
    at async onHMRUpdate (file:///Users/vojtadrbohlav/dev/sl/go-slideslive/node_modules/vite/dist/node/chunks/config.js:28145:35)
    at async onFileAddUnlink (file:///Users/vojtadrbohlav/dev/sl/go-slideslive/node_modules/vite/dist/node/chunks/config.js:28163:3) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

Node.js v24.3.0
```

## `vite.config.js`
```js
import { fileURLToPath, URL } from 'node:url';

import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import vueDevTools from 'vite-plugin-vue-devtools';

import { cloudflare } from '@cloudflare/vite-plugin';

// https://vite.dev/config/
export default defineConfig({
  plugins: [vue(), vueDevTools(), cloudflare()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
});
```

## `wrangler.jsonc`
```
...
  "d1_databases": [
    {
      "binding": "DB",
      "database_name": "database",
      "database_id": "<uuid>",
      "migrations_table": "d1_migrations",
      "migrations_dir": "migrations",
      "remote": true
    }
  ]
```

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
Fixes #11063 

Previously, if another Vite plugin (such as `vite-plugin-vue-devtools`) sent HMR events during `configureServer` before the Cloudflare plugin had initialized its runner, the dev server would crash with `AssertionError: The WebSocket is undefined`. The environment's WebSocket operations are now deferred until the runner is fully initialized, allowing early HMR events to be handled gracefully.

---

- Tests
  - [x] Tests included/updated
  - [ ] Automated tests not possible - manual testing has been completed as follows:
  - [ ] Additional testing not necessary because:
- Public documentation
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: fixing a bug

*A picture of a cute animal (not mandatory, but encouraged)*

---

<a href="https://app.devin.ai/review/cloudflare/workers-sdk/pull/12859" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

**Comment by workers-devprod** [comment]
Codeowners approval required for this PR:
- ✅ @cloudflare/wrangler

<details><summary>Show detailed file reviewers</summary>


</details>

File: packages/vite-plugin-cloudflare/src/cloudflare-environment.ts [hunk 1]
```diff
@@ -71,31 +61,55 @@ function createHotChannel(
...
+						);
+						return value.apply(ws, args);
+					});
+			},
+			set(_target, property, _value) {
+				throw new Error(
+					`Internal Error: unexpected ${JSON.stringify(property)} set run on envWebSocket`
+				);
+			},
+		});
```
Comment (edmundhung) [inline packages/vite-plugin-cloudflare/src/cloudflare-environment.ts]: I am not sure if I like making these methods async. Could we instead buffer early `hot.send()` payloads in an array and flush them once the runner websocket is initialized?

Something like this: https://github.com/cloudflare/workers-sdk/commit/d9168a7aa579a5b4f877c392ce7647f9a81757a6

I don't think we need to buffer `client.send` or defer `hot.listen()` / `hot.close()`. as I believe they are only called by vite in a later step. If a plugin call it, it's probably a bad idea and we can rightfully crash? 🤔

Comment (dario-piotrowicz) [reply packages/vite-plugin-cloudflare/src/cloudflare-environment.ts]: Personally I really like the fact that here we can isolate complexity in the proxy object and make the rest of the code simpler and cleaner (at least in my opinion).

I can understand your point of view and also the proxy abstraction also is clearly not perfect.

I'm ok to instead go with the buffering, I cherry-picked your commit 👍
