### PR TITLE
Log token info after authentication errors

### LINKED ISSUE #1197: polish: On 10000/ auth errors, we should log details about the token
A significant number of bug reports/issues are about auth and tokens and stuff. While there are bugs that we should fix, some of it is just configuration. So when wrangler fails with a 10000 error, we should log details related to the token so it's easier to debug/report. (api for getting permission groups: https://api.cloudflare.com/#permission-groups-list-permission-groups)

### PR DESCRIPTION
**Pull request by penalosa**
Fixes #1197.

**What this PR solves / how to test:**

After the API returns an authentication error, log the token info returned by `whoami()`, to help the user diagnose the issue.

**Associated docs issue(s)/PR(s):**

- [insert associated docs issue(s)/PR(s)]

**Author has included the following, where applicable:**

- ~[ ] Tests~
- [x] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer is to perform the following, as applicable:**

- Checked for inclusion of relevant tests
- Checked for inclusion of a relevant changeset
- Checked for creation of associated docs updates
- Manually pulled down the changes and spot-tested

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

File: packages/wrangler/src/index.ts [hunk 1]
```diff
@@ -721,6 +722,9 @@ export async function main(argv: string[]): Promise<void> {
 			// The workaround is to re-run the parsing with an additional `--help` flag, which will result in the correct help message being displayed.
 			// The `wrangler` object is "frozen"; we cannot reuse that with different args, so we must create a new CLI parser to generate the help message.
 			await createCLIParser([...argv, "--help"]).parse();
+		} else if (isAuthenticationError(e)) {
+			logger.log(formatMessage(e));
+			await whoami();
```
Comment (JacobMGEvans) [inline packages/wrangler/src/index.ts:727]: Should this return or throw?

**Review by JacobMGEvans — CHANGES_REQUESTED** [review]

File: packages/wrangler/src/index.ts (hunk 1 above)
Comment (penalosa) [reply packages/wrangler/src/index.ts:727]: No, it's thrown at the end of this function
