### PR TITLE
Fix wrangler module import under npm monorepos

### LINKED ISSUE #7129: 🐛 BUG: wrangler fails to resolve wasm module in npm monorepo
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.83.0

### What version of Node are you using?

18.20.2

### What operating system and version are you using?

Ubuntu 24.04

### Observed behavior
Wrangler is only be able to resolve modules in a relative `node_modules` directory and not the workspace root `node_modules` directory. And will otherwise throw the following errors:

```plain
ENOENT: no such file or directory, open
  <an absolute path from the local node_modules>
The plugin "wrangler-module-collector" was triggered by this import
```

### Expected behavior
Wrangler resolution matches bundler resolution.

### Steps to reproduce

```bash
git clone -b intent https://github.com/nickbabcock/cloud-functions
npm install
npm run --workspace src/highwayhasher build
```

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by nickbabcock**
This PR updates import resolution for files and package exports

In an npm workspace environment, wrangler will now be able to successfully resolve package exports.

Previously, wrangler would only be able to resolve modules in a relative `node_modules` directory and not workspace root `node_modules` directory.

Installing locally fixes #7129

--- 

Soft ping to @Cherry who originally implemented this feature, some extra eyes would be appreciated 👀 

---

- Tests
  - [ ] TODO (before merge)
  - [x] Tests included
  - [ ] Tests not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [ ] Required
  - [x] Not required because: passing on https://github.com/cloudflare/workers-sdk/pull/7283
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: as this implements the behavior implied by documentation.

### CODE REVIEW

**Comment by Cherry** [comment]
Thanks for the ping!

Do the tests added for https://github.com/cloudflare/workers-sdk/pull/4135 and https://github.com/cloudflare/workers-sdk/pull/4748, with those use-cases, still work as expected here? I had issues getting `require.resolve` to play nicely unfortunately.

**Comment by nickbabcock** [comment]
That was my concern too, but (unless I'm missing something) they pass locally when I execute:
```
pnpm run --filter import-wasm-example test:watch
```

**Comment by nickbabcock** [comment]
Ah, I should have been executing the following to know if I introduced regressions:
```
pnpm run test:ci --concurrency 1 --filter=./fixtures/import-wasm-example
```
Turns out I did, and reintroducing `resolve` for non-exported members fixed the issue.

I still need to add a test before this PR is good to go.

**Comment by nickbabcock** [comment]
Alright, added npm workspace fixture which demonstrates the PR fixing the bundling issue.

✅ PR now ready for further review.

File: packages/wrangler/src/deployment-bundle/module-collection.ts [hunk 1]
```diff
@@ -284,46 +263,13 @@ export function createModuleCollector(props: {
...
-											);
-										}
-									} catch (e) {
-										// We tried, now it'll just fall-through to the previous behaviour
-										// and ENOENT if the absolute file path doesn't exist.
-									}
+								try {
+									filePath = require.resolve(args.path, {
+										paths: [args.resolveDir],
+									});
```
Comment (penalosa) [inline packages/wrangler/src/deployment-bundle/module-collection.ts:269]: I think this might be better using esbuild's resolution algorithm rather than `require.resolve()`? Something along the lines of:

```ts
const resolved = await build.resolve(args.path, {
  kind: "import-statement",
  resolveDir: args.resolveDir,
  pluginData: {
	  skip: true,
  },
  });
  if (resolved.path) {
  filePath = resolved.path;
  }
```

with a check for `pluginData.skip` at the top of the `onResolve()` callback to prevent infinite loops.

Comment (nickbabcock) [reply packages/wrangler/src/deployment-bundle/module-collection.ts]: Updated to use esbuild's plugin. All the tests seem to pass. Is there a particular reason why you prefer the esbuild plugin vs require.resolve?

**Review by penalosa — APPROVED** [review]

**Comment by emily-shen** [comment]
thanks so much for the contribution!
