### PR TITLE
Show a clearer user error when trying to use a python worker without the `python_workers` compatibility flag specified

### LINKED ISSUE #5479: 🐛 BUG: Need a better error for dev-ing Python modules when missing the `python_workers` compatibility flag
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.43.0

### What version of Node are you using?

_No response_

### What operating system and version are you using?

macOS

### Describe the Bug

If you're missing the `compatibility_flags = ["python_workers"]` in your `wrangler.toml`, you just get an opaque

```
✘ [ERROR] service core:user:worker: Uncaught Error: internal error


✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
```

when trying to `wrangler dev`.

This should be improved to instead be a useful error message prompting the user to add that flag to their config file.

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by penalosa**
## What this PR solves / how to test

Fixes #5479

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [ ] Required / Maybe required
  - [x] Not required because: not covered by e2e tests
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Not necessary because: messsaging improvement

### CODE REVIEW

File: packages/wrangler/src/config/index.ts [hunk 1]
```diff
@@ -156,6 +156,11 @@ export function readConfig(
 		if (!config.rules.some((rule) => rule.type === "PythonModule")) {
 			config.rules.push({ type: "PythonModule", globs: ["**/*.py"] });
 		}
+		if (!config.compatibility_flags.includes("python_workers")) {
```
Comment (andyjessop) [inline packages/wrangler/src/config/index.ts:159]: Nit: this `readConfig` function is growing and gaining more responsibilities. It's not the time or place for a big refactor, of course, but I'm wondering if we should extract the python validation code to a separate function to keep `readConfig` more readable as it grows.

File: packages/wrangler/src/__tests__/configuration.test.ts [hunk 2]
```diff
@@ -1,13 +1,50 @@
...
+import { runInTempDir } from "./helpers/run-in-tmp";
+import { writeWranglerToml } from "./helpers/write-wrangler-toml";
 import type {
 	ConfigFields,
 	RawConfig,
 	RawDevConfig,
 	RawEnvironment,
 } from "../config";
 
+describe.only("readConfig()", () => {
```
Comment (andyjessop) [inline packages/wrangler/src/__tests__/configuration.test.ts:14]: Was this left in unintentionally?

**Review by andyjessop — APPROVED** [review]
A few small comments, but otherwise LGTM!
