### PR TITLE
Fix `--test-scheduled` with custom builds & `--x-dev-env`

### LINKED ISSUE #7152: 🐛 BUG: `--test-scheduled` w/ custom build does not work from 3.80.0 onward
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.80.0

### What version of Node are you using?

20.9.0

### What operating system and version are you using?

macOS Sonoma 14.7.1

### Observed behavior

With a valid worker using a custom build, that exports a scheduled handler, and a cron trigger defined in the `wrangler.toml`, using `npx wrangler dev --test-scheduled` does not expose the `/__scheduled` route.

_However_, setting `--x-dev-env=false` alongside `--test-scheduled` does allow the `/__scheduled` route to be exposed again.

### Expected behavior

`/__scheduled` should be exposed with `--test-scheduled`

### Steps to reproduce

- `npm create cloudflare@latest --yes -- test --category demo --type scheduled --deploy false --git false --lang js --accept-defaults`
- `cd test`
- `printf "\n[build]\ncommand = \"true\"\n" >> wrangler.toml`
&nbsp;
- `npm i wrangler@3.79.0`
- `npx wrangler dev --test-scheduled`
- `curl "http://localhost:8787/__scheduled?cron=*+*+*+*+*"` => `Ran scheduled event`
&nbsp;
- `npm i wrangler@3.80.0`
- `npx wrangler dev --test-scheduled`
- `curl "http://localhost:8787/__scheduled?cron=*+*+*+*+*"` => `To test the scheduled handler ...`&nbsp;
- `npm i wrangler@3.80.0`
- `npx wrangler dev --test-scheduled --x-dev-env=false`
- `curl "http://localhost:8787/__scheduled?cron=*+*+*+*+*"` => `Ran scheduled event`

### Side note

As an aside, all versions after `3.72.3` (`3.73.0` is the first broken) log the `Use '--test-scheduled' to forward fetch triggers` warning even when `--test-scheduled` is provided.

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by penalosa**
Fixes #7152 

Correctly pass the `--test-scheduled` flag in `BundleController` when using a custom build. Previously the types for `bundleWorker()` allowed arguments not to be passed—this PR changes that to require an explicit `undefined` to be passed, which should prevent this type of regression happening again.

---

- Tests
  - [ ] TODO (before merge)
  - [x] Tests included
  - [ ] Tests not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [x] Required
  - [ ] Not required because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: bugfix

### CODE REVIEW

File: packages/wrangler/src/deployment-bundle/bundle.ts [hunk 1]
```diff
@@ -424,10 +422,7 @@ export async function bundleWorker(
 				...define,
 			},
 		}),
-		loader: {
-			...COMMON_ESBUILD_OPTIONS.loader,
-			...(loader || {}),
```
Comment (penalosa) [inline packages/wrangler/src/deployment-bundle/bundle.ts:429]: The loader option wasn't used anywhere, so I removed it

File: packages/wrangler/src/versions/upload.ts [hunk 2]
```diff
@@ -321,6 +322,17 @@ See https://developers.cloudflare.com/workers/platform/compatibility-dates for m
 							props.compatibilityDate ?? config.compatibility_date,
 							props.compatibilityFlags ?? config.compatibility_flags
 						),
+						plugins: [logBuildOutput(nodejsCompatMode)],
```
Comment (penalosa) [inline packages/wrangler/src/versions/upload.ts:325]: This is a separate fix to unify versions & deploy messaging

File: packages/wrangler/src/api/startDevWorker/BundlerController.ts [hunk 3]
```diff
@@ -133,6 +133,20 @@ export class BundlerController extends Controller<BundlerControllerEventMap> {
 							config.compatibilityDate,
 							config.compatibilityFlags
 						),
+						testScheduled: config.dev.testScheduled,
```
Comment (penalosa) [inline packages/wrangler/src/api/startDevWorker/BundlerController.ts:136]: This is the actual fix for the reported issue

**Comment by MattIPv4** [comment]
👋 Just confirming that following my repro steps in the issue, /__scheduled works as expected with this preview version, and the warning is also no longer showing!

**Review by GregBrimble — APPROVED** [review]

File: packages/wrangler/src/__tests__/navigator-user-agent.test.ts [hunk 4]
```diff
@@ -110,6 +110,7 @@ describe("defineNavigatorUserAgent is respected", () => {
 				exports: [],
 			},
 			path.resolve("dist"),
+			// @ts-expect-error Ignore the requirement for passing undefined values
```
Comment (edmundhung) [inline packages/wrangler/src/__tests__/navigator-user-agent.test.ts:113]: Nit: Just wanted to avoid `@ts-expect-error`. This might also make the test clearer which options the tests really cares.

```ts
{
  // Extracted from the original options
  ...defaultBundleOptions,
  defineNavigatorUserAgent: false,
}
```

**Review by edmundhung — APPROVED** [review]
