### PR TITLE
Fix Durable Object dev registry websockets

### LINKED ISSUE #2676: 🐛 BUG: Proxying a websocket connection to a durable object (defined in a worker) leads to "invalid upgrade header" error in wrangler pages dev.
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler

### What version of `Wrangler` are you using?

2.9.0

### What operating system are you using?

Linux

### Describe the Bug

Proxying a websocket connection to a durable object (defined in a worker) leads to "invalid upgrade header" error in wrangler pages dev.

Replicate:

```
git clone https://github.com/amadeuspagel/pages-do-minimal
cd pages-do-minimal
npm run devworker
npm run devpages
```

then open localhost:8788

### PR DESCRIPTION
**Pull request by GregBrimble**
Fixes #2676.

**What this PR solves / how to test:**

**Author has included the following, where applicable:**

- [ ] Tests
- [ ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer has performed the following, where applicable:**

- [ ] Checked for inclusion of relevant tests
- [ ] Checked for inclusion of a relevant changeset
- [ ] Checked for creation of associated docs updates
- [ ] Manually pulled down the changes and spot-tested

### CODE REVIEW

File: packages/wrangler/src/miniflare-cli/index.ts [hunk 1]
```diff
@@ -87,7 +87,7 @@ async function main() {
 								id.toString()
 							);
 
-							return fetch(request);
+							return upgradingFetch(request);
```
Comment (CarmenPopoviciu) [inline packages/wrangler/src/miniflare-cli/index.ts:90]: this is all it took ha? 😅

Comment (GregBrimble) [reply packages/wrangler/src/miniflare-cli/index.ts:90]: Yup!

**Review by CarmenPopoviciu — APPROVED** [review]

**Comment by CarmenPopoviciu** [comment]
LGTM. I'd maaaaybe hold off until Kevin confirms this fixes the issues he encounters as well, but your call
