### PR TITLE
Fix `keep_vars` having no effect in wrangler.toml

### LINKED ISSUE #2866: 🐛 BUG: keep_vars in wrangler.toml is not respected
### Which Cloudflare product(s) does this pertain to?

Workers/Other, Wrangler

### What version of `Wrangler` are you using?

2.12.0

### What operating system are you using?

Linux

### Describe the Bug

With keep_vars set on wrangler.toml, variables are still removed from Worker, using command `wrangler publish`.
In other hand, when using command `wrangler publish --keep-vars`, it's working correctly and manually configured variables are not removed.

### PR DESCRIPTION
**Pull request by jspspike**
Fixes #2866 

**Author has included the following, where applicable:**

- [x] Tests
- [x] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer has performed the following, where applicable:**

- [x] Checked for inclusion of relevant tests
- [x] Checked for inclusion of a relevant changeset
- [x] Checked for creation of associated docs updates
- [ ] Manually pulled down the changes and spot-tested

### CODE REVIEW

File: packages/wrangler/src/publish/publish.ts [hunk 1]
```diff
@@ -335,7 +335,7 @@ See https://developers.cloudflare.com/workers/platform/compatibility-dates for m
 
 	const jsxFactory = props.jsxFactory || config.jsx_factory;
 	const jsxFragment = props.jsxFragment || config.jsx_fragment;
-	const keepVars = props.keepVars ?? config.keep_vars;
+	const keepVars = props.keepVars || config.keep_vars;
```
Comment (petebacondarwin) [inline packages/wrangler/src/publish/publish.ts:338]: Mea culpa. I added this bug.

**Review by petebacondarwin — APPROVED** [review]
Thanks for fixing this @jspspike
