### PR TITLE
fix(wrangler) Clean `pages dev` terminal output

### LINKED ISSUE #4265: 🐛 BUG: pages dev output is unnecessarily verbose
### Which Cloudflare product(s) does this pertain to?

Pages, Wrangler core

### What version(s) of the tool(s) are you using?

3.14.0

### What version of Node are you using?

18.18.0

### What operating system are you using?

Windows

### Describe the Bug

When running `npx wrangler pages dev <dir>`, you get a _LOT_ of verbose output:

image

```
> npx wrangler pages dev ./dist

▲ [WARNING] No compatibility_date was specified. Using today's date: 2023-10-23.

  Pass it in your terminal:
  \`\`\`
  --compatibility-date=2023-10-23
  \`\`\`
  See https://developers.cloudflare.com/workers/platform/compatibility-dates/ for more information.


Compiling worker to "C:\Users\james\AppData\Local\Temp\functionsWorker-0.005178014829587907.mjs"...
✨ Compiled Worker successfully
 ⛅️ wrangler 3.14.0
-------------------
▲ [WARNING] --local is no longer required and will be removed in a future version.

  `wrangler dev` now uses the local Cloudflare Workers runtime by default. 🎉


⎔ Starting local server...
▲ [WARNING] Parsed 5 valid header rules.


[mf:wrn] The latest compatibility date supported by the installed Cloudflare Workers Runtime is "2023-10-16",
but you've requested "2023-10-23". Falling back to "2023-10-16"...
kj/async-io-win32.c++:982: warning: Bind address resolved to multiple addresses.  Only the first address will be used.  If this is incorrect, specify the address numerically.  This may be fixed in the future.; addrs[0].toString() = 127.0.0.1:59452
[mf:inf] Ready on http://0.0.0.0:8788
[mf:inf] - http://172.22.208.1:8788
[mf:inf] - http://192.168.50.240:8788
[mf:inf] - http://127.0.0.1:8788
```

That's a lot of visual noise to try and scan and determine if my command was successful or not.

This is without any `wrangler.toml` in my directory.

Actionable things I'd recommend:

- Reduce compat date warnings. Improved in https://github.com/cloudflare/workers-sdk/pull/4209
- Remove `--local` warning - pages dev is ONLY local and I didn't even pass this. I suspect it's coming from `unstable_dev`: https://github.com/cloudflare/workers-sdk/pull/4687
- Remove "warnings" for valid header rules
- Remove workerd startup warnings with multiple networks in windows: https://github.com/cloudflare/workerd/issues/1408

### PR DESCRIPTION
**Pull request by CarmenPopoviciu**
## What this PR solves / how to test

The `wrangler pages dev` terminal output is currently a bit noisy and lacking a clearer, more organised structure. This PR cleans up the `pages dev` `stdout`/`stderr` logs in an attempt to make it more readable and easier to reason about for our users (and ourselves 😉 ) <3

<details>
<summary>After TLDR;</summary>

Screenshot 2024-06-05 at 14 25 39
Screenshot 2024-06-05 at 14 26 47
</details>

As part of this PR, the following issues were addressed:
<details>
<summary>1. `compatibility-date` warnings</summary>

**Before**
`wrangler dev`
Screenshot 2024-05-27 at 16 34 51

`wrangler pages dev`
Screenshot 2024-05-27 at 16 33 46

**After**
`wrangler dev` 
Screenshot 2024-05-27 at 17 31 51

`wrangler pages dev`
Screenshot 2024-05-27 at 16 32 56
</details>

<details>
<summary>2. wrangler logo display</summary>

**Before** 
`wrangler dev`
Screenshot 2024-05-27 at 18 49 39

`wrangler pages dev`
Screenshot 2024-05-27 at 18 50 30

**After**
`wrangler dev`
Screenshot 2024-05-27 at 18 32 42

`wrangler pages dev`
Screenshot 2024-05-27 at 18 32 02

</details>

<details>
<summary>3. `_headers` / `_redirects` parsing warnings</summary>

**Before**
Screenshot 2024-06-05 at 11 33 19

**After**
Screenshot 2024-06-05 at 11 37 09

</details>

<details>
<summary>4. verbiage in `_routes.json` warning</summary>

**Before**
Screenshot 2024-06-05 at 13 07 58

**After**
Screenshot 2024-06-05 at 13 07 13

</details>

<details>
<summary>5. Output "Compiling worker to..." to `debug` logs</summary>

**Before**
Screenshot 2024-06-05 at 13 25 12

**After**
Screenshot 2024-06-05 at 13 24 35

</details>

Fixes #4265.

⚡️⚡️⚡️**Please review per commit, as each commit addresses a separate issue** 🙏 

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [x] Required / Maybe required
  - [ ] Not required because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): <https://github.com/cloudflare/cloudflare-docs/pull/>...
  - [x] Not necessary because: terminal output format is not documented anywhere AFAIK

### CODE REVIEW

**Review by WalshyDev — APPROVED** [review]
This looks awesome, thank you so much for cleaning this up!

File: packages/wrangler/src/dev.tsx [hunk 1]
```diff
@@ -293,6 +293,8 @@ export function devOptions(yargs: CommonYargsArgv) {
 type DevArguments = StrictYargsOptionsToInterface<typeof devOptions>;
 
 export async function devHandler(args: DevArguments) {
+	await printWranglerBanner();
```
Comment (penalosa) [inline packages/wrangler/src/dev.tsx:296]: This should still take `args.updateCheck`

Comment (CarmenPopoviciu) [reply packages/wrangler/src/dev.tsx:296]: I can add, but to verify my assumption here...can `--update-check` actually ever be passed to `wrangler dev`? It is not defined in `devOptions`, so unless it inherits it from somewhere I figure it's safe to be removed from that API call?

Comment (penalosa) [reply packages/wrangler/src/dev.tsx:296]: Oh good point! In that case completely ignore me

File: packages/wrangler/src/__tests__/dev.test.tsx [hunk 2]
```diff
@@ -113,20 +113,15 @@ describe("wrangler dev", () => {
...
-			          \`\`\`
-			          --compatibility-date=<current-date>
-			          \`\`\`
-			          See [4mhttps://developers.cloudflare.com/workers/platform/compatibility-dates/[0m for more information.
+"[33m▲ [43;33m[[43;30mWARNING[43;33m][0m [1mNo compatibility_date was specified. Using the installed Workers runtime's latest supported date: <current-date>.[0m
 
-			        "
-		      `);
+  ❯❯ Add one to your wrangler.toml file: compatibility_date = \\"<current-date>\\", or
+  ❯❯ Pass it in your terminal: wrangler dev [<SCRIPT>] --compatibility-date=<current-date>
```
Comment (penalosa) [inline packages/wrangler/src/__tests__/dev.test.tsx:119]: Should this be `wrangler pages dev [<ASSETS>]`?

File: packages/wrangler/src/api/dev.ts [hunk 3]
```diff
@@ -126,6 +128,12 @@ export async function unstable_dev(
 		enablePagesAssetsServiceBinding,
 	} = experimentalOptions;
 
+	const updateCheck = options?.updateCheck ?? false;
+
+	if (!options?.disableWranglerBanner) {
+		await printWranglerBanner(updateCheck);
+	}
```
Comment (penalosa) [inline packages/wrangler/src/api/dev.ts:135]: Perhaps controversial, but what about just removing this from `unstable_dev` entirely? I can't really see any reason someone would want this if they're using Wrangler as an API

File: packages/wrangler/src/update-check.ts [hunk 4]
```diff
@@ -16,11 +16,13 @@ export async function printWranglerBanner(performUpdateCheck = true) {
...
 	logger.log(
-		text +
+		"\n" +
+			text +
 			"\n" +
 			(supportsColor.stdout
 				? chalk.hex("#FF8800")("-".repeat(text.length))
-				: "-".repeat(text.length))
+				: "-".repeat(text.length)) +
+			"\n"
```
Comment (penalosa) [inline packages/wrangler/src/update-check.ts:25]: Is there a reason we're changing the general shape of the banner? This will affect every Wrangler command, I think?

File: packages/pages-shared/metadata-generator/createMetadataObject.ts [hunk 5]
```diff
@@ -61,18 +68,31 @@ function constructRedirects({
 	const num_valid = redirects.rules.length;
 	const num_invalid = redirects.invalid.length;
 
+	// exhaustive check, since we could not have parsed `redirects` out of
+	// a non-existing redirects file
+	const redirectsRelativePath = redirectsFile
+		? relative(process.cwd(), redirectsFile)
+		: "";
```
Comment (penalosa) [inline packages/pages-shared/metadata-generator/createMetadataObject.ts:75]: Could this just be an assert on `redirectsFile`?

**Review by penalosa — APPROVED** [review]

File: packages/wrangler/src/__tests__/dev.test.tsx (hunk 2 above)
Comment (CarmenPopoviciu) [reply packages/wrangler/src/__tests__/dev.test.tsx:119]: these are the wrangler proper `dev` tests

File: packages/wrangler/src/api/dev.ts (hunk 3 above)
Comment (CarmenPopoviciu) [reply packages/wrangler/src/api/dev.ts:135]: I 100% agree. The only reason I implemented the flag was because I was afraid I might be missing some context around how folks depend on this API, and didn't want to break any existing expectations. But if we're good with what you're proposing, I'm abs behind the idea!

File: packages/wrangler/src/update-check.ts (hunk 4 above)
Comment (CarmenPopoviciu) [reply packages/wrangler/src/update-check.ts:25]: indeed it will. My perception was that, without the new extra space, the logo tends to be squished by all other logs, which gives it all a crammed feeling. Like this, it gets some nicer spacing between it and everything else that gets logged after. But this is all purely my aesthetic feeling.

You can see what I'm referring to in the screenshot I added in the `wrangler logo display` section, for `wrangler dev`.

File: packages/wrangler/src/dev.tsx (hunk 1 above)
Comment (Skye-31) [reply packages/wrangler/src/dev.tsx:296]: `updateCheck` is set by unstable dev to avoid calling out to NPM in your tests (though this is definitely less relevant with the vitest stuff), but if this handler gets called by unstable_dev, it should probably remain to keep that behaviour

File: packages/wrangler/src/api/dev.ts (hunk 3 above)
Comment (Skye-31) [reply packages/wrangler/src/api/dev.ts:135]: I had originally added this when unstable_dev was the best way to write tests, and wanted to avoid a network call when I had disabled `net.connect`. Now that we have vitest-pool-workers, I don't think it's as necessary anymore, but I'll let you decide

File: packages/wrangler/src/dev.tsx (hunk 1 above)
Comment (CarmenPopoviciu) [reply packages/wrangler/src/dev.tsx:296]: wrangler proper doesn't use `unstable_dev`, and this is the `wrangler dev` handler, so I assume we're good?

File: packages/wrangler/src/api/dev.ts (hunk 3 above)
Comment (CarmenPopoviciu) [reply packages/wrangler/src/api/dev.ts:135]: awesome! thank you for providing the context ❤️

Comment (CarmenPopoviciu) [reply packages/wrangler/src/api/dev.ts:135]: ✅

File: packages/pages-shared/metadata-generator/createMetadataObject.ts (hunk 5 above)
Comment (CarmenPopoviciu) [reply packages/pages-shared/metadata-generator/createMetadataObject.ts]: oh, `assert`ing on that redirectsFile actually breaks some `pages-shared` files, so I'd rather leave it out

File: packages/wrangler/src/dev.tsx (hunk 1 above)
Comment (Skye-31) [reply packages/wrangler/src/dev.tsx:303]: Sounds good to me

File: packages/wrangler/src/pages/dev.ts [hunk 6]
```diff
@@ -251,12 +251,7 @@ export const Handler = async (args: PagesDevArguments) => {
 		logger.loggerLevel = args.logLevel;
 	}
 
-	/*
-	 * `unstable_dev` already does this for us, but ideally we'd want to print
-	 * the banner right at the top, before any other logs. So let's turn that
-	 * off, and print here instead.
-	 */
-	await printWranglerBanner(true);
```
Comment (CarmenPopoviciu) [inline packages/wrangler/src/pages/dev.ts]: `pages dev` is the only place where we call `printWranglerBanner(true);`. In the spirit of consistency, changing this to `printWranglerBanner();`, which basically mean, we won't check whether a new wrangler version is available, and will just display the currently installed version

**Review by RamIdeas — APPROVED** [review]
