### PR TITLE
C3: Detect production branch when creating pages project

### LINKED ISSUE #3637: 🐛 BUG: c3 fails to deploy Astro if git init.defaultBranch is set to something else than `main`
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

2.0.13

### What version of Node are you using?

18.14.2

### What operating system are you using?

Mac

### Describe the Bug

if you set the git defaults to not use `main` as the default branch, for example by calling:
```
git config --global init.defaultBranch master
```

and then invoke c3 to create an Astro project:
```
$ npx create-cloudflare@latest

using create-cloudflare version 2.0.13

╭ Create an application with Cloudflare Step 1 of 3
│ 
├ In which directory do you want to create your application?
│ dir ./proud-wildflower-f3fb
│
├ What type of application do you want to create?
│ type Website or web app
│
├ Which development framework do you want to use?
│ framework Astro
│
╰ Continue with Astro via `npx create-astro@3.1.5 proud-wildflower-f3fb --no-install`
...
```

The application will be deployed but the deployment will not be accessible at the production url, for example https://proud-wildflower-f3fb.pages.dev

This appears to be because the application is by default deployed with production branch hardcoded as `main`:
```
├ Creating Pages project 
│ created via `npx wrangler pages project create proud-wildflower-f3fb --productio
n-branch main `
│ 
├ Deploying your application 
│ deployed via `npm run pages:deploy`
│ 
├  SUCCESS  View your deployed application at https://proud-wildflower-f3fb.pages.dev
│ 
```

But since this `main` branch doesn't exist, Pages defaults to creating a "preview" deployment rather than production deployment:

Screenshot 2023-07-19 at 11 05 24 AM

As far as I can tell, I think there are two things that could be fixed here:
- [ ] C3 should not hardcode the default git branch, and instead try to read the current git branch name, or the git config to determine the branch name to use
- [ ] `wrangler pages project create` behavior is surprising and maybe we could warn or error if this kind of misconfiguration is detected?

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

$ npx create-cloudflare@latest

using create-cloudflare version 2.0.13

╭ Create an application with Cloudflare Step 1 of 3
│ 
├ In which directory do you want to create your application?
│ dir ./proud-wildflower-f3fb
│
├ What type of application do you want to create?
│ type Website or web app
│
├ Which development framework do you want to use?
│ framework Astro
│
╰ Continue with Astro via `npx create-astro@3.1.5 proud-wildflower-f3fb --no-install`

╭─────╮  Houston:
│ ◠ ◡ ◠  Let's claim your corner of the internet.
╰─────╯

 astro   v2.8.5 Launch sequence initiated.

      ◼  dir Using proud-wildflower-f3fb as project directory

  tmpl   How would you like to start your new project?
         Include sample files
      ✔  Template copied
      ◼  No problem! Remember to install dependencies after setup.

    ts   Do you plan to write TypeScript?
         Yes

   use   How strict should TypeScript be?
         Strict
      ✔  TypeScript customized

   git   Initialize a new git repository?
         Yes
      ✔  Git initialized

  next   Liftoff confirmed. Explore your project!

         Enter your project directory using cd ./proud-wildflower-f3fb 
         Run npm run dev to start the dev server. CTRL+C to stop.
         Add frameworks like react or tailwind using astro add.

         Stuck? Join us at https://astro.build/chat

╭─────╮  Houston:
│ ◠ ◡ ◠  Good luck out there, astronaut! 🚀
╰─────╯

╭ Configuring your application for Cloudflare Step 2 of 3
│ 
├ Installing dependencies 
│ installed via `npm install`
│ 
├ Installing adapter 
│ installed via `npx astro add cloudflare`
│ 
├ Installing wrangler A command line tool for building Cloudflare Workers 
│ installed via `npm install wrangler --save-dev`
│ 
├ Adding command scripts for development and deployment
│ added commands to `package.json`
│ 
╰ Application configured 

╭ Deploy with Cloudflare Step 3 of 3
│ 
├ Do you want to deploy your application?
│ yes deploy via `npm run pages:deploy`
│
├ Logging into Cloudflare checking authentication status 
│ logged in
│ 
├ Selecting Cloudflare account retrieving accounts 
│ account more than one account available
│ 
├ Which account do you want to use?
│ account Project Igor
│
├ Creating Pages project 
│ created via `npx wrangler pages project create proud-wildflower-f3fb --productio
n-branch main `
│ 
├ Deploying your application 
│ deployed via `npm run pages:deploy`
│ 
├  SUCCESS  View your deployed application at https://proud-wildflower-f3fb.pages.dev
│ 
│ Navigate to the new directory: cd proud-wildflower-f3fb
│ Run the development server npm run pages:dev
│ Deploy your application npm run pages:deploy
│ Read the documentation https://developers.cloudflare.com/pages
│ Stuck? Join us at https://discord.gg/cloudflaredev
│ 
├ Waiting for DNS to propagate 
│ DNS propagation complete.
│ 
├ Waiting for deployment to become available 
│ timed out while waiting for https://proud-wildflower-f3fb.pages.dev - try access
ing it in a few minutes.
│ 
╰ See you again soon!

### PR DESCRIPTION
**Pull request by jculvey**
Fixes #3637.

**What this PR solves / how to test:**

This fixes an issue where pages project will fail to be created properly if the user has a different default branch name configured other than `main`. That's because the production branch is currently hardcoded. This fixes it by detecting the current branch and passing that along to `wrangler pages project create`.

**Associated docs issue(s)/PR(s):**

- [insert associated docs issue(s)/PR(s)]

**Author has included the following, where applicable:**

- [ ] Tests
- [ x ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer is to perform the following, as applicable:**

- Checked for inclusion of relevant tests
- Checked for inclusion of a relevant changeset
- Checked for creation of associated docs updates
- Manually pulled down the changes and spot-tested

### CODE REVIEW

File: packages/create-cloudflare/src/common.ts [hunk 1]
```diff
@@ -315,3 +315,21 @@ export async function initializeGit(cwd: string) {
 		await runCommand(`git init`, { useSpinner: false, silent: true, cwd });
 	}
 }
+
+export async function getProductionBranch(cwd: string) {
+	try {
+		const producitonBranch = await runCommand(
+			"git rev-parse --abbrev-ref HEAD",
```
Comment (RamIdeas) [inline packages/create-cloudflare/src/common.ts:322]: Is there a reason to not use `git branch --show-current`? If it's to support older version of git, I suggest:

```suggestion
      // "git branch --show-current", // git@^2.22
			"git rev-parse --abbrev-ref HEAD", // git@^1.6.3
```

File: packages/create-cloudflare/src/common.ts [hunk 2]
```diff
@@ -315,3 +315,21 @@ export async function initializeGit(cwd: string) {
 		await runCommand(`git init`, { useSpinner: false, silent: true, cwd });
 	}
 }
+
+export async function getProductionBranch(cwd: string) {
+	try {
+		const producitonBranch = await runCommand(
```
Comment (RamIdeas) [inline packages/create-cloudflare/src/common.ts:321]: nit: 
```suggestion
		const productionBranch = await runCommand(
```

File: packages/create-cloudflare/src/common.ts [hunk 3]
```diff
@@ -315,3 +315,21 @@ export async function initializeGit(cwd: string) {
...
+			"git rev-parse --abbrev-ref HEAD",
+			{
+				silent: true,
+				cwd,
+				useSpinner: false,
+				captureOutput: true,
+			}
+		);
+
+		return producitonBranch.trim();
```
Comment (RamIdeas) [inline packages/create-cloudflare/src/common.ts:331]: nit

```suggestion
		return productionBranch.trim();
```

File: packages/create-cloudflare/src/common.ts [hunk 4]
```diff
@@ -315,3 +315,21 @@ export async function initializeGit(cwd: string) {
...
+	} catch (err) {}
+
+	return "main";
```
Comment (RamIdeas) [inline packages/create-cloudflare/src/common.ts:334]: What happens if the user chose to not use git? Will the default `main` still work or should we throw a better error than the potential crash would?

**Review by RamIdeas — APPROVED** [review]
minor suggestions

File: packages/create-cloudflare/src/common.ts (hunk 4 above)
Comment (petebacondarwin) [reply packages/create-cloudflare/src/common.ts:334]: Pages needs a "production branch" even if git isn't used (e.g. for direct uploads). It is used as a tag for the production environment. So I think this is OK.
We should move this return statement inside the catch block, though, rather than having an empty catch block.

Comment (jculvey) [reply packages/create-cloudflare/src/common.ts:334]: It'll default to the current behavior. We need to supply a `--productionBranch` argument to the pages create command, otherwise the call to `wrangler pages project create` will fail when it demands interactive input.

File: packages/create-cloudflare/src/common.ts (hunk 1 above)
Comment (jculvey) [reply packages/create-cloudflare/src/common.ts:322]: Nope no reason, I just copied the wrangler code. Good suggestion
