### PR TITLE
fix analog template and tests - bumping to 2.1.3

### LINKED ISSUE #11470: create-cloudflare doesn't produce functioning Analog projects
### What versions & operating system are you using?

```
  System:
    OS: macOS 26.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 279.19 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.20.0 - /Users/dario/.nvm/versions/node/v22.20.0/bin/node
    Yarn: 1.22.22 - /Users/dario/.yarn/bin/yarn
    npm: 10.9.3 - /Users/dario/.nvm/versions/node/v22.20.0/bin/npm
    pnpm: 9.12.2 - /Users/dario/Library/pnpm/pnpm
    bun: 1.0.6 - /Users/dario/.bun/bin/bun
    Deno: 1.25.3 - /opt/homebrew/bin/deno
  npmPackages:
    wrangler: ^4.51.0 => 4.51.0 
```

### Please provide a link to a minimal reproduction

no minimal repro needed

### Describe the Bug

If I use create-cloudflare to create an Analog project (specifically `npm create cloudflare -- --framework=analog my-c3-analog-app`) the resulting project fails to build, with the following error:
```
An unhandled exception occurred: Could not find the implementation for builder @analogjs/platform:vite
See "/private/var/folders/7c/rlg3zs454_jfwt_x_10j1gjr0000gp/T/ng-xTi7ue/angular-errors.log" for further details.
```

See:
https://github.com/user-attachments/assets/6cb7d6ae-1080-41ec-8db9-982cac3ab98b

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by petebacondarwin**
Fixes #11470

---

- Tests
  - [x] Tests included/updated
  - [ ] Tests not necessary because:
- Public documentation
  - [x] Cloudflare docs PR(s): https://github.com/cloudflare/cloudflare-docs/pull/26995
  - [ ] Documentation not necessary because: just a fix
- Wrangler V3 Backport
  - [ ] Wrangler PR: 
  - [x] Not necessary because:  create-cloudflare not backported

*A picture of a cute animal (not mandatory, but encouraged)*

### CODE REVIEW

File: packages/create-cloudflare/templates/analog/c3.ts [hunk 1]
```diff
@@ -1,106 +1,84 @@
...
 		path: "./templates",
 	},
+	path: "templates/analog",
 	generate,
 	configure,
 	transformPackageJson: async () => ({
 		scripts: {
-			preview: `${npm} run build && wrangler pages dev`,
-			deploy: `${npm} run build && wrangler pages deploy`,
+			preview: `${npm} run build && npx wrangler dev`,
```
Comment (dario-piotrowicz) [inline packages/create-cloudflare/templates/analog/c3.ts]:
```suggestion
			preview: `${npm} run build && wrangler dev`,
```
