### PR TITLE
[wrangler] fix: apply source mapping to deployment validation errors

### LINKED ISSUE #2741: 🐛 BUG: "A request to the CloudFlare API... failed" errors are non-obvious and confusing.
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

 2.10.0

### What operating system are you using?

Mac

## Actual Behavior

'Just got the following error while running `wrangler publish`:

CleanShot 2023-02-16 at 06 50 14

The problem here is that _on the surface_ this error can't possibly be my fault.  The error location  -`worker.js:7480` - doesn't exist in my project.  (`find . -name worker.js` comes up empty.)   Nor do I have any code in my worker that references `global`.  Also, it's not obvious that the worker code is being run as part of the "publish" process, so this is kind of an odd place for a runtime error to appear.

All of the above turns this error into a bit of a head-scratcher.

Now, I eventually figured out what was going on but it would have been very helpful if more insight and direction for how to diagnose the problem were provided.

## Expected Behavior

Ideally the error detail should contain the file and line number of the source file where the error occurred, rather than referencing the bundled `worker.js` file.

Failing that (or perhaps in addition to that)  it would be nice if some guidance were given as to what exactly the "publish" command does ("bundling the worker, uploading the bundle, then executing it to verify there's no runtime errors"), as well as how to diagnose the problem.

After asking around, I eventually figured out that running `wrangler publish --dry-run --outdir=worker.temp` generates a local copy of the bundle that `wrangler` uploads.   Once I had that in hand, it all made sense, but I had to nag the folks on the \#wrangler Discord channel to get that magic incantation.  Prior to that... yeah... definitely confusing.

### PR DESCRIPTION
**Pull request by mrbbot**
Fixes #2741.

**What this PR solves / how to test:**

Previously if a Worker failed validation during `wrangler deploy`, the displayed error would reference locations in built JavaScript files. This made it more difficult to debug validation errors. This change ensures these errors are now source mapped, referencing locations in source files instead. To test this, try to deploy a TypeScript worker referencing a non-existent variable in the global scope. The validation error should include the location in the TypeScript file.

**Author has addressed the following:**

- Tests
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [x] Not necessary because: change to error messaging

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

**Review by RamIdeas — APPROVED** [review]

File: packages/wrangler/src/sourcemap.ts [hunk 1]
```diff
@@ -1,10 +1,60 @@
...
+	try {
+		return fs.readFileSync(filePath, "utf8");
+	} catch (e: unknown) {
+		const notFound =
+			typeof e === "object" && e !== null && "code" in e && e.code === "ENOENT";
+		if (!notFound) throw e;
+	}
+}
+
+export type RetrieveSourceMap = NonNullable<Options["retrieveSourceMap"]>;
```
Comment (petebacondarwin) [inline packages/wrangler/src/sourcemap.ts:17]: NIT: I found this type a bit confusing to begin with. I would propose we call it `RetrieveSourceMapFunction` or `RetrieveSourceMapMethod`.

File: packages/wrangler/src/sourcemap.ts [hunk 2]
```diff
@@ -1,10 +1,60 @@
...
+		if (map === undefined) return null;
+		return { map, url: mapUrl.href };
+	}
+}
+
 let sourceMappingPrepareStackTrace: typeof Error.prepareStackTrace;
-function getSourceMappingPrepareStackTrace(): NonNullable<
-	typeof Error.prepareStackTrace
-> {
+let retrieveSourceMapOverride: RetrieveSourceMap | undefined;
```
Comment (petebacondarwin) [inline packages/wrangler/src/sourcemap.ts:51]: Why is this variable outside the `getSourceMappingPrepareStackTrace()` function? It doesn't seem to be used outside there?

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
I know it is quite awkward but we might need to construct some actual source and compiled files, with source maps that can act as additional modules, etc so that we can cover the missing code-paths in tests.

File: packages/wrangler/src/sourcemap.ts (hunk 2 above)
Comment (mrbbot) [reply packages/wrangler/src/sourcemap.ts:51]: `getSourceMappingPrepareStackTrace()` ensures `sourceMappingPrepareStackTrace` is set and returns that. `sourceMappingPrepareStackTrace` is only set once, but we'd like to customise its source map retrieval each time it gets called. Therefore, we put the `retrieveSourceMapOverride` in the module scope so the "singleton" `sourceMappingPrepareStackTrace` always has access to the latest override.

Comment (petebacondarwin) [reply packages/wrangler/src/sourcemap.ts:51]: Ah I see. That was not at all clear from the code - for me at least 😅.
I think a more detailed comment at this declaration would help future readers of the code.

File: packages/wrangler/src/sourcemap.ts (hunk 1 above)
Comment (mrbbot) [reply packages/wrangler/src/sourcemap.ts]: Renamed in 1ae7029

File: packages/wrangler/src/sourcemap.ts (hunk 2 above)
Comment (mrbbot) [reply packages/wrangler/src/sourcemap.ts]: I also got a little confused coming back to this. 😅 Added in a7f20e4 👍

File: packages/wrangler/src/__tests__/deploy.test.ts [hunk 3]
```diff
@@ -1836,42 +1836,116 @@ addEventListener('fetch', event => {});`
...
+					}
+				);
+				msw.use(handler);
+			}
+
+			it("with TypeScript source file", async () => {
+				writeWranglerToml();
+				fs.writeFileSync(
+					`index.ts`,
+					`interface Env {
```
Comment (petebacondarwin) [inline packages/wrangler/src/__tests__/deploy.test.ts:1857]: You might like to consider the `dedent` utility here...

**Review by petebacondarwin — APPROVED** [review]
Magic!

File: packages/wrangler/src/__tests__/deploy.test.ts (hunk 3 above)
Comment (mrbbot) [reply packages/wrangler/src/__tests__/deploy.test.ts:1857]: Thanks for the suggestion. Considering these tests depend on exact offsets in the string literals, I'd prefer we don't pass them through a function that changes these. 👍

Comment (mrbbot) [reply packages/wrangler/src/__tests__/deploy.test.ts:1857]: Although, the offset is always `1` 😅 , might try it...
