### PR TITLE
Fix `wrangler types --check` ignoring `--env-interface` and secondary`--config` entries

### LINKED ISSUE #13508: `wrangler types --check` ignores `--env-interface`, `-c`, and other flags, always comparing against default output
### What versions & operating system are you using?

  System:
    OS: macOS 26.3.1
    CPU: (8) arm64 Apple M2
    Memory: 129.31 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.14.0 - /Users/johndoe/.nvm/versions/node/v22.14.0/bin/node
    Yarn: 1.22.22 - /Users/johndoe/.nvm/versions/node/v22.14.0/bin/yarn
    npm: 10.9.2 - /Users/johndoe/.nvm/versions/node/v22.14.0/bin/npm
    pnpm: 10.10.0 - /Users/johndoe/.nvm/versions/node/v22.14.0/bin/pnpm
    bun: 1.3.12 - /Users/johndoe/.bun/bin/bun
    Deno: 2.2.6 - /Users/johndoe/.deno/bin/deno

### Please provide a link to a minimal reproduction

https://github.com/kotkoroid/wrangler-types-check-bug

### Describe the Bug

`wrangler types --check` ignores all additional flags (`--env-interface`, `-c`, `--include-runtime`) and always compares the existing `worker-configuration.d.ts` against what plain `wrangler types` (with no flags) would generate. This means `--check` always fails when custom flags are used during generation, even immediately after a fresh `wrangler types` run.

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
Fixes https://github.com/cloudflare/workers-sdk/issues/13508

Previously, `wrangler types --check` ran its staleness check before resolving the `--env-interface` flag and before collecting secondary worker entry points from additional `--config` arguments. This meant it could incorrectly report types as up to date when they were actually stale due to a different env interface name or changes in secondary worker configs. The check now runs after all options are fully resolved, so it correctly detects mismatches.

---

- Tests
  - [x] Tests included/updated
  - [ ] Automated tests not possible - manual testing has been completed as follows:
  - [ ] Additional testing not necessary because:
- Public documentation
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: bugfix

*A picture of a cute animal (not mandatory, but encouraged)*

---

<a href="https://app.devin.ai/review/cloudflare/workers-sdk/pull/13572" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

**Comment by workers-devprod** [comment]
Codeowners approval required for this PR:
- ✅ @cloudflare/wrangler

<details><summary>Show detailed file reviewers</summary>


</details>

File: packages/wrangler/src/type-generation/helpers.ts [hunk 1]
```diff
@@ -147,11 +147,20 @@ const unsafeParseBooleanString = (value: unknown): boolean => {
...
+ *   used for cross-worker type resolution (service/DO bindings)
+ *
  * @throws {UserError} If the types file doesn't exist or wasn't generated by Wrangler
  */
 export const checkTypesUpToDate = async (
 	primaryConfig: Config,
-	typesPath: string = DEFAULT_WORKERS_TYPES_FILE_PATH
+	typesPath: string = DEFAULT_WORKERS_TYPES_FILE_PATH,
+	envInterface?: string,
+	serviceEntries: Map<string, Entry> = new Map()
```
Comment (NuroDev) [inline packages/wrangler/src/type-generation/helpers.ts]: Nit pick: Can we swap the order of `typesPath` and `envInterface` so parameters with default values are always last.

File: packages/wrangler/src/__tests__/type-generation.test.ts
Comment (NuroDev) [inline packages/wrangler/src/__tests__/type-generation.test.ts:1]: We actually already have e2e tests for the `--check` flag in `packages/wrangler/e2e/types.test.ts`. Would these tests not be better in there?

File: packages/wrangler/src/type-generation/helpers.ts (hunk 1 above)
Comment (dario-piotrowicz) [reply packages/wrangler/src/type-generation/helpers.ts]: done 🙂👍 

https://github.com/cloudflare/workers-sdk/pull/13572/commits/7f409a14ab18ff13eb5c031b0fef416cc7d6e2c6

File: packages/wrangler/src/__tests__/type-generation.test.ts
Comment (dario-piotrowicz) [reply packages/wrangler/src/__tests__/type-generation.test.ts:1]: I've moved them: https://github.com/cloudflare/workers-sdk/pull/13572/commits/26ac99109d53d67371b55e686b15bf75f82ff6c7

However I don't really understand why it'd be better to have these as e2es, and also actually why there's a need to have the types generation logic being tested both with e2e and unit tests. I would assume that the e2es (if actually necessary) should just cover the very basic/plumbing scenarios just to make sure that the command runs and the unit tests should cover everything else (logic, different configurations, edge cases, etc...)

(Unit tests are much easier/convenient/quicker to iterate on since they don't require wrangler to be built)

That's not the case right now, it does feel to me like there's a bit of a unnecessary/unideal blur between what we unit test and what we e2e test for the type generation, possibly something that we could potentially improve? 🤔

Comment (NuroDev) [reply packages/wrangler/src/__tests__/type-generation.test.ts:1]: Yeah this is a valid point. I think it's worth in future doing some cleanup to try and have a better clean split between the unit and E2E tests for type generation.

**Review by NuroDev — APPROVED** [review]

**Review by workers-devprod — APPROVED** [review]
Codeowners reviews satisfied
