### PR TITLE
Log file fixes

### LINKED ISSUE #4482: 🐛 BUG: Wrangler is updating indefinitely to logs
### Which Cloudflare product(s) does this pertain to?

Pages

### What version(s) of the tool(s) are you using?

3.17.0

### What version of Node are you using?

21.2.0

### What operating system are you using?

Mac

### Describe the Bug

I'm creating a new project with astro following the [docs here](https://developers.cloudflare.com/pages/framework-guides/deploy-an-astro-site/)

running this command

```
npm create cloudflare@latest my-astro-app -- --framework=astro
```

After creation i'm running

```
npm run pages:dev
```

Preview

https://youtu.be/scxoTM8X07A

The error seems to be related to https://github.com/cloudflare/workers-sdk/pull/4341

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

```
--- 2023-11-22T00:34:27.059Z debug
🐛 Writing logs to ".wrangler/logs/wrangler-2023-11-22_00-34-26_974.log"
---

--- 2023-11-22T00:34:27.059Z log
Running astro dev...
---

--- 2023-11-22T00:34:27.061Z log
Sleeping 5 seconds to allow proxy process to start before attempting to automatically determine port...
---

--- 2023-11-22T00:34:27.062Z log
To skip, specify the proxy port with --proxy.
---

--- 2023-11-22T00:34:27.638Z log
[proxy]: 02:34:27 AM [@astrojs/cloudflare] 
---

--- 2023-11-22T00:34:27.638Z log
[proxy]: The current configuration does not support image optimization. To allow your project to build with the original, unoptimized images, the image service has been automatically switched to the 'noop' option. See https://docs.astro.build/en/reference/configuration-reference/#imageservice

---

--- 2023-11-22T00:34:32.165Z log
Automatically determined the proxy port to be 4321.
---

--- 2023-11-22T00:34:32.166Z log
No functions. Shimming...
---

--- 2023-11-22T00:34:32.167Z log
 ⛅️ wrangler 3.17.0
[38;2;255;136;0m-------------------[39m
---

--- 2023-11-22T00:34:32.215Z warn
[33m▲ [43;33m[[43;30mWARNING[43;33m][0m [1m--local is no longer required and will be removed in a future version.[0m

  `wrangler dev` now uses the local Cloudflare Workers runtime by default. 🎉


---

--- 2023-11-22T00:34:32.241Z debug
Retrieving cached values for userId from node_modules/.cache/wrangler
---

--- 2023-11-22T00:34:32.242Z debug
Metrics dispatcher: Posting data {"type":"event","name":"run dev","properties":{"local":true,"usesTypeScript":true}}
---

--- 2023-11-22T00:34:32.250Z log
Using vars defined in .dev.vars
---

--- 2023-11-22T00:34:32.282Z log
[proxy]: 02:34:32 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log

---

--- 2023-11-22T00:34:32.293Z log
[2m⎔ Starting local server...[22m
---

--- 2023-11-22T00:34:32.383Z log
[proxy]: 02:34:32 AM [astro] update /.wrangler/tmp/bundle-Hl9JMj/checked-fetch.js
---

--- 2023-11-22T00:34:32.383Z log
[proxy]: 
02:34:32 AM [astro] update /.wrangler/tmp/bundle-Hl9JMj/middleware-insertion-facade.js
02:34:32 AM [astro] update /.wrangler/tmp/bundle-Hl9JMj/middleware-loader.entry.ts
02:34:32 AM [astro] update /.wrangler/tmp/dev-gDzxUn/pages-shim.js.map

---

--- 2023-11-22T00:34:32.383Z log
[proxy]: 02:34:32 AM [astro] update /.wrangler/tmp/dev-gDzxUn/pages-shim.js

---

--- 2023-11-22T00:34:32.383Z log
[proxy]: 02:34:32 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log

---

--- 2023-11-22T00:34:32.439Z debug
Metrics dispatcher: Posting data {"type":"event","name":"run pages dev","properties":{}}
---

--- 2023-11-22T00:34:32.484Z log
[proxy]: [2K
---

--- 2023-11-22T00:34:32.484Z log
[proxy]: [1G[1A02:34:32 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x2)

---

--- 2023-11-22T00:34:32.585Z log
[proxy]: [2K[1G[1A02:34:32 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x3)

---

--- 2023-11-22T00:34:32.669Z log
[proxy]:   🚀  astro  v3.5.7 started in 5133ms
  
  ┃ Local    http://localhost:4321/
  ┃ Network  use --host to expose
  

---

--- 2023-11-22T00:34:32.681Z log
[proxy]: 02:34:32 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log

---

--- 2023-11-22T00:34:32.782Z log
[proxy]: [2K[1G[1A
---

--- 2023-11-22T00:34:32.783Z log
[proxy]: 02:34:32 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x2)

---

--- 2023-11-22T00:34:32.883Z log
[proxy]: [2K[1G
---

--- 2023-11-22T00:34:32.883Z log
[proxy]: [1A02:34:32 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x3)

---

--- 2023-11-22T00:34:32.985Z log
[proxy]: [2K[1G
---

--- 2023-11-22T00:34:32.986Z log
[proxy]: [1A02:34:32 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x4)

---

--- 2023-11-22T00:34:33.085Z log
[proxy]: [2K[1G[1A02:34:33 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x5)

---

--- 2023-11-22T00:34:33.186Z log
[proxy]: [2K[1G
---

--- 2023-11-22T00:34:33.186Z log
[proxy]: [1A02:34:33 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x6)

---

--- 2023-11-22T00:34:33.288Z log
[proxy]: [2K[1G
---

--- 2023-11-22T00:34:33.288Z log
[proxy]: [1A02:34:33 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x7)

---

--- 2023-11-22T00:34:33.389Z log
[proxy]: [2K
---

--- 2023-11-22T00:34:33.389Z log
[proxy]: [1G[1A02:34:33 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x8)

---

--- 2023-11-22T00:34:33.489Z log
[proxy]: [2K[1G[1A02:34:33 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x9)

---

--- 2023-11-22T00:34:33.590Z log
[proxy]: [2K[1G[1A
---

--- 2023-11-22T00:34:33.590Z log
[proxy]: 02:34:33 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x10)

---

--- 2023-11-22T00:34:33.691Z log
[proxy]: [2K[1G
---

--- 2023-11-22T00:34:33.692Z log
[proxy]: [1A02:34:33 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x11)

---

--- 2023-11-22T00:34:33.791Z log
[proxy]: [2K
---

--- 2023-11-22T00:34:33.792Z log
[proxy]: [1G[1A02:34:33 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x12)

---

--- 2023-11-22T00:34:33.893Z log
[proxy]: [2K[1G
---

--- 2023-11-22T00:34:33.893Z log
[proxy]: [1A02:34:33 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x13)

---

--- 2023-11-22T00:34:33.993Z log
[proxy]: [2K[1G
---

--- 2023-11-22T00:34:33.993Z log
[proxy]: [1A02:34:33 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x14)

---

--- 2023-11-22T00:34:34.094Z log
[proxy]: [2K
---

--- 2023-11-22T00:34:34.094Z log
[proxy]: [1G[1A02:34:34 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x15)

---

--- 2023-11-22T00:34:34.195Z log
[proxy]: [2K[1G[1A
---

--- 2023-11-22T00:34:34.195Z log
[proxy]: 02:34:34 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x16)

---

--- 2023-11-22T00:34:34.298Z log
[proxy]: [2K[1G[1A02:34:34 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x17)

---

--- 2023-11-22T00:34:34.396Z log
[proxy]: [2K[1G
---

--- 2023-11-22T00:34:34.396Z log
[proxy]: [1A02:34:34 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x18)

---

--- 2023-11-22T00:34:34.499Z log
[proxy]: [2K[1G[1A
---

--- 2023-11-22T00:34:34.499Z log
[proxy]: 02:34:34 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x19)

---

--- 2023-11-22T00:34:34.597Z log
[proxy]: [2K[1G[1A
---

--- 2023-11-22T00:34:34.598Z log
[proxy]: 02:34:34 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x20)

---

--- 2023-11-22T00:34:34.697Z log
[proxy]: [2K[1G[1A
---

--- 2023-11-22T00:34:34.697Z log
[proxy]: 02:34:34 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x21)

---

--- 2023-11-22T00:34:34.798Z log
[proxy]: [2K[1G[1A
---

--- 2023-11-22T00:34:34.798Z log
[proxy]: 02:34:34 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x22)

---

--- 2023-11-22T00:34:34.899Z log
[proxy]: [2K[1G[1A
---

--- 2023-11-22T00:34:34.899Z log
[proxy]: 02:34:34 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x23)

---

--- 2023-11-22T00:34:35.001Z log
[proxy]: [2K
---

--- 2023-11-22T00:34:35.001Z log
[proxy]: [1G[1A02:34:35 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x24)

---

--- 2023-11-22T00:34:35.101Z log
[proxy]: [2K[1G[1A
---

--- 2023-11-22T00:34:35.102Z log
[proxy]: 02:34:35 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x25)

---

--- 2023-11-22T00:34:35.202Z log
[proxy]: [2K[1G
---

--- 2023-11-22T00:34:35.202Z log
[proxy]: [1A02:34:35 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x26)

---

--- 2023-11-22T00:34:35.302Z log
[proxy]: [2K[1G
---

--- 2023-11-22T00:34:35.302Z log
[proxy]: [1A02:34:35 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x27)

---

--- 2023-11-22T00:34:35.402Z log
[proxy]: [2K[1G[1A
---

--- 2023-11-22T00:34:35.403Z log
[proxy]: 02:34:35 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x28)

---

--- 2023-11-22T00:34:35.504Z log
[proxy]: [2K[1G[1A
---

--- 2023-11-22T00:34:35.504Z log
[proxy]: 02:34:35 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x29)

---

--- 2023-11-22T00:34:35.604Z log
[proxy]: [2K[1G
---

--- 2023-11-22T00:34:35.605Z log
[proxy]: [1A02:34:35 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x30)

---

--- 2023-11-22T00:34:35.705Z log
[proxy]: [2K[1G[1A
---

--- 2023-11-22T00:34:35.706Z log
[proxy]: 02:34:35 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x31)

---

--- 2023-11-22T00:34:35.806Z log
[proxy]: [2K[1G
---

--- 2023-11-22T00:34:35.807Z log
[proxy]: [1A02:34:35 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x32)

---

--- 2023-11-22T00:34:35.908Z log
[proxy]: [2K[1G
---

--- 2023-11-22T00:34:35.908Z log
[proxy]: [1A02:34:35 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x33)

---

--- 2023-11-22T00:34:36.009Z log
[proxy]: [2K[1G[1A
---

--- 2023-11-22T00:34:36.010Z log
[proxy]: 02:34:36 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x34)

---

--- 2023-11-22T00:34:36.110Z log
[proxy]: [2K[1G
---

--- 2023-11-22T00:34:36.111Z log
[proxy]: [1A02:34:36 AM [astro] update /.wrangler/logs/wrangler-2023-11-22_00-34-26_974.log (x35)

---
```

### PR DESCRIPTION
**Pull request by RamIdeas**
Fixes #4482.

**What this PR solves / how to test:**

Changes the default directory wrangler writes log files to.

Also writes the log file location to stderr (as warning) to avoid polluting stdout (some commands print json to stdout). Further, now only prints when the log file contains an error message to avoid pointing the user to this file unnecessarily.

**Author has addressed the following:**

- Tests
  - [ ] Included
  - [x] Not necessary because: minor changes
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] Included
  - [ ] Not necessary because:
- Associated docs
  - [x] Issue(s)/PR(s):
  - [ ] Not necessary because:

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

**Review by mrbbot — APPROVED** [review]

File: packages/wrangler/src/utils/log-file.ts [hunk 1]
```diff
@@ -62,21 +62,30 @@ ${message}
...
+				logger.warn(`🪵 Logs were written to "${relativeFilepath}"`); // use logger.warn here so not to pollute stdout -- some commands print json to stdout
+			}
 		});
 	}
 
+	if (!hasSeenErrorMessage) {
+		// TODO(consider): adding `|| messageLevel === "warn"`
+		hasSeenErrorMessage = messageLevel === "error";
+	}
+
```
Comment (penalosa) [inline packages/wrangler/src/utils/log-file.ts:79]: Does this create multiple `onExit` hooks? Do they need to be cleaned up?

Comment (RamIdeas) [reply packages/wrangler/src/utils/log-file.ts:79]: The onExit call is guarded by an if-block ensuring it's only called once

**Review by penalosa — APPROVED** [review]
🎉
