### PR TITLE
Detect Cloudflare WAF block pages and show a helpful error message in stead of "Received a malformed response from the API"

### LINKED ISSUE #13312: Wrangler Deploy Error: Received a malformed response from the API
### What versions & operating system are you using?

wrangler 4.80.0, bun 1.3.11, macOS Tahoe 26.4 (25E246)

### Please provide a link to a minimal reproduction

not applicable

### Describe the Bug

When deploying using `bunx wrangler deploy` I get an error indicating an unexpected HTML response from the cloudflare API.

I monkey patched Wrangler to see the full HTML page, and noticed the following:

```
✘ [ERROR] Received a malformed response from the API
...
          <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
          <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to
  access</span> api.cloudflare.com</h2>
```

I.e. the Cloudflare WAF on `api.cloudflare.com` is blocking my request.

This is a false positive, I am a normal user, not doing any kind of security research and simply trying to deploy my worker.

Cloudflare Ray ID: 9e8116df4823e2c5

### Please provide any relevant error logs

```
bunx wrangler deploy --env production

 ⛅️ wrangler 4.80.0
───────────────────
▲ [WARNING] You are about to publish a Workers Service that was last updated via the script API.

  Edits that have been made via the script API will be overridden by your local code and config.


✔ Would you like to continue? … yes

🌀 Building list of assets...
✨ Read 14 files from the assets directory [redacted]
🌀 Starting asset upload...
No updated asset files to upload. Proceeding with deployment...
Total Upload: 4.64 KiB / gzip: 1.87 KiB
Your Worker has access to the following bindings:
Binding                                                              Resource
[redacted]
✘ [ERROR] Received a malformed response from the API
[redacted]
...
  POST /accounts/[redacted]/workers/scripts/[redacted]/versions ->
  403 Forbidden

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose
```

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
Fixes #13312 

When the Cloudflare WAF blocks an API request, the response is an HTML page rather than JSON. Previously, this caused a confusing "Received a malformed response from the API" error with a truncated HTML snippet. Wrangler now detects WAF block pages and displays a clear error message explaining that the request was blocked by the firewall, along with the Cloudflare Ray ID (when available) for use in support tickets.

---

- Tests
  - [x] Tests included/updated
  - [ ] Automated tests not possible - manual testing has been completed as follows:
  - [ ] Additional testing not necessary because:
- Public documentation
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: UX improvement

*A picture of a cute animal (not mandatory, but encouraged)*

### CODE REVIEW

**Comment by workers-devprod** [comment]
Codeowners approval required for this PR:
- ✅ @cloudflare/wrangler

<details><summary>Show detailed file reviewers</summary>


</details>

File: packages/wrangler/src/cfetch/internal.ts [hunk 1]
```diff
@@ -220,6 +232,70 @@ export function truncate(text: string, maxLength: number): string {
...
 
+/**
+ * Checks whether the response body looks like a Cloudflare WAF block page.
+ * These are HTML pages returned when the WAF rejects a request, and will
+ * never parse as JSON.
+ *
+ * @param body - The raw response body text to check.
+ * @returns `true` if the body appears to be a Cloudflare WAF block page.
+ */
+export function isWAFBlockResponse(body: string): boolean {
```
Comment (WalshyDev) [inline packages/wrangler/src/cfetch/internal.ts]: i'd use cf-mitigated: https://developers.cloudflare.com/r2/platform/troubleshooting/#if-you-have-a-cf-mitigated-header

File: packages/wrangler/src/cfetch/internal.ts [hunk 2]
```diff
@@ -220,6 +232,70 @@ export function truncate(text: string, maxLength: number): string {
...
+}
+
+/**
+ * Extracts the Cloudflare Ray ID from a WAF block page, if present.
+ * The Ray ID is a hex string typically shown at the bottom of the page.
+ *
+ * @param html - The HTML body of a WAF block page.
+ * @returns The Ray ID hex string, or `undefined` if not found.
+ */
+export function extractWAFBlockRayId(html: string): string | undefined {
```
Comment (WalshyDev) [inline packages/wrangler/src/cfetch/internal.ts]: i'd just pull from headers, body is fragile

**Comment by WalshyDev** [comment]
also for any and all html instead of json it'd be good to get a ray id even aside WAF, we can always use that to dig into logs :)

File: packages/wrangler/src/cfetch/internal.ts (hunk 1 above)
Comment (dario-piotrowicz) [reply packages/wrangler/src/cfetch/internal.ts]: oh, awesome call! Thanks! 🫶

Comment (dario-piotrowicz) [reply packages/wrangler/src/cfetch/internal.ts]: Updated here: https://github.com/cloudflare/workers-sdk/pull/13574/commits/e9610fb56aa0cf9337c2df3ff4e51a51ac36957d

File: packages/wrangler/src/cfetch/internal.ts (hunk 2 above)
Comment (dario-piotrowicz) [reply packages/wrangler/src/cfetch/internal.ts]: again, thanks for the awesome suggestion! 😄 

done: https://github.com/cloudflare/workers-sdk/pull/13574/commits/e9610fb56aa0cf9337c2df3ff4e51a51ac36957d

**Comment by dario-piotrowicz** [comment]
> also for any and all html instead of json it'd be good to get a ray id even aside WAF, we can always use that to dig into logs :)

Done! 🫡 😄  https://github.com/cloudflare/workers-sdk/pull/13574/commits/11cbf00c18a388ccc18c65b7898a18df293125a8

File: .changeset/malformed-response-ray-id.md
Comment (emily-shen) [inline .changeset/malformed-response-ray-id.md:1]: these could probably be one changeset?

**Review by emily-shen — APPROVED** [review]

**Review by workers-devprod — APPROVED** [review]
Codeowners reviews satisfied

File: .changeset/malformed-response-ray-id.md
Comment (dario-piotrowicz) [reply .changeset/malformed-response-ray-id.md:1]: done 🫡 

https://github.com/cloudflare/workers-sdk/pull/13574/commits/0b90fb2d2b093f64f1e8f32ecbfd93f476947fd3
