### PR TITLE
fix: don't warn about `node:async_hooks` if `nodejs_als` is set

### LINKED ISSUE #6011: 🐛 BUG: wrangler does not mark `node:async_hooks` as external when `nodejs_als` compatibility flag is used
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler core

### What version(s) of the tool(s) are you using?

3.60.2

### What version of Node are you using?

18

### What operating system and version are you using?

macOS 14.5

### Observed behavior
Please describe.

`wrangler.toml`
```toml
#: schema ../node_modules/wrangler/config-schema.json

compatibility_date = "2024-05-24"
main = "src/worker.ts"
compatibility_flags = ["nodejs_als"]
```

`src/worker.ts`
```ts
import { AsyncLocalStorage } from 'node:async_hooks'
```

### Expected behavior

No warning is generated, since the `"nodejs_als"` compatibility flag is specified in `wrangler.toml`.

### Actual behavior

```
▲ [WARNING] The package "node:async_hooks" wasn't found on the file system but is built into node.
```

from [kian](https://ptb.discord.com/channels/595317990191398933/1214571685424930846/1250341639939952701) on Cloudflare's Discord:
> Wrangler has no idea about that flag so it doesn’t know what to do with it. I'd open an issue

### PR DESCRIPTION
**Pull request by petebacondarwin**
## What this PR solves / how to test

Fixes #6011

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [x] Required / Maybe required
  - [ ] Not required because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Not necessary because: bug fix

### CODE REVIEW

File: packages/wrangler/src/deployment-bundle/esbuild-plugins/als-external.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import type { Plugin } from "esbuild";
+
+/**
+ * An esbuild plugin that will mark `node:async_hooks` imports as external.
+ */
+export const asyncLocalStoragePlugin: Plugin = {
+	name: "Mark async local storage imports as external plugin",
+	setup(pluginBuild) {
+		pluginBuild.onResolve({ filter: /^node:async_hooks/ }, () => {
```
Comment (RamIdeas) [inline packages/wrangler/src/deployment-bundle/esbuild-plugins/als-external.ts:9]:
```suggestion
		pluginBuild.onResolve({ filter: /^node:async_hooks$/ }, () => {
```

**Review by RamIdeas — APPROVED** [review]

File: packages/wrangler/src/deployment-bundle/esbuild-plugins/als-external.ts (hunk 1 above)
Comment (petebacondarwin) [reply packages/wrangler/src/deployment-bundle/esbuild-plugins/als-external.ts:9]: I did this for the potential future case of there being a sub entry point to `async_hooks`. Since we would also want this plugin to kick in for imports like:

```ts
import {...} from "node:async_hooks/blah";
```

Do you feel that we should not support this @RamIdeas ?

Comment (petebacondarwin) [reply packages/wrangler/src/deployment-bundle/esbuild-plugins/als-external.ts:9]: I guess there is the fear that a new module called `node:async_hooks_2` would also match this...

I could tighten this up a bit...?

Comment (RamIdeas) [reply packages/wrangler/src/deployment-bundle/esbuild-plugins/als-external.ts:9]: I was thinking the latter but I guess the former is equally likely. Since we're only marking as external, I think we can leave it as-is 👍

Comment (petebacondarwin) [reply packages/wrangler/src/deployment-bundle/esbuild-plugins/als-external.ts]: Doh! I updated it now 😆

File: packages/workers-shared/package.json [hunk 2]
```diff
@@ -33,7 +33,7 @@
 		"clean": "rimraf dist",
 		"dev": "pnpm run clean && concurrently -n bundle:asset-worker,bundle:router-worker -c blue,magenta \"pnpm run bundle:asset-worker --watch\" \"pnpm run bundle:router-worker --watch\"",
 		"test": "vitest",
-		"test:ci": "pnpm run test"
+		"test:ci": "pnpm run test run"
```
Comment (RamIdeas) [inline packages/workers-shared/package.json:36]: mistake?

File: packages/wrangler/src/deployment-bundle/esbuild-plugins/als-external.ts [hunk 3]
```diff
@@ -6,7 +6,7 @@ import type { Plugin } from "esbuild";
 export const asyncLocalStoragePlugin: Plugin = {
 	name: "Mark async local storage imports as external plugin",
 	setup(pluginBuild) {
-		pluginBuild.onResolve({ filter: /^node:async_hooks/ }, () => {
+		pluginBuild.onResolve({ filter: /^node:async_hooks(\/|$)/ }, () => {
```
Comment (RamIdeas) [inline packages/wrangler/src/deployment-bundle/esbuild-plugins/als-external.ts:9]: 👍

File: packages/workers-shared/package.json (hunk 2 above)
Comment (petebacondarwin) [reply packages/workers-shared/package.json:36]: This is not a mistake as such because the original script is wrong; not adding `run` causes local runs of `test:ci` to hang since this one goes into interactive mode.
