### PR TITLE
Fix vitest watch with durable objects

### LINKED ISSUE #9913: `vitest watch` fails on the second run using `runInDurableObject`
### Which Cloudflare product(s) does this pertain to?

Workers Vitest Integration

### What versions & operating system are you using?

Mac OS Sonoma 14.3, Node 21.7.1, also tried v22.12.0, @cloudflare/vitest-pool-workers 0.8.50, vitest 3.2.4, wrangler 4.24.0

### Please provide a link to a minimal reproduction

https://github.com/yoh-000/min-repro-cf-do-testing

### Describe the Bug

Tests pass with `vitest run`.
Tests pass with `vitest watch` initially.
Tests fail with `vitest watch` when a code change triggers a rerun.

### Expected behavior

Tests pass with `vitest watch` initially and every subsequent rerun.

### Steps to reproduce

- `git clone https://github.com/yoh-000/min-repro-cf-do-testing.git`
- `cd min-repro-cf-do-testing`
- `pnpm test:watch`
- Hit enter to cause a rerun.

### Please provide any relevant error logs

```
❯ pnpm test:watch

> @ test:watch /Users/yohsuzuki/Development/Metatheory/min-repro-cf-do-testing
> DEBUG=vpw:* vitest watch


 DEV  v3.2.4 /Users/yohsuzuki/Development/Metatheory/min-repro-cf-do-testing

[vpw:info] Starting isolated runtimes for vitest.config.ts...
 ✓ src/index.test.ts (1 test) 11ms
   ✓ index > durable object test 7ms

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  23:24:17
   Duration  604ms (transform 21ms, setup 0ms, collect 19ms, tests 11ms, environment 0ms, prepare 114ms)

 PASS  Waiting for file changes...
       press h to show help, press q to quit






 RERUN  rerun all tests x1 

[vpw:debug] Reusing runtime for vitest.config.ts...
workerd/jsg/util.c++:320: error: e = workerd/util/sqlite.c++:499: failed: expected _ec == SQLITE_OK [14 == 0]; unable to open database file: SQLITE_CANTOPEN
stack: 1052e3f4f 1052e3a6b 10497d0af 10497cb07 10497c963 104f4df2b 104f2ad5b 104f2a8b7 104968a83 10496847b 10497b627 10497a9c3 1049a1613 1052b0670 1052b2b73 104937b38 1050c5120 104fdc2f0; sentryErrorContext = jsgInternalError; wdErrId = ni7cuqgpaeoig0bd1cg4sh1p
 ❯ src/index.test.ts (1 test | 1 failed) 15ms
   × index > durable object test 7ms
     → internal error; reference = ni7cuqgpaeoig0bd1cg4sh1p
```

### LINKED ISSUE #10506: bug: vitest and cloudflare d1 experiencing Error: internal error; reference = in latest version
### What versions & operating system are you using?

  System:
    OS: macOS 15.6.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 16.40 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.14.0 - /usr/local/bin/node
    npm: 10.9.2 - /usr/local/bin/npm
    pnpm: 10.10.0 - /usr/local/bin/pnpm
    bun: 1.1.6 - ~/.bun/bin/bun

### Please provide a link to a minimal reproduction

https://github.com/rxliuli/vitest-cloudflare-d1-error

### Describe the Bug

When running tests containing d1, the first execution works fine, but if I modify the test file causing the tests to re-run, a mysterious `Error: internal error; reference = akrfi30jdp9t7ba7rn8q225o` error appears, making integration testing nearly impossible.

https://github.com/user-attachments/assets/99efdefc-4177-434e-943c-37e5582f2a7a

I had to roll back the versions of vitest/@cloudflare/vitest-pool-workers/wrangler. If anyone is interested, the specific versions are:

```js
   "@cloudflare/vitest-pool-workers": "0.8.12",
    "vitest": "3.0.9",
    "wrangler": "4.8.0"
```

### Please provide any relevant error logs

```sh
Error: internal error; reference = akrfi30jdp9t7ba7rn8q225o
 ❯ D1DatabaseSessionAlwaysPrimary._send cloudflare-internal:d1-api:147:26
 ❯ D1DatabaseSessionAlwaysPrimary._sendOrThrow cloudflare-internal:d1-api:124:25
 ❯ D1PreparedStatement.run cloudflare-internal:d1-api:311:29
 ❯ applyD1Migrations Users/rxliuli/code/web/demo/my-first-worker-v2/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.8.68_@vitest+runner@3.2.4_@vitest+snapshot@3.2.4_vitest@3.2.4/node_modules/@cloudflare/vitest-pool-workers/dist/worker/lib/cloudflare/test-internal.mjs:32:3
```

### PR DESCRIPTION
**Pull request by avenceslau**
Fixes #9913
Fixes #10506

Running vitest-pool-workers with `vitest --watch` would fail second runs due to SQLITE_CANT_OPEN errors or internal reference errors. This was a bug in one of the functions that handles clean up between tests `emptyDir`, for DOs specifically we were deleting not only the sqlite files but also the dir itself.

This meant that `workerd` would not be able to recreate the DO's sqlite storage and DOs would fail to reboot up.
---

- Tests
  - [x] Tests included/updated
  - [ ] Tests not necessary because:
- Public documentation
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: Just a bug fix

*A picture of a cute animal (not mandatory, but encouraged)*

---

<a href="https://app.devin.ai/review/cloudflare/workers-sdk/pull/11771" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

**Comment by petebacondarwin** [comment]
@claude

File: packages/vitest-pool-workers/src/pool/loopback.ts [hunk 1]
```diff
@@ -62,24 +62,31 @@ async function handleSnapshotRequest(
 }
 
 async function emptyDir(dirPath: string) {
-	let names: string[];
+	let entries: { name: string; isDirectory: boolean }[];
 	try {
-		names = await fs.readdir(dirPath);
+		const dirents = await fs.readdir(dirPath, { withFileTypes: true });
```
Comment (anonrig) [inline packages/vitest-pool-workers/src/pool/loopback.ts]: opendir with async iterator would be a lot faster and more memory efficient than this

Comment (petebacondarwin) [reply packages/vitest-pool-workers/src/pool/loopback.ts]: I did try changing this to use opendir locally but then got weird "directory already closed" errors, which I couldn't fathom.

I don't think these directories ever get very large or deep so I think it is safe to leave it like this for the moment.
