### PR TITLE
Fix usage of patch API in bulk secrets update

### LINKED ISSUE #4496: 🐛 BUG: regression: secret:bulk broken presumably due #4179
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.17.1

### What version of Node are you using?

_No response_

### What operating system are you using?

mac, linux

### Describe the Bug

It seems like #4179 changed secret:bulk from using the secrets PUT API to script PATCH... this sounds like a good idea, but in practice, it seems to have broken our CI builds without any notice about this in the changelog, or without any explanation given in the CLI output _or_ `wrangler.log`

CleanShot 2023-11-22 at 14 39 44@2x

I am happy to share more detailed logging output privately if someone is interested.

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

--- 2023-11-22T22:36:22.137Z log
 ⛅️ wrangler 3.17.1
-------------------
---

--- 2023-11-22T22:36:22.141Z debug
Saving to cache: {"account":{"id":"***","name":""}}
---

--- 2023-11-22T22:36:22.142Z log
🌀 Creating the secrets for the Worker "gg-preview-pr-667-gameserver" 
---

--- 2023-11-22T22:36:22.145Z debug
-- START CF API REQUEST: GET https://api.cloudflare.com/client/v4/accounts/***/workers/scripts/gg-preview-pr-667-gameserver/settings
---

--- 2023-11-22T22:36:22.145Z debug
HEADERS: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-11-22T22:36:22.145Z debug
INIT: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-11-22T22:36:22.145Z debug
-- END CF API REQUEST
---

--- 2023-11-22T22:36:22.557Z debug
-- START CF API RESPONSE: OK 200
---

--- 2023-11-22T22:36:22.557Z debug
HEADERS: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-11-22T22:36:22.557Z debug
RESPONSE: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-11-22T22:36:22.557Z debug
-- END CF API RESPONSE
---

--- 2023-11-22T22:36:22.558Z debug
-- START CF API REQUEST: PATCH https://api.cloudflare.com/client/v4/accounts/***/workers/scripts/gg-preview-pr-667-gameserver/settings
---

--- 2023-11-22T22:36:22.558Z debug
HEADERS: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-11-22T22:36:22.558Z debug
INIT: omitted; set WRANGLER_LOG_SANITIZE=false to include sanitized data
---

--- 2023-11-22T22:36:22.558Z debug
-- END CF API REQUEST
---

### PR DESCRIPTION
**Pull request by matthewdavidrodgers**
Only specifying the name and type of a binding instructs the patch API to copy the existing binding over - but we were including the contents of the binding as well. Normally that's OK, but there are some subtle differences between what you specify to _create_ a binding vs what it looks like once it's _created_, specifically for Durable Objects. So instead, we just use the simpler inheritance.

Note that this depends on a not-yet-released EWC change to fix a separate bug in the patch API, and should hold until that makes it out

Fixes #4496, WC-1774

### CODE REVIEW

**Comment by aroman** [comment]
@matthewdavidrodgers awesome to see this being worked on, any idea when the EWC change will land / this can be merged? this landing would let me upgrade wrangler and get a lot of other great changes that have landing since

File: packages/wrangler/src/secret/index.ts [hunk 1]
```diff
@@ -444,9 +444,11 @@ export const secretBulkHandler = async (secretBulkArgs: SecretBulkArgs) => {
...
 		}
 	}
-	const inheritBindings = existingBindings.filter((binding) => {
-		return binding.type !== "secret_text" || !content[binding.name];
-	});
+	const inheritBindings = existingBindings
+		.filter(
+			(binding) => binding.type !== "secret_text" || !content[binding.name]
+		)
+		.map((binding) => ({ type: binding.type, name: binding.name }));
```
Comment (petebacondarwin) [inline packages/wrangler/src/secret/index.ts:451]: Given that this looks like you are just copying properties like for like over, I think a comment for future readers explaining that you are actually excluding unwanted properties and why would be useful.

Comment (KamaniBhavin) [reply packages/wrangler/src/secret/index.ts:451]: @petebacondarwin, indeed, this fix addresses the problem I reported in my GitHub issue (https://github.com/cloudflare/workers-sdk/issues/4675). Specifically, the conflict arises from the d1 database binding. The Cloudflare API expects a d1 binding to have a `id` key, but when making a GET request to https://api.cloudflare.com/client/v4/accounts/{account_identifier}/workers/scripts/{script_name}/settings, the response contains a `database_id` key instead of `id` for d1 binding object.

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
Looks good. Could you please update the test at https://github.com/cloudflare/workers-sdk/blob/c2c35a5d961dded2e20c6a43538171f804f93547/packages/wrangler/src/__tests__/secret.test.ts#L732 to check this behaviour.

**Comment by matthewdavidrodgers** [comment]
tests updated - note that we should still hold until the EWC fix is in (was expecting that to release by now, but that will be early next week at this point it seems)

**Review by petebacondarwin — APPROVED** [review]
Thanks for updating the test!

**Comment by matthewdavidrodgers** [comment]
EWC changes have been released - this is ready to go forward whenever
