### PR TITLE
fix: allow D1 local commands to work without database_id

### LINKED ISSUE #11802: D1 execute (local) fails if database_id is not provided
### What versions & operating system are you using?

wrangler 4.56.0, macos

### Please provide a link to a minimal reproduction

see description

### Describe the Bug

{
	"name": "worker-ts",
	"main": "src/index.ts",
	"compatibility_date": "2025-05-04",
	"d1_databases": [
		{
			"binding": "D1",
			"database_name": "D1",
		},
	],
}
with a sql file like this:

DROP TABLE IF EXISTS Customers;
CREATE TABLE IF NOT EXISTS Customers (CustomerId INTEGER PRIMARY KEY, CompanyName TEXT, ContactName TEXT);
INSERT INTO Customers (CustomerID, CompanyName, ContactName) VALUES (1, 'Alfreds Futterkiste', 'Maria Anders'), (4, 'Around the Horn', 'Thomas Hardy'), (11, 'Bs Beverages', 'Victoria Ashworth'), (13, 'Bs Beverages', 'Random Name');

Then running this command will fail:

npx wrangler d1 execute D1 --local --file=./schema.sql 

with

✘ [ERROR] Couldn't find a D1 DB with the name or binding 'D1' in your wrangler.json file.

If you add a random database id in, the execute command succeeds.

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by emily-shen**
Fixes #11802.

Now that resource provisioning means wrangler dev doesn't need database_ids, local versions of d1 commands also shouldn't need the id. 

---

Link to Devin run: https://app.devin.ai/sessions/92cc6dea3f1543ecb6667ad7d1f85ad0
Devin PR requested by @emily-shen 
(rewrote a lot of it though)

- Tests
  - [x] Tests included/updated
  - [ ] Tests not necessary because:
- Public documentation
  - [ ] Cloudflare docs PR(s):
  - [x] Documentation not necessary because: This is a bug fix
Screenshot 2026-01-07 at 17 35 27

---

<a href="https://app.devin.ai/review/cloudflare/workers-sdk/pull/11804">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

**Comment by alsuren** [comment]
I've not dug into the code yet, but from some local testing with `wrangler.js d1 migrations apply` on this branch:

## 1: If you have 2 bindings pointing at the same database name, it will do the migration separately for each binding

to reproduce:

wrangler.jsonc:

```
{
  "d1_databases": [
    {
      "binding": "dlaban_workers_sdk_5438_on_delete_cascade",
      "database_name": "dlaban-workers-sdk-5438-on-delete-cascade"
    },
    {
      "binding": "dlaban_workers_sdk_5438_on_delete_cascade_2",
      "database_name": "dlaban-workers-sdk-5438-on-delete-cascade"
    }
  ]
}
```

migrations/0001_test-migration.sql: this can be empty

This works as expected:
```
$ wrangler.js d1 migrations apply dlaban_workers_sdk_5438_on_delete_cascade

 ⛅️ wrangler 4.56.0 (update available 4.58.0)
─────────────────────────────────────────────
Resource location: local 

Use --remote if you want to access the remote instance.

Migrations to be applied:
┌─────────────────────────┐
│ name                    │
├─────────────────────────┤
│ 0001_test-migration.sql │
└─────────────────────────┘
✔ About to apply 1 migration(s)
Your database may not be available to serve requests during the migration, continue? … yes
🌀 Executing on local database dlaban_workers_sdk_5438_on_delete_cascade (dlaban_workers_sdk_5438_on_delete_cascade) from .wrangler/state/v3/d1:
🌀 To execute on your remote database, add a --remote flag to your wrangler command.
🚣 1 command executed successfully.
┌─────────────────────────┬────────┐
│ name                    │ status │
├─────────────────────────┼────────┤
│ 0001_test-migration.sql │ ✅     │
└─────────────────────────┴────────┘

$ wrangler.js d1 migrations apply dlaban_workers_sdk_5438_on_delete_cascade

 ⛅️ wrangler 4.56.0 (update available 4.58.0)
─────────────────────────────────────────────
Resource location: local 

Use --remote if you want to access the remote instance.

✅ No migrations to apply!
```

I would expect migrating the second binding to also say `✅ No migrations to apply!` but instead it says:
```
wrangler.js d1 migrations apply dlaban_workers_sdk_5438_on_delete_cascade_2

 ⛅️ wrangler 4.56.0 (update available 4.58.0)
─────────────────────────────────────────────
Resource location: local 

Use --remote if you want to access the remote instance.

Migrations to be applied:
┌─────────────────────────┐
│ name                    │
├─────────────────────────┤
│ 0001_test-migration.sql │
└─────────────────────────┘
✖ About to apply 1 migration(s)
Your database may not be available to serve requests during the migration, continue? … yes
```

## 2: If you start without a database id, and then add it in later, it also attempts to migrate the db from scratch

To reproduce:

After doing the migration above, change wrangler.toml to:

```
{
  "d1_databases": [
    {
      "binding": "dlaban_workers_sdk_5438_on_delete_cascade",
      "database_name": "dlaban-workers-sdk-5438-on-delete-cascade",
      "database_id": "0e34f968-245c-4e25-853b-5e67c05420cf"
    },
    {
      "binding": "dlaban_workers_sdk_5438_on_delete_cascade_2",
      "database_name": "dlaban-workers-sdk-5438-on-delete-cascade",
      "database_id": "0e34f968-245c-4e25-853b-5e67c05420cf"
    }
  ]
}
```

and then run `wrangler.js d1 migrations apply dlaban_workers_sdk_5438_on_delete_cascade` - it will prompt you to migrate the db again, even though it should already be migrated.

I think these are both symptoms of it not knowing how to map things to the appropriate .wrangler/state/v3/d1/miniflare-D1DatabaseObject/ sqlite db.

* for 1: I feel like it should use database_name rather than the binding name if it doesn't have a database_id
* for 2: I'm not sure. I wonder if it should have some kind of fallback behaviour, so if it doesn't see a db with the right database_id, but there is one for the database_name, it should prefer the one for database_name. 

There are going to be bunch of horrible edge cases here, where old wrangler versions use one lookup scheme and new ones do something different. We can simulate the upgrade from current wrangler in tests by making bindings with just database_id, and then adding database_name later maybe?

File: packages/wrangler/src/d1/utils.ts [hunk 1]
```diff
@@ -7,15 +7,30 @@ import type { ComplianceConfig, Config } from "@cloudflare/workers-utils";
 
 export function getDatabaseInfoFromConfig(
 	config: Config,
-	name: string
+	name: string,
+	options?: {
+		/** Local databases might not have a database id, so we don't require it for local-only operations */
+		requireDatabaseId?: boolean;
```
Comment (alsuren) [inline packages/wrangler/src/d1/utils.ts:16]: (nit that you don't necessarily need to do anything about): I am generally not a fan of optional boolean flags that default to true. 

It seems that e.g. `isLocal({local, remote}, default)` defaults to true as well though, so that might be the wrangler code style.

If you're keeping it like this, maybe call out what the default is in the flag's docstring?

File: packages/wrangler/src/d1/utils.ts [hunk 2]
```diff
@@ -7,15 +7,30 @@ import type { ComplianceConfig, Config } from "@cloudflare/workers-utils";
...
+
 	for (const d1Database of config.d1_databases) {
-		if (
-			d1Database.database_id &&
-			(name === d1Database.database_name || name === d1Database.binding)
-		) {
+		if (name === d1Database.database_name || name === d1Database.binding) {
+			if (requireDatabaseId && !d1Database.database_id) {
+				throw new UserError(
+					`Found a database with name or binding ${name} but it is missing a database_id, which is needed for operations on remote resources. Please create the remote D1 database by deploying your project or running 'wrangler d1 create ${name}'.`
```
Comment (alsuren) [inline packages/wrangler/src/d1/utils.ts:25]: This means that adding a second binding with a matching binding/database_name but without a database_id might or might not poison future invocations of wrangler commands, or might not, depending on which order we iterate over things.

In the face of a config with some bindings having database_id and some not, Options are to make it consistently permissive (by raising a warning and then continuing?), make it consistently strict (by validating all d1_databases before returning), or leave it inconsistent as it is now.

This is a super edge case, and making things consistent might add unnecessary complexity, so use your judgement here.

File: packages/wrangler/src/d1/utils.ts (hunk 1 above)
Comment (emily-shen) [reply packages/wrangler/src/d1/utils.ts:16]: i think that's a losing battle to fight in this codebase 😅 

but for my own interest, why? consistency?

File: packages/wrangler/src/d1/utils.ts (hunk 2 above)
Comment (emily-shen) [reply packages/wrangler/src/d1/utils.ts:25]: hmm i think this is enough of an edgecase to ignore - having duplicate bindings names is already forbidden, so that won't be an issue, and i can't really see _why_ you'd end up having two bindings to the same database_name, and also only have one of them with a database_id.

File: packages/wrangler/src/d1/utils.ts (hunk 1 above)
Comment (alsuren) [reply packages/wrangler/src/d1/utils.ts:16]: I can't remember where I picked up the habit. Possibly from writing untyped javascript, when "go to definition" in your editor wasn't so reliable. I have a feeling that being able to provide a default value for js positional function arguments is an ES6 thing, and it was common for people to just pass the resulting `undefined` into if statements, and relied on it being falsy? (maybe I'm misremembering?)

Probably just me showing my age, and not a thing people care about anymore.

I also have thing about boolean variables that have negative-sounding names. I have a very small brain, and those take me too long to read each time. I think we're okay here though.
