### PR TITLE
Use correct host in exchange

### LINKED ISSUE #2018: 🐛 BUG: `wrangler dev` sends request to hostname of custom zone, instead of full domain
### What version of `Wrangler` are you using?

2.1.11

### What operating system are you using?

Linux

### Describe the Bug

I've got my domain `example.com`, and a Worker deployed at `worker.example.com`. The second-level domain hosts a website, which is totally unrelated to what my Worker does.

I use a grey-clouded DNS record pointing to my server for `example.com`, and an orange-clouded DNS record pointing to `100::` for `worker.example.com`.

When trying to test the Worker using `wrangler dev`, an error message pops up with the content of a typical 404 reply from my `example.com` website. Publishing the Worker works fine and interacting with it once published is also fine. Changing the Workers route to the default `workers.dev` domain also makes the error disappear.

Though not being able to test my Worker this way is annoying, my main concern is that I don't understand why on Earth a request to `example.com` is done in the process.

### PR DESCRIPTION
**Pull request by penalosa**
What this PR solves / how to test:

URLs from the Cloudflare API are usually relative to the zone. Sometimes the base zone will be grey-clouded, and so the host must be swapped out for the worker route host, which is more likely to be orange-clouded.

Associated docs issues/PR:

- Bugfix, so no docs changes needed

Author has included the following, where applicable:

- [ ] Tests
- [x] Changeset

Reviewer has performed the following, where applicable:

- [ ] Checked for inclusion of relevant tests
- [ ] Checked for inclusion of a relevant changeset
- [ ] Checked for creation of associated docs updates
- [ ] Manually pulled down the changes and spot-tested

Fixes #2018, #2602, #2581

### CODE REVIEW

File: packages/wrangler/src/create-worker-preview.ts [hunk 1]
```diff
@@ -122,13 +130,15 @@ export async function createPreviewSession(
...
 
-	const { exchange_url } = await fetchResult<{ exchange_url: string }>(
+	let { exchange_url } = await fetchResult<{ exchange_url: string }>(
 		initUrl,
 		undefined,
 		undefined,
 		abortSignal
 	);
 
+	exchange_url = switchHost(exchange_url, ctx.host).toString();
```
Comment (JacobMGEvans) [inline packages/wrangler/src/create-worker-preview.ts:140]: Rather than changing this to let and re-assigning the variable, it could stay `const` give the new expression its own variable name expliciting defining what has been done to it `switchedExchangeURL` which can be passed into the `fetch` at `line 144` (only place I saw it being used) 

```suggestion
	const { exchange_url } = await fetchResult<{ exchange_url: string }>(
		initUrl,
		undefined,
		undefined,
		abortSignal
	);

const switchedExchangeURL = switchHost(exchange_url, ctx.host).toString();
```
On line 144:
```ts
const exchangeResponse = await fetch(switchedExchangeURL, { signal: abortSignal });
```

File: packages/wrangler/src/create-worker-preview.ts [hunk 2]
```diff
@@ -147,16 +157,15 @@ export async function createPreviewSession(
...
+	const inspector = new URL(inspector_websocket);
+	inspector.searchParams.append("cf_workers_preview_token", token);
 
 	return {
 		id: randomId(),
 		value: token,
-		host,
-		inspectorUrl: new URL(`${inspector_websocket}?${query}`),
-		prewarmUrl: new URL(prewarm),
+		host: ctx.host ?? inspector.host,
```
Comment (JacobMGEvans) [inline packages/wrangler/src/create-worker-preview.ts:166]: Can the host be `""` (I don't remember if the config validator prevents that) if so this could have unintended behavior.

File: packages/wrangler/src/create-worker-preview.ts [hunk 3]
```diff
@@ -109,6 +109,14 @@ function randomId(): string {
 	});
 }
 
+// URLs are often relative to the zone. Sometimes the base zone
+// will be grey-clouded, and so the host must be swapped out for
+// the worker route host, which is more likely to be orange-clouded
+function switchHost(originalUrl: string, host?: string): URL {
+	const url = new URL(originalUrl);
+	url.hostname = host ?? url.hostname;
```
Comment (JacobMGEvans) [inline packages/wrangler/src/create-worker-preview.ts:117]: If host can be falsey `""` this could cause unintended behaviors

**Review by JacobMGEvans — CHANGES_REQUESTED** [review]
It is looking good! Just a question around the nullish operator issue and suggestion on handling `exchange_url`

File: packages/wrangler/src/create-worker-preview.ts (hunk 3 above)
Comment (GregBrimble) [reply packages/wrangler/src/create-worker-preview.ts:117]: Is there any reason not to always just use the probably-orange-clouded host?

Comment (penalosa) [reply packages/wrangler/src/create-worker-preview.ts:117]: Sometimes we might not be able to parse an orange-clouded host (i.e. when the only route is `*/*`)

File: packages/wrangler/src/create-worker-preview.ts (hunk 1 above)
Comment (penalosa) [reply packages/wrangler/src/create-worker-preview.ts:140]: Much nicer, yeah!

File: packages/wrangler/src/create-worker-preview.ts (hunk 3 above)
Comment (GregBrimble) [reply packages/wrangler/src/create-worker-preview.ts:117]: So is there a circumstance when I'm using a wildcard route e.g. `*/*` but my root domain is grey-clouded, where this won't work?

Comment (penalosa) [reply packages/wrangler/src/create-worker-preview.ts:117]: Yes, but there's kinda nothing we can do there if you've provided no other information. I think there's a dev.host config parameter you can add to explicitly set this, but I'll double check

**Review by JacobMGEvans — APPROVED** [review]
My concern was discussed offline. Looks good to go!
