### PR TITLE
 Avoid mutating the Worker config during build.

### LINKED ISSUE #10650: `@vitejs/plugin-rsc` build fails with `@cloudflare/vite-plugin` since v1.13.0
### What versions & operating system are you using?

  System:
    OS: Linux 6.16 Arch Linux
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-12650H
    Memory: 19.84 GB / 31.05 GB
    Container: Yes
    Shell: 5.3.3 - /usr/bin/bash
  Binaries:
    Node: 22.18.0 - ~/.volta/tools/image/node/22.18.0/bin/node
    npm: 10.9.3 - ~/.volta/tools/image/node/22.18.0/bin/npm
    pnpm: 10.16.1 - ~/.volta/bin/pnpm
    bun: 1.2.20 - ~/.local/bin/bun
  npmPackages:
    @cloudflare/vite-plugin: 1.13.0 => 1.13.0 
    wrangler: 4.36.0 => 4.36.0 

### Please provide a link to a minimal reproduction

https://github.com/hi-ogawa/reproductions/tree/main/vite-rsc-851-cloudflare-entry-virtual

### Describe the Bug

`@vitejs/plugin-rsc` requires building certain environments multiple times. The build error is found in https://github.com/vitejs/vite-plugin-react/pull/851. Simplified version would look like the minimal reproduction above:

```js
{
  builder: {
    async buildApp(builder) {
      await builder.build(builder.environments.ssr!);
      await builder.build(builder.environments.ssr!);
    }
  }
}
```

This logic seems to have a problem with `@cloudflare/vite-plugin` since v1.13.0 and the error look like this:

```js
$ pnpm build
> vite build

vite v7.1.5 building SSR bundle for production...
✓ 2 modules transformed.
dist/ssr/.vite/manifest.json  0.16 kB
dist/ssr/wrangler.json        1.26 kB
dist/ssr/index.js             0.32 kB
✓ built in 33ms
vite v7.1.5 building SSR bundle for production...
✓ 1 modules transformed.
✗ Build failed in 9ms
error during build:
[vite]: Rollup failed to resolve import "virtual:cloudflare/user-entry" from "virtual:cloudflare/worker-entry".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteLog (file:///home/hiroshi/code/personal/reproductions/vite-rsc-851-cloudflare-entry-virtual/node_modules/.pnpm/vite@7.1.5/node_modules/vite/dist/node/chunks/dep-M_KD0XSK.js:34340:57)
    at onRollupLog (file:///home/hiroshi/code/personal/reproductions/vite-rsc-851-cloudflare-entry-virtual/node_modules/.pnpm/vite@7.1.5/node_modules/vite/dist/node/chunks/dep-M_KD0XSK.js:34374:9)
    at onLog (file:///home/hiroshi/code/personal/reproductions/vite-rsc-851-cloudflare-entry-virtual/node_modules/.pnpm/vite@7.1.5/node_modules/vite/dist/node/chunks/dep-M_KD0XSK.js:34169:4)
    at file:///home/hiroshi/code/personal/reproductions/vite-rsc-851-cloudflare-entry-virtual/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:20939:32
    at Object.logger [as onLog] (file:///home/hiroshi/code/personal/reproductions/vite-rsc-851-cloudflare-entry-virtual/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:22825:9)
    at ModuleLoader.handleInvalidResolvedId (file:///home/hiroshi/code/personal/reproductions/vite-rsc-851-cloudflare-entry-virtual/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21569:26)
    at file:///home/hiroshi/code/personal/reproductions/vite-rsc-851-cloudflare-entry-virtual/node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21527:26
 ELIFECYCLE  Command failed with exit code 1.
```

From what I debugged so far, `workerConfig.main` during the 2nd build became different from the `wrangler.jsonc`'s main field

https://github.com/cloudflare/workers-sdk/blob/597e07a440405919fd39bc800cfd0426132d2c42/packages/vite-plugin-cloudflare/src/index.ts#L220-L222

During the first build, `console.log({ source, main: workerConfig.main })` logs

```
{
  source: 'virtual:cloudflare/user-entry',
  main: '/home/hiroshi/code/personal/reproductions/vite-rsc-851-cloudflare-entry-virtual/worker/index.js'
}
```

but during the 2nd build, it becomes

```
{ source: 'virtual:cloudflare/user-entry', main: 'index.js' }
```

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by jamesopstad**
Fixes #10650.

This fixes an issue that can occur if the same Worker environment is built twice.

---

- Tests
  - [x] Tests included
  - [ ] Tests not necessary because
- Public documentation
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: internal change
- Wrangler V3 Backport
  - [ ] Wrangler PR: 
  - [x] Not necessary because: not a Wrangler change

### CODE REVIEW

File: packages/vite-plugin-cloudflare/src/index.ts [hunk 1]
```diff
@@ -328,23 +319,27 @@ if (import.meta.hot) {
...
 				// Set to `undefined` if it's an empty object so that the user doesn't see a warning about using `unsafe` fields when deploying their Worker.
-				if (config.unsafe && Object.keys(config.unsafe).length === 0) {
-					config.unsafe = undefined;
+				if (
+					outputConfig.unsafe &&
+					Object.keys(outputConfig.unsafe).length === 0
+				) {
+					outputConfig = {
+						...outputConfig,
+						unsafe: undefined,
```
Comment (dario-piotrowicz) [inline packages/vite-plugin-cloudflare/src/index.ts]: Nit: why not just doing `outputConfig.unsafe = undefined`? 🤔

File: packages/vite-plugin-cloudflare/src/index.ts [hunk 2]
```diff
@@ -244,13 +245,13 @@ if (import.meta.hot) {
 			generateBundle(_, bundle) {
 				assertIsNotPreview(resolvedPluginConfig);
 
-				let config: Unstable_RawConfig | undefined;
+				let outputConfig: Unstable_RawConfig | undefined;
 
 				if (resolvedPluginConfig.type === "workers") {
-					const workerConfig =
+					const inputConfig =
 						resolvedPluginConfig.workers[this.environment.name];
```
Comment (dario-piotrowicz) [inline packages/vite-plugin-cloudflare/src/index.ts:252]: What about cloning the config here?

```suggestion
					const inputConfig =
						structuredClone(resolvedPluginConfig.workers[this.environment.name]);
```

So that later you don't have to be careful and remember to always destructuring it etc...?

(PS: destructuring also doesn't guarantee that you won't modify nested properties)

**Review by dario-piotrowicz — APPROVED** [review]

File: packages/vite-plugin-cloudflare/src/index.ts (hunk 2 above)
Comment (jamesopstad) [reply packages/vite-plugin-cloudflare/src/index.ts:252]: We could. I think how I've done it is fine though as we're not dealing with lots of nested properties.

File: packages/vite-plugin-cloudflare/src/index.ts (hunk 1 above)
Comment (jamesopstad) [reply packages/vite-plugin-cloudflare/src/index.ts]: https://github.com/cloudflare/workers-sdk/pull/10664/commits/1f8e235962d2df32829eef8fa844f224046a00bc
