### PR TITLE
fix: setting triggers.crons:[] in Wrangler config should delete deployed cron schedules

### LINKED ISSUE #9180: Remove a schedule in wrangler.jsonc does not remove it in Cloudflare
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What versions & operating system are you using?

4.14.4

### Please provide a link to a minimal reproduction

_No response_

### Describe the Bug

If you have a schedule in wrangler.jsonc and you deploy
```
"triggers": {
  "crons": ["*/5 * * * *"],
},
```

then you remove it, it will still be active and you have to go and remove it manually in the dashboard on cloudflare.com

It should be that it is removed or synced, since it is not obvious that it is not reflected 😊

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by petebacondarwin**
Fixes #9180

Previously if the array was empty it would just not touch the deployed schedules.
Providing either `triggers: { crons: undefined }` or no `triggers` property in your Wrangler configuration will continue to leave the deployed schedules untouched.

---

- Tests
  - [ ] TODO (before merge)
  - [x] Tests included
  - [ ] Tests not necessary because:
- Wrangler / Vite E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [x] Required
  - [ ] Not required because:
- Public documentation
  - [ ] TODO (before merge)
  - [x] Cloudflare docs PR(s): https://github.com/cloudflare/cloudflare-docs/pull/22462
  - [ ] Documentation not necessary because:
- Wrangler V3 Backport
  - [ ] TODO (before merge)
  - [x] Wrangler PR: https://github.com/cloudflare/workers-sdk/pull/9267
  - [ ] Not necessary because:

### CODE REVIEW

File: packages/wrangler/src/triggers/deploy.ts [hunk 1]
```diff
@@ -258,17 +258,18 @@ export default async function triggersDeploy(
...
-	if (triggers && triggers.length) {
+	// If schedules is not defined then we just leave whatever is previously deployed alone.
+	// If it is an empty array we will remove all schedules.
+	if (schedules) {
 		deployments.push(
 			fetchResult(`${workerUrl}/schedules`, {
 				// Note: PUT will override previous schedules on this script.
 				method: "PUT",
-				body: JSON.stringify(triggers.map((cron) => ({ cron }))),
+				body: JSON.stringify(schedules.map((cron) => ({ cron }))),
```
Comment (vicb) [inline packages/wrangler/src/triggers/deploy.ts:268]: Is this tested with a 0 length ?

Comment (vicb) [reply packages/wrangler/src/triggers/deploy.ts:268]: Thanks!
I asked because we never used length = 0 before.
(Looking at the [API](https://developers.cloudflare.com/api/resources/workers/subresources/scripts/subresources/schedules/methods/update/) now, [] must work because there is no DELETE anyway).

**Review by vicb — APPROVED** [review]
Thanks!
