### PR TITLE
vite-plugin: add support for Node.js ALS compat mode

### LINKED ISSUE #8869: `nodejs_als` unsupported by `@cloudflare/vite-plugin`
### Which Cloudflare product(s) does this pertain to?

Vite Plugin

### What versions & operating system are you using?

wrangler 4.9.1, macOS

### Please provide a link to a minimal reproduction

_No response_

### Describe the Bug

when using the `nodejs_als` compatibility flag in `wrangler.toml`:

```
compatibility_flags = ["nodejs_als"]
```

this does NOT work:

```ts
import { AsyncLocalStorage } from 'node:async_hooks';
```

and produces this output:

```
3:58:55 PM [vite] Unexpected Node.js imports for environment "gg_gameserver". Do you need to enable the "nodejs_compat" compatibility flag? Refer to https://developers.cloudflare.com/workers/runtime-apis/nodejs/ for more details.
 - "node:async_hooks" imported from "../server/src/RoomDurableObject.ts"
```

HOWEVER, using the `node_compat` compatibility flag DOES work. This is not WAI.

### PR DESCRIPTION
**Pull request by petebacondarwin**
Fixes #8869

---

- Tests
  - [ ] TODO (before merge)
  - [x] Tests included
  - [ ] Tests not necessary because:
- Wrangler / Vite E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [x] Required
  - [ ] Not required because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: bug fix
- Wrangler V3 Backport
  - [ ] TODO (before merge)
  - [ ] Wrangler PR: 
  - [x] Not necessary because: vite plugin not backported

### CODE REVIEW

File: packages/vite-plugin-cloudflare/playground/node-compat/worker-als/index.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+import { AsyncLocalStorage } from "node:async_hooks";
+
+export default {
+	async fetch() {
+		const storage = new AsyncLocalStorage();
+		return storage.run({}, () => new Response("OK!"));
```
Comment (dario-piotrowicz) [inline packages/vite-plugin-cloudflare/playground/node-compat/worker-als/index.ts:6]: nit: would it make sense to also test that the `ALS` store actually works? 🤔 

(maybe not since that's a runtime thing anyways...)

File: packages/vite-plugin-cloudflare/src/index.ts [hunk 2]
```diff
@@ -652,6 +653,26 @@ export function cloudflare(pluginConfig: PluginConfig = {}): vite.Plugin[] {
 				);
 			},
 		},
+		// Plugin that handles Node.js Async Local Storage (ALS)compatibility support for Vite Environments that are hosted in Cloudflare Workers.
```
Comment (dario-piotrowicz) [inline packages/vite-plugin-cloudflare/src/index.ts:656]:
```suggestion
		// Plugin that handles Node.js Async Local Storage (ALS) compatibility support for Vite Environments that are hosted in Cloudflare Workers.
```

**Review by dario-piotrowicz — APPROVED** [review]

File: packages/vite-plugin-cloudflare/playground/node-compat/worker-als/index.ts (hunk 1 above)
Comment (petebacondarwin) [reply packages/vite-plugin-cloudflare/playground/node-compat/worker-als/index.ts:6]: That is definitely tested elsewhere.

Comment (dario-piotrowicz) [reply packages/vite-plugin-cloudflare/playground/node-compat/worker-als/index.ts:6]: ah ok I see, sounds good to me 🙂👍

**Review by jamesopstad — APPROVED** [review]

File: packages/vite-plugin-cloudflare/src/index.ts [hunk 3]
```diff
@@ -770,6 +799,11 @@ export function cloudflare(pluginConfig: PluginConfig = {}): vite.Plugin[] {
 				const workerConfig = getWorkerConfig(this.environment.name);
 
 				if (workerConfig && !isNodeCompat(workerConfig)) {
+					if (isNodeAls(workerConfig) && /^(node:)?async_hooks$/.test(source)) {
```
[the remark this answers is not in the document]
Comment (petebacondarwin) [reply packages/vite-plugin-cloudflare/src/index.ts]: fe73c7e325a3e7993299f1a04d4afde8e5c034ed
