### PR TITLE
Various `--from-dash` improvements

### LINKED ISSUE #4401: 🐛 BUG: Format of routes from API doesn't match expected format when trying to download existing worker into wrangler
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.15.0

### What version of Node are you using?

18.18.2

### What operating system are you using?

Mac

### Describe the Bug

First time installing Wrangler to work with workers locally. I wanted to download an existing worker, so followed the instructions: 
` wrangler init --from-dash someworkername
`
which it told me was no longer supported, and so it automatically ran 
`Running `npm create cloudflare@2 someworkername -- --type pre-existing --existing-script someworkername`...
`
I answered the various questions, logged in through OAuth, and received the following error (specific names/domains anonymised):

✘ [ERROR] Processing wrangler.toml configuration:

```
    - Expected "routes" to be an array of either strings or objects with the shape { pattern, custom_domain, zone_id | zone_name }, but these weren't valid: [
        {
          "pattern": "somedomain.com/someworker*",
          "zone_name": "",
          "script": "someworkername"
        },
        {
          "pattern": "https://someotherdomain.com/someroute*",
          "zone_name": "",
          "script": "someworkername"
        }
      ].
```

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by penalosa**
Fixes #4401 #4352 #4043 #3825

**What this PR solves / how to test:**

This improves `wrangler init --from-dash` to:
* Always use JavaScript, rather than prompting for TypeScript (the API only returns JavaScript files right now)
* Support Custom Domains & workers.dev property setting
* Hide standard usage model if set

**Author has addressed the following:**

- Tests
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [ ] Not necessary because:

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

File: packages/create-cloudflare/src/workers.ts [hunk 1]
```diff
@@ -42,13 +42,16 @@ export const runWorkersGenerator = async (args: C3Args) => {
 		args,
 		originalCWD,
 	};
+	const { preexisting } = await getTemplate(ctx);
 
-	ctx.args.ts = await processArgument<boolean>(ctx.args, "ts", {
```
Comment (jculvey) [inline packages/create-cloudflare/src/workers.ts:46]: I think we actually want the following:

```	
  const { preexisting } = await getTemplate(ctx);

	if (preexisting) {
		ctx.args.ts = false;
	}

	await processArgument<boolean>(ctx.args, "ts", {
		type: "confirm",
		question: "Do you want to use TypeScript?",
		label: "typescript",
		defaultValue: C3_DEFAULTS.ts,
	});
```

`processArgument` won't prompt the user for input if the first param passed to it is already defined. So a pattern we use in other places where we want to infer some arguments from others is to directly set the inferred value on `ctx.args`. 

In addition, `processArgument` returns a value but also has the important side-effect of informing the user about the selection (note the typescript question with the proposed changed):

image

**Review by jculvey — APPROVED** [review]
lgtm other than the issue I mentioned

File: packages/wrangler/src/init.ts [hunk 2]
```diff
@@ -942,25 +930,33 @@ async function getWorkerConfig(
...
+					zone_name: c.zone_name,
+					custom_domain: true,
+				} as CustomDomainRoute)
+		),
+	];
 
 	return {
+		name: workerName,
+		main: entrypoint,
+		workers_dev: workersDev.enabled,
```
Comment (mrbbot) [inline packages/wrangler/src/init.ts:950]: Could we set `workers_dev` to `undefined` if it's disabled?

**Review by mrbbot — APPROVED** [review]

File: packages/wrangler/src/init.ts (hunk 2 above)
Comment (penalosa) [reply packages/wrangler/src/init.ts:950]: An undefined `workers_dev` property is inferred as either true or false depending on the value of `routes`, and so I thought it would be better to be explicit

Comment (mrbbot) [reply packages/wrangler/src/init.ts:949]: Fair enough 🙂

File: packages/create-cloudflare/src/workers.ts (hunk 1 above)
Comment (jculvey) [reply packages/create-cloudflare/src/workers.ts:46]: Also FYI we're [using this pattern ](https://github.com/cloudflare/workers-sdk/blob/main/packages/create-cloudflare/src/cli.ts#L91)to infer the `pre-existing` type when `--existing-script foo` is used.

**Comment by jculvey** [comment]
A rebase should fix the yarn e2e tests

File: packages/wrangler/src/init.ts [hunk 3]
```diff
@@ -942,25 +929,33 @@ async function getWorkerConfig(
...
 		compatibility_date:
 			serviceEnvMetadata.script.compatibility_date ??
 			new Date().toISOString().substring(0, 10),
-		...routeOrRoutesToConfig,
-		usage_model: serviceEnvMetadata.script.usage_model,
+		compatibility_flags: serviceEnvMetadata.script.compatibility_flags,
+		...(allRoutes.length ? { routes: allRoutes } : {}),
+		usage_model:
```
Comment (zebp) [inline packages/wrangler/src/init.ts:955]: We just noticed this ourselves and we decided that we wanted `usage_model` to be unspecified if the user has standard instead of just the Worker using the standard usage model. I implemented this in [this commit](https://github.com/zebp/workers-sdk/commit/3881974852f56cc9c8a44b458527010fa9a1cf9f#diff-fa9a52007c2b6571335f75c75e00cf783306b826a082fe144ac0337b3bfff9fcR969) before realizing you had this PR up.

**Comment by penalosa** [comment]
@zebp Could you have a look and see if the updates here integrating https://github.com/cloudflare/workers-sdk/pull/4521 are valid?

**Review by zebp — APPROVED** [review]

**Comment by admah** [comment]
@penalosa I'm still seeing the behavior from #4352 in this pre-release. 

To repro:
- I created a new worker from the dash.
- I installed the prerelease here and ran the command in the develop with Wrangler CLI guide
- I'm still prompted for TS/JS (which shouldn't happen)
-  I still get a `src/worker.ts` file created even when choosing "no" to TS.

**Comment by penalosa** [comment]
@admah That'll probably happen until C3 is released, this this coe path bounces back and forth between the two. Does it work now in the deployed version?
