### PR TITLE
fix: hide wrangler banner in `secret list --format=json`

### LINKED ISSUE #8101: 🐛 BUG: `wrangler secret list --format json` emits non-JSON characters
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What versions are you using?

3.108.0

### What operating system and version are you using?

Mac Sequoia 15.1.1

### Please provide a link to a minimal reproduction

_No response_

### Describe the Bug

As of 3.108, wrangler is emitting non-JSON characters when specifying `--format json`.

Before (3.107):

```
npx wrangler@3.107 secret list --format json --name WORKER_NAME
[
  {
    "name": "secret_A",
    "type": "secret_text"
  },
  {
    "name": "secret_B",
    "type": "secret_text"
  }
]
```

Current version (3.108):

```
npx wrangler@3.108 secret list --format json --name WORKER_NAME

 ⛅️ wrangler 3.108.0
--------------------

[
  {
    "name": "secret_A",
    "type": "secret_text"
  },
  {
    "name": "secret_B",
    "type": "secret_text"
  }
]
```

This is causing my code to fail because I capture this output and assume it is JSON.

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by emily-shen**
Fixes #8101 
---

- Tests
  - [ ] TODO (before merge)
  - [x] Tests included
  - [ ] Tests not necessary because:
- Wrangler E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [ ] Required
  - [x] Not required because: e2e should cover
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: bug fix

### CODE REVIEW

File: packages/wrangler/src/secret/index.ts [hunk 1]
```diff
@@ -342,7 +343,13 @@ export const secretListCommand = createCommand({
 			hidden: true,
 		},
 	},
+	behaviour: {
+		printBanner: false,
```
Comment (penalosa) [inline packages/wrangler/src/secret/index.ts:347]: `printBanner` can be a function that decides whether to print based on the args— `printBanner: (args) => args.format === "pretty",`

File: .changeset/proud-days-study.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"wrangler": patch
+---
+
+fix: fix bug where `wrangler secret lis --format=json` was printing the wrangler banner.
```
Comment (penalosa) [inline .changeset/proud-days-study.md:5]:
```suggestion
fix: fix bug where `wrangler secret list --format=json` was printing the wrangler banner.
```

File: packages/wrangler/src/secret/index.ts [hunk 3]
```diff
@@ -19,6 +19,7 @@ import { requireAuth } from "../user";
 import { getLegacyScriptName } from "../utils/getLegacyScriptName";
 import { isLegacyEnv } from "../utils/isLegacyEnv";
 import { readFromStdin, trimTrailingWhitespace } from "../utils/std";
+import { printWranglerBanner } from "../wrangler-banner";
```
Comment (penalosa) [inline packages/wrangler/src/secret/index.ts:22]: This is no longer needed

File: packages/wrangler/src/__tests__/secret.test.ts [hunk 4]
```diff
@@ -710,6 +710,33 @@ describe("wrangler secret", () => {
...
+
+		describe("banner tests", () => {
+			it("banner if pretty", async () => {
+				vi.unmock("../wrangler-banner");
+				mockListRequest({ scriptName: "script-name" });
+				await runWrangler("secret list --name script-name  --format=pretty");
+				expect(std.out).toMatchInlineSnapshot(`
+					"Secret Name: the-secret-name
+					"
+				`);
```
Comment (penalosa) [inline packages/wrangler/src/__tests__/secret.test.ts:722]: This doesn't seem to be showing the banner?

File: packages/wrangler/src/secret/index.ts [hunk 5]
```diff
@@ -342,6 +342,9 @@ export const secretListCommand = createCommand({
 			hidden: true,
 		},
 	},
+	behaviour: {
+		printBanner: (args) => args.format === "pretty",
```
Comment (petebacondarwin) [inline packages/wrangler/src/secret/index.ts:346]: I guess you didn't want to go with `args.format !== "json"`?

**Review by petebacondarwin — APPROVED** [review]

**Comment by penalosa** [comment]
For posterity—this does not affect C3, so merging without C3 tests fully finished
