### PR TITLE
wrangler: truncate Pages commit message at UTF-8 boundary

### LINKED ISSUE #11749: Cloudflare Pages deployment fails with "Invalid commit message" for long multi-line UTF-8 commit messages
### What versions & operating system are you using?

```
System:
OS: macOS 26.2
CPU: (16) arm64 Apple M3 Max
Memory: 1.92 GB / 64.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
Node: 24.8.0 - /Users/xxx/.local/share/mise/installs/node/24.8.0/bin/node
npm: 11.4.2 - /Users/xxx/.local/share/mise/installs/node/24.8.0/bin/npm
npmPackages:
wrangler: ^4.56.0 => 4.56.0
```

### Please provide a link to a minimal reproduction

It does not depend on project files and is triggered only by the commit message content.

### Describe the Bug

Hi Cloudflare team 👋 
I encountered the following issue when deploying to Cloudflare Pages.

## Summary

Cloudflare Pages deployment fails with the following error:

```bash
$ npx wrangler pages deploy
✘ [ERROR] A request to the Cloudflare API (/accounts/{{account_id}}/pages/projects/{{project_name}}/deployments) failed.
  Invalid commit message, it must be a valid UTF-8 string. [code: 8000111]
```

The commit message is valid UTF-8 locally.

## Minimal Reproduction

Based on my testing, the error occurs when all conditions are met:

- Commit message has 5 or more lines
- Message is at least 381 bytes (so byte index 380 exists)
- Byte 380 (0-indexed) of the UTF-8 byte sequence is a continuation byte (0x80–0xBF)

### Why This Happens

It appears the server truncates commit messages at byte 380 when the message has 5+ lines. If a multi-byte UTF-8 character spans this boundary, the truncation breaks the character mid-sequence.

For example, if bytes 379-381 contain "あ" (U+3042, encoded as `E3 81 82`):

```
Byte 379: E3  (start byte)
Byte 380: 81  (continuation byte) ← truncated here
Byte 381: 82  (continuation byte)
```

After truncation at byte 380, only `E3 81` remains, which is an incomplete UTF-8 sequence, causing the "Invalid commit message" error.

> **Note:** These conditions are derived from empirical testing and may not be exhaustive. The actual server-side truncation logic is unknown.

### Failing Examples

All examples below have been verified to fail on Cloudflare Pages deployment.

**Example 1: Minimal reproduction (382 bytes, 5 lines)**

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaあ
```

Structure:

- Line 1: 69 bytes of 'a'
- Line 2: empty
- Line 3: 86 bytes of 'a'
- Line 4: 101 bytes of 'a'
- Line 5: 118 bytes of 'a' + "あ" (U+3042, 3 bytes: E3 81 82)

Byte 380 = 0x82 (continuation byte of "あ")

**Example 2: More lines (381 bytes, 6 lines)**

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
あ
```

Structure:

- Line 1: 69 bytes of 'a'
- Line 2: empty
- Line 3: 86 bytes of 'a'
- Line 4: 101 bytes of 'a'
- Line 5: 117 bytes of 'a'
- Line 6: "あ" (U+3042, 3 bytes: E3 81 82)

Byte 380 = 0x81 (continuation byte of "あ")

### Passing Examples (for comparison)

**380 bytes (byte 380 does not exist, passes):**

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaあ
```

**4 lines (382 bytes, passes):**

```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaあ
```

## Expected Behavior

When truncating long commit messages, Pages should truncate at valid UTF-8 character boundaries to ensure the resulting string remains valid UTF-8, allowing deployment to succeed.

## Actual Behavior

When the message has 5+ lines and is 381+ bytes, it appears to be truncated at byte 380 on the server side. If byte 380 is a UTF-8 continuation byte, this breaks the UTF-8 sequence and causes the error.

---

Thanks for taking a look, and please let me know if you need any additional information or testing on my side.

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by X6TXY**
Fixes #11749

Safely truncate Cloudflare Pages commit messages at valid UTF-8 boundaries before sending them to the Pages deployments API.

Cloudflare Pages enforces a fixed byte limit (384 bytes) on git commit metadata. When a multi-line commit message containing multi-byte UTF-8 characters (e.g. Cyrillic, Japanese, emoji) is truncated mid-character on the server side, the resulting string becomes invalid UTF-8 and deployments fail with error 8000111.

This change ensures Wrangler never sends an invalid UTF-8 commit message by truncating at the nearest valid UTF-8 boundary on the client side.

---

### What was changed

- Added `truncateUtf8Bytes()` in `packages/wrangler/src/api/pages/deploy.ts`
  - Truncates UTF-8 strings to 384 bytes
  - Backs off to a valid UTF-8 boundary if truncation lands mid-sequence
- Integrated truncation into the Pages deploy request so all commit messages are sanitized before being sent
- Added comprehensive tests in `packages/wrangler/src/__tests__/pages/utf8-truncation.test.ts`
  - Cyrillic, Japanese, and emoji coverage
  - Boundary cases (exactly 384 bytes, continuation bytes at the cutoff)
  - Multi-line (5+ lines) messages reproducing the reported failure

---

### Tests

- [x] Tests included/updated
- [ ] Automated tests not possible - manual testing has been completed as follows:
- [ ] Additional testing not necessary because:

---

### Public documentation

Docs: Not required — this is an internal deployment-safety fix affecting only the Pages deploy API payload. No user-facing CLI or API changes.

### CODE REVIEW

File: packages/wrangler/src/api/pages/deploy.ts [hunk 1]
```diff
@@ -36,6 +36,29 @@ import type { BundleResult } from "../../deployment-bundle/bundle";
 import type { Deployment, Project } from "@cloudflare/types";
 import type { Config } from "@cloudflare/workers-utils";
 
+const MAX_COMMIT_MESSAGE_BYTES = 384;
+
+export function truncateUtf8Bytes(str: string, maxBytes: number): string {
```
Comment (vicb) [inline packages/wrangler/src/api/pages/deploy.ts]: Maybe this should be moved to the `workers-util` package? What do others think?

At least we just push this util function toward the bottom of the file.

File: packages/wrangler/src/api/pages/deploy.ts [hunk 2]
```diff
@@ -36,6 +36,29 @@ import type { BundleResult } from "../../deployment-bundle/bundle";
...
+
+	let result = "";
+	let byteCount = 0;
+
+	for (const char of str) {
+		const charBytes = Buffer.byteLength(char, "utf8");
+		if (byteCount + charBytes > maxBytes) {
+			break;
+		}
+		result += char;
```
Comment (vicb) [inline packages/wrangler/src/api/pages/deploy.ts]: perf: concatenating string is `O(n^2)` and 384^2 = 147k. It would be better to `chars.push(char)` and then `return chars.join("")`

`return str.slice(...)` and not pushing is also an option

Comment (X6TXY) [reply packages/wrangler/src/api/pages/deploy.ts]: Agreed. I’ll push an update using the bytes-first approach

File: packages/wrangler/src/api/pages/deploy.ts (hunk 1 above)
Comment (X6TXY) [reply packages/wrangler/src/api/pages/deploy.ts]: good point, i think it  should be in workers-util

**Comment by X6TXY** [comment]
Got it, I’ll wait for other feedback and fix everything together.
Thanks for the review, @vicb!

File: packages/wrangler/src/api/pages/deploy.ts (hunk 2 above)
Comment (vicb) [reply packages/wrangler/src/api/pages/deploy.ts]: FYI, Gemini help me came up with:

```ts
export function truncateUtf8Bytes(str: string, maxBytes: number): string {
  const buf = Buffer.from(str);
  if (buf.length <= maxBytes) return str;

  let i = maxBytes;
  
  // Scan backwards from the limit (max 3 bytes for UTF-8)
  // We stop if we find a "Start Byte" or ASCII (value < 128)
  while (i > 0) {
    i--;
    const byte = buf[i];

    // If it's a Continuation Byte (0x80 - 0xBF), keep stepping back.
    if ((byte & 0xC0) === 0x80) continue;

    // We found the Start Byte (or ASCII). 
    // Now we perform the single check: "Does this char fit?"
    
    // Calculate expected size:
    // ASCII (0xxxxxxx) -> 1
    // 110xxxxx -> 2
    // 1110xxxx -> 3
    // 11110xxx -> 4
    let charLength = 1;
    if (byte >= 0xC0) charLength = 2;
    if (byte >= 0xE0) charLength = 3;
    if (byte >= 0xF0) charLength = 4;

    // If the sequence + start index fits within maxBytes, we are good!
    // Otherwise, we cut BEFORE this character (at i).
    if (i + charLength > maxBytes) {
      return buf.subarray(0, i).toString('utf8');
    }
    
    // If it fits, the cut was clean.
    break;
  }

  return buf.subarray(0, maxBytes).toString('utf8');
}
```
