### PR TITLE
Run deploy interactively in C3

### LINKED ISSUE #4263: 🐛 BUG: ✘ [ERROR] This command cannot be run in a non-interactive context
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

^3.0.0

### What version of Node are you using?

v18.18.2

### What operating system are you using?

Mac

### Describe the Bug

I tried following the Getting Started Tutorial: https://developers.cloudflare.com/workers/get-started/guide/

When i run `npm create cloudflare@latest` I choose a directory, choose "Hello World" Worker, and choose Typescript "yes". 
The script fails with 

✘ [ERROR] This command cannot be run in a non-interactive context
 ⛅️ wrangler 3.14.0
-------------------
Total Upload: 0.19 KiB / gzip: 0.16 KiB
▲ [WARNING] You need to register a workers.dev subdomain before publishing to workers.dev

? Would you like to register a workers.dev subdomain now?
🤖 Using default value in non-interactive context: yes

✘ [ERROR] This command cannot be run in a non-interactive context

If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### LINKED ISSUE #4915: 🐛 BUG: Registering worked.dev subdomain fails in "wrangler init"
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.26.0

### What version of Node are you using?

20.10.0

### What operating system and version are you using?

PopOS (22 LTS)

### Observed behavior
After authorising Wrangler to nuke my Cloudflare account, the following happens while running `wrangler init` in an interactive shell:
```
 ⛅️ wrangler 3.26.0
-------------------
Total Upload: 0.19 KiB / gzip: 0.16 KiB
▲ [WARNING] You need to register a workers.dev subdomain before publishing to workers.dev


? Would you like to register a workers.dev subdomain now?
🤖 Using fallback value in non-interactive context: yes

✘ [ERROR] This command cannot be run in a non-interactive context
```

### Expected behavior
`wrangler init` finishes successfully, not lying to its dependencies that it's run non-interactively.

### Steps to reproduce
`npx wrangler init NAME` in a clean directory, follow the instructions from [API Tutorial](https://developers.cloudflare.com/d1/tutorials/build-a-comments-api/)

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

```
--- 2024-02-03T15:43:57.925Z debug
🪵  Writing logs to "/home/uriel/.config/.wrangler/logs/wrangler-2024-02-03_15-43-57_816.log"
---

--- 2024-02-03T15:43:57.925Z debug
Failed to load .env file ".env": Error: ENOENT: no such file or directory, open '.env'
    at Object.openSync (node:fs:581:18)
    at Object.readFileSync (node:fs:457:35)
    at tryLoadDotEnv (/home/uriel/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:124257:72)
    at loadDotEnv (/home/uriel/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:124266:12)
    at /home/uriel/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:162342:20
    at /home/uriel/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:131131:16
    at maybeAsyncResult (/home/uriel/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:129352:44)
    at /home/uriel/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:131130:14
    at /home/uriel/.npm/_npx/32026684e21afda6/node_modules/wrangler/wrangler-dist/cli.js:129339:22
    at Array.reduce (<anonymous>) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.env'
}
---

--- 2024-02-03T15:43:57.931Z log
 ⛅️ wrangler 3.26.0
-------------------
---

--- 2024-02-03T15:43:58.114Z log
Using npm as package manager.
---

--- 2024-02-03T15:43:58.155Z warn
▲ [WARNING] The `init` command is no longer supported. Please use `npm create cloudflare\@2 -- trionficfd1` instead.

  The `init` command will be removed in a future version.


---

--- 2024-02-03T15:43:58.155Z log
Running `npm create cloudflare\@2 -- trionficfd1`...
---

--- 2024-02-03T15:44:48.760Z log

---

--- 2024-02-03T15:44:48.761Z error
✘ [ERROR] Command failed with exit code 1: npm create cloudflare@2 -- trionficfd1


---

--- 2024-02-03T15:44:48.762Z log
If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
---

--- 2024-02-03T15:52:41.899Z debug
Sentry: Capturing exception Error: Command failed with exit code 1: npm create cloudflare@2 -- trionficfd1
---
```

### LINKED ISSUE #6230: 🐛 BUG: npm create cloudflare => Deploy doesn't prompt to auto-report bug?
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

2.21.9

### What version of Node are you using?

v22.3.0

### What operating system and version are you using?

Sonoma 14.5

### Describe the Bug

1. Run `npm create cloudflare`
2. Select the hello world template
3. Choose the option to deploy
4. Observe (what looks like an intermittent) error
5. Observe that the failure prompts you to report an issue here on the `cloudflare/workers-sdk` repository, but **appears to skip over the automated error reporting**

```
"? Would you like to report this error to Cloudflare?
🤖 Using fallback value in non-interactive context: no"
```

```
...
├ Selecting Cloudflare account retrieving accounts 
│ account more than one account available
│ 
├ Which account do you want to use?
│ account ACCOUNT
│
├ Deploying your application 
│ 
> service-binding-to@0.0.0 deploy
> wrangler deploy


 ⛅️ wrangler 3.63.1
-------------------

Total Upload: 0.19 KiB / gzip: 0.16 KiB

✘ [ERROR] fetch failed


If you think this is a bug then please create an issue at https://github.com/cloudflare/workers
-sdk/issues/new/choose
? Would you like to report this error to Cloudflare?
🤖 Using fallback value in non-interactive context: no
🪵  Logs were written to
...
```

It's not clear to me if the bug was automatically reported, or if I need to report it.

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by penalosa**
## What this PR solves / how to test

Previously, C3 ran `wrangler deploy` and `wrangler pages deploy` non-interactively. Since this is intended to be an interactive command, this led to various bugs. However, since C3 parsed the output of Wrangler's deploy command (and that's not possible with an interactive spawn), a change was also needed to how C3 figured out what Wrangler did during a deploy. This PR runs the deploy command interactively, after that change to Wrangler's output was made in https://github.com/cloudflare/workers-sdk/pull/6571

Fixes #4915, fixes #4263, fixes #6230

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [x] Required / Maybe required
  - [ ] Not required because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Not necessary because: bugfix

### CODE REVIEW

File: packages/create-cloudflare/src/deploy.ts [hunk 1]
```diff
@@ -99,24 +103,42 @@ export const runDeploy = async (ctx: C3Context) => {
...
 	];
 
-	const result = await runCommand(deployCmd, {
-		silent: true,
+	const outputFile = join(
+		await mkdtemp(join(tmpdir(), "c3-wrangler-deploy-")),
+		"output.json",
+	);
+
+	await runCommand(deployCmd, {
```
Comment (CarmenPopoviciu) [inline packages/create-cloudflare/src/deploy.ts:111]: is removing that `silent; true` flag that switches the command from non-interactive to interactive?

File: .changeset/smart-drinks-joke.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+"create-cloudflare": patch
+"wrangler": patch
```
Comment (CarmenPopoviciu) [inline .changeset/smart-drinks-joke.md:3]: how come we're bumping wrangler as well? all changes are in the C3 package

Comment (penalosa) [reply .changeset/smart-drinks-joke.md:3]: Oops, good catch!

File: packages/create-cloudflare/src/deploy.ts [hunk 3]
```diff
@@ -99,24 +103,42 @@ export const runDeploy = async (ctx: C3Context) => {
...
+		const url: string | undefined =
+			entries.find((entry) => entry.type === "deploy")?.targets?.[0] ??
+			entries.find((entry) => entry.type === "pages-deploy")?.url;
+		const deployedUrlRegex = /https:\/\/.+\.(pages|workers)\.dev/;
+		const deployedUrlMatch = url?.match(deployedUrlRegex);
+		if (deployedUrlMatch) {
+			ctx.deployment.url = deployedUrlMatch[0];
+		} else {
+			throw new Error("Failed to find deployment url.");
+		}
```
[the remark this answers is not in the document]
Comment (penalosa) [reply packages/create-cloudflare/src/deploy.ts:140]: The deployed URL should always be workers.dev or pages.dev, since this is the first deploy from a template—the user won't have had a chance to set up a custom domain/route yet

**Review by andyjessop — APPROVED** [review]
