### PR TITLE
[C3] Ensure `ts` is defined

### LINKED ISSUE #4599: 🐛 BUG: C3 2.8.2 always initialises JavaScript, even when TypeScript is selected
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

C3 2.8.2

### What version of Node are you using?

20.10.0

### What operating system are you using?

Windows 11

## c3 2.8.1

- `npm create cloudflare@2.8.1 -- --no-auto-update`
- use all defaults - ensure you say "yes" to TypeScript
- you'll get a TypeScript project, with `src/index.ts`

## c3 2.8.2

- `npm create cloudflare@2.8.2 -- --no-auto-update`
- use all defaults - ensure you say "yes" to TypeScript
- you'll get a JavaScript project, no types, `src/index.js`

---

It seems this regression was introduced in https://github.com/cloudflare/workers-sdk/pull/4470 and unfortunately wasn't caught in any automated testing. It also took longer than I care to admit to find that PR, without a changeset 😅

### PR DESCRIPTION
**Pull request by penalosa**
Closes #4599 

**What this PR solves / how to test:**

This fixes a bug introduced in 3.8.2 where the result of `processArgument` for `ts wasn't being used. See https://github.com/cloudflare/workers-sdk/pull/4470/commits/01e2542ba8b3badadebc73547a9e3744de4e2f9c

**Author has addressed the following:**

- Tests
  - [ ] Included
  - [x] Not necessary because: C3 doesn't currently have a way to test interactive prompting, which is the only way to write a regression test for this. It should, and expanding Wrangler's support for interactive prompt testing to support C3 should be a prompt followup
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [x] Not necessary because: Bugfix

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

**Review by jculvey — APPROVED** [review]

**Comment by jculvey** [comment]
My mistake here for sharing a bad code snippet, thanks for fixing this up!

**Comment by petebacondarwin** [comment]
Could we add a test for this?

**Comment by penalosa** [comment]
@petebacondarwin C3 doesn't currently have a way to test interactive prompting, which is the only way to write a regression test for this. It should, and expanding Wrangler's support for interactive prompt testing to support C3 should be a prompt followup, but since this is currently breaking, I think this might be good to get in relatively quickly?

File: packages/cli/interactive.ts [hunk 1]
```diff
@@ -1,10 +1,14 @@
 import { ConfirmPrompt, SelectPrompt, TextPrompt } from "@clack/core";
 import ansiEscapes from "ansi-escapes";
-import logUpdate from "log-update";
+import { createLogUpdate } from "log-update";
 import { blue, bold, brandColor, dim, gray } from "./colors";
 import { cancel, newline, shapes, space, status } from "./index";
 import type { ChalkInstance } from "chalk";
 
+process.stdout.columns = 300;
```
Comment (mrbbot) [inline packages/cli/interactive.ts:8]: Should this be hardcoded?

**Review by mrbbot — APPROVED** [review]

File: packages/cli/interactive.ts (hunk 1 above)
Comment (penalosa) [reply packages/cli/interactive.ts:8]: No, but it can be improved in a followup. We should find a way to get the actual column width, which we're not able to get right now because we're in a child process
