### PR TITLE
[miniflare] fix: allow relative modules `scriptPath` outside of CWD

### LINKED ISSUE #4721: 🐛 BUG: "can't use ".." to break out of starting directory" when using Service Bindings in monorepo
### Which Cloudflare product(s) does this pertain to?

Miniflare

### What version(s) of the tool(s) are you using?

3.20231218.1 [miniflare]

### What version of Node are you using?

20

### What operating system are you using?

Mac

### Describe the Bug

I'm attempting to use Miniflare to run one app (app-2) with a second app (app-1) as a Service Binding. The docs are a little thin here, so I'm not sure if I'm defining the workers in the correct way.

```js
return new Miniflare({
  port: 4000,

  workers: [
    {
      name: 'musicfetch-api',
      scriptPath: 'dist/index.js',
      modules: true,

      serviceBindings: {
        APP_2: 'app-2',
      },
    },
    {
      name: 'app-2',
      scriptPath: resolvePath(__dirname, '../app-2/dist/index.js'),
      modules: true,

      durableObjects: {
        MyDurableObject: 'MyClass',
      },
    },
  ],
});
```

In doing this I'm getting the error:

```
workerd/util/symbolizer.c++:98: warning: Not symbolizing stack traces because $LLVM_SYMBOLIZER is not set. To symbolize stack traces, set $LLVM_SYMBOLIZER to the location of the llvm-symbolizer binary. When running tests under bazel, use `--test_env=LLVM_SYMBOLIZER=<path>`.
workerd/jsg/util.c++:281: error: e = kj/filesystem.c++:315: failed: expected parts.size() > 0 [0 > 0]; can't use ".." to break out of starting directory
stack: 1028e4c07 1028e3963 1028e383f 1008c776f 100b7ece3 100da687f 100db41ef 100db4083 100877e67 10087ddc7 1008815c3 10087ff13 100871b03 100871733 100871653 10087163b 1028fb9ff 1028fbd47 1028fa4a7 1028fa277 1008641af 182aed0df; sentryErrorContext = jsgInternalError
service core:user:rate-limiter: Uncaught Error: internal error
```

Notably: `can't use ".." to break out of starting directory`

I've tried various other approaches (eg. importing a Miniflare instance from `app-2` and calling it programatcally), but it results in the same error. It feels like I'm battling against the framework here for what I imagine is a common project structure.

- Is there a way to define the Miniflare CWD? If so I could have it execute in the parent directory.
- For now I will probably hack around this, but just wanted to leave an issue here to confirm there wasn't a better way.

Cheers 🍺 

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by mrbbot**
Fixes #4721.

**What this PR solves / how to test:**

Previously, Miniflare would resolve relative `scriptPath`s against `moduleRoot` multiple times resulting in incorrect paths and module names. This would lead to `can't use ".." to break out of starting directory` `workerd` errors. This change ensures Miniflare uses `scriptPath` as is, and only resolves it relative to `modulesRoot` when computing module names. Note this bug didn't affect service workers. This allows you to reference a modules `scriptPath` outside the working directory with something like:

```js
const mf = new Miniflare({
	modules: true,
	modulesRoot: "..",
	scriptPath: "../worker.mjs",
});
```

Notably, this wasn't a problem if `modulesRoot` and `scriptPath` were absolute paths.

**Author has addressed the following:**

- Tests
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [x] Not necessary because: fixing a bug

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

File: packages/miniflare/src/plugins/core/modules.ts [hunk 1]
```diff
@@ -174,8 +174,6 @@ export class ModuleLocator {
 	}
 
 	visitEntrypoint(code: string, modulePath: string) {
-		modulePath = path.resolve(this.modulesRoot, modulePath);
```
Comment (mrbbot) [inline packages/miniflare/src/plugins/core/modules.ts:177]: I think this change is safe to make. Resolving to the `modulesRoot` root isn't correct here if `modulePath` is relative. If `modulePath` were absolute, this call would do nothing anyways.

File: packages/miniflare/test/plugins/core/modules.spec.ts [hunk 2]
```diff
@@ -278,6 +279,30 @@ You must manually define your modules when constructing Miniflare:
...
+		await fs.writeFile(
+			path.join(tmp, "worker.mjs"),
+			'export default { fetch() { return new Response("body"); } }'
+		);
+		useCwd(t, child);
+
+		const mf = new Miniflare({
+			modules: true,
+			modulesRoot: "..",
+			scriptPath: "../worker.mjs",
```
Comment (RamIdeas) [inline packages/miniflare/test/plugins/core/modules.spec.ts:298]: could we avoid the cwd change+resetting by choosing another tmp dir for the worker and using a relative path from the cwd to the other tmp dir?

File: packages/miniflare/src/plugins/core/modules.ts (hunk 1 above)
Comment (mrbbot) [reply packages/miniflare/src/plugins/core/modules.ts:177]: Yep, the recursive function is `#visitJavaScriptModule()` below. 👍

File: packages/miniflare/test/plugins/core/modules.spec.ts (hunk 2 above)
Comment (mrbbot) [reply packages/miniflare/test/plugins/core/modules.spec.ts:298]: Yeah, we could. Was keen to this behaviour using the CWD specifically since it's very simple, and is what users are most likely to hit. The `useCwd()` implementation is actually from #4795, which uses it for some other tests too, so we're not just adding it for this. 👍
