### PR TITLE
fix(wrangler): Fixed invalid command / argument error logging

### LINKED ISSUE #11823: Unknown Wrangler commands skip error messaging with a flag
## Problem

Currently if you try to run `wrangler` with an unknown or command that doesn't exist you get an error message like so:
```
➜ npx -y wrangler@latest foo

✘ [ERROR] Unknown argument: foo


wrangler

COMMANDS
  wrangler docs [search..]        📚 Open Wrangler's command documentation in your browser
```
But if you add a flag of any kind, such as `--help` or similar, it will not print this error:
```
➜ npx -y wrangler@latest foo --help
wrangler

COMMANDS
  wrangler docs [search..]        📚 Open Wrangler's command documentation in your browser
```

## Proposed Solution

Update the logic inside of `packages/wrangler/src/core/handle-errors.ts` to make sure that any unknown command errors always get printed, regardless of provided flags.

### PR DESCRIPTION
**Pull request by NuroDev**
Fixes #11823

#### Before
```
➜ wrangler foo --help
wrangler

COMMANDS
  wrangler docs [search..]        📚 Open Wrangler's command documentation in your browser
```

#### After
```
➜ wrangler foo --help

✘ [ERROR] Unknown argument: foo

wrangler

COMMANDS
  wrangler docs [search..]        📚 Open Wrangler's command documentation in your browser
```

---

#### Before
```
➜ ❯ wrangler types --hello

✘ [ERROR] Unknown argument: hello


wrangler

COMMANDS
  wrangler docs [search..]        📚 Open Wrangler's command documentation in your browser
```

#### After
```
➜ wrangler types --hello

✘ [ERROR] Unknown argument: hello


wrangler types [path]

📝 Generate types from your Worker configuration
```

---

- Tests
  - [x] Tests included/updated
  - [ ] Automated tests not possible - manual testing has been completed as follows:
  - [ ] Additional testing not necessary because:
- Public documentation
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: Minor bug fix

*A picture of a cute animal (not mandatory, but encouraged)*

Screenshot 2026-01-22 at 3 38 35 pm

---

<a href="https://app.devin.ai/review/cloudflare/workers-sdk/pull/12050">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

File: packages/wrangler/src/index.ts [hunk 1]
```diff
@@ -1746,16 +1747,29 @@ export async function main(argv: string[]): Promise<void> {
...
 		await showHelpWithCategories();
 		return;
 	}
+
+	// Check for unknown command with a `--help` flag
+	const [subCommand] = nonFlagArgs;
+	if (hasHelpFlag && subCommand) {
+		const knownCommands = registry.topLevelCommands;
+		if (!knownCommands.has(subCommand)) {
+			logger.info("");
```
Comment (NuroDev) [inline packages/wrangler/src/index.ts:1903]: This is here simply to appease formatting to match other errors by adding a spacing around the error.

File: packages/wrangler/src/core/CommandRegistry.ts [hunk 2]
```diff
@@ -67,6 +67,12 @@ export class CommandRegistry {
 	 */
 	#categories: CategoryMap;
 
+	/**
+	 * Set of legacy command names registered outside the `CommandRegistry` class.
+	 * Used to track commands like `containers`, `pubsub`, etc.
+	 */
+	#legacyCommands: Set<string>;
```
Comment (vicb) [inline packages/wrangler/src/core/CommandRegistry.ts:74]: Why can't they all be moved to the registry ?

Comment (NuroDev) [reply packages/wrangler/src/core/CommandRegistry.ts:74]: Most commands are registered with the registry, but a handful of others still use the `wrangler.command(...)` system and we need to aggregate them both into a single source of truth.

To keep this PR simple(r) and not break anything I didn't want to move them to the registry yet. It could be simple, but I'm still not extremely well versed in the CLI setup to know if legacy commands require something that the registry doesn't?

File: packages/wrangler/src/index.ts [hunk 3]
```diff
@@ -1746,16 +1747,28 @@ export async function main(argv: string[]): Promise<void> {
...
+
+	// Check for unknown command with a `--help` flag
+	const [subCommand] = nonFlagArgs;
+	if (hasHelpFlag && subCommand) {
+		const knownCommands = registry.topLevelCommands;
+		if (!knownCommands.has(subCommand)) {
+			logger.error(`Unknown argument: ${subCommand}`);
+			await showHelpWithCategories();
+			throw new CommandLineArgsError(`Unknown argument: ${subCommand}`);
+		}
```
[the remark this answers is not in the document]
Comment (NuroDev) [reply packages/wrangler/src/index.ts:1907]: This is intentional to make it so we can control the order of logging (Error message, help menu, exit process) whilst retaining that the process is throwing an error and not just returning a successful error code.

File: packages/wrangler/src/core/CommandRegistry.ts (hunk 2 above)
Comment (vicb) [reply packages/wrangler/src/core/CommandRegistry.ts:74]: I had a similar question on a PR from TK yesterday.

My opinion is that we should stop adding things in the wrong way(TM) and refactor first - unless there is an urgent need to do otherwise.

Having different code paths is also something that also impacts the other PR.

+100 to refactor before doing more changes that will make the needed refactor harder later.

/cc @MattieTK @petebacondarwin 

edit: I think the following somehow proves my point:

> I'm still not extremely well versed in the CLI setup to know if legacy commands require something that the registry doesn't?

Yes the current code is too complex.
What we should do is to simplify/unify it instead of making if more complex for the next one that will debug/edit it.

Comment (vicb) [reply packages/wrangler/src/core/CommandRegistry.ts:74]: xref https://github.com/cloudflare/workers-sdk/pull/12055#issuecomment-3788668130

**Comment by NuroDev** [comment]
Spoke with @petebacondarwin yesterday about this and I'm going to put this PR on hold until #12055 is merged so this fix doesn't have to rely on legacy commands.

File: packages/wrangler/src/__tests__/index.test.ts [hunk 4]
```diff
@@ -166,6 +166,36 @@ describe("wrangler", () => {
...
+			await expect(
+				runWrangler("invalid-command --help")
+			).rejects.toThrowErrorMatchingInlineSnapshot(
+				`[Error: Unknown argument: invalid-command]`
+			);
+
+			expect(std.err).toContain("Unknown argument: invalid-command");
+			expect(std.out).toContain("wrangler");
+			expect(std.out).toContain("COMMANDS");
+			expect(std.out).toContain("ACCOUNT");
```
Comment (dario-piotrowicz) [inline packages/wrangler/src/__tests__/index.test.ts:182]:
```suggestion
```

are these needed?

File: packages/wrangler/src/__tests__/index.test.ts [hunk 5]
```diff
@@ -166,6 +166,36 @@ describe("wrangler", () => {
...
+			).rejects.toThrowErrorMatchingInlineSnapshot(
+				`[Error: Unknown arguments: invalid-flag-xyz, invalidFlagXyz]`
+			);
+
+			expect(std.err).toContain("Unknown arguments: invalid-flag-xyz");
+			expect(std.out).toContain("wrangler types");
+			expect(std.out).toContain(
+				"Generate types from your Worker configuration"
+			);
+			expect(std.out).not.toContain("ACCOUNT");
```
Comment (dario-piotrowicz) [inline packages/wrangler/src/__tests__/index.test.ts:201]: what is this here for?

I'm confused... why in the test above you were making sure that `std.out` contained `ACCOUNT` but now you check the contrary?

Comment (dario-piotrowicz) [inline packages/wrangler/src/__tests__/index.test.ts:201]: are these needed? 🤔 
```suggestion
```

File: packages/wrangler/src/core/handle-errors.ts [hunk 6]
```diff
@@ -446,19 +446,33 @@ export async function handleError(
...
+
+		const isUnknownArgOrCommand =
+			e.message.includes("Unknown argument") ||
+			e.message.includes("Unknown command");
+
+		const unknownArgsMatch = e.message.match(
+			/Unknown (?:arguments?|command): (.+)/
+		);
+		const unknownArgs = unknownArgsMatch
+			? unknownArgsMatch[1].split(", ").map((a) => a.trim())
```
Comment (dario-piotrowicz) [inline packages/wrangler/src/core/handle-errors.ts]: nit: we can just split by `,` as there's already a `trim()` anyways

```suggestion
			? unknownArgsMatch[1].split(",").map((a) => a.trim())
```

File: packages/wrangler/src/__tests__/index.test.ts (hunk 4 above)
Comment (NuroDev) [reply packages/wrangler/src/__tests__/index.test.ts:182]: This was more to ensure / validate the help message is being written and not just showing the error message.

File: packages/wrangler/src/__tests__/index.test.ts (hunk 5 above)
Comment (NuroDev) [reply packages/wrangler/src/__tests__/index.test.ts:201]: In this case it is because we're running `wrangler types --invalid-flag-xyz` so it should show the `wrangler types --help` help menu and not the root help menu. So we're just explicitly checking that.

File: packages/wrangler/src/__tests__/index.test.ts (hunk 4 above)
Comment (dario-piotrowicz) [reply packages/wrangler/src/__tests__/index.test.ts:182]: ah ok 🙂, possibly I'd add a code comment to clarify this, but up to you 👍

File: packages/wrangler/src/__tests__/index.test.ts (hunk 5 above)
Comment (dario-piotrowicz) [reply packages/wrangler/src/__tests__/index.test.ts:201]: ah ok 🙂 

possibly I'd add a code comment to clarify this, but up to you 👍

Comment (dario-piotrowicz) [reply packages/wrangler/src/__tests__/index.test.ts:201]: code comment, but up to you! 😁
