### PR TITLE
fix: correctly find the latest version of create-cloudflare

### LINKED ISSUE #4729: 🐛 BUG: C3 fails if `npm info` returns warning messages as well as the expected output
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

[C3] latest

### What version of Node are you using?

???

### What operating system are you using?

Windows

### Describe the Bug

As reported by Daniel Benhamou, if npm is configured strangely the warnings get returned as part of the call to `npm info` that C3 makes. This can result in semver complaining about the length of the string it is parsing. E.g.

```
npm create cloudflare@latest
...
TypeError: version is longer than 256 characters.
```

This is due to the semver library trying to parse the warning that is included in the npm command line output: https://github.com/npm/node-semver/blob/816c7b2cbfcb1986958a290f941eddfd0441139e/classes/semver.js#L24

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

The workaround was to remove configuration that caused the warnings.

But the better long term solution would be for C3 to access the npm REST API directly rather than using the command line tool.

### PR DESCRIPTION
**Pull request by petebacondarwin**
When create-cloudflare starts up, it checks to see if the version being run is the latest available on npm.

**What this PR solves / how to test:**

Previously this check used `npm info` to look up the version. But was prone to failing if that command returned additional unexpected output such as warnings.

Now we make a fetch request to the npm REST API directly for the latest version, which does not have the problem of unexpected warnings.

Since the same approach is used to compute the latest version of workerd, the function to do this has been put into a helper.

Fixes #4729

**Author has addressed the following:**

- Tests
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [x] Not necessary because: no user facing change

### CODE REVIEW

**Review by dario-piotrowicz — APPROVED** [review]
Nice! 🤩👍

File: packages/create-cloudflare/src/helpers/latestPackageVersion.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+import { fetch } from "undici";
+
+interface NpmInfoResponse {
+	"dist-tags": { latest: string };
+}
+
+/**
+ * Get the latest version of an npm package by making a request to the npm REST API.
+ */
+export async function getLatestPackageVersion(packageSpecifier: string) {
```
Comment (dario-piotrowicz) [inline packages/create-cloudflare/src/helpers/latestPackageVersion.ts:10]: Not a huge deal, but I think that most if not all functions in create-cloudflare are defined as arrow functions

I personally do prefer standard clear `function`s but maybe we should try to be consistent in this?

Comment (dario-piotrowicz) [reply packages/create-cloudflare/src/helpers/latestPackageVersion.ts:10]: never mind... I can see that we actually have a bit of a mix of both 😅

File: packages/create-cloudflare/src/helpers/latestPackageVersion.ts [hunk 2]
```diff
@@ -0,0 +1,14 @@
+import { fetch } from "undici";
+
+interface NpmInfoResponse {
+	"dist-tags": { latest: string };
+}
```
Comment (dario-piotrowicz) [inline packages/create-cloudflare/src/helpers/latestPackageVersion.ts:5]: just out of curiosity, any reason in particular to use an `interface` here instead of a `type`? 🙂

Comment (petebacondarwin) [reply packages/create-cloudflare/src/helpers/latestPackageVersion.ts:5]: Just did that without thinking. There is basically no difference in this scenario, right?

Comment (dario-piotrowicz) [reply packages/create-cloudflare/src/helpers/latestPackageVersion.ts:5]: Yes I don't think there's really a difference here, I was just thinking of consistency thought the codebase (I think that in C3 `type` is generally used)

Screenshot 2024-01-18 at 16 00 31
Screenshot 2024-01-18 at 16 00 43

But I am fine with either 🙂👍

Comment (dario-piotrowicz) [reply packages/create-cloudflare/src/helpers/latestPackageVersion.ts:5]: as I said I was just curious, I leave it up to you 😄

Comment (petebacondarwin) [reply packages/create-cloudflare/src/helpers/latestPackageVersion.ts]: Done

**Review by RamIdeas — APPROVED** [review]

File: packages/create-cloudflare/src/cli.ts [hunk 3]
```diff
@@ -25,7 +26,13 @@ export const main = async (argv: string[]) => {
 	// Print a newline
 	logRaw("");
 
-	if (args.autoUpdate && (await isUpdateAvailable())) {
+	if (
+		args.autoUpdate &&
+		!process.env.VITEST &&
+		!process.env.CI &&
+		isInteractive() &&
```
Comment (petebacondarwin) [inline packages/create-cloudflare/src/cli.ts:33]: I moved these checks here to make it easier to test the `isUpdateAvailable()` function but also because it is not really nice having checks like that hidden deep down in the code.

**Review by jculvey — APPROVED** [review]
Love the tests!
