### PR TITLE
C3: Don't offer git if username and email unconfigured

### LINKED ISSUE #3683: 🐛 BUG: C3 crashes on git config if username & email are not set on host machine
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

2.1.0 [C3]

### What version of Node are you using?

v18.16.1

### What operating system are you using?

Linux (Fedora 38)

### Describe the Bug

I'm running C3 on a freshly installed machine where the global config for git has not been done, e.g. the two commands below have **not** been run:

```
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
```

During the installation process, the CLI asks whether I would like to use git, I say yes and get the error message seen in the error below.

C3 should first check whether the required settings are in place before running into the error and forcing the user to re-do the entire process (e.g. selecting the stack again)

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

├ Committing new files
│ Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'mxschumacher@fedora.(none)')

│
Error: Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'mxschumacher@fedora.(none)')

npm ERR! code 1
npm ERR! path /home/mxschumacher/code
npm ERR! command failed
npm ERR! command sh -c create-cloudflare

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mxschumacher/.npm/_logs/2023-07-28T11_14_33_787Z-debug-0.log

### PR DESCRIPTION
**Pull request by jculvey**
Fixes #3683.

**What this PR solves / how to test:**

Skips the prompt offering git to c3 users if they haven't yet configured `user.name` and `user.email`. 

**Associated docs issue(s)/PR(s):**

- [insert associated docs issue(s)/PR(s)]

**Author has included the following, where applicable:**

- [ ] Tests
- [ x ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer is to perform the following, as applicable:**

- Checked for inclusion of relevant tests
- Checked for inclusion of a relevant changeset
- Checked for creation of associated docs updates
- Manually pulled down the changes and spot-tested

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

File: packages/create-cloudflare/src/common.ts [hunk 1]
```diff
@@ -361,6 +375,26 @@ async function isGitInstalled() {
...
+
+		const email = await runCommand("git config user.name", {
+			useSpinner: false,
+			silent: true,
+		});
+		if (!email) return false;
+
+		return true;
+	} catch {
+		return null;
```
Comment (dario-piotrowicz) [inline packages/create-cloudflare/src/common.ts:394]: nit: why not `return false` here? below 👇 in the catch you do return `false`, so for consistency I guess I'd do the same here? (or return `null` there too)

**Review by dario-piotrowicz — APPROVED** [review]

**Review by petebacondarwin — APPROVED** [review]
I guess it is too fiddly to write a test for this?

File: packages/create-cloudflare/src/common.ts [hunk 2]
```diff
@@ -371,19 +371,19 @@ async function getGitVersion() {
...
+export async function isGitConfigured() {
 	try {
 		const userName = await runCommand("git config user.name", {
 			useSpinner: false,
 			silent: true,
 		});
 		if (!userName) return false;
 
-		const email = await runCommand("git config user.name", {
+		const email = await runCommand("git config user.email", {
```
Comment (petebacondarwin) [inline packages/create-cloudflare/src/common.ts:386]: Testing - for the win!

**Review by petebacondarwin — APPROVED** [review]
