### PR TITLE
fix: ensure tail exits when the WebSocket disconnects

### LINKED ISSUE #3927: 🐛 BUG: wrangler tail does not recover or exit when websocket disconnects
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.7.0

### What version of Node are you using?

_No response_

### What operating system are you using?

macOS

### Describe the Bug

I've had this issue for awhile: 

When I have an active `wrangler tail` running, and my internet disconnects and reconnects, logs stop coming in, but the command keeps on "running" as if it was still connected to Cloudflare.

I end up running like:

```sh
while sleep 1 ; do wrangler tail ; done
```

and then ctrl+c every few hours to make sure it's still working. This is obviously not a great developer experience.

Question: is there any sort of a "watchdog" on `wrangler tail` that's _supposed_ to detect when a connection is disconnected?

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

There's no error logs when the disconnect happens; the "bug" is the lack of error logs.

### PR DESCRIPTION
**Pull request by petebacondarwin**
## What this PR solves

Previously when the we tail WebSocket disconnected, e.g. because of an Internet failure,
the `wrangler tail` command would just hang and neither exit nor any longer receive tail messages.

Now the process exits with an exit code of 1, and outputs an error message.

The error message is formatted appropriately, if the tail format is set to `json`.

Fixes #3927

## How to test

Automated tests have been added.

But you can test this manually by building Wrangler locally, tailing any Worker and then manually turning off the Internet connection. After 2 secs Wrangler should exit with a suitable error message.

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): <https://github.com/cloudflare/cloudflare-docs/pull/>...
  - [x] Not necessary because: simple bug fix

### CODE REVIEW

File: packages/wrangler/src/tail/index.ts [hunk 1]
```diff
@@ -201,11 +193,59 @@ export async function tailHandler(args: TailArgs) {
...
+	 * We need to know if the connection to the tail drops.
+	 * To do this we send a ping message to the backend every few seconds.
+	 * If we don't get a matching pong message back before the next ping is due
+	 * then we have probably lost the connect.
+	 */
+	function startWebSocketPing() {
+		/** The corelation message to send to tail when pinging. */
+		const PING_MESSAGE = Buffer.from("wrangler tail ping");
+		/** How long to wait between pings. */
+		const PING_INTERVAL = 2000;
```
Comment (Skye-31) [inline packages/wrangler/src/tail/index.ts:221]: This feels a little low - users with poor connections, or those far away from DOs could easily get this timeout, something like 10s would feel a lot better imo

Comment (petebacondarwin) [reply packages/wrangler/src/tail/index.ts:221]: Fair comment. I'll bump it. Thanks

**Review by RamIdeas — APPROVED** [review]

File: packages/wrangler/src/__tests__/tail.test.ts [hunk 2]
```diff
@@ -733,6 +727,51 @@ describe("tail", () => {
...
+				doNotFake: ["setTimeout"],
+			});
+			// Block the websocket from replying to the ping
+			jest.spyOn(MockWebSocket2.prototype, "ping").mockImplementation();
+			await runWrangler("tail test-worker --format=pretty");
+			await api.ws.connected;
+			// The ping is sent every 2 secs, so it should not fail until the second ping is due.
+			await jest.advanceTimersByTimeAsync(2000);
+			await expect(
+				jest.advanceTimersByTimeAsync(2000)
```
Comment (Skye-31) [inline packages/wrangler/src/__tests__/tail.test.ts:751]: These timers need an update too! Perhaps it could be a shared constant from the actual code & the test code?

Comment (petebacondarwin) [reply packages/wrangler/src/__tests__/tail.test.ts:751]: Yeah I missed them first time around but then the tests failed (as is desired!) and I fixed it in an amend commit.
I don't really want to export the constant just for the tests. The tests themselves should tell us if this constant changes unexpectedly.

**Review by Skye-31 — APPROVED** [review]
