### PR TITLE
C3: Fix usage with yarn

### LINKED ISSUE #4230: 🐛 BUG: C3 fails with `yarn`
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

create-cloudflare@2.6.0 / yarn v1.22.19

### What version of Node are you using?

v18.18.2

### What operating system are you using?

Mac

### Describe the Bug

If you use C3 with `yarn` like `yarn create cloudflare`, it fails to create a project. The reason is C3 runs the command as follows:

```txt
yarn create-astro@4.2.1 super-foo-bar --no-install
```

With `yarn`, it should be this (the version number is also not needed):

```txt
yarn create astro super-foo-bar
```

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

```txt
yusuke $ yarn create cloudflare
yarn create v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-cloudflare@2.6.0" with binaries:
      - create-cloudflare
[###################################################################################################################################################################] 197/197
using create-cloudflare version 2.6.0

╭ Create an application with Cloudflare Step 1 of 3
│
├ In which directory do you want to create your application?
│ dir ./super-foo-bar
│
├ What type of application do you want to create?
│ type Website or web app
│
├ Which development framework do you want to use?
│ framework Astro
│
╰ Continue with Astro via `yarn create-astro@4.2.1 super-foo-bar --no-install`

yarn run v1.22.19
error Couldn't find a package.json file in "/Users/yusuke/work/c"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-cloudflare
Arguments:
Directory: /Users/yusuke/work/c
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

### PR DESCRIPTION
**Pull request by jculvey**
Fixes #4230

**What this PR solves / how to test:**

This fixes a regression that was causing c3 to fail with web frameworks when using yarn. 

Being able to version the framework creators we use is important for c3, but unfortunately `yarn` can't `yarn create some-framework@some-particular-version`. This change modifies the `runFrameworkGenerator` helper to use `npx` and spoof the npm user agent so framework creators treat it like a `yarn create` invocation. 

It also patches the package manager reset logic to make it only run when truly needed (i.e. when there's a mismatch between installed node modules and the type of lockfile used by the desired package manager).

This also adds e2e coverage for yarn to hopefully prevent future regressions.

**Author has addressed the following:**

- Tests
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [ ] Not necessary because:

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

File: packages/create-cloudflare/src/helpers/command.ts [hunk 1]
```diff
@@ -185,11 +186,19 @@ export const retry = async <T>(
...
 export const runFrameworkGenerator = async (
 	ctx: PagesGeneratorContext,
-	cmd: string
+	argString: string
 ) => {
+	const cli = getFrameworkCli(ctx);
+	const { npm, dlx } = detectPackageManager();
+
+	// yarn cannot `yarn create@some-version` and doesn't have an npx equivalent
+	// So to retain the ability to lock verisons we run it with `npx` and spoof
```
Comment (dario-piotrowicz) [inline packages/create-cloudflare/src/helpers/command.ts:197]:
```suggestion
	// So to retain the ability to lock versions we run it with `npx` and spoof
```

File: packages/create-cloudflare/src/helpers/command.ts [hunk 2]
```diff
@@ -185,11 +186,19 @@ export const retry = async <T>(
...
+	// the user agent so scaffolding tools treat the invocation like yarn
+	let cmd = `${npm === "yarn" ? "npx" : dlx} ${cli} ${argString}`;
+	const env = npm === "yarn" ? { npm_config_user_agent: "yarn" } : {};
```
Comment (dario-piotrowicz) [inline packages/create-cloudflare/src/helpers/command.ts:200]: why is this needed?

**Review by dario-piotrowicz — APPROVED** [review]

**Comment by yusukebe** [comment]
Thanks for handling the issue!

File: packages/create-cloudflare/src/helpers/command.ts (hunk 2 above)
Comment (jculvey) [reply packages/create-cloudflare/src/helpers/command.ts:200]: So that the scaffolding tools think that they were invoked via `yarn create my-framework`. This means that they'll use `yarn` when doing any npm installs, which in turn means that we don't need to `resetPackageManager`.

Comment (dario-piotrowicz) [reply packages/create-cloudflare/src/helpers/command.ts:200]: ah ok, so here is basically when we run `npx` instead of yarn and we add this user agent to trick the underlying CLIs to think that we're actually using yarn?

Comment (jculvey) [reply packages/create-cloudflare/src/helpers/command.ts:200]: exactly!

File: packages/create-cloudflare/src/helpers/command.ts [hunk 3]
```diff
@@ -254,18 +263,34 @@ export const npmInstall = async () => {
 	});
 };
 
+const needsReset = (ctx: PagesGeneratorContext) => {
```
Comment (RamIdeas) [inline packages/create-cloudflare/src/helpers/command.ts:266]: I'm not sure needsReset is named adequately in a file called command.ts

If this is the prerequisite check before calling resetPackageManager, maybe name is packageManagerNeedsReset

**Review by RamIdeas — APPROVED** [review]

File: .changeset/dirty-bobcats-eat.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+"create-cloudflare": patch
+---
+
+Fixes c3 usage with yarn
```
Comment (petebacondarwin) [inline .changeset/dirty-bobcats-eat.md:5]: Can we have a bit more explanation here? This will appear in the changelog for the package. We should write from the point of view of someone trying to find out what has changed in a release.

File: packages/create-cloudflare/src/frameworks/qwik/index.ts [hunk 5]
```diff
@@ -2,17 +2,12 @@ import { endSection } from "@cloudflare/cli";
...
-import { getFrameworkCli } from "../index";
 import type { FrameworkConfig, PagesGeneratorContext } from "types";
 
-const { npm, npx, dlx } = detectPackageManager();
+const { npm, npx } = detectPackageManager();
 
 const generate = async (ctx: PagesGeneratorContext) => {
-	const cli = getFrameworkCli(ctx);
-
-	// TODO: make this interactive when its possible to specify the project name
```
Comment (petebacondarwin) [inline packages/create-cloudflare/src/frameworks/qwik/index.ts:13]: Is this TODO no longer relevant?

File: packages/create-cloudflare/src/helpers/command.ts (hunk 2 above)
Comment (petebacondarwin) [reply packages/create-cloudflare/src/helpers/command.ts:200]: I assume the code comments were added after this discussion?

File: packages/create-cloudflare/src/helpers/command.ts (hunk 3 above)
Comment (petebacondarwin) [reply packages/create-cloudflare/src/helpers/command.ts:266]: Since it is local to this file and only used in one place I don't think this name is too problematic.

File: packages/create-cloudflare/src/helpers/command.ts [hunk 6]
```diff
@@ -254,18 +263,34 @@ export const npmInstall = async () => {
...
+};
+
 // Resets the package manager context for a project by clearing out existing dependencies
 // and lock files then re-installing.
 export const resetPackageManager = async (ctx: PagesGeneratorContext) => {
 	const { npm } = detectPackageManager();
 
-	// Only do this when using pnpm or yarn
-	if (npm === "npm") return;
+	if (!needsReset(ctx)) return;
```
Comment (petebacondarwin) [inline packages/create-cloudflare/src/helpers/command.ts:287]: Surely we have a lint rule that stops if blocks not in curlies?
I know these are only single line ifs, and I'm being a bit pedantic, but this is a very common cause of errors.

**Review by petebacondarwin — APPROVED** [review]
A few minor nits

File: packages/create-cloudflare/src/helpers/command.ts (hunk 6 above)
Comment (dario-piotrowicz) [reply packages/create-cloudflare/src/helpers/command.ts:287]: I agree it's does feel a bit unsafe (although I understand the convenience)

I don't think we have the [eslint rule](https://eslint.org/docs/latest/rules/curly) set and actually we do this sort of thing in a bunch of different places (C3 not being the biggest offender):
Screenshot 2023-11-02 at 12 49 19

I'm totally on board adding the rule in a followup PR if devprod's on board with it 🙂

File: packages/create-cloudflare/src/frameworks/qwik/index.ts (hunk 5 above)
Comment (jculvey) [reply packages/create-cloudflare/src/frameworks/qwik/index.ts:13]: Yup, very stale comment.
