### PR TITLE
fix(r2): validate bucket names

### LINKED ISSUE #9148: [FEATURE] Improve `wrangler r2` UX
We have found several issue with the `wrangler r2` commands when developing the OpenNext adapters - using wrangler v4.6

### local

**L.1: it is possible to put when the bucket does not exist:**

```
-> % wrangler r2 object put "unexisting-bucket/key" --file LICENSE --local 

 ⛅️ wrangler 4.6.0 (update available 4.14.2)
------------------------------------------------------

Creating object "key" in bucket "unexisting-bucket".
▲ [WARNING] By default, `wrangler r2` commands access a local simulator of your R2 bucket, the same as that used by `wrangler dev`. To access your remote R2 bucket, re-run the command with the --remote flag


Upload complete.
```

**L.2:  bucket names are not validated (they should be lowercase)**

```
-> % wrangler r2 object put "INVALID/key" --file LICENSE --local 

 ⛅️ wrangler 4.6.0 (update available 4.14.2)
------------------------------------------------------

Creating object "key" in bucket "INVALID".
▲ [WARNING] By default, `wrangler r2` commands access a local simulator of your R2 bucket, the same as that used by `wrangler dev`. To access your remote R2 bucket, re-run the command with the --remote flag


Upload complete.
```

Here we should error saying that the bucket name is invalid

### remote

**R.1: invalid bucket names generate not very helpful error message**

```
-> % wrangler r2 object put "INVALID/key" --file LICENSE --remote

 ⛅️ wrangler 4.6.0 (update available 4.14.2)
------------------------------------------------------

Creating object "key" in bucket "INVALID".

✘ [ERROR] Failed to fetch /accounts/0a32994c9e7d81ae884d4b40873dd43f/r2/buckets/INVALID/objects/key - 400: Bad Request);


If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
Note that there is a newer version of Wrangler available (4.14.2). Consider checking whether upgrading resolves this error.
✔ Would you like to report this error to Cloudflare? Wrangler's output and the error details will be shared with the Wrangler team to help us diagnose and fix the issue. … no
```

We should probably have an error message like this one:

```
-> % wrangler r2 bucket create "INVALID"

 ⛅️ wrangler 4.6.0 (update available 4.14.2)
------------------------------------------------------


✘ [ERROR] The bucket name "INVALID" is invalid. Bucket names must begin and end with an alphanumeric and can only contain letters (a-z), numbers (0-9), and hyphens (-).
```

/cc @conico974 @james-elicx

### PR DESCRIPTION
**Pull request by vicb**
Fixes #9148

Before this PR, bucket names were only validated when creating a bucket (via `wrangler r2 create bucket_name`)

This PR adds validation to:
- wrangler config
- object commands - when trying to put, get, delete an object
- pages dev CLI command
- pipeline config

---

- Tests
  - [ ] TODO (before merge)
  - [x] Tests included
  - [ ] Tests not necessary because:
- Wrangler / Vite E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [x] Required
  - [ ] Not required because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: names are documented
- Wrangler V3 Backport
  - [ ] TODO (before merge)
  - [x] Wrangler PR: https://github.com/cloudflare/workers-sdk/pull/9172
  - [ ] Not necessary because: patch

### CODE REVIEW

**Comment by penalosa** [comment]
@vicb this needs a backport since it's a Wrangler patch

**Comment by vicb** [comment]
> @vicb this needs a backport since it's a Wrangler patch

I don't think we want to backport that?

**Comment by vicb** [comment]
> > @vicb this needs a backport since it's a Wrangler patch
> 
> I don't think we want to backport that?

Discussed offline, I'll create a v3 PR when this one is green and approved

File: fixtures/pages-functions-app/functions/r2/create.ts [hunk 1]
```diff
@@ -1,8 +1,8 @@
 type Env = {
-	BUCKET: R2Bucket;
+	bucket: R2Bucket;
```
Comment (petebacondarwin) [inline fixtures/pages-functions-app/functions/r2/create.ts:2]: Seems like an unnecessary change, or am I missing something?

File: packages/wrangler/src/config/validation.ts [hunk 2]
```diff
@@ -2561,6 +2562,18 @@ const validateR2Binding: ValidatorFn = (diagnostics, field, value) => {
...
 	}
+	if (
+		isValid &&
+		hasProperty(value, "bucket_name") &&
+		!isValidR2BucketName(value.bucket_name)
+	) {
+		diagnostics.errors.push(
+			`"${field}.bucket_name" must begin and end with an alphanumeric, only contain letters (a-z), numbers (0-9), and hyphens (-)," +
+			" and be between 3 and 63 characters long. but got ${JSON.stringify(value.bucket_name)}.`
+		);
```
Comment (petebacondarwin) [inline packages/wrangler/src/config/validation.ts:2573]: This message is repeated six times in the code. Could it just be added to the `isValidR2BucketName()` function to avoid the duplication?

File: packages/wrangler/src/pages/dev.ts [hunk 3]
```diff
@@ -1269,6 +1270,16 @@ function getBindingsFromArgs(args: typeof pagesDevCommand.args): Partial<
...
 				}
 
+				const bucketName = ref || binding.toString();
+
+				if (!isValidR2BucketName(bucketName)) {
+					logger.error(
+						`The bucket name "${bucketName}" is invalid. ` +
+							"Bucket names must begin and end with an alphanumeric, only contain letters (a-z), numbers (0-9), and hyphens (-), and be between 3 and 63 characters long."
+					);
+					return;
```
Comment (petebacondarwin) [inline packages/wrangler/src/pages/dev.ts:1280]: Why the quiet exit here?
If you throw a UserError then the process will exit with a non-zero exit code.

File: packages/wrangler/src/config/validation.ts [hunk 4]
```diff
@@ -2561,6 +2562,18 @@ const validateR2Binding: ValidatorFn = (diagnostics, field, value) => {
 		);
 		isValid = false;
 	}
+	if (
+		isValid &&
+		hasProperty(value, "bucket_name") &&
+		!isValidR2BucketName(value.bucket_name)
+	) {
+		diagnostics.errors.push(
+			`"${field}.bucket_name" must begin and end with an alphanumeric, only contain letters (a-z), numbers (0-9), and hyphens (-)," +
```
Comment (emily-shen) [inline packages/wrangler/src/config/validation.ts:2571]: looks like uppercase letters are invalid too, even though the api error message gives zero indication about this :/

```suggestion
			`"${field}.bucket_name" must begin and end with an alphanumeric character, only contain lowercase letters (a-z), numbers (0-9), and hyphens (-)," +
```

File: packages/wrangler/src/pipelines/cli/create.ts [hunk 5]
```diff
@@ -157,6 +158,10 @@ export const pipelinesCreateCommand = createCommand({
 
 	async handler(args, { config }) {
 		const bucket = args.r2Bucket;
+		if (!isValidR2BucketName(bucket)) {
+			`The bucket name "${bucket}" is invalid. ` +
```
Comment (emily-shen) [inline packages/wrangler/src/pipelines/cli/create.ts:162]: this doesn't seem to be throwing an error

File: fixtures/pages-functions-app/functions/r2/create.ts (hunk 1 above)
Comment (vicb) [reply fixtures/pages-functions-app/functions/r2/create.ts:2]: The name should be lowercase

File: packages/wrangler/src/config/validation.ts (hunk 2 above)
Comment (vicb) [reply packages/wrangler/src/config/validation.ts:2573]: We can do that, probably renaming the function to `validateR2BucketName` returning `{isValid, errorMsg?}`

File: packages/wrangler/src/pages/dev.ts (hunk 3 above)
Comment (vicb) [reply packages/wrangler/src/pages/dev.ts:1280]: Because this is similar to line 1270 and I don't any `UserError` here.

File: packages/wrangler/src/pipelines/cli/create.ts (hunk 5 above)
Comment (vicb) [reply packages/wrangler/src/pipelines/cli/create.ts:162]: Good catch, it's missing a `throw UserError(...)` I guess

File: fixtures/pages-functions-app/functions/r2/create.ts (hunk 1 above)
Comment (petebacondarwin) [reply fixtures/pages-functions-app/functions/r2/create.ts:2]: But this is not the bucket name, it is the binding name, which doesn't have the same validation requirements.

**Comment by vicb** [comment]
@emily-shen @petebacondarwin thanks for the reviews, I have addressed the feedback, PTAL

- Factor and clarify the format message into a single const
- Add a missing `throw new UserError(...)`

File: packages/wrangler/src/config/validation.ts [hunk 6]
```diff
@@ -2569,6 +2581,17 @@ const validateR2Binding: ValidatorFn = (diagnostics, field, value) => {
 		);
 		isValid = false;
 	}
+	if (
+		isValid &&
```
Comment (emily-shen) [inline packages/wrangler/src/config/validation.ts:2585]: with this `isValid` check, if you have invalid  bucket_name and invalid preview_bucket_name, only the error for bucket_name will show up I think?

Comment (vicb) [reply packages/wrangler/src/config/validation.ts:2585]: That's right.

I felt like this was good enough (i.e. you'll get the other error the next time if only one is fixed) vs making the code more complicated (to only validate when there is a name)

But if you feel strongly I can change that, LMK

Comment (emily-shen) [reply packages/wrangler/src/config/validation.ts:2585]: i think it we usually try our best to avoid that pattern - fixing something and exposing another error, although the error is the same here so its probably not a huge deal.

**Review by emily-shen — APPROVED** [review]

File: packages/wrangler/src/config/validation.ts (hunk 6 above)
Comment (vicb) [reply packages/wrangler/src/config/validation.ts:2585]: I understand but at the same time I don't really understand why we have a `preview_bucket_name` when we have environments and I don't think other bindings have a similar thing.

**Comment by arcticmatt** [comment]
would be nice if there was a flag/option to disable this behavior, since it's not backwards compatible with all `wrangler.jsonc` files that were working before this patch

**Comment by edmundhung** [comment]
@arcticmatt We are relaxing R2 bucket validation for pages dev commands in #9257 based on the feedbacks and will release it very soon.

**Comment by arcticmatt** [comment]
@edmundhung I'm not using pages dev

Here's an example of the issue I ran into:

```
pnpm wrangler d1 migrations apply DB_NAME --local

 ⛅️ wrangler 4.15.1
-------------------


✘ [ERROR] Processing wrangler.jsonc configuration:

    - r2_buckets[0].bucket_name="REPLACEME_R2_BUCKET_NAME" is invalid. Bucket names must begin and
  end with an alphanumeric character, only contain lowercase letters, numbers, and hyphens, and be
  between 3 and 63 characters long.
```

I have some existing code that uses all caps for bucket names, and then I replace the bucket name with a valid one once deploying. It's not too bad to start using lowercase for the placeholder name, but I didn't expect this to break when upgrading to a new minor version of Wrangler

**Comment by Cherry** [comment]
Yeah, this being validated at wrangler config level, which happens for (almost?) every command in `wrangler` can be quite problematic when this wasn't previous enforced this way. Template or multi-stage-like projects where bindings are inserted at build time, etc. are going to suffer with errors now when upgrading.

If this is to be validated, I'd recommend it's only on operations where it fundamentally needs to be - like `r2` commands, deploying a worker, etc. Running local d1 migrations for example in a project with a `wrangler.json` that has a template like `<BINDING_NAME>` similar to the docs really shouldn't start causing commands to throw errors when upgrading to a new minor wrangler version.
