### PR TITLE
fix: ensure logs containing `at ` not truncated to `at [object Object]`

### LINKED ISSUE #4668: 🐛 BUG: Logs with `at ` get truncated to `at [object Object]`
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.22.1

### What version of Node are you using?

20.10.0

### What operating system are you using?

Windows 11

### Describe the Bug

With the following code:
```typescript
export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		console.log('some normal text to log')
		console.log('text with at the in the middle')
		return new Response('Hello World!');
	},
};
```
Running `npx wrangler dev` and then hitting the worker, results in:
```
[wrangler:inf] GET / 200 OK (14ms)
some normal text to log
text with at [object Object]
```

On further debug, it seems that `at` followed by a space, gets truncated to `at [object Object]` in all console logs. I suspect this line in `miniflare` is catching it:

https://github.com/cloudflare/workers-sdk/blob/main/packages/miniflare/src/plugins/core/errors/callsite.ts#L40

Originally reported on the forum: https://community.cloudflare.com/t/wrangler-dev-fails-to-properly-log-at-the/596263?u=cherryjimbo

### PR DESCRIPTION
**Pull request by mrbbot**
Fixes #4668.

**What this PR solves / how to test:**

Previously, logs containing `at ` were always treated as stack trace call sites requiring source mapping. This change updates the call site detection to avoid false positives, by requiring an indent of 4 spaces and a valid file name. We aren't able to rely on newlines here, as we support source mapping with `console.log({ stack: new Error("oopps").stack })`. In this case, the `value` passed to `getSourceMappedString()` contains ANSI colour codes and looks something like...

```
{
  value: '{\n' +
    "  stack: \x1B[32m'Error: oopps\\n'\x1B[39m +\n" +
    "    \x1B[32m'    at Object.fetch (file:///Users/bcoll/.wrangler/tmp/dev-Bzz87I/index.js:53:26)\\n'\x1B[39m +\n" +
    "    \x1B[32m'    at __facade_modules_fetch__ (file:///Users/bcoll/.wrangler/tmp/dev-Bzz87I/index.js:111:46)\\n'\x1B[39m +\n" +
    "    \x1B[32m'    at __facade_invokeChain__ (file:///Users/bcoll/.wrangler/tmp/dev-Bzz87I/index.js:39:10)\\n'\x1B[39m +\n" +
    "    \x1B[32m'    at Object.next (file:///Users/bcoll/.wrangler/tmp/dev-Bzz87I/index.js:36:14)\\n'\x1B[39m +\n" +
    "    \x1B[32m'    at jsonError (file:///Users/bcoll/.wrangler/tmp/dev-Bzz87I/index.js:69:32)\\n'\x1B[39m +\n" +
    "    \x1B[32m'    at __facade_invokeChain__ (file:///Users/bcoll/.wrangler/tmp/dev-Bzz87I/index.js:39:10)\\n'\x1B[39m +\n" +
    "    \x1B[32m'    at __facade_invoke__ (file:///Users/bcoll/.wrangler/tmp/dev-Bzz87I/index.js:42:10)\\n'\x1B[39m +\n" +
    "    \x1B[32m'    at Object.fetch (file:///Users/bcoll/.wrangler/tmp/dev-Bzz87I/index.js:162:14)'\x1B[39m\n" +
    '}'
}
```

To test this, run `wrangler dev` in `fixtures/worker-app` and make a request to `http://localhost:8787`. You should see all `console.log()`s correctly logged in the output.

**Author has addressed the following:**

- Tests
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [x] Not necessary because: fixing a regression

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

File: packages/wrangler/src/sourcemap.ts [hunk 1]
```diff
@@ -118,7 +120,7 @@ export function getSourceMappedString(value: string): string {
  */
 
 const CALL_SITE_REGEXP =
-	/at (?:(.+?)\s+\()?(?:(.+?):(\d+)(?::(\d+))?|([^)]+))\)?/g;
+	/ {4}at (?:(.+?)\s+\()?(?:(.+?):(\d+)(?::(\d+))?|([^)]+))\)?/g;
```
Comment (matthewjosephtaylor) [inline packages/wrangler/src/sourcemap.ts:123]: IMHO this entire 'feature' wants to be scrapped. No way can it be correct to perform REGEX on the output like this to replace console log messages. This is just ASKING for endless weird bugs and frustration.

Basically this just seems to hide the bug and change it from 'at' to ' {4}at' which is also quite likely to be a normal console log message a user might want to log.

Comment (mrbbot) [reply packages/wrangler/src/sourcemap.ts:123]: Apologies for the frustration this caused you. This is a fair point and something I considered. I'm also checking that a valid file name was found in the match...
https://github.com/cloudflare/workers-sdk/blob/2362fb4d4a1ebd69e739b81f129fca91346342e9/packages/wrangler/src/sourcemap.ts#L92
...and have added a test to cover the simple ` {4}at` case...
https://github.com/cloudflare/workers-sdk/blob/2362fb4d4a1ebd69e739b81f129fca91346342e9/fixtures/worker-app/tests/index.test.ts#L47
You're right it's still possible to trick this heuristic though. An alternative idea would be to override `Error.prepareStackTrace` inside the worker to actually perform source mapping. The thing that makes this tricky is that `Error.prepareStackTrace` functions need to be synchronous, and we can't really access the file system for source maps inside a worker synchronously right now. We could override this function to insert an invisible character that this regexp looked for to verify the log was actually a stack trace. 🤔

Comment (mrbbot) [reply packages/wrangler/src/sourcemap.ts:123]: Alternatively, we already know all the files passed to workerd, so we could also pass those files' source maps as bindings? The source maps could be pretty big though, which may impact startup time.

Comment (mrbbot) [reply packages/wrangler/src/sourcemap.ts:123]: Or we use a module fallback service to allow source maps to be imported as data modules? 🤔

Comment (mrbbot) [reply packages/wrangler/src/sourcemap.ts]: After speaking with @RamIdeas, I've updated the regexp to require `    at` appears at the start of a line, optionally after whitespace and a single quote to handle the `console.log({ stack: new Error("oopps").stack })` case.

File: fixtures/worker-app/tests/index.test.ts [hunk 2]
```diff
@@ -35,14 +35,22 @@ describe("'wrangler dev' correctly renders pages", () => {
...
+			/Error: logged error one.+fixtures\/worker-app\/src\/log\.ts:7:14/s
 		);
 		expect(output).toMatch(
-			/Error: logged error two.+fixtures\/worker-app\/src\/log.ts:8:14/s
+			/Error: logged error two.+fixtures\/worker-app\/src\/log\.ts:8:14/s
 		);
 		expect(output).toMatch(
-			/Error: logged error three.+fixtures\/worker-app\/src\/log.ts:9:23/s
+			/Error: logged error three.+fixtures\/worker-app\/src\/log\.ts:9:23/s
 		);
```
Comment (RamIdeas) [inline fixtures/worker-app/tests/index.test.ts:45]: I – and this could just be me – lost context of what we were matching here with the `.+` in the middle

I think this might be clearer:
```
expect(output).toMatch(
    /Error: logged error one\n.+at logErrors.+fixtures\/worker-app\/src\/log\.ts:7:14/
);
expect(output).toMatch(
    /Error: logged error two\n.+at logErrors.+fixtures\/worker-app\/src\/log\.ts:8:14/
);
expect(output).toMatch(
    /Error: logged error three\n.+at logErrors.+fixtures\/worker-app\/src\/log\.ts:9:23/
);
```

Comment (mrbbot) [reply fixtures/worker-app/tests/index.test.ts]: Updated in 06daaaa

**Review by RamIdeas — APPROVED** [review]
