### PR TITLE
Bail early on middleware format mismatch

### LINKED ISSUE #3575: 🐛 BUG: Fail early when env-wrapping middleware are used with service-worker syntax workers
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

3.1.2

### What operating system are you using?

Mac

### Describe the Bug

Adding a D1 binding to a service-worker syntax Worker isn't supported, which I think is a general problem for all bindings involving middleware shims. I get the following error:

```
[mf:err] TypeError: head is not a function
    at __facade_invokeChain__ (/Users/glen/src/experiments/service-worker-syntax/node_modules/wrangler/templates/middleware/common.ts:53:9)
    at Object.next (/Users/glen/src/experiments/service-worker-syntax/node_modules/wrangler/templates/middleware/common.ts:50:11)
    at jsonError (/Users/glen/src/experiments/service-worker-syntax/node_modules/wrangler/templates/middleware/middleware-miniflare3-json-error.ts:22:30)
    at __facade_invokeChain__ (/Users/glen/src/experiments/service-worker-syntax/node_modules/wrangler/templates/middleware/common.ts:53:9)
    at __facade_invoke__ (/Users/glen/src/experiments/service-worker-syntax/node_modules/wrangler/templates/middleware/common.ts:63:9)
    at null.<anonymous> (/Users/glen/src/experiments/service-worker-syntax/node_modules/wrangler/templates/middleware/loader-sw.ts:209:3)
```

Although, saying that, this seems to be a service-worker-specific version of the middleware functionality?

The generated code's method looks like this, FYI:

```js
  function __facade_invokeChain__(request, env, ctx, dispatch, middlewareChain) {
    const [head, ...tail] = middlewareChain;
    const middlewareCtx = {
      dispatch,
      next(newRequest, newEnv) {
        return __facade_invokeChain__(newRequest, newEnv, ctx, dispatch, tail);
      }
    };
    return head(request, env, ctx, middlewareCtx);
  }
```

In any case, Wrangler should early-detect a service-worker syntax file and a D1 binding and explicitly reject them. Even if there's a way to fix the shim/middleware code and make it work, there's a new version of the binding coming that doesn't support service-worker syntax, so we may as well start explicitly rejecting it now.

### PR DESCRIPTION
**Pull request by penalosa**
Fixes #3575

**What this PR solves / how to test:**

Fail early with a helpful error message when a configured middleware doesn't support your Worker's script format (i.e. D1 and multiworker only support the modules format).

**Author has included the following, where applicable:**

- [ ] Tests
- [ ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer is to perform the following, as applicable:**

- Checked for inclusion of relevant tests
- Checked for inclusion of a relevant changeset
- Checked for creation of associated docs updates
- Manually pulled down the changes and spot-tested

### CODE REVIEW

File: packages/wrangler/src/deployment-bundle/bundle.ts [hunk 1]
```diff
@@ -302,6 +306,7 @@ export async function bundleWorker(
 			config: {
 				D1_IMPORTS: betaD1Shims,
 			},
+			supports: ["modules"],
```
Comment (mrbbot) [inline packages/wrangler/src/deployment-bundle/bundle.ts:309]: Is there a reason this and the multi-worker middleware can't support the `service-worker` format? Could you call `getMaskedEnv()` on the global scope?

Comment (JacobMGEvans) [reply packages/wrangler/src/deployment-bundle/bundle.ts:309]: ?

**Comment by JacobMGEvans** [comment]
Is there (besides the conflict) holding this back?

**Comment by lrapoport-cf** [comment]
hey @penalosa :) do you still plan on landing this or should it be closed?

**Comment by penalosa** [comment]
@lrapoport-cf Still planning to land this, if possible. @mrbbot given that D1 doesn't support module workers and we generally encourage module workers over service workers, is this okay to go in as-is, or would you prefer it to try and support service workers?

**Review by mrbbot — APPROVED** [review]
@penalosa that's fair. Adding support for them can be a separate PR if we deem that necessary. We're not breaking existing users with this PR. 👍
