### PR TITLE
[wrangler] fix: check permissions on authentication error with API token set

### LINKED ISSUE #4078: 🐛 BUG: Failure to report Authentication Error
### Which Cloudflare product(s) does this pertain to?

D1

### What version(s) of the tool(s) are you using?

3.8.0 -> 3.10.1

### What version of Node are you using?

_No response_

### What operating system are you using?

Linux

### Describe the Bug

I was running this command in ci: `wrangler d1 migrations apply customer_db --env staging` and my script would just die. No logging output, nothing I could do to get any information.

After numerous failures debugging the issue, I added this command: `wrangler d1 backup list customer_db --env staging` and viola...
```
✘ [ERROR] A request to the Cloudflare API (/accounts/{MYACCTID}/d1/database/{MYDBID}/backup) failed.
  Authentication error [code: 10000]
```

I went and updated my API Token, which didn't have D1 edit permissions and magically it all worked. 

Wrangler has to display an error message when not authenticated / authorized for the given functionality.

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by mrbbot**
Fixes #4078.

**What this PR solves / how to test:**

The API tokens set with the `CLOUDFLARE_API_TOKEN` environment variable may not include all required permissions for Wrangler. This change ensures the error message for authentication errors includes a suggestion to check token permissions. Ideally, authentication errors would inclusion the name of the required permission that was missing, but they don't. 🙁 

**Author has addressed the following:**

- Tests
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [x] Not necessary because: this is an improvement to error messaging

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

File: packages/wrangler/src/index.ts [hunk 1]
```diff
@@ -724,6 +731,13 @@ export async function main(argv: string[]): Promise<void> {
 			await createCLIParser([...argv, "--help"]).parse();
 		} else if (isAuthenticationError(e)) {
 			logger.log(formatMessage(e));
+			const envAuth = getAuthFromEnv();
+			if (envAuth !== undefined && "apiToken" in envAuth) {
+				const message =
+					"📎 It looks like you've set a custom API token with an environment variable.\n" +
```
Comment (petebacondarwin) [inline packages/wrangler/src/index.ts:737]:
```suggestion
					"📎 It looks like you are authenticating Wrangler via a custom API token set in an environment variable.\n" +
```

**Review by petebacondarwin — APPROVED** [review]
Minor textual change suggestion. Otherwise LGTM.
