### PR TITLE
fix(wrangler): show error when D1 migration commands run without config file

### LINKED ISSUE #11709: Wrangler d1 migrations apply in non-worker folder gives no feedback
### What versions & operating system are you using?

```
  System:
    OS: macOS 26.2
    CPU: (14) arm64 Apple M4 Pro
    Memory: 1.51 GB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.11.1 - /Users/jilles/.local/state/fnm_multishells/85211_1759849658659/bin/node
    npm: 11.6.2 - /Users/jilles/.local/state/fnm_multishells/85211_1759849658659/bin/npm
    pnpm: 10.25.0 - /Users/jilles/Library/pnpm/pnpm
  npmPackages:
    @cloudflare/vite-plugin: ^1.13.8 => 1.17.1
    wrangler: ^4.54.0 => 4.54.0
```

### Please provide a link to a minimal reproduction

https://github.com/jillesme/thecoffeecluster

### Describe the Bug

When I accidentally ran wrangler d1 migration apply in the wrong folder (a non worker folder) I get no feedback. No success or failure. I'd expect something like "no wrangler.json or toml found in [folder]"

Image

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by southpolesteve**
Fixes #11709.

Previously, running `wrangler d1 migrations apply`, `wrangler d1 migrations list`, or `wrangler d1 migrations create` in a directory without a `wrangler.toml` or `wrangler.json` file would silently exit with no feedback, leaving users confused about what went wrong.

Now these commands display a clear error message:
> "No configuration file found. Create a wrangler.toml or wrangler.json file to define your D1 database."

Written using OpenCode and Claude Opus 4.5

Prompt: "Can you solve this issue for me https://github.com/cloudflare/workers-sdk/issues/11709"

---

- Tests
  - [x] Tests included/updated
  - [ ] Tests not necessary because:
- Public documentation
  - [ ] Cloudflare docs PR(s):
  - [x] Documentation not necessary because: This is a bug fix that adds an error message; no new features or API changes
- Wrangler V3 Backport
  - [ ] Wrangler PR:
  - [x] Not necessary because: Not a patch change to stable V3; this is a UX improvement for current version

### CODE REVIEW

File: packages/wrangler/src/d1/migrations/create.ts [hunk 1]
```diff
@@ -40,17 +40,19 @@ export const d1MigrationsCreateCommand = createCommand({
 	},
 	positionalArgs: ["database", "message"],
 	async handler({ database, message }, { config }) {
+		if (!config.configPath) {
```
Comment (lambrospetrou) [inline packages/wrangler/src/d1/migrations/create.ts:43]: Wasn't this covered by the database info check below?

File: packages/wrangler/src/d1/migrations/create.ts [hunk 2]
```diff
@@ -40,17 +40,19 @@ export const d1MigrationsCreateCommand = createCommand({
...
+			throw new UserError(
+				"No configuration file found. Create a wrangler.toml or wrangler.json file to define your D1 database."
```
Comment (petebacondarwin) [inline packages/wrangler/src/d1/migrations/create.ts]: We are trying to discourage TOML usage:


```suggestion
				"No configuration file found. Create a wrangler.jsonc to define your D1 database."
```

File: packages/wrangler/src/d1/migrations/create.ts (hunk 1 above)
Comment (petebacondarwin) [reply packages/wrangler/src/d1/migrations/create.ts:43]: In the case of create I think you are right and you'd see an error like:

```
Couldn't find a D1 DB with the name or binding 'data-base-name' in your Wrangler configuration file.
```

But in the case of apply (which is what the original issue is about) it only shows that error if you have specified `--remote`.

**Review by petebacondarwin — CHANGES_REQUESTED** [review]

File: packages/wrangler/src/d1/migrations/create.ts (hunk 2 above)
Comment (petebacondarwin) [reply packages/wrangler/src/d1/migrations/create.ts]: The tests will need to change too 😢

File: packages/wrangler/src/d1/migrations/create.ts (hunk 1 above)
Comment (southpolesteve) [reply packages/wrangler/src/d1/migrations/create.ts:43]: Yes, the other error would get thrown as well, but I think it isn't exactly clear what's going on. 

Seems fine to throw an earlier error if we don't have a config file at all. Better DX

**Review by petebacondarwin — APPROVED** [review]
