### PR TITLE
[wrangler] Add support for customising inspector IP address

### LINKED ISSUE #5603: 🐛 BUG: It does not seem possible to have the inspector listen on non-localhost IP
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler core, Miniflare

### What version(s) of the tool(s) are you using?

Wrangler 3.50.0

### What version of Node are you using?

v20.11.1

### What operating system and version are you using?

Debian Bookworm

### Observed behavior
Even when specifying `wrangler dev --ip 0.0.0.0`, the inspector only listens on 127.0.0.1 and there does not appear to be any additional flags to force the inspector to bind to any IP other than the loopback.

### Expected behavior
There should be some way to for the inspector to bind to non-loopback addresses. This is important when running wrangler inside of a docker container, where port exposure works by forwarding the container's internal socket (e.g. 172.40.40.11:9223) to some host socket e.g. 192.168.1.77:1234. It's not possible to forward a container's loopback address.

In some sense, this is a regression caused by https://github.com/cloudflare/workers-sdk/pull/4437
It's totally understandable for the inspector to listen only on loopback by default, but it's a bummer that there is now no way to have it listen on non-loopback addresses.

### Steps to reproduce
Just run `wrangler dev` and observe that there is no way to have the inspector bind to anything other than loopback. Specifying `--ip 0.0.0.0` does not seem to allow this, either.

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by penalosa**
Fixes #5603

This PR adds support for customising the IP address that the inspector server listens on via a new `--inspector-ip` CLI flag and `dev.inspector_ip` configuration option.

## Problem

Previously, the inspector was hardcoded to listen only on `127.0.0.1`, which prevented debugging in Docker containers and other environments where external access is needed.

## Solution

- Added `--inspector-ip` CLI flag to `wrangler dev`
- Added `dev.inspector_ip` configuration option in `wrangler.json`/`wrangler.toml`
- Updated the inspector proxy controller to accept and use a custom hostname
- Added comprehensive tests for the new functionality
- Default remains `127.0.0.1` for security

## Example Usage

```bash
# CLI flag
wrangler dev --inspector-ip 0.0.0.0
```

```jsonc
// wrangler.json
{
  "dev": {
    "inspector_ip": "0.0.0.0"
  }
}
```

---

- Tests
  - [x] Tests included/updated
  - [ ] Automated tests not possible - manual testing has been completed as follows:
  - [ ] Additional testing not necessary because:
- Public documentation
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: CLI flag and config option are self-documenting, and the changeset includes usage examples

### CODE REVIEW

File: packages/wrangler/src/api/startDevWorker/ConfigController.ts [hunk 1]
```diff
@@ -60,6 +60,25 @@ import type { WorkerRegistry } from "miniflare";
 const getInspectorPort = memoizeGetPort(DEFAULT_INSPECTOR_PORT, "127.0.0.1");
 const getLocalPort = memoizeGetPort(DEFAULT_LOCAL_PORT, "localhost");
 
+async function resolveInspectorConfig(
```
Comment (NuroDev) [inline packages/wrangler/src/api/startDevWorker/ConfigController.ts:63]: Nit pick: Can we add a JSDoc comment here, just so we have a bit of detail on the function.

Comment (penalosa) [reply packages/wrangler/src/api/startDevWorker/ConfigController.ts:63]: Can do—what would you be looking for it to include?

Comment (NuroDev) [reply packages/wrangler/src/api/startDevWorker/ConfigController.ts:63]: I think just a basic description and `@param`s would do. Just makes skimming through and getting more detail easier.

Comment (penalosa) [reply packages/wrangler/src/api/startDevWorker/ConfigController.ts:63]: Hmmm, I'm not sure what value that would really provide. The params section of JSDoc is less useful with TS, and in this case both params are widely used across the codebase with good JSDoc descriptions at their source.

In terms of a basic description, I suspect that would end up as "Resolve the inspector config from (in order), passed in parameters, the config file, and default values", and IMO the function is simple enough that that's not useful.
