### PR TITLE
fix(vitest-pool-workers): improve error message with isolated storage

### LINKED ISSUE #5629: 🐛 BUG: Durable Object tests won't run, `.sqlite` error
### Which Cloudflare product(s) does this pertain to?

Workers Vitest Integration

### What version(s) of the tool(s) are you using?

0.1.19 [@cloudflare/vitest-pool-workers], 1.3.0 [vitest]

### What version of Node are you using?

v20.7.0

### What operating system and version are you using?

Mac Sonoma 14.4.1

### Observed behavior
Tests fail with a fatal error when a `fetch` response body is **not** consumed by tests.

```console
/Users/maxime/.nvm/versions/node/v20.7.0/bin/node /Users/maxime/Code/NC/lalala/node_modules/vitest/vitest.mjs --run --reporter ../../../Applications/WebStorm.app/Contents/plugins/javascript-impl/helpers/vitest-intellij/node_modules/vitest-intellij-reporter-safe.js --testNamePattern=^ ?smoke checks 404s on non-consume path$ /Users/maxime/Code/NC/lalala/src/durable_objects/Lalala.test.ts
▲ [WARNING] Processing wrangler.toml configuration:

    - "unsafe" fields are experimental and may change or break at any time.


[vpw:inf] Starting single runtime for vitest.config.js...

================================================================================
Failed to pop isolated storage stack frame in src/durable_objects/Lalala.test.ts's test "404s on non-consume path".
This usually means your Worker tried to access storage outside of a test.
In particular, we were unable to pop Durable Objects storage.
Ensure you `await` all `Promise`s that read or write to these services.

- AssertionError [ERR_ASSERTION]: Expected .sqlite, got /var/folders/47/5fsq322s5dx9y0f1c2shbvvh0000gn/T/miniflare-0d475a4a00fc573e720de1f3fdc5d38f/do/vitest-pool-workers-runner--__VITEST_POOL_WORKERS_USER_OBJECTLalala/88e8e9cf16735464763622e7564089aa29822a772684bb26d1a72a7edc321ec8.sqlite-shm
================================================================================

Error running worker: AssertionError [ERR_ASSERTION]: Isolated storage failed. There should be additional logs above.
    at new AssertionError (node-internal:internal_assertionerror:419:15)
    at Function.strictEqual (node-internal:internal_assert:200:11)
    at WorkersTestRunner.updateStackedStorage (Users/maxime/Code/NC/lalala/node_modules/@cloudflare/vitest-pool-workers/dist/worker/lib/cloudflare/test-runner.mjs:107:12)
    at WorkersTestRunner.onAfterRunSuite (Users/maxime/Code/NC/lalala/node_modules/@cloudflare/vitest-pool-workers/dist/worker/lib/cloudflare/test-runner.mjs:142:5)
    at runSuite (Users/maxime/Code/NC/lalala/node_modules/@vitest/runner/dist/index.js:875:5)
    at runFiles (Users/maxime/Code/NC/lalala/node_modules/@vitest/runner/dist/index.js:896:5)
    at startTests (Users/maxime/Code/NC/lalala/node_modules/@vitest/runner/dist/index.js:905:3)
    at Users/maxime/Code/NC/lalala/node_modules/vitest/dist/chunks/runtime-runBaseTests.0UwIvo_U.js:114:7
    at withEnv (Users/maxime/Code/NC/lalala/node_modules/vitest/dist/chunks/runtime-runBaseTests.0UwIvo_U.js:82:5)
    at run (Users/maxime/Code/NC/lalala/node_modules/vitest/dist/chunks/runtime-runBaseTests.0UwIvo_U.js:103:3)

Failure cause not provided for '404s on non-consume path'

Isolated storage failed. There should be additional logs above.
AssertionError [ERR_ASSERTION]: Isolated storage failed. There should be additional logs above.
    at new AssertionError (node-internal:internal_assertionerror:419:15)
    at Function.strictEqual (node-internal:internal_assert:200:11)
    at WorkersTestRunner.updateStackedStorage (Users/maxime/Code/NC/lalala/node_modules/@cloudflare/vitest-pool-workers/dist/worker/lib/cloudflare/test-runner.mjs:107:12)
    at WorkersTestRunner.onAfterRunSuite (Users/maxime/Code/NC/lalala/node_modules/@cloudflare/vitest-pool-workers/dist/worker/lib/cloudflare/test-runner.mjs:142:5)
    at runSuite (Users/maxime/Code/NC/lalala/node_modules/@vitest/runner/dist/index.js:875:5)
    at runFiles (Users/maxime/Code/NC/lalala/node_modules/@vitest/runner/dist/index.js:896:5)
    at startTests (Users/maxime/Code/NC/lalala/node_modules/@vitest/runner/dist/index.js:905:3)
    at Users/maxime/Code/NC/lalala/node_modules/vitest/dist/chunks/runtime-runBaseTests.0UwIvo_U.js:114:7
    at withEnv (Users/maxime/Code/NC/lalala/node_modules/vitest/dist/chunks/runtime-runBaseTests.0UwIvo_U.js:82:5)
    at run (Users/maxime/Code/NC/lalala/node_modules/vitest/dist/chunks/runtime-runBaseTests.0UwIvo_U.js:103:3)
```

That error is very confusing.

### Please provide a link to a minimal reproduction

https://github.com/punkeel/repro-5629

Run `make` to run tests.

### PR DESCRIPTION
**Pull request by edmundhung**
Fixes #5629

This PRs updated the error message with isolated storage with a link to known issues documented in https://github.com/cloudflare/cloudflare-docs/pull/20033

---

- Tests
  - [ ] TODO (before merge)
  - [ ] Tests included
  - [x] Tests not necessary because: updated error message only
- Wrangler E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [ ] Required
  - [x] Not required because: no impact to wrangler
- Public documentation
  - [ ] TODO (before merge)
  - [x] Cloudflare docs PR(s): https://github.com/cloudflare/cloudflare-docs/pull/20033
  - [ ] Documentation not necessary because:

### CODE REVIEW

File: packages/vitest-pool-workers/src/pool/loopback.ts [hunk 1]
```diff
@@ -326,11 +326,9 @@ function checkAllStorageOperationsResolved(
 			"",
 			separator,
 			`Failed to ${action} isolated storage stack frame in ${source}.`,
-			"This usually means your Worker tried to access storage outside of a test, or failed to cleanup storage passed across an RPC boundary.",
-			`In particular, we were unable to ${action} ${LIST_FORMAT.format(
-				failedProducts
-			)} storage.`,
-			"Ensure you `await` all `Promise`s that read or write to these services, and make sure you use the `using` keyword when passing data across JSRPC. See https://developers.cloudflare.com/workers/runtime-apis/rpc/lifecycle#explicit-resource-management for more details.",
+			`In particular, we were unable to ${action} ${LIST_FORMAT.format(failedProducts)} storage.`,
+			"This usually means your Worker access storage outside of a test, or some resources have not been disposed of properly.",
```
Comment (penalosa) [inline packages/vitest-pool-workers/src/pool/loopback.ts:330]:
```suggestion
			"This usually means your Worker tried to access storage outside of a test, or some resources have not been disposed of properly.",
```

File: packages/vitest-pool-workers/src/pool/loopback.ts [hunk 2]
```diff
@@ -326,11 +326,9 @@ function checkAllStorageOperationsResolved(
...
+			"See https://developers.cloudflare.com/workers/testing/vitest-integration/known-issues/#isolated-storage for common causes and suggested solution.",
```
Comment (penalosa) [inline packages/vitest-pool-workers/src/pool/loopback.ts:331]: Why are we removing the actionable info from the error message? Could it be:

> Ensure you `await` all `Promise`s that read or write to these services, and make sure you use the `using` keyword when passing data across JSRPC. Refer to https://developers.cloudflare.com/workers/testing/vitest-integration/known-issues/#isolated-storage for more details.

Comment (edmundhung) [reply packages/vitest-pool-workers/src/pool/loopback.ts]: Right. Probably better to keep the actionable info there. Updated in https://github.com/cloudflare/workers-sdk/pull/8173/commits/541c1f774844cdbe214945597ca1406606ccfc96.

**Review by penalosa — APPROVED** [review]
