### PR TITLE
fix: ensure that directory imports in commonjs modules get resolved to their index file

### LINKED ISSUE #6406: 🐛 BUG: Node modules `require('./dir')` does not resolve to `require('./dir/index.js')`
### Which Cloudflare product(s) does this pertain to?

Workers Vitest Integration

### What version(s) of the tool(s) are you using?

0.4.17

### What version of Node are you using?

_No response_

### What operating system and version are you using?

macOS Sonoma 14.5

### Observed & expected behavior

When importing `knex` in a Vitest test, its subdependency `db-errors` will make a `require('./lib/parsers')` call. This should resolve to `./lib/parsers/index.js` but it does not, instead throwing:
```
Error: No such module "<root>/node_modules/db-errors/lib/parsers"
```
This is in contrast to the default Vitest tests, which import it correctly.

### Steps to reproduce

Import `knex` in a test.

### Please provide a link to a minimal reproduction

https://github.com/hansottowirtz/workers-sdk-index-js-require-repro

```
pnpm i
pnpm test
```

Result will be:

```
Error: No such module "<root>/node_modules/.pnpm/ext-dep-1@file+vendor+ext-dep/node_modules/ext-dep-1/subfolder".
```

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by petebacondarwin**
## What this PR solves / how to test

Fixes #6406

The build from this PR should fix the reproduction here: https://github.com/hansottowirtz/workers-sdk-index-js-require-repro.

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [x] Required / Maybe required
  - [ ] Not required because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Not necessary because: bug fix

### CODE REVIEW

File: packages/vitest-pool-workers/src/pool/module-fallback.ts [hunk 1]
```diff
@@ -75,6 +75,17 @@ function isFile(filePath: string): boolean {
...
+	try {
+		return fs.statSync(filePath).isDirectory();
+	} catch (e) {
+		if (isFileNotFoundError(e)) {
+			return false;
+		}
+		throw e;
+	}
+}
+
```
Comment (andyjessop) [inline packages/vitest-pool-workers/src/pool/module-fallback.ts:88]: We have basically the same code in several other places in the repo - I wonder if we can consolidate these?

[1](https://github.com/cloudflare/workers-sdk/blob/c2bb42fefa402ece691fd4b034a749d2862ec61a/packages/wrangler/src/global-wrangler-config-path.ts/#L6-L13), [2](https://github.com/cloudflare/workers-sdk/blob/c2bb42fefa402ece691fd4b034a749d2862ec61a/packages/wrangler/src/pages/functions/buildPlugin.ts/#L67-L72), [3](https://github.com/cloudflare/workers-sdk/blob/c2bb42fefa402ece691fd4b034a749d2862ec61a/packages/wrangler/src/pages/functions/buildWorker.ts/#L94-L99), [4](https://github.com/cloudflare/workers-sdk/blob/c2bb42fefa402ece691fd4b034a749d2862ec61a/packages/create-cloudflare/src/helpers/files.ts/#L39-L49). [5](https://github.com/cloudflare/workers-sdk/blob/c2bb42fefa402ece691fd4b034a749d2862ec61a/packages/wrangler/src/pages/dev.ts/#L351-L352), [6](https://github.com/cloudflare/workers-sdk/blob/c2bb42fefa402ece691fd4b034a749d2862ec61a/packages/wrangler/src/pages/functions.ts/#L48-L49)

**Review by RamIdeas — APPROVED** [review]

**Review by andyjessop — APPROVED** [review]
Looks good! One comment, but more as a case-in-point of something that happens all over the repo. Perhaps it's time to create a utils package as a common place for these types of functions.

File: packages/vitest-pool-workers/src/pool/module-fallback.ts (hunk 1 above)
Comment (petebacondarwin) [reply packages/vitest-pool-workers/src/pool/module-fallback.ts:88]: For sure within a package (such as the 4 versions in wrangler). I am less bothered about sharing little utilities like this between packages.

Comment (petebacondarwin) [reply packages/vitest-pool-workers/src/pool/module-fallback.ts:88]: Feel free to follow up with clean up PRs for that sort of thing.

Comment (andyjessop) [reply packages/vitest-pool-workers/src/pool/module-fallback.ts:88]: The case for, I would say, is to both standardise and to avoid common errors. This one, for example, will throw an error that TS doesn't pick up:

```
const t = fs.statSync('sdfs').isDirectory();
```

There are other common pitfalls, like `parseInt(couldBeEmptyString, 10) -> Nan`.

One more reason is that we have some nice little gems that might never get discovered because they're hidden away, like [this one from the C3 code base](https://github.com/cloudflare/workers-sdk/blob/c2bb42fefa402ece691fd4b034a749d2862ec61a/packages/create-cloudflare/src/helpers/retry.ts/#L24-L39).

I think a common utility library could make our code more consistent as well as more robust and discoverable.
