### PR TITLE
only commit on c3 initialized repos

### LINKED ISSUE #4273: 🐛 BUG: create-cloudflare tried to commit to my git repo without asking me
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

create-cloudflare 2.6.1

### What version of Node are you using?

v18.17.1

### What operating system are you using?

Windows

### Describe the Bug

I was a little shocked to see that when I simply tried to create a new worker, create-cloudflare tried to commit to my git repo without asking me.  
I feel this should be something that is not turned on by default. 

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
Fixes #4273

### CODE REVIEW

File: packages/create-cloudflare/src/common.ts [hunk 1]
```diff
@@ -325,8 +326,8 @@ export const gitCommit = async (ctx: PagesGeneratorContext) => {
 	//       we unconditionally run this command here
 	const commitMessage = await createCommitMessage(ctx);
 
-	if (!(await isGitInstalled()) || !(await isInsideGitRepo(ctx.project.path)))
-		return;
+	// we actually commit only if c3 was the one initializing the git repository
+	if (!ctx.c3InitializedGitRepo) return;
```
Comment (dario-piotrowicz) [inline packages/create-cloudflare/src/common.ts:330]: instead of doing this here we could prompt the user asking if they'd want us to commit for them, I think I'd prefer not to do that because:
- in this was we keep things simple and clean, no potential edge cases or risk to committing things wrongly (e.g. monorepos with dirty directories)
- maintain a very clear/basic behavior (clear/basic both for us and users): when we initialize the git repo we also generate the first commit, there are no other possible cases/alternative behaviors
- this seems to be the general behavior of such type of CLI tools
- asking the user at this point feels a bit pointless, as they can just committing themselves (the only benefit we could bring would be that we can create a commit with all the C3 details, but I am not sure if people really care about it)


But let me know what you think, if someone strongly prefers prompting the user and potentially committing the changes I am also ok with doing that 🙂

File: packages/create-cloudflare/src/types.ts [hunk 2]
```diff
@@ -40,6 +40,7 @@ export type PagesGeneratorContext = {
 	};
 	type?: "pages" | "workers";
 	originalCWD: string;
+	c3InitializedGitRepo?: boolean;
```
Comment (dario-piotrowicz) [inline packages/create-cloudflare/src/types.ts:43]: code in C3 usually doesn't use the term `c3` as that does feel rather pointless... here I did so to make super clear that c3 initialized the repo (and that that wasn't done by a framework's cli run by c3 for example), I'm totally happy to use any other name here, if you have suggestions please let me know 🙂 

(just `initializedGitRepo`? `gitRepoInitializedByUs`? etc...)

File: packages/create-cloudflare/src/common.ts [hunk 3]
```diff
@@ -316,6 +316,7 @@ export const offerGit = async (ctx: PagesGeneratorContext) => {
 			startText: "Initializing git repo",
 			doneText: `${brandColor("initialized")} ${dim(`git`)}`,
 		});
+		ctx.c3InitializedGitRepo = true;
```
Comment (IgorMinar) [inline packages/create-cloudflare/src/common.ts:319]: some frameworks also initialize git on their own, if we encouter that scenario, we should consider the repo as initialized by c3 too and commit.

Comment (dario-piotrowicz) [reply packages/create-cloudflare/src/common.ts:319]: I was going to open a separate issue for this, my thought was that we should try to prevent frameworks to do any git operation (we already do that but I don't think we do that across the board), and if they do it's sort of outside of the scope of C3

if we allow frameworks to do git operations and they for example generate an initial commit, do we them `--amend` with our own changes? or commit on top of them?

seems to me like trying to prevent framework clis to do any git operation and have a clear distinction between C3 and the frameworks in this regard could be the cleaner behavior here 🤔 

But it might not be that simple, not all CLIs could allow us to prevent git operations, and even if they do users could force git operations by passing args to the underlying CLIs with `--` 🤔

Comment (dario-piotrowicz) [reply packages/create-cloudflare/src/common.ts]: Scrap the above comment 😅 

I've changed the behavior to account for git repos initialized by framework CLIs, please have a look 🙏

**Review by jculvey — APPROVED** [review]
