### PR TITLE
fix(wrangler): Show feedback on Pages Function upload failure

### LINKED ISSUE #3966: 🐛 BUG: wrangler logs success for pages deploy even with Functions failures
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.8.0

### What version of Node are you using?

18.17.1

### What operating system are you using?

Windows 10

### Describe the Bug

When publishing a Pages project with Functions, wrangler will seemingly always report a success, even if the Functions upload fails.

Example:

`index.html`: 
```
<html>
<body>
	<h1>Hello World</h1>
</body>
</html>
```

`functions/_middleware.js`:
```javascript
const a = true;
a();
export function onRequest(context){
	return context.next()
}
```

Result via wrangler (`npx wrangler@3.8.0 pages deploy .`):
```
✨ Successfully created the 'test-functions-errors' project.
✨ Compiled Worker successfully
🌏  Uploading... (1/1)

✨ Success! Uploaded 1 files (1.56 sec)

✨ Uploading Functions bundle
✨ Deployment complete! Take a peek over at https://3f676375.test-functions-errors.pages.dev
```

But the Cloudflare Pages dashboard shows an error:

And the project isn't actually available. There's no way to get logs about what happened here, so folks are left confused.

This happens periodically in Discord, requiring a Pages team member to pull logs for a deployment ID, as well as on the forum such as at https://community.cloudflare.com/t/wrangler-pages-publish-always-fails-tried-both-with-nextjs-and-with-astro-templates/554749?u=cherryjimbo.

### PR DESCRIPTION
**Pull request by CarmenPopoviciu**
## What this PR solves / how to test

Today, if uploading a Pages Function, or deploying a Pages project fails for whatever reason, there’s no feedback shown to the user. Worse yet, the shown message is misleading, saying the deployment was successful, when in fact it was not:

Screenshot 2024-05-14 at 14 22 31

This PR ensures that moving forward, we provide users with:

- the correct feedback with respect to their Pages deployment
- the appropriate messaging depending on the status of their project's deployment status
- the appropriate logs in case of a deployment failure

Fixes #3966 and WC-2090.

**Before**
Screenshot 2024-05-14 at 14 22 31

**After**

- success
Screenshot 2024-05-15 at 16 45 35

- failure
Screenshot 2024-05-15 at 16 46 42

- failure with log level set to `debug`
Screenshot 2024-05-15 at 16 48 36

- unknown deployment status
Screenshot 2024-05-15 at 16 57 16

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [ ] Required / Maybe required
  - [x] Not required because: no e2e tests changes were made
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): <https://github.com/cloudflare/cloudflare-docs/pull/>...
  - [x] Not necessary because: bug fix

### CODE REVIEW

File: packages/wrangler/src/pages/deploy.tsx [hunk 1]
```diff
@@ -337,9 +337,42 @@ export const Handler = async (args: PagesDeployArgs) => {
 		project_name: projectName,
 	});
 
-	logger.log(
-		`✨ Deployment complete! Take a peek over at ${deploymentResponse.url}`
-	);
+	let latestDeploymentStage: DeploymentStage | undefined;
+
+	// can this ever become an infinite loop?
```
Comment (CarmenPopoviciu) [inline packages/wrangler/src/pages/deploy.tsx:342]: I'm wondering if we shouldn't put some max on how many times we want to keep on polling here 🤔 , to avoid ever running into some type of infinite loop situation

File: packages/wrangler/src/pages/deploy.tsx [hunk 2]
```diff
@@ -337,9 +337,42 @@ export const Handler = async (args: PagesDeployArgs) => {
...
+			`/accounts/${accountId}/pages/projects/${projectName}/deployments/${deploymentResponse.id}/history/logs?size=10000000`
+		);
+		// last log entry will be the most relevant for Direct Uploads
+		const failureMessage = logs.data[logs.total - 1].line;
+
+		logger.error(failureMessage.replace("Error:", "").trim());
+		logger.log("❌ Deployment failed!");
+	}
+
 	await metrics.sendMetricsEvent("create pages deployment");
```
Comment (CarmenPopoviciu) [inline packages/wrangler/src/pages/deploy.tsx:376]: do we still want to send this metric in the event the deployment failed?

File: packages/wrangler/src/pages/deploy.tsx [hunk 3]
```diff
@@ -337,9 +337,42 @@ export const Handler = async (args: PagesDeployArgs) => {
...
+		latestDeploymentStage?.status !== "success" &&
+		latestDeploymentStage?.status !== "failure"
+	) {
+		try {
+			const deployment = await fetchResult<Deployment>(
+				`/accounts/${accountId}/pages/projects/${projectName}/deployments/${deploymentResponse.id}`
+			);
+			latestDeploymentStage = deployment.latest_stage;
+		} catch (err) {
+			logger.debug(
```
Comment (CarmenPopoviciu) [inline packages/wrangler/src/pages/deploy.tsx:354]: - I'm assuming we don't want to exit here?
- Is `debug` log level OK?
- would also appreciate a check on the wording. I feel like in the crr state it might confuse folks and needs some resolution at the end?

File: packages/wrangler/src/pages/deploy.tsx [hunk 4]
```diff
@@ -337,9 +337,42 @@ export const Handler = async (args: PagesDeployArgs) => {
...
+				`Attempt to get deployment status for deployment with id "${deploymentResponse.id}" failed: ${err}`
+			);
+		}
+	}
+
+	if (latestDeploymentStage.status === "success") {
```
Comment (CarmenPopoviciu) [inline packages/wrangler/src/pages/deploy.tsx:360]: @CarmenPopoviciu if we fail to get the deployment details repeatedly for some reason, and we set a max attempts cap, we'll exit that `while` loop in a weird state, with an unknown deployment status. We should resolve that status one way or the other (`success` | `failure`) so we can show the appropriate user msg

Comment (CarmenPopoviciu) [reply packages/wrangler/src/pages/deploy.tsx:360]: @WalshyDev or @tanushree-sharma would appreciate some input here on what the desired behaviour is 🙏

File: packages/wrangler/src/pages/deploy.tsx (hunk 3 above)
Comment (GregBrimble) [reply packages/wrangler/src/pages/deploy.tsx:354]: all lgtm!

File: packages/wrangler/src/pages/deploy.tsx (hunk 4 above)
Comment (GregBrimble) [reply packages/wrangler/src/pages/deploy.tsx:360]:
```
Deployment complete. However, we couldn't ascertain the final status of your deployment.

Visit your deployment: ${deploymentResponse.url}
Check logs on the Cloudflare dashboard here: https://dash.cloudflare.com/xyz/projects/xyz/${deploymentResponse.id}
```

**Review by GregBrimble — APPROVED** [review]
Thanks Carmen! Once you've got a sleep and cap added in to that loop, pretty much ready to merge, imo!

File: packages/wrangler/src/pages/deploy.tsx (hunk 1 above)
Comment (CarmenPopoviciu) [reply packages/wrangler/src/pages/deploy.tsx:342]: yeah, agreed. Will fix!

File: packages/wrangler/src/pages/deploy.tsx (hunk 4 above)
Comment (CarmenPopoviciu) [reply packages/wrangler/src/pages/deploy.tsx:360]: like the wording very much. Thank you thank you! Will add!

File: packages/wrangler/src/pages/deploy.tsx (hunk 1 above)
Comment (CarmenPopoviciu) [reply packages/wrangler/src/pages/deploy.tsx:342]: ✅

File: packages/wrangler/src/pages/deploy.tsx (hunk 2 above)
Comment (CarmenPopoviciu) [reply packages/wrangler/src/pages/deploy.tsx:376]: I had a look at how we're using these metrics, and I think leaving as is is 👌 .

File: packages/wrangler/src/pages/deploy.tsx (hunk 1 above)
Comment (CarmenPopoviciu) [reply packages/wrangler/src/pages/deploy.tsx:342]: IMHO polling for 2 minutes with possibly no UI feedback (unless log level is set to debug) might be pushing it? I've set the cap to 16s, but could up to 32s. Anything above felt like a stretch of my patience as a user 😅. But I might be wrong in my thinking?

Comment (CarmenPopoviciu) [reply packages/wrangler/src/pages/deploy.tsx:342]: 👇 what I meant by having log level set to `debug`
Screenshot 2024-05-14 at 20 19 28

Comment (WalshyDev) [reply packages/wrangler/src/pages/deploy.tsx]: Yeah 2m is quite a long time. We should be finishing pretty quick here, our internal timeout is 15 seconds so 16 sounds good.

File: packages/wrangler/src/pages/deploy.tsx (hunk 4 above)
Comment (CarmenPopoviciu) [reply packages/wrangler/src/pages/deploy.tsx:360]: ✅

File: packages/wrangler/src/pages/deploy.tsx [hunk 5]
```diff
@@ -20,8 +20,8 @@ import type {
 	CommonYargsArgv,
 	StrictYargsOptionsToInterface,
 } from "../yargs-types";
-import type { PagesConfigCache } from "./types";
-import type { Project } from "@cloudflare/types";
+import type { Deployment, DeploymentStage, PagesConfigCache } from "./types";
```
Comment (WalshyDev) [inline packages/wrangler/src/pages/deploy.tsx]: We have Deployment & DeploymentStage in `@cloudflare/types`

**Review by WalshyDev — APPROVED** [review]

File: packages/wrangler/src/pages/deploy.tsx (hunk 1 above)
Comment (CarmenPopoviciu) [reply packages/wrangler/src/pages/deploy.tsx]: yeah, I can totes do that. Only thing that stopped me from doing that was some concern around not adding to much noise to stdout. But perhaps a one liner saying smth like `Waiting for deployment status` won't be such a big deal?

File: packages/wrangler/src/pages/deploy.tsx [hunk 6]
```diff
@@ -337,9 +345,65 @@ export const Handler = async (args: PagesDeployArgs) => {
 		project_name: projectName,
 	});
 
-	logger.log(
-		`✨ Deployment complete! Take a peek over at ${deploymentResponse.url}`
-	);
+	let latestDeploymentStage: DeploymentStage | undefined;
+	let attempts = 0;
+
+	logger.log("🌎 Checking deployment status...");
```
Comment (WalshyDev) [inline packages/wrangler/src/pages/deploy.tsx:351]: Maybe this should just be "Deploying..."? That's what we're actually doing while waiting, I don't think we need to surface our status checking to the user.

File: packages/wrangler/src/pages/deploy.tsx [hunk 7]
```diff
@@ -337,9 +345,65 @@ export const Handler = async (args: PagesDeployArgs) => {
...
+		// last log entry will be the most relevant for Direct Uploads
+		const failureMessage = logs.data[logs.total - 1].line;
+
+		logger.error(failureMessage.replace("Error:", "").trim());
+		logger.log("❌ Deployment failed!");
+	} else {
+		logger.log(
+			`✨ Deployment complete! However, we couldn't ascertain the final status of your deployment.\n\n` +
+				`⚡️ Visit your deployment at ${deploymentResponse.url}\n` +
+				`⚡️ Check the deployment logs on the Cloudflare dashboard: https://dash.cloudflare.com/${accountId}/pages/view/${projectName}/${deploymentResponse.id}`
```
Comment (WalshyDev) [inline packages/wrangler/src/pages/deploy.tsx:403]: There are gonna be no logs here for DU users, they could see a green tick and red triangle but that's it. I probably wouldn't bother linking to dash

File: packages/wrangler/src/pages/deployments.tsx [hunk 8]
```diff
@@ -54,7 +55,10 @@ export async function ListHandler({ projectName }: ListArgs) {
 
 	const getStatus = (deployment: Deployment) => {
 		// Return a pretty time since timestamp if successful otherwise the status
-		if (deployment.latest_stage.status === `success`) {
+		if (
+			deployment.latest_stage.status === `success` &&
```
Comment (WalshyDev) [inline packages/wrangler/src/pages/deployments.tsx:59]: nit
```suggestion
			deployment.latest_stage.status === "success" &&
```

**Review by WalshyDev — APPROVED** [review]

File: packages/wrangler/src/pages/deploy.tsx [hunk 9]
```diff
@@ -337,9 +345,65 @@ export const Handler = async (args: PagesDeployArgs) => {
...
+			latestDeploymentStage = deployment.latest_stage;
+		} catch (err) {
+			// don't retry if API call retruned an error
+			logger.debug(
+				`Attempt to get deployment status for deployment with id "${deploymentResponse.id}" failed: ${err}`
+			);
+		}
+	}
+
+	if (latestDeploymentStage?.status === "success") {
```
Comment (jahands) [inline packages/wrangler/src/pages/deploy.tsx:385]: We probably want to double check that `name === "deploy"` here rather than "build"

File: packages/wrangler/src/pages/deploy.tsx (hunk 6 above)
Comment (CarmenPopoviciu) [reply packages/wrangler/src/pages/deploy.tsx:351]: ✅

File: packages/wrangler/src/pages/deployments.tsx (hunk 8 above)
Comment (CarmenPopoviciu) [reply packages/wrangler/src/pages/deployments.tsx:59]: how did prettier not catch this?

Comment (CarmenPopoviciu) [reply packages/wrangler/src/pages/deployments.tsx:59]: oh wait...that's a backtick. that's why

File: packages/wrangler/src/pages/deploy.tsx (hunk 9 above)
Comment (CarmenPopoviciu) [reply packages/wrangler/src/pages/deploy.tsx:385]: that's a very good callout!

Comment (CarmenPopoviciu) [reply packages/wrangler/src/pages/deploy.tsx:385]: ✅

File: packages/wrangler/src/pages/deploy.tsx (hunk 7 above)
Comment (CarmenPopoviciu) [reply packages/wrangler/src/pages/deploy.tsx:403]: true, but given that we couldn't tell whether the deployment was successful or failed from within wrangler, I think there might be some value in linking to Dash. I changed the wording to `Check the deployment details on ...`

**Comment by CarmenPopoviciu** [comment]
thanks everyone for reviewing this PR and providing valuable feedback 🙏

**Comment by wouterds** [comment]
Bless you, finally I get a clear error message what's going wrong with my deploy 😌 

Screenshot 2024-05-15 at 19 56 26

**Comment by CarmenPopoviciu** [comment]
whoohooo! much awesomeness! so so happy this PR helps!

**Comment by CarmenPopoviciu** [comment]
ugh...not sure how I missed that 😅. Fix PR is here: https://github.com/cloudflare/workers-sdk/pull/5862
