### PR TITLE
fix: make vitest-pool-workers not crash with scripts that have Workflows

### LINKED ISSUE #7414: 🐛 BUG: Cloudflare Workflows: MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start
### Which Cloudflare product(s) does this pertain to?

Miniflare, Other

### What version(s) of the tool(s) are you using?

0.5.32 [@cloudflare/vitest-pool-workers], 3.91.0 [wrangler]

### What version of Node are you using?

22.9.0

### What operating system and version are you using?

MacOs Ventura

### Observed behavior
Vitests doesn't run if wrangler toml contains workflows and following error occurs:
```
Worker "workflows:webhook-workflow"'s binding "USER_WORKFLOW" refers to service "core:user:vitest-pool-workers-runner-" with a named entrypoint "WebhookWorkflow", but "core:user:vitest-pool-workers-runner-" has no such named entrypoint.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
 ❯ #assembleAndUpdateConfig node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:9983:13
 ❯ process.processTicksAndRejections node:internal/process/task_queues:105:5
 ❯ Mutex.runWith node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:3632:16
 ❯ #waitForReady node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:10040:5
 ❯ getProjectMiniflare node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_hwo7pvv77thpfn5lwl6xtnhhae/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs:1430:5
 ❯ Object.runTests node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_hwo7pvv77thpfn5lwl6xtnhhae/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs:1683:20
 ❯ executeTests node_modules/.pnpm/vitest@2.0.5_@types+node@22.10.1/node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js:9330:5
 ❯ node_modules/.pnpm/vitest@2.0.5_@types+node@22.10.1/node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js:14935:9

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { code: 'ERR_RUNTIME_FAILURE' }
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 Test Files  no tests
      Tests  no tests
     Errors  1 error
   Start at  21:04:10
   Duration  140ms (transform 0ms, setup 0ms, collect 0ms, tests 0ms, environment 0ms, prepare 0ms)


 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
Cancelling test run. Press CTRL+c again to exit forcefully.

[vpw:dbg] Shutting down runtimes...
error during close MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (/Users/cah4a/work/unknown-project/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:9983:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (/Users/cah4a/work/unknown-project/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:3632:16)
    at async #waitForReady (/Users/cah4a/work/unknown-project/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js:10040:5)
    at async Promise.all (index 0)
    at async getProjectMiniflare (file:///Users/cah4a/work/unknown-project/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_hwo7pvv77thpfn5lwl6xtnhhae/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs:1430:5)
    at async Object.runTests (file:///Users/cah4a/work/unknown-project/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_hwo7pvv77thpfn5lwl6xtnhhae/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs:1683:20)
    at async Promise.all (index 5)
    at async executeTests (file:///Users/cah4a/work/unknown-project/node_modules/.pnpm/vitest@2.0.5_@types+node@22.10.1/node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js:9330:5)
    at async file:///Users/cah4a/work/unknown-project/node_modules/.pnpm/vitest@2.0.5_@types+node@22.10.1/node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js:14935:9 {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined,
  type: 'Unhandled Error',
  stacks: [
    {
      method: '#assembleAndUpdateConfig',
      file: '/Users/cah4a/work/unknown-project/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js',
      line: 9983,
      column: 13
    },
    {
      method: 'process.processTicksAndRejections',
      file: '/Users/cah4a/work/unknown-project/node:internal/process/task_queues',
      line: 105,
      column: 5
    },
    {
      method: 'Mutex.runWith',
      file: '/Users/cah4a/work/unknown-project/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js',
      line: 3632,
      column: 16
    },
    {
      method: '#waitForReady',
      file: '/Users/cah4a/work/unknown-project/node_modules/.pnpm/miniflare@3.20241106.1/node_modules/miniflare/dist/src/index.js',
      line: 10040,
      column: 5
    },
    {
      method: 'getProjectMiniflare',
      file: '/Users/cah4a/work/unknown-project/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_hwo7pvv77thpfn5lwl6xtnhhae/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs',
      line: 1430,
      column: 5
    },
    {
      method: 'Object.runTests',
      file: '/Users/cah4a/work/unknown-project/node_modules/.pnpm/@cloudflare+vitest-pool-workers@0.5.32_@cloudflare+workers-types@4.20241127.0_@vitest+runner@_hwo7pvv77thpfn5lwl6xtnhhae/node_modules/@cloudflare/vitest-pool-workers/dist/pool/index.mjs',
      line: 1683,
      column: 20
    },
    {
      method: 'executeTests',
      file: '/Users/cah4a/work/unknown-project/node_modules/.pnpm/vitest@2.0.5_@types+node@22.10.1/node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js',
      line: 9330,
      column: 5
    },
    {
      method: '',
      file: '/Users/cah4a/work/unknown-project/node_modules/.pnpm/vitest@2.0.5_@types+node@22.10.1/node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js',
      line: 14935,
      column: 9
    }
  ]
}

```

### Expected behavior
Vitests does run if wrangler toml contains workflows.

### Steps to reproduce
1) Generate empty project using `pnpm create cloudflare@latest`
2) Add workflow as described on the [guide](https://developers.cloudflare.com/workflows/get-started/guide/)
3) pnpm vitest
4) Observe error

### Please provide a link to a minimal reproduction

https://github.com/cah4a/cloudflare-workers-workflows-vitest

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by LuisDuarte1**
Because `vitest-pool-workers` uses its runner worker as the entrypoint and not the user provided worker. The user provided worker is loaded AFAICT though eval (`vitest-pool-workers` enables eval) so we need, at startup time, to add the required entrypoints and make them dynamically call the user one.

Not only that, if you try to create a workflow instance it would throw a `isolated storage` error - I suspect that is this caused by engine still being active at the end of the test (since workflows are async, not in the request path, and might take undefinite time to complete).

In order to fix this, I've bypassed the isolated storage check for workflows internal DOs. I wonder if there might be collisions between test files if there are any concurrency regarding test files (aka `singleWorker` is false) - I think that this is fine to do, the point of this PR is not to make workflows really testable yet but to at least to make `vitest-pool-workers` **not** crash if a user includes a workflow in the worker definition.

Fixes (partially) #7414.

---

- Tests
  - [ ] TODO (before merge)
  - [x] Tests included
  - [ ] Tests not necessary because:
- Wrangler E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [x] Required
  - [ ] Not required because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: doesn't add support to individually test workflows but only makes vitest not crash if they are defined
 - Wrangler V3 Backport
   - [ ] TODO (before merge)
   - [ ] Wrangler PR: 
   - [x] Not necessary because: patch for vitest-pool-workers doesn't affect wrangler

### CODE REVIEW

File: packages/vitest-pool-workers/src/pool/loopback.ts [hunk 1]
```diff
@@ -277,7 +277,10 @@ async function popStackedStorage(fromDepth: number, persistPath: string) {
 				break;
 			}
 			const namePath = path.join(keyPath, name);
-			assert(name.endsWith(".sqlite"), `Expected .sqlite, got ${namePath}`);
+			// if we are using workflows, we don't care if the sqlite got commited or not.
+			if (!persistPath.endsWith("workflows")) {
+				assert(name.endsWith(".sqlite"), `Expected .sqlite, got ${namePath}`);
+			}
```
Comment (edmundhung) [inline packages/vitest-pool-workers/src/pool/loopback.ts:283]: Why?

File: fixtures/vitest-pool-workers-examples/workflows/README.md [hunk 2]
```diff
@@ -0,0 +1,8 @@
+# 🤯 rpc
+
+This Worker defines `WorkerEntrypoint` default and named exports. It also defines Durable Objects subclassing `DurableObject`. All of these classes define properties and methods that can be called over RPC. Integration tests dispatch events, access properties and call methods using the `SELF` helper from the `cloudflare:test` module.
+
+| Test                                                      | Overview                                     |
+| --------------------------------------------------------- | -------------------------------------------- |
+| [integration-self.test.ts](test/integration-self.test.ts) | Integration test using `SELF`                |
+| [unit.test.ts](test/unit.test.ts)                         | Unit tests calling exported classes directly |
```
Comment (edmundhung) [inline fixtures/vitest-pool-workers-examples/workflows/README.md:8]: You might wanna modify this to Workflow? We point people to these examples all the time. So it is best to tell people Workflow support is not ready yet in the readme.

File: packages/vitest-pool-workers/src/pool/loopback.ts (hunk 1 above)
Comment (LuisDuarte1) [reply packages/vitest-pool-workers/src/pool/loopback.ts:283]: My thought process here was that because workflows can have pretty much indefinite length - it wouldn't make much sense to expect the underlying DO to actually finish hence allowing `.sqlite-shm` files (since the DO will be aborted in a running state? my understading of `vitest-pool-wokers` is not that high, but this seemed right to do)

If this isn't the right thing to do, I'm more than happy for ideas or to remove it from this PR :)

Comment (penalosa) [reply packages/vitest-pool-workers/src/pool/loopback.ts:283]: I don't think this is the right approach, since it breaks our isolated storage guarantees. Instead, I think you should throw an early validation error if the user is using Workflows with isolatedStorage turned on

Comment (LuisDuarte1) [reply packages/vitest-pool-workers/src/pool/loopback.ts:283]: > I don't think this is the right approach, since it breaks our isolated storage guarantees. Instead, I think you should throw an early validation error if the user is using Workflows with isolatedStorage turned on.

Yeah, that's fine, maybe we should think how we can make it work with `isolatedStorage` but this can happen later :)

Should the error only happen when the users calls into the `.create` binding?

Comment (penalosa) [reply packages/vitest-pool-workers/src/pool/loopback.ts:283]: Yeah, but I think an early error telling people to change their configuration is a better experience.

Comment (LuisDuarte1) [reply packages/vitest-pool-workers/src/pool/loopback.ts]: done - feel free to bikeshed on the error itself :)

File: fixtures/vitest-pool-workers-examples/workflows/vitest.config.ts [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+		poolOptions: {
+			workers: {
+				singleWorker: true,
+				// FIXME(lduarte): currently for the workflow binding to work, isolateStorage must be disabled.
+				isolatedStorage: false,
+				miniflare: {
+					// Required to use `SELF.scheduled()`. This is an experimental
+					// compatibility flag, and cannot be enabled in production.
+					compatibilityFlags: ["service_binding_extra_handlers"],
+				},
```
Comment (penalosa) [inline fixtures/vitest-pool-workers-examples/workflows/vitest.config.ts:18]: This is not needed in this test

File: packages/vitest-pool-workers/src/pool/index.ts [hunk 4]
```diff
@@ -404,9 +449,27 @@ function buildProjectWorkerOptions(
...
+
+	if (
+		workflowClassNames.length !== 0 &&
+		project.options.isolatedStorage === true
+	) {
+		const message = [
+			`Project ${project.relativePath} has Workflows defined and \`isolatedStorage\` set to true.`,
+			"Please set `isolatedStorage` to false in order to run projects with Workflows.",
+			`Workflows defined in project: ${workflowClassNames.join(", ")}`,
+		].join("\n");
```
Comment (penalosa) [inline packages/vitest-pool-workers/src/pool/index.ts:464]: Why is this an array? It should just be a string

File: packages/vitest-pool-workers/src/pool/loopback.ts [hunk 5]
```diff
@@ -277,7 +277,7 @@ async function popStackedStorage(fromDepth: number, persistPath: string) {
 				break;
 			}
 			const namePath = path.join(keyPath, name);
-			assert(name.endsWith(".sqlite"), `Expected .sqlite, got ${namePath}`);
+
```
Comment (penalosa) [inline packages/vitest-pool-workers/src/pool/loopback.ts:280]: This line shouldn't be removed

**Review by penalosa — COMMENTED** [review]
Is there any way to test that the workflow is actually triggered properly? It looks like the current tests just make sure Vitest doesn't throw.

**Comment by LuisDuarte1** [comment]
> Is there any way to test that the workflow is actually triggered properly? It looks like the current tests just make sure Vitest doesn't throw.

I mean the purpose here of the PR was to make vitest _not crash_, but sure i'll add a simple test to see if the instance actually completes or not :)

File: packages/vitest-pool-workers/src/pool/index.ts [hunk 6]
```diff
@@ -313,6 +328,36 @@ function fixupDurableObjectBindingsToSelf(
 	return result;
 }
 
+function fixupWorkflowBindingsToSelf(
+	worker: SourcelessWorkerOptions
+): Set<string> {
+	// TODO(someday): may need to extend this to take into account other workers
+	//  if doing multi-worker tests across workspace projects
+	// TODO(someday): may want to validate class names are valid identifiers?
```
Comment (petebacondarwin) [inline packages/vitest-pool-workers/src/pool/index.ts:336]: These are copied over from `fixupDurableObjectBindingsToSelf()` but I guess they are still relevant here.

File: packages/vitest-pool-workers/src/pool/index.ts [hunk 7]
```diff
@@ -313,6 +328,36 @@ function fixupDurableObjectBindingsToSelf(
...
+	}
+	for (const key of Object.keys(worker.workflows)) {
+		const designator = worker.workflows[key];
+		// `designator` hasn't been validated at this point
+		if (typeof designator === "string") {
+			// Either this is a simple `string` designator to the current worker...
+			result.add(designator);
+			worker.workflows[key].className = USER_OBJECT_MODULE_NAME + designator;
+		} else if (isWorkflowDesignatorToSelf(designator, worker.name)) {
+			// ...or it's an object designator to the current worker
```
Comment (petebacondarwin) [inline packages/vitest-pool-workers/src/pool/index.ts:349]: I don't believe that Workflow designators can be a simple string.

```suggestion
		if (isWorkflowDesignatorToSelf(designator, worker.name)) {
```

File: packages/vitest-pool-workers/src/pool/index.ts [hunk 8]
```diff
@@ -404,9 +449,23 @@ function buildProjectWorkerOptions(
...
+		fixupWorkflowBindingsToSelf(runnerWorker)
+	).sort();
+
+	if (
+		workflowClassNames.length !== 0 &&
+		project.options.isolatedStorage === true
+	) {
+		throw new Error(`Project ${project.relativePath} has Workflows defined and \`isolatedStorage\` set to true.
+Please set \`isolatedStorage\` to false in order to run projects with Workflows.
+Workflows defined in project: ${workflowClassNames.join(", ")}`);
```
Comment (petebacondarwin) [inline packages/vitest-pool-workers/src/pool/index.ts:462]: So this only errors if there are "local" Workflows, right?

Comment (LuisDuarte1) [reply packages/vitest-pool-workers/src/pool/index.ts:457]: What do you mean by "local" Workflows? I think it's all workers in a bitest project  (since there's only one entrypoint, but there could be multiple workers? ), maybe I'm misunderstanding this :)

Comment (petebacondarwin) [reply packages/vitest-pool-workers/src/pool/index.ts:457]: A Workflow configuration looks like:

```ts
{
  name: string;
  className: string;
  scriptName?: string | undefined;
}
```

If `scriptName` is provided (and isn't the same name as the current worker) then the Workflow is not "local" it is being hosted in an external Worker that we are effectively service binding to, right?

Comment (LuisDuarte1) [reply packages/vitest-pool-workers/src/pool/index.ts:457]: ah yes, I think that makes sense :)

Comment (petebacondarwin) [reply packages/vitest-pool-workers/src/pool/index.ts:457]: But I think this is fine. External Workflows will either be in other Workers that are running in the same Vitest pool, and so would have their own validation, or they are running in completely different Vitest processes (is that even supported?) which again would mean they are validated elsewhere.

File: packages/vitest-pool-workers/src/worker/entrypoints.ts [hunk 9]
```diff
@@ -489,3 +493,67 @@ export function createDurableObjectWrapper(
...
+		const { mainPath, entrypointValue } = await getWorkerEntrypointExport(
+			this.env,
+			entrypoint
+		);
+		const userEnv = stripInternalEnv(this.env);
+		// workflow entrypoint value should always be a constructor
+		if (typeof entrypointValue === "function") {
+			// Assuming the user has defined a `WorkflowEntrypoint` subclass
+			const ctor = entrypointValue as WorkflowEntrypointConstructor;
+			const instance = new ctor(this.ctx, userEnv);
```
Comment (petebacondarwin) [inline packages/vitest-pool-workers/src/worker/entrypoints.ts:538]: I'm a little concerned that calling run instantiates a new Workflow instance each time.

Shouldn't this follow a similar structure to how the DurableObjectWrapper works?

**Review by petebacondarwin — APPROVED** [review]
OK so I am approving on the grounds that the point of this PR is (I think) just to avoid crashes if there are Workflows defined (as specified in the PR title) rather than actually implementing them properly, which would allow the client to call `get()` and `create()` to interact with instances properly.

File: packages/vitest-pool-workers/src/worker/entrypoints.ts (hunk 9 above)
Comment (LuisDuarte1) [reply packages/vitest-pool-workers/src/worker/entrypoints.ts:538]: Workflows work a bit differently :sweat_smile: , our engine DO (which is namespaced by `instanceId`) calls the `run` method, accordingly - so this should be fine to do.

In order words, `WorkflowEntrypoint` is pretty much a "stateless" class, the state is provided via the `step` argument in `run` by engine

Comment (petebacondarwin) [reply packages/vitest-pool-workers/src/worker/entrypoints.ts:538]: OK - showing my ignorance here 😄

**Comment by penalosa** [comment]
We're going to merge this mostly as-is, which will prevent Workflows from crashing Vitest. However, there's a bug where console.logs in a Workflow will cause Vitest to hang. This will need to be fixed as part of the general effort to add testing APIs for Vitest & Workflows.

**Review by penalosa — APPROVED** [review]
