### PR TITLE
Set `ignoreOutdatedRequests` to `true` in `optimizeDeps` config

### LINKED ISSUE #10702: Vite plugin is not working with React-Router 7 with Vite >=7.1.3
### What versions & operating system are you using?

"@cloudflare/vite-plugin": "1.13.3"
"react": "19.1.1"
"react-dom": "19.1.1"
"react-router": "7.9.1"
"vite": "7.1.6"
"wrangler": "4.38.0"

### Please provide a link to a minimal reproduction

_No response_

### Describe the Bug

On version 7.1.3, Vite "fixed" its optimizer in this commit: https://github.com/vitejs/vite/commit/446fe83033686dd38d13b786a217b8277b5c5f09

Since Vite 7.1.3, use `@cloudflare/vite` plugin would cause vite runtime to throw error like

`There is a new version of the pre-bundle for "/.vite/deps_ssr/tailwind-merge.js?v=f68467e2", a page reload is going to ask for it.`

If I go back to Vite 7.1.2, everything just works well.

### Please provide any relevant error logs

There is a new version of the pre-bundle for "/web/node_modules/.vite/deps_ssr/react.js?v=78402c81", a page reload is going to ask for it.

### PR DESCRIPTION
**Pull request by jamesopstad**
Fixes #10702.

Set `ignoreOutdatedRequests` to `true` in `optimizeDeps` config.

This is a workaround for https://github.com/vitejs/vite/issues/20867 and will resolve `Error: There is a new version of the pre-bundle for ...` errors that some users are experiencing. The longer term solution is to use full-bundle mode rather than `optimizeDeps` once it is supported for server environments. Vite v7.3.1 or above is needed for this change to take effect.

The `ignoreOutdatedRequests` option was added in https://github.com/vitejs/vite/pull/21364 and released in Vite 7.3.1 and 8.0.0-beta.6.

---

- Tests
  - [ ] Tests included/updated
  - [x] Tests not necessary because: compatible with existing tests
- Public documentation
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: bug fix

*A picture of a cute animal (not mandatory, but encouraged)*

### CODE REVIEW

File: packages/vite-plugin-cloudflare/src/cloudflare-environment.ts [hunk 1]
```diff
@@ -248,7 +251,7 @@ export function createCloudflareEnvironmentOptions({
 				],
 				define,
 			},
-		},
+		} as vite.DepOptimizationOptions,
```
Comment (dario-piotrowicz) [inline packages/vite-plugin-cloudflare/src/cloudflare-environment.ts]: instead of a cast here what about using a `@ts-iexpect-error` comment? (feels safer, cleaner and clearer to me)
Screenshot 2026-01-07 at 09 45 02

**Review by dario-piotrowicz — APPROVED** [review]
Nice one! 😄

File: packages/vite-plugin-cloudflare/src/cloudflare-environment.ts (hunk 1 above)
Comment (jamesopstad) [reply packages/vite-plugin-cloudflare/src/cloudflare-environment.ts]: Good idea. https://github.com/cloudflare/workers-sdk/pull/11815/commits/7c0a325938ef013f53c196bbcc9109be8d4efcaa.

File: packages/vite-plugin-cloudflare/src/cloudflare-environment.ts [hunk 2]
```diff
@@ -227,6 +227,10 @@ export function createCloudflareEnvironmentOptions({
 		optimizeDeps: {
 			// Note: ssr pre-bundling is opt-in and we need to enable it by setting `noDiscovery` to false
 			noDiscovery: false,
+			// Workaround for https://github.com/vitejs/vite/issues/20867
+			// Longer term solution is to use full-bundle mode rather than `optimizeDeps`
+			// @ts-expect-error - option added in Vite 7.3.1
```
Comment (petebacondarwin) [inline packages/vite-plugin-cloudflare/src/cloudflare-environment.ts:232]: Have the typings not been updated for Vite?

File: .changeset/grumpy-papayas-smile.md [hunk 3]
```diff
@@ -0,0 +1,7 @@
+---
+"@cloudflare/vite-plugin": patch
+---
+
+Set `ignoreOutdatedRequests` to `true` in `optimizeDeps` config.
+
+This is a workaround for https://github.com/vitejs/vite/issues/20867 and will resolve `Error: There is a new version of the pre-bundle for ...` errors that some users are experiencing. The longer term solution is to use full-bundle mode rather than `optimizeDeps` once it is supported for server environments. Vite v7.3.1 or above is needed for this change to take effect.
```
Comment (petebacondarwin) [inline .changeset/grumpy-papayas-smile.md:7]: Do we need to bump the peer dependency on Vite then?

File: packages/vite-plugin-cloudflare/src/cloudflare-environment.ts (hunk 2 above)
Comment (jamesopstad) [reply packages/vite-plugin-cloudflare/src/cloudflare-environment.ts:232]: They have but we currently need to use `7.1.12` to build the plugin as it's the latest version where the module runner is compatible with Vite 6, 7 and 8. See the comment here:

https://github.com/cloudflare/workers-sdk/blob/faf8d275d04e75e88ec90328b440e0f83c0fcdba/pnpm-workspace.yaml#L48-L50

I'm considering making some changes so that we bundle multiple versions of the module runner and import it conditionally based on the Vite version being used.

File: .changeset/grumpy-papayas-smile.md (hunk 3 above)
Comment (jamesopstad) [reply .changeset/grumpy-papayas-smile.md:7]: That would be a breaking change. It's fine to use older versions of Vite but if you do then you might encounter this error.
