### PR TITLE
fix: `email` method not working in ExportedHandler exports in development

### LINKED ISSUE #11230: TypeError: Expected "default" export of "index.ts" to be a subclass of `WorkerEntrypoint` for RPC
### What versions & operating system are you using?

  System:
    OS: macOS 26.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 107.41 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.13.1 - /Users/bahaa/.nvm/versions/node/v22.13.1/bin/node
    npm: 11.3.0 - /Users/bahaa/.nvm/versions/node/v22.13.1/bin/npm
    pnpm: 10.6.5 - /Users/bahaa/Library/pnpm/pnpm
    Watchman: 2025.11.03.00 - /opt/homebrew/bin/watchman
  npmPackages:
    @cloudflare/vite-plugin: ^1.2.3 => 1.14.0 
    wrangler: ^4.17.0 => 4.46.0 

### Please provide a link to a minimal reproduction

https://github.com/BahaaZidan/miniflare-email-handler-min-repro

### Describe the Bug

I have a worker codebase built using Hono, Vite, and the cloudflare worker Vite plugin. I also want to handle some inbound email logic using email workers. So I started with the following code:

```ts
import * as PostalMime from "postal-mime";
import { Hono } from "hono";

const email: NonNullable<
	ExportedHandler<CloudflareBindings, unknown, unknown>["email"]
> = async (message, bindings, context) => {
	const parser = new PostalMime.default();
	const rawEmail = new Response(message.raw);
	const email = await parser.parse(await rawEmail.arrayBuffer());

	console.log(email);
	console.log(bindings);
};

const app = new Hono<{ Bindings: CloudflareBindings }>();

app.get("/lolo", (c) => {
	const lolo = { lolo: "lolo" };
	console.log(c.env);

	return c.json(lolo);
});

export default {
	fetch: app.fetch,
	email
} satisfies ExportedHandler<CloudflareBindings>;
```

For the fetch handler this works well both locally and in prod. But when I'm trying to test the email handler locally I get the following error:
```
TypeError: Expected "default" export of "/Users/bahaa/labs/miniflare-email-handler-min-repro/src/index.ts" to be a subclass of `WorkerEntrypoint` for RPC.
    at async handleEmail (file:///Users/bahaa/labs/miniflare-email-handler-min-repro/node_modules/.pnpm/miniflare@4.20251105.0/node_modules/miniflare/dist/src/workers/core/entry.worker.js:3348:10)
    at async Object.fetch (file:///Users/bahaa/labs/miniflare-email-handler-min-repro/node_modules/.pnpm/miniflare@4.20251105.0/node_modules/miniflare/dist/src/workers/core/entry.worker.js:4470:18)%
```

I test the email using the following cURL:
```
curl --request POST 'http://localhost:5173/cdn-cgi/handler/email' \
  --url-query 'from=sender@example.com' \
  --url-query 'to=recipient@example.com' \
  --header 'Content-Type: application/json' \
  --data-raw 'Received: from smtp.example.com (127.0.0.1)
        by cloudflare-email.com (unknown) id 4fwwffRXOpyR
        for <recipient@example.com>; Tue, 27 Aug 2024 15:50:20 +0000
From: "John" <sender@example.com>
Reply-To: sender@example.com
To: recipient@example.com
Subject: Testing Email Workers Local Dev
Content-Type: text/html; charset="windows-1252"
X-Mailer: Curl
Date: Tue, 27 Aug 2024 08:49:44 -0700
Message-ID: <6114391943504294873000@ZSH-GHOSTTY>
```

Now I tried doing what the error suggested. And so I exported a class instead:
```ts
export default class extends WorkerEntrypoint<CloudflareBindings> {
	fetch = app.fetch;
	email(message: any, env: CloudflareBindings, ctx: any) {
		return email(message, env, ctx);
	}
}
```

This made the error handler work locally. But the value of the bindings became `undefined` so I couldn't access secrets or environment variables locally. I looked at the definition for the `WorkerEntrypoint` class and indeed it only takes one argument in fetch :`request` and one argument in case of email: `message`.

I don't know if I'm missing something here. But I would assume I shouldn't need the class syntax to begin with since all the documentation only uses the normal object syntax.

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by jamesopstad**
Fixes #11230

This also adds exhaustiveness checks so that the type checking will fail if we miss new methods in future.

We missed this before because the `email` method wasn't included in the `WorkerEntrypoint` types. This was fixed in https://github.com/cloudflare/workerd/pull/5538.

---

- Tests
  - [x] Tests included
  - [ ] Tests not necessary because:
- Public documentation
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: bug fix
- Wrangler V3 Backport
  - [ ] Wrangler PR: 
  - [x] Not necessary because: not a Wrangler change

### CODE REVIEW

File: packages/vite-plugin-cloudflare/src/workers/runner-worker/keys.ts [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+// Remove branded keys
+type UnbrandedKeys<T> = Exclude<keyof T, `__${string}_BRAND`>;
+
+// Check that we've included all possible keys
+export const _workerEntrypointExhaustive: (typeof WORKER_ENTRYPOINT_KEYS)[number] =
+	undefined as unknown as UnbrandedKeys<WorkerEntrypoint>;
+export const _durableObjectExhaustive: (typeof DURABLE_OBJECT_KEYS)[number] =
+	undefined as unknown as UnbrandedKeys<DurableObject>;
+export const _workflowEntrypointExhaustive: (typeof WORKFLOW_ENTRYPOINT_KEYS)[number] =
+	undefined as unknown as UnbrandedKeys<WorkflowEntrypoint>;
```
Comment (jamesopstad) [inline packages/vite-plugin-cloudflare/src/workers/runner-worker/keys.ts]: Exporting these so that type checking doesn't report them as unused.

Comment (ascorbic) [reply packages/vite-plugin-cloudflare/src/workers/runner-worker/keys.ts]: What are the these types used for?

Comment (jamesopstad) [reply packages/vite-plugin-cloudflare/src/workers/runner-worker/keys.ts]: They are used to check the exhaustiveness of the arrays i.e. that they include all the unbranded keys from the classes. This is so that type checking will fail if new methods are added to the classes in future that we haven't added here.

Comment (dario-piotrowicz) [reply packages/vite-plugin-cloudflare/src/workers/runner-worker/keys.ts]: > Exporting these so that type checking doesn't report them as unused.

Maybe we should add a comment about that?

Also I was playing with this to see if we can avoid exporting anything and I think we can:
Screenshot 2025-11-20 at 11 56 32

I am not sure though if this is more or less confusing than your version anyways 😅

**Review by dario-piotrowicz — APPROVED** [review]

File: packages/vite-plugin-cloudflare/src/workers/runner-worker/keys.ts (hunk 1 above)
Comment (jamesopstad) [reply packages/vite-plugin-cloudflare/src/workers/runner-worker/keys.ts]: I like your version. [c616027](https://github.com/cloudflare/workers-sdk/pull/11342/commits/c616027cf1b7c3f14437dc8b0d460e037a001a59)
