### PR TITLE
Use `zone_name` for deployment of custom hostnames

### LINKED ISSUE #3662: 🐛 BUG: Wrangler routes don't work with Cloudflare for SaaS Custom Hostnames
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.3.0

### What version of Node are you using?

18.12.1

### What operating system are you using?

Mac

### Describe the Bug

When adding a route on a domain that is setup as a [custom hostname](https://developers.cloudflare.com/ssl/reference/migration-guides/digicert-update/custom-hostname-certificates/#custom-hostnames), I get the following error:

`✘ [ERROR] Could not find zone for [www.example-dev.com]`

The custom hostname in question is setup on the zone noted in the wrangler.toml. The route can still be added in the Cloudflare interface, but wrangler won't allow it.

Note that it does work if there is a zone in the same account that matches the top level domain of the route trying to be added. (e.g. A route can be added for test.example.com on any zone if there is an example.com zone).

```
name = "test-worker"
main = "src/worker.ts"
compatibility_date = "2023-07-02"
usage_model = "bundled"
env = { }

# This will throw error if www.example-dev.com is setup as a custom hostname unless there is a zone called www.example-dev.com or example-dev.com on the same account.
[[routes]]
pattern = "www.example-dev.com/some-path"
zone_name = "dev.example.com"
```

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by romeupalos**
Fixes #3662

**What this PR solves / how to test:**
use `zone_name` to determine a zone when the pattern is a custom hostname

In Cloudflare for SaaS, custom hostnames of third party domain owners can be used in Cloudflare.
Workers are allowed to intercept these requests based on the routes configuration.
Before this change, the same logic used by `wrangler dev` was used in `wrangler deploy`, which caused wrangler to fail with:

✘ [ERROR] Could not find zone for [partner-saas-domain.com]

Example of routes definition that wouldn't work before this PR:
```toml
routes = [
    { pattern = "buy.partner-saas-domain.com/*", zone_name = "mydomain.com" }
]
```

**Author has included the following, where applicable:**

- [x] Tests
- [x] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer is to perform the following, as applicable:**

- Checked for inclusion of relevant tests
- Checked for inclusion of a relevant changeset
- Checked for creation of associated docs updates
- Manually pulled down the changes and spot-tested

### CODE REVIEW

**Comment by romeupalos** [comment]
I have created a changeset for "minor", however, this change could also be considered a "patch".
Please, let me know if there is a need to change it.

**Comment by romeupalos** [comment]
@penalosa Could you please take a look on this change when you have a chance?
This is impacting our companies production deployment. After every deploy, we need to add the triggers manually.

File: packages/wrangler/src/zones.ts
Comment (penalosa) [inline packages/wrangler/src/zones.ts:1]: @romeupalos thanks for this PR! Unfortunately I don't think this is the right fix for this issue, since we don't want to split the implementations of `dev` and `deploy`. I think a simpler option would be to change the implementation of `getZoneForRoute` to 

```ts
export async function getZoneForRoute(route: Route): Promise<Zone | undefined> {
	const host = getHostFromRoute(route);
	let id: string | undefined;

	if (typeof route === "object" && "zone_id" in route) {
		id = route.zone_id;
	} else if (typeof route === "object" && "zone_name" in route) {
		id = await getZoneIdFromHost(route.zone_name);
	} else if (host) {
		id = await getZoneIdFromHost(host);
	}

	return id && host ? { id, host } : undefined;
}
```
Does that work for your use case?

**Review by penalosa — CHANGES_REQUESTED** [review]

File: packages/wrangler/src/zones.ts
Comment (romeupalos) [reply packages/wrangler/src/zones.ts:1]: @penalosa 
Thank you for reviewing my changes. The code you suggested would work for my use case, but I believe it will just undo this earlier change (https://github.com/cloudflare/workers-sdk/pull/1946/files) and it may cause this issue to come back: https://github.com/cloudflare/workers-sdk/issues/1814.

Perhaps we can fallback to `zone_name` if there is no zone id in the account for the hostname extracted from the pattern, thus keeping a single piece of code? Please, let me know what you think and I can make the code changes.

Something like:
```javascript
export async function getZoneForRoute(route: Route): Promise<Zone | undefined> {
  const host = getHostFromRoute(route);
  let id: string | undefined;

  if (typeof route === "object" && "zone_id" in route) {
    id = route.zone_id;
  } else {
    try {
      id = await getZoneIdFromHost(host);
    } catch (e) {
      if (e === 'Zone does not exist' && typeof route === "object" && "zone_name" in route) { // TODO: Verify actual error code here.
        id = await getZoneIdFromHost(route.zone_name);
      }
    }
  }

  return id && host ? { id, host } : undefined;
}
```

Comment (romeupalos) [reply packages/wrangler/src/zones.ts:1]: Oh, I think I misread something. Your code suggestion will work. Let me give it a try and update the PR.

File: packages/wrangler/src/__tests__/dev.test.tsx [hunk 1]
```diff
@@ -369,22 +369,6 @@ describe("wrangler dev", () => {
 			expect(std.err).toMatchInlineSnapshot(`""`);
 		});
 
-		it("should fail for non-existing zones", async () => {
```
Comment (romeupalos) [inline packages/wrangler/src/__tests__/dev.test.tsx:372]: @penalosa
I've removed this UT, since it does not seem to be correct when having Cloudflare for SaaS product in mind.
Please, let me know if it is ok to remove it.

File: packages/wrangler/src/zones.ts
Comment (romeupalos) [reply packages/wrangler/src/zones.ts:1]: @penalosa I've incorporated your code suggestion and updated the PR.
Please, let me know if it looks good to be merged.

**Review by penalosa — APPROVED** [review]
