### PR TITLE
fix(vitest-pool-workers): responses from `fetchMock` should have immutable headers

### LINKED ISSUE #7468: 🐛 BUG: Responses from fetchMock do not have immutable headers
### Which Cloudflare product(s) does this pertain to?

Workers Vitest Integration

### What version(s) of the tool(s) are you using?

0.5.2 [Vitest Pool Workers], 2.0.5 [vitest], 3.60.3 [wrangler] 

### What version of Node are you using?

20.12.0

### What operating system and version are you using?

Mac OS 15.1.1

### Observed behavior
Responses from fetchMock do not have immutable headers like when running in the workers runtime for a deployed worker

### Expected behavior
Responses from fetchMock should have immutable headers

### Steps to reproduce
Run `npm test` in repro repo

### Please provide a link to a minimal reproduction

https://github.com/tyler-goodwin/immutable-headers-repro/tree/main

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by edmundhung**
Fixes #7468.

---

- Tests
  - [ ] TODO (before merge)
  - [x] Tests included
  - [ ] Tests not necessary because:
- Wrangler E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [ ] Required
  - [x] Not required because: no impact outside of vitest-pool-workers
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: bugfix

### CODE REVIEW

File: packages/vitest-pool-workers/src/worker/fetch-mock.ts [hunk 1]
```diff
@@ -170,7 +170,19 @@ globalThis.fetch = async (input, init) => {
...
 				Object.defineProperty(response, "url", { value: url.href });
+				Object.defineProperty(response.headers, "set", {
+					value: throwImmutableHeaderError,
+				});
+				Object.defineProperty(response.headers, "append", {
+					value: throwImmutableHeaderError,
+				});
+				Object.defineProperty(response.headers, "delete", {
+					value: throwImmutableHeaderError,
+				});
```
Comment (dario-piotrowicz) [inline packages/vitest-pool-workers/src/worker/fetch-mock.ts:185]: I think if you could use `defineProperties` instead to do all of this in one single go, for example
```ts
const immutableValue = { value: throwImmutableHeaderError };
Object.defineProperties(response.headers, {
	set: immutableValue,
	append: immutableValue,
	delete: immutableValue,
});
```

**Review by dario-piotrowicz — APPROVED** [review]

File: packages/vitest-pool-workers/src/worker/fetch-mock.ts (hunk 1 above)
Comment (edmundhung) [reply packages/vitest-pool-workers/src/worker/fetch-mock.ts]: Good call! Updated in https://github.com/cloudflare/workers-sdk/pull/8254/commits/e54d234c1a71e5d23dd9b985e5a76e39f3d8763f
