### PR TITLE
Strip CF-Connecting-IP header from all outbound requests

### LINKED ISSUE #7835: 🐛 BUG: fetch() call to public Zero Trust URL from Worker results in error 1000
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What versions are you using?

Wrangler v3.103.2, Node v22.13.0

### What operating system and version are you using?

macOS Sequoia 15.2 (Intel)

### Please provide a link to a minimal reproduction

_No response_

### Describe the Bug

In versions of wrangler after **3.100.0**, making a `fetch()` call to one of my public Zero Trust URLs results in a Cf **Error 1000**. Additional details and screenshot are in [this Cf forum post](https://community.cloudflare.com/t/can-no-longer-make-fetch-call-to-public-zero-trust-url-from-worker/760347).

I've tried every version of wrangler since **3.100.0** with the same result. Wrangler version **3.100.0** is the latest version that works as expected. I've been using Cf Zero Trust public endpoints in lieu of ngrok for weeks without issue. The problem arose when I updated from wrangler version **3.100.0** to the latest (**3.103.2**).

### Additional info

Just wanted to note that this issue pertains to local development with `wrangler dev`.

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by andyjessop**
Fixes #7835, #7924

Strip the CF-Connecting-IP header from outbound requests.

~This cannot be effectively tested in CI because it interacts badly and in strange ways with bot management and various other protections.~ To test manually:
- Create a hello world worker (or use `fixtures/worker-ts`)
- Add `return fetch("https://www.cloudflare.com", request)` to the Worker
- Run `wrangler dev`
- With this PR, validate that the Cloudflare landing page is returned
- _Without_ this PR (`pnpx wrangler@latest dev`), validate that an error page is returned

---

- Tests
  - [ ] TODO (before merge)
  - [x] Tests included
  - [ ] Tests not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [ ] Required
  - [x] Not required because: covered by unit tests
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: bugfix
- Wrangler V3 Backport
  - [ ] TODO (before merge)
  - [x] Wrangler PR: https://github.com/cloudflare/workers-sdk/pull/8681
  - [ ] Not necessary because:

### CODE REVIEW

**Review by penalosa — DISMISSED** [review]

File: packages/wrangler/src/dev/miniflare.ts [hunk 1]
```diff
@@ -1052,6 +1059,18 @@ export async function buildMiniflareOptions(
 					entrypoint: name,
 					proxy: true,
 				})),
+				outboundService(request) {
+					if (request.headers.has("CF-Connecting-IP")) {
+						request.headers.delete("CF-Connecting-IP");
+					}
```
Comment (edmundhung) [inline packages/wrangler/src/dev/miniflare.ts:1065]: This `outboundService` applies to the User Worker only. We were trying to add it to all workers in the `LocalRuntimeController` which might includes wrapped bindings and crash because it does not support `outboundService`.

**Comment by emily-shen** [comment]
should we be doing this in miniflare?

**Comment by edmundhung** [comment]
> should we be doing this in miniflare?

Good point. I didn't notice this was done on the miniflare side. I will give it another look to see if we can strip it there.

**Comment by LukePammant** [comment]
Hey there, curious if there are any plans to get this in the next version of wrangler. I'm unable to locally test on any of my customers sites (#8333). Or is there any quick work around I can add to my code to get around this limitation in the meantime?

File: packages/wrangler/src/api/startDevWorker/ProxyController.ts [hunk 2]
```diff
@@ -94,6 +94,7 @@ export class ProxyController extends Controller<ProxyControllerEventMap> {
 							unsafePreventEviction: true,
 						},
 					},
+					stripCfConnectingIp: false,
```
Comment (petebacondarwin) [inline packages/wrangler/src/api/startDevWorker/ProxyController.ts:97]: It is worth adding a comment here to explain why this is necessary?
And in miniflare.ts too?

File: packages/miniflare/test/index.spec.ts [hunk 3]
```diff
@@ -2995,6 +2995,23 @@ test("Miniflare: CF-Connecting-IP is preserved when present", async (t) => {
...
+		script:
+			"export default { fetch(request) { return fetch('https://shopify.com') } }",
+		modules: true,
+	});
+	t.teardown(() => mf.dispose());
+
+	const landingPage = await mf.dispatchFetch("http://example.com/");
+	t.assert(
+		!(await landingPage.text()).includes(
+			"Unfortunately, it is resolving to an IP address that is creating a conflict within Cloudflare's system"
```
[the remark this answers is not in the document]
Comment (penalosa) [reply packages/miniflare/test/index.spec.ts]: [fb431dc](https://github.com/cloudflare/workers-sdk/pull/7914/commits/fb431dc1d811ef1aebe1d02348b9461663f552da)

File: packages/wrangler/src/api/startDevWorker/ProxyController.ts (hunk 2 above)
Comment (penalosa) [reply packages/wrangler/src/api/startDevWorker/ProxyController.ts:97]: [fb431dc](https://github.com/cloudflare/workers-sdk/pull/7914/commits/fb431dc1d811ef1aebe1d02348b9461663f552da)

File: packages/miniflare/test/index.spec.ts [hunk 4]
```diff
@@ -2995,6 +2995,46 @@ test("Miniflare: CF-Connecting-IP is preserved when present", async (t) => {
...
 });
 
+// regression test for https://github.com/cloudflare/workers-sdk/issues/7924
+test("Miniflare: strips CF-Connecting-IP", async (t) => {
+	const server = new Miniflare({
+		script:
+			"export default { fetch(request) { return new Response(request.headers.get(`CF-Connecting-IP`)) } }",
+		modules: true,
+	});
+	const url = await server.ready;
```
Comment (petebacondarwin) [inline packages/miniflare/test/index.spec.ts:3005]: NIT: it would be helpful to give this a more context specific name:

```suggestion
	const serverUrl = await server.ready;
```

File: packages/miniflare/test/index.spec.ts [hunk 5]
```diff
@@ -2995,6 +2995,46 @@ test("Miniflare: CF-Connecting-IP is preserved when present", async (t) => {
 	t.deepEqual(await ip.text(), "128.0.0.1");
 });
 
+// regression test for https://github.com/cloudflare/workers-sdk/issues/7924
```
Comment (petebacondarwin) [inline packages/miniflare/test/index.spec.ts:2998]: It might be helpful to a future reader to have a comment explaining the setup of the tests here. E.g.

> The "server" service just returns the value of the CF-Connecting-IP header which would normally be added by Miniflare. If you send a request to with no such header, Miniflare will add one.
> The "client" service makes an outbound request with a fake CF-Connecting-IP header to the "server" service. If the outbound stripping happens then this header will not make it to the "server" service so its response will contain the header added by Miniflare. If the stripping is turned off then the response from the "server" service will contain the fake header.

File: packages/miniflare/test/index.spec.ts [hunk 6]
```diff
@@ -2995,6 +2995,46 @@ test("Miniflare: CF-Connecting-IP is preserved when present", async (t) => {
...
+		modules: true,
+	});
+	t.teardown(() => client.dispose());
+	t.teardown(() => server.dispose());
+
+	const landingPage = await client.dispatchFetch("http://example.com/");
+	// The CF-Connecting-IP header value of "fake-value" should be stripped by Miniflare, and should be replaced with a generic 127.0.0.1
+	t.notDeepEqual(await landingPage.text(), "fake-value");
+});
+test("Miniflare: does not strip CF-Connecting-IP when configured", async (t) => {
```
Comment (petebacondarwin) [inline packages/miniflare/test/index.spec.ts:3018]: Can we add an empty line here?

**Review by petebacondarwin — APPROVED** [review]
