### PR TITLE
fix(wrangler): vectorize list and list-metadata-index should output valid json

### LINKED ISSUE #11011: `wrangler vectorize list --json` and `list-metadata-index --json` output a log/message (not valid json)
### What versions & operating system are you using?

```
  System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 157.92 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.20.0 - /Users/azuma/.nvm/versions/node/v22.20.0/bin/node
    npm: 10.9.3 - /Users/azuma/.nvm/versions/node/v22.20.0/bin/npm
    pnpm: 10.10.0 - /Users/azuma/Library/pnpm/pnpm
  npmPackages:
    wrangler: ^4.43.0 => 4.43.0
```

### Please provide a link to a minimal reproduction

_No response_

### Describe the Bug

Similar to issue #10508, the `wrangler vectorize list` and `wrangler vectorize list-metadata-index` commands also output an extra log message as the first line when the `--json` flag is used.

This makes the stdout invalid JSON and breaks piping to tools like `jq`.

#### To Reproduce (`list`):
```bash
$ pnpm wrangler vectorize list --json
```

#### Actual Output (`list`):
```
📋 Listing Vectorize indexes...
[
  {
    "created_on": "2025-10-18T13:28:30.259277Z",
    "modified_on": "2025-10-18T13:28:30.259277Z",
    "name": "test-index",
    "description": "",
    "config": {
      "dimensions": 768,
      "metric": "cosine"
    }
  }
]
```

#### To Reproduce (`list-metadata-index`):
```bash
$ pnpm wrangler vectorize list-metadata-index test-index --json
```

#### Actual Output (`list-metadata-index`):
```
📋 Fetching metadata indexes...
[
  {
    "propertyName": "test_metadata_index",
    "indexType": "String"
  }
]
```

#### Expected Output (for both):

The output should be *only* the valid JSON array, starting with `[` and without any preceding log lines.

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by MaxwellCalkin**
Fixes #11011.

Follows the same pattern as PR #10517 (which fixed `list-vectors --json` for #10508).

## Problem

`wrangler vectorize list --json` and `wrangler vectorize list-metadata-index --json` print a human-readable log message before the JSON output:

```
📋 Listing Vectorize indexes...
[
  { ... }
]
```

This makes stdout invalid JSON and breaks piping to `jq` and other tools.

## Fix

Wrap the `logger.log()` calls in `if (!args.json)` guards so the log message is suppressed when `--json` is used — the same one-line pattern applied in #10517 for `list-vectors`.

**`list.ts`:**
```diff
-		logger.log(`📋 Listing Vectorize indexes...`);
+		if (!args.json) {
+			logger.log(`📋 Listing Vectorize indexes...`);
+		}
```

**`listMetadataIndex.ts`:**
```diff
-		logger.log(`📋 Fetching metadata indexes...`);
+		if (!args.json) {
+			logger.log(`📋 Fetching metadata indexes...`);
+		}
```

---

- Tests
  - [x] Tests included
  - [ ] Tests not necessary because:
- Public documentation
  - [ ] Cloudflare docs PR(s):
  - [x] Documentation not necessary because: bugfix
- Wrangler V3 Backport
  - [ ] Wrangler PR:
  - [x] Not necessary because: v4 only

---

<a href="https://app.devin.ai/review/cloudflare/workers-sdk/pull/12807" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

**Comment by workers-devprod** [comment]
Codeowners approval required for this PR:
- ✅ @cloudflare/wrangler

<details><summary>Show detailed file reviewers</summary>


</details>

File: packages/wrangler/src/vectorize/create.ts [hunk 1]
```diff
@@ -110,7 +114,7 @@ export const vectorizeCreateCommand = createCommand({
 		}
 
 		if (args.json) {
-			logger.log(JSON.stringify(index, null, 2));
+			logger.log(JSON.stringify(indexResult, null, 2));
```
Comment (dario-piotrowicz) [inline packages/wrangler/src/vectorize/create.ts:117]: mh... I wonder if this should have an extra changeset, since you're fixing something unrelated to the json formatting 🤔

File: .changeset/quiet-foxes-grow.md
Comment (dario-piotrowicz) [inline .changeset/quiet-foxes-grow.md:1]: mh... I think that this PR should have three changesets instead of one 🤔 

- a `patch` one for the fix for the commands that already supported `--json` but outputted extra lines
- a `minor` one for the commands that this PR is adding `--json` support to
- a `patch` one for the `create`'s `indexResult` fix

Comment (emily-shen) [reply .changeset/quiet-foxes-grow.md:1]: we didn't add json to any new commands? but fair enough on the `indexResult`.

Comment (dario-piotrowicz) [reply .changeset/quiet-foxes-grow.md:1]: > we didn't add json to any new commands?

oh, you're right! sorry I misread the code! I saw a new `logger.log(JSON.stringify(...))` and thought it was being added, it was being moved instead 😅

File: .changeset/quiet-foxes-grow.md [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+
+This fixes:
+
+- `wrangler vectorize create`
+- `wrangler vectorize info`
+- `wrangler vectorize insert`
+- `wrangler vectorize upsert`
+- `wrangler vectorize list`
+- `wrangler vectorize list-vectors`
+- `wrangler vectorize list-metadata-index`
```
Comment (emily-shen) [inline .changeset/quiet-foxes-grow.md:15]:
```suggestion
- `wrangler vectorize list-metadata-index`

Also, `wrangler vectorize create --json` also includes the `created_at`, `modified_on` and `description` fields.
```

File: .changeset/quiet-foxes-grow.md [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+
+Also, `wrangler vectorize create --json` also includes the `created_at`, `modified_on` and `description` fields.
```
Comment (emily-shen) [inline .changeset/quiet-foxes-grow.md]:
```suggestion
Also, `wrangler vectorize create --json` now also includes the `created_at`, `modified_on` and `description` fields.
```
