### PR TITLE
C3: Add angular e2e coverage

### LINKED ISSUE #4023: 🐛 BUG: C3 - creating an Angular project fails with pnpm
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

C3 2.3.0

### What operating system are you using?

Mac

### Describe the Bug

If I try to create a new Angular project using pnpm (via `pnpm dlx create-cloudflare@latest`) the process errors out:
Screenshot 2023-09-25 at 12 50 22

The issue is that this code
https://github.com/cloudflare/workers-sdk/blob/ef949392311683e5fc1ace1e5509ee77d7ab88e4/packages/create-cloudflare/src/frameworks/angular/index.ts#L32
runs `pnpm @angular/cli@next analytics disable` instead of running `pnpm dlx @angular/cli@next analytics disable`

Note: the application still gets created since this failure happens around the end of the process

### PR DESCRIPTION
**Pull request by jculvey**
Fixes #4023

**What this PR solves / how to test:**

This PR adds e2e coverage for angular. 

It also replaces the `predeploy` and `prestart` scripts in angular's package.json scripts as [pnpm doesn't support](https://pnpm.io/cli/run#differences-with-npm-run) `pre` and `post` scripts out of the box. 

This branch is based off of [this PR](https://github.com/cloudflare/workers-sdk/pull/4096) which refactors c3 e2e.

**Associated docs issue(s)/PR(s):**

- [insert associated docs issue(s)/PR(s)]

**Author has included the following, where applicable:**

- [ x ] Tests
- [ x ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer is to perform the following, as applicable:**

- Checked for inclusion of relevant tests
- Checked for inclusion of a relevant changeset
- Checked for creation of associated docs updates
- Manually pulled down the changes and spot-tested

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

**Review by dario-piotrowicz — APPROVED** [review]

**Comment by petebacondarwin** [comment]
This feels like it built on top of another PR?
Perhaps land that one first and then ping for another review?

**Comment by dario-piotrowicz** [comment]
> This feels like it built on top of another PR? Perhaps land that one first and then ping for another review?

yeah I reviewed both PRs and saw that the same logic was getting repeated, I just approved as I didn't want to be a hindrance 😅

**Comment by jculvey** [comment]
> This feels like it built on top of another PR? Perhaps land that one first and then ping for another review?

Yup, it is, as is [this one](https://github.com/cloudflare/workers-sdk/pull/4120). Since #4096 is a major refactor of e2e, not branching off of those changes would have caused some eventual merge conflicts that I wanted to avoid. 

I also didn't want to avoid touching anything e2e related while it was afloat since there's some high priority items. I honestly didn't think it was going to take this long to get approval for #4096.

**Comment by jculvey** [comment]
> Perhaps land that one first and then ping for another review?

@petebacondarwin done! I think this is ready for another look

File: packages/create-cloudflare/src/frameworks/angular/index.ts [hunk 1]
```diff
@@ -27,9 +27,8 @@ const generate = async (ctx: PagesGeneratorContext) => {
 };
 
 const configure = async (ctx: PagesGeneratorContext) => {
-	const cli = getFrameworkCli(ctx, false);
 	process.chdir(ctx.project.path);
-	await runCommand(`${npx} ${cli}@next analytics disable`, {
+	await runCommand(`${npx} ng analytics disable`, {
```
Comment (petebacondarwin) [inline packages/create-cloudflare/src/frameworks/angular/index.ts:31]: Perhaps `ng@latest`?

Comment (petebacondarwin) [reply packages/create-cloudflare/src/frameworks/angular/index.ts:31]: Or perhaps it doesn't really matter, since this is just disabling the analytics

**Review by petebacondarwin — APPROVED** [review]
