### PR TITLE
[vitest-pool-workers] Fix JSON require() in module fallback

### LINKED ISSUE #9822: require-ing a json file breaks vitest
### What versions & operating system are you using?

wrangler@4.22.0, @cloudflare/vitest-pool-workers

### Please provide a link to a minimal reproduction

https://github.com/threepointone/test-vitest-workers-json-require

### Describe the Bug

A `require` of a JSON file (NOT an `import`) will fail to run with `@cloudflare/vitest-pool-workers`, with a cryptic error message `SyntaxError: Unexpected token ':'`.

Why is this important? Sure, developers might use `import` to import JSON files, but third party dependencies (like the very popular `ajv`) do cjs builds, which end up `require`ing JSON files.

(like here: https://unpkg.com/ajv@8.17.1/dist/core.js)

This works when we do wrangler dev or vite dev, but fails when we run `vitest`.

## Repro

```bash
npm install && npm test
```

Either we should make it work with vitest/vitest-pool-workers, or we should have a better error.

Workaround:

add it to the `deps` section of `vitest.config.ts`

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by ksawaneh**
Fixes #9822.

`@cloudflare/vitest-pool-workers`'s module fallback service returned `.json` files as `commonJsModule` source. When a CommonJS dependency does `require("./data.json")`, `workerd` would try to parse the JSON as JavaScript and throw `SyntaxError: Unexpected token ':'`.

This change:
- Extends fallback resolution to consider `.json`
- Serves `.json` as an ES module wrapper that exports `JSON.parse(...)` (avoids object-literal `__proto__` prototype mutation)
- Adds a regression test covering CommonJS JSON require
- Adds a changeset for `@cloudflare/vitest-pool-workers`

---

- Tests
  - [x] Tests included/updated
  - [ ] Automated tests not possible - manual testing has been completed as follows:
  - [ ] Additional testing not necessary because:

Commands run:
- `pnpm check`
- `pnpm --filter @cloudflare/vitest-pool-workers run check:lint`
- `pnpm --filter @cloudflare/vitest-pool-workers run check:type`
- `pnpm exec vitest run test/json-require.test.ts` (from `packages/vitest-pool-workers`)

- Public documentation
  - [ ] Cloudflare docs PR(s):
  - [x] Documentation not necessary because: internal module fallback behavior + regression test, no docs change required

*A picture of a cute animal (not mandatory, but encouraged)*

 /\_/\
( o.o )
 > ^ <

---

<a href="https://app.devin.ai/review/cloudflare/workers-sdk/pull/11917">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

File: packages/vitest-pool-workers/src/pool/module-fallback.ts [hunk 1]
```diff
@@ -458,6 +460,25 @@ async function load(
 		filePath.endsWith(".mjs") ||
 		(filePath.endsWith(".js") && isWithinTypeModuleContext(filePath));
 
+	// JSON modules: CommonJS `require("./data.json")` is common in many widely
```
Comment (penalosa) [inline packages/vitest-pool-workers/src/pool/module-fallback.ts:463]: Is this specific to CommonJS? Looks like this code will work for an ESM import of json as well

File: packages/vitest-pool-workers/test/json-require.test.ts
Comment (penalosa) [inline packages/vitest-pool-workers/test/json-require.test.ts:1]: Thank you for adding this test! However, I think it might be more appropriate as a fixture test importing a real library that suffers from this (e.g. `mime-types`) in `fixtures/vitest-pool-workers-examples/module-resolution/src/index.ts`. Happy to add this if you'd like

File: .changeset/vitest-pool-workers-json-require.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@cloudflare/vitest-pool-workers": patch
+---
+
+Fix CommonJS `require()` of `.json` files in the module fallback service (avoids `SyntaxError: Unexpected token ':'`).
```
Comment (penalosa) [inline .changeset/vitest-pool-workers-json-require.md:5]: Does this work for ESM imports as well? Reading through the code it seems like it would

**Review by penalosa — COMMENTED** [review]
Thank you for this PR! It's looking good, just a couple of questions about comments and testing

File: packages/vitest-pool-workers/src/pool/module-fallback.ts [hunk 3]
```diff
@@ -458,6 +460,25 @@ async function load(
...
+	if (filePath.endsWith(".json")) {
+		const json = fs.readFileSync(filePath, "utf8");
+		const targetUrl = pathToFileURL(target);
+		const esModule = withSourceUrl(
+			`export default JSON.parse(${JSON.stringify(json)});`,
+			targetUrl
+		);
+		debuglog(logBase, "json:", filePath);
+		return buildModuleResponse(target, { esModule });
+	}
```
Comment (vicb) [inline packages/vitest-pool-workers/src/pool/module-fallback.ts:471]: Could we return a `json` module instead of converting json to esm?

```suggestion
	if (filePath.endsWith(".json")) {
		const json = fs.readFileSync(filePath, "utf8");
		return buildModuleResponse(target, { json });
	}
```

File: packages/vitest-pool-workers/src/pool/module-fallback.ts [hunk 4]
```diff
@@ -200,14 +200,16 @@ function withImportMetaUrl(contents: string, url: string | URL): string {
 	return contents.replaceAll("import.meta.url", JSON.stringify(url.toString()));
 }
 
-const jsExtensions = [".js", ".mjs", ".cjs"];
+// Extensions `workerd` won't resolve automatically, but Node.js will.
+// Note: `.json` is especially important for CommonJS `require()` chains.
+const moduleExtensions = [".js", ".mjs", ".cjs", ".json"];
```
Comment (vicb) [inline packages/vitest-pool-workers/src/pool/module-fallback.ts:205]: Not directly related to the changes in this PR but I think this is specific to `resolveMethod === "require"` and should not be used with "import".

Maybe we should create a separate issue to tackle that.

Comment (vicb) [reply packages/vitest-pool-workers/src/pool/module-fallback.ts:205]: Created https://github.com/cloudflare/workers-sdk/issues/12022 to follow up in a separate PR

**Comment by vicb** [comment]
Thanks for the PR @ksawaneh
