### PR TITLE
[wrangler] fix: prevent repeated reloads with circular service bindings

### LINKED ISSUE #4673: 🐛 BUG: circular service bindings cause dev server to repeatedly reload
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.22.1 Wrangler

### What version of Node are you using?

20.10.0

### What operating system are you using?

WSL

## Summary

After upgrading wrangler to 3.19.0 or higher, circular service dependencies cause the dev server to enter a reload loop. 3.18.0 seems to handle circular dependencies without any issues. Deploying the Workers also works as expected.

## Steps to reproduce

See the linked repo below for a reproduction with three Workers in a circular service binding configuration.

- Create two or more Workers with circular service bindings defined in `wrangler.toml`
- Run `wrangler dev` to start each Worker
- The `wrangler dev` logs show the dev server repeatedly reloading the Workers
- Downgrade wrangler to `3.18.0` and restart the Workers
- The Workers start successfully and requests process through all service bindings

## Expected behavior

3.18.0 behaves as expected, starting the Workers successfully and forwarding the requests through all service bindings (provided there are no cycles). Through some trial and error I found that 3.19.0 is where the behavior seems to have changed.

Thanks for all the effort towards making developing locally with Workers a joy ❤️ 

### Please provide a link to a minimal reproduction

https://github.com/rtbenfield/repro-wrangler-circular-services

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by mrbbot**
Fixes #4673.

**What this PR solves / how to test:**

`wrangler@3.19.0` introduced a bug where starting multiple `wrangler dev` sessions with service bindings to each other resulted in a reload loop. This change ensures Wrangler only reloads when dependent `wrangler dev` sessions start/stop, by registering workers in the dev registry with the URL of the proxy worker, not the user worker.

Using the user worker URL meant that when a dependent service was started, the original service picked up the change and restarted its user worker getting a new port. The original service registered this new port, which was picked up by the dependent service which itself restarted its user worker on a new port. This created a reload loop.

We're planning to slightly change how dev registry registration works as part of the later WaaL milestones. This should also help prevent these sorts of issues.

To test this, add the following to `fixtures/service-bindings-app`...

```toml
[[services]]
binding = "AYY"
service = 'a'
```

...then run `pnpm dev` in `fixtures/serivce-bindings-app`. Both `wrangler dev` sessions should start up without entering into a reload loop.

**Author has addressed the following:**

- Tests
  - [ ] Included
  - [x] Not necessary because: we currently skip most of our dev registry tests because of flakiness in CI. Once #4241 lands, we should re-enable these tests, including coverage for circular bindings like this.
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [x] Not necessary because: fixing a regression

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

File: packages/wrangler/src/dev/local.tsx [hunk 1]
```diff
@@ -157,8 +165,6 @@ function useLocalWorker(props: LocalProps) {
 			const newServer = new MiniflareServer();
 			miniflareServerRef.current = server = newServer;
 			server.addEventListener("reloaded", async (event) => {
-				await maybeRegisterLocalWorker(event, props.name);
```
Comment (petebacondarwin) [inline packages/wrangler/src/dev/local.tsx:160]: So this is the crux of this fix, right?

Comment (mrbbot) [reply packages/wrangler/src/dev/local.tsx:160]: Kinda, we still register the local worker, just with the URL of the proxy worker, not the user worker.

**Review by petebacondarwin — APPROVED** [review]
Nice! This works for me. I pulled it down and also tested locally.

**Comment by petebacondarwin** [comment]
To test this locally, I followed the procedure laid out in the PR description:

> To test this, add the following to fixtures/service-bindings-app...
> 
> ```
> [[services]]
> binding = "AYY"
> service = 'a'
> ```
> ...then run pnpm dev in fixtures/serivce-bindings-app. Both wrangler dev sessions should start up without entering into a reload loop.

**Comment by RamIdeas** [comment]
To add some context after discussion with @mrbbot:

This was a good fix to go in now but the _real_ fix is to register the ProxyWorker with the Dev Registry in startDevWorker Phase 2. This fix will be reverted once that is implemented 👍
