### PR TITLE
fix(wrangler): Display correct global flags in `wrangler pages --help`

### LINKED ISSUE #5725: 🐛 BUG: Some global flags listed by `wrangler pages --help` do not apply to Pages
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.52.0

### What version of Node are you using?

16.17.0

### What operating system and version are you using?

MacOS Sonoma 14.4.1

### Observed behavior
Running `wrangler pages --help` will list, amongst others, the following global flags:
Screenshot 2024-04-29 at 22 08 34

As per our [docs](https://developers.cloudflare.com/workers/wrangler/commands/), these global flags should apply to all commands. However, that is not actually the case, since flags such as `--config` or `--experimental-json-config` are not supported for Pages.

### Expected behavior
Running `wrangler pages --help` will list the correct supported flags, for a given command

### Steps to reproduce
Run `wrangler pages --help` in your terminal

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by CarmenPopoviciu**
## What this PR solves / how to test

Running `wrangler pages --help` will list, amongst others, the following global flags:

Screenshot 2024-05-13 at 19 18 22

Some of these global flags however, such as `--env`, `--config` or `--experimental-json-config`, are not supported by Pages, and therefore listing them as if they were gets users confused.

This PR ensures we only list the relevant flags when running `wrangler pages --help`

Fixes #5725.

**Before**
`wrangler --help`
Screenshot 2024-05-13 at 19 18 22

`wrangler pages --help`
Screenshot 2024-05-13 at 19 27 59

**After**
`wrangler --help`
Screenshot 2024-05-13 at 19 18 22

`wrangler pages --help`
Screenshot 2024-05-13 at 19 24 59

`wrangler pages dev --help`
Screenshot 2024-05-13 at 19 25 34

## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [ ] Required / Maybe required
  - [x] Not required because: changes are covered by unit tests and that's enough
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [x] Included
  - [ ] Not necessary because:
- Public documentation
  - [ ] TODO (before merge)
  - [x] Cloudflare docs PR(s): [<https://github.com/cloudflare/cloudflare-docs/pull/>...](https://github.com/cloudflare/cloudflare-docs/pull/14591)
  - [ ] Not necessary because:

### CODE REVIEW

File: packages/wrangler/src/pages/deploy.tsx [hunk 1]
```diff
@@ -93,6 +93,17 @@ export const Handler = async (args: PagesDeployArgs) => {
 		);
 	}
 
+	if (args.experimentalJsonConfig) {
+		throw new FatalError("Pages does not support `wrangler.json`", 1);
+	}
+
+	if (args.env) {
+		throw new FatalError(
+			"Pages does not support imperatively targeting a particular environment",
```
Comment (CarmenPopoviciu) [inline packages/wrangler/src/pages/deploy.tsx:102]: not sure if `imperatively targeting a particular environment` is the best wording here. Happy for suggestions

Comment (penalosa) [reply packages/wrangler/src/pages/deploy.tsx:102]: Maybe something like: `Pages does not support targeting an environment with the --env flag. Use the --branch flag to target your production or preview branch`?

**Review by penalosa — APPROVED** [review]

File: packages/wrangler/src/index.ts [hunk 2]
```diff
@@ -430,6 +430,10 @@ export function createCLIParser(argv: string[]) {
 
 	// pages
 	wrangler.command("pages", "⚡️ Configure Cloudflare Pages", (pagesYargs) => {
+		// Pages does not support the `--config`, `--experimental-json-config`,
+		// and `--env` flags, therefore hiding them from the global flags list.
+		pagesYargs.hide("config").hide("env").hide("experimental-json-config");
```
Comment (petebacondarwin) [inline packages/wrangler/src/index.ts:435]: TIL!

File: packages/wrangler/src/pages/deploy.tsx (hunk 1 above)
Comment (petebacondarwin) [reply packages/wrangler/src/pages/deploy.tsx:102]: Yeah @penalosa's wording sounds good. Makes it clear that it is the --env flag that is at fault here.

File: packages/wrangler/src/pages/dev.ts [hunk 3]
```diff
@@ -263,6 +263,17 @@ export const Handler = async (args: PagesDevArguments) => {
 		);
 	}
 
+	if (args.experimentalJsonConfig) {
+		throw new FatalError("Pages does not support `wrangler.json`", 1);
+	}
+
+	if (args.env) {
+		throw new FatalError(
+			"Pages does not support imperatively targeting a particular environment",
```
Comment (petebacondarwin) [inline packages/wrangler/src/pages/dev.ts:272]: Same here.

**Review by petebacondarwin — APPROVED** [review]
Subject to the wording change!
