### PR TITLE
[vitest-pool-workers] Suppress `CODE_MOVED` log spam from workerd

### LINKED ISSUE #12685: @cloudflare/vitest-pool-workers broken in macOS after upgrade
### What versions & operating system are you using?

- Wrangler: v4.69.0 (Previous version: 4.67.0)
- vitest: 3.2.4
- vite: 7.3.1
- @cloudflare/vitest-pool-workers: 0.12.18
- @cloudflare/vite-plugin: 1.25.6
- The workerd version - https://github.com/cloudflare/workerd/releases/tag/v1.20260305.0

### Please provide a link to a minimal reproduction

https://github.com/elct9620/gna

### Describe the Bug

When running `pnpm test` or `pnpm test:coverage`, the tests failed by workerd error. I have 2 projects has different errors.

- Both work correctly before the Wrangler upgrade
- Unable to rollback (one project update, then all project fails)

### Please provide any relevant error logs

Project 1 (Gna, Public):

- GitHub Action works correctly
- Need to use `pkill` to clean up `workerd`
- Run single test can pass

[project1.txt](https://github.com/user-attachments/files/25580356/project1.txt)

> [!NOTE]
> Enable `singleWorker` fix this issue. The issue may related to too many tests.

---

Project 2 (Private, no CI because GitLab Self-Hosted Runner in Container does not work)

- Test case contains CJK

[project2.txt](https://github.com/user-attachments/files/25580365/project2.txt)

### PR DESCRIPTION
**Pull request by penalosa**
Fixes #12685.

Miniflare's structured log handler already filters `CODE_MOVED for unknown code block` messages (an internal workerd diagnostic), but `vitest-pool-workers` uses a custom `handleRuntimeStdio` callback that bypasses the structured logs pipeline and pipes stderr directly to `process.stderr`. This adds the pattern to the pool's own ignore list.

---

- Tests
  - [ ] Tests included/updated
  - [ ] Automated tests not possible - manual testing has been completed as follows:
  - [x] Additional testing not necessary because: The change adds a string to an existing ignore list — the filtering mechanism is already well-tested by the existing entries.
- Public documentation
  - [ ] Cloudflare docs PR(s):
  - [x] Documentation not necessary because: Internal log filtering, no user-facing API change.

---

<a href="https://app.devin.ai/review/cloudflare/workers-sdk/pull/13070" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

**Comment by workers-devprod** [comment]
Codeowners approval required for this PR:
- ✅ @cloudflare/wrangler

<details><summary>Show detailed file reviewers</summary>


</details>

File: packages/vitest-pool-workers/src/pool/index.ts [hunk 1]
```diff
@@ -80,6 +80,9 @@ const ignoreMessages = [
 	"disconnected: operation canceled",
 	"disconnected: worker_do_not_log; Request failed due to internal error",
 	"disconnected: WebSocket was aborted",
+	// Internal workerd diagnostic, not relevant to application developers
+	// See: https://github.com/cloudflare/workerd/blob/d170f4d9b/src/workerd/jsg/setup.c%2B%2B#L566
```
Comment (penalosa) [inline packages/vitest-pool-workers/src/pool/index.ts]:
```suggestion
```
