### PR TITLE
[vitest-pool-workers] Suppress outputGateBroken stderr noise when testing Workflows

### LINKED ISSUE #12764: vitest-pool-workers: outputGateBroken stderr noise when testing Workflows
## What versions & operating system are you using?

```
  System:
    OS: macOS 26.3
    CPU: (12) arm64 Apple M3 Pro
    Memory: 1.20 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.8.0
    npm: 11.6.0
    pnpm: 10.28.2
  npmPackages:
    @cloudflare/vitest-pool-workers: 0.12.19
    wrangler: 4.70.0
```

## Please provide a link to a minimal reproduction

https://github.com/andrskr/vitest-pool-workers-outputgate-repro

## Describe the Bug

When testing any Cloudflare Workflow with `@cloudflare/vitest-pool-workers` and `introspectWorkflowInstance`, two `outputGateBroken` error lines are printed to stderr on every test run:

```
workerd/io/io-context.c++:436: info: uncaught exception; exception = workerd/api/actor-state.c++:1110: failed: broken.outputGateBroken; jsg.Error: Instance dispose
stack: 10471c188
```

The errors don't affect test results — all tests pass — but they add noise to test output and CI logs.

### Steps to reproduce

1. Clone the minimal reproduction repo:
   ```sh
   git clone https://github.com/andrskr/vitest-pool-workers-outputgate-repro.git
   cd vitest-pool-workers-outputgate-repro
   npm install
   ```
2. Run the tests:
   ```sh
   npx vitest run
   ```
3. Observe the `outputGateBroken` lines in stderr between `[vpw:info]` startup and the test results.

### Expected behavior

No errors or warnings should be printed to stderr when a Workflow test completes successfully.

### Actual behavior

Two identical `broken.outputGateBroken; jsg.Error: Instance dispose` lines are printed to stderr on every run, regardless of workflow complexity or test content.

### Notes

- The reproduction follows the [official Workflows testing guide](https://blog.cloudflare.com/better-testing-for-workflows/) and [write-your-first-test docs](https://developers.cloudflare.com/workers/testing/vitest-integration/write-your-first-test/) exactly.
- The workflow is trivial (two `step.do` calls, no sleeps, no external fetches, no mocking).
- The error appears to originate from workerd's Durable Object output gate disposal during test teardown (`actor-state.c++:1110`).
- The existing `handleRuntimeStdio` → `ignoreMessages` filter in `vitest-pool-workers` already suppresses similar known messages (`"disconnected: operation canceled"`, etc.), but `outputGateBroken` is not in that list.

## Please provide any relevant error logs

Full test output:

```
 RUN  v3.2.4 /private/tmp/workflow-test-project

[vpw:debug] Adding `enable_nodejs_tty_module` compatibility flag during tests as this feature is needed to support the Vitest runner.
[vpw:debug] Adding `enable_nodejs_fs_module` compatibility flag during tests as this feature is needed to support the Vitest runner.
[vpw:debug] Adding `enable_nodejs_http_modules` compatibility flag during tests as this feature is needed to support the Vitest runner.
[vpw:debug] Adding `enable_nodejs_perf_hooks_module` compatibility flag during tests as this feature is needed to support the Vitest runner.
[vpw:info] Starting isolated runtimes for vitest.config.ts...
[mf:warn] The latest compatibility date supported by the installed Cloudflare Workers Runtime is "2026-03-01",
but you've requested "2026-03-04". Falling back to "2026-03-01"...
workerd/io/io-context.c++:436: info: uncaught exception; exception = workerd/api/actor-state.c++:1110: failed: broken.outputGateBroken; jsg.Error: Instance dispose
stack: 10471c188
workerd/io/io-context.c++:436: info: uncaught exception; exception = workerd/api/actor-state.c++:1110: failed: broken.outputGateBroken; jsg.Error: Instance dispose
stack: 10471c188
 ✓ test/workflow.test.ts (2 tests) 33ms

 Test Files  1 passed (1)
      Tests  2 passed (2)
   Start at  20:51:36
   Duration  1.01s (transform 32ms, setup 0ms, collect 34ms, tests 33ms, environment 0ms, prepare 206ms)

[vpw:debug] Shutting down runtimes...
[vpw:debug] Disposing remote proxy sessions...
```

### PR DESCRIPTION
**Pull request by penalosa**
Fixes #12764.

When testing Cloudflare Workflows with `introspectWorkflowInstance`, workerd emits `broken.outputGateBroken; jsg.Error: Instance dispose` to stderr during test teardown as the Durable Object backing the Workflow instance is disposed. This is normal workerd behaviour — the output gate is broken as part of DO cleanup — but it was being forwarded to the user's stderr, adding noise to test output and CI logs.

The existing `ignoreMessages` filter in `handleRuntimeStdio` already suppresses similar known-benign workerd messages. This PR adds `"broken.outputGateBroken; jsg.Error: Instance dispose"` to that list.

---

- Tests
  - [ ] Tests included/updated
  - [ ] Automated tests not possible - manual testing has been completed as follows:
  - [x] Additional testing not necessary because: single-line filter addition matching an existing suppression pattern; the reproduction repo in the issue can be used to verify manually
- Public documentation
  - [x] Documentation not necessary because: internal noise suppression, no user-facing API change

---

<a href="https://app.devin.ai/review/cloudflare/workers-sdk/pull/13069" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

File: packages/vitest-pool-workers/src/pool/index.ts [hunk 1]
```diff
@@ -80,6 +80,9 @@ const ignoreMessages = [
 	"disconnected: operation canceled",
 	"disconnected: worker_do_not_log; Request failed due to internal error",
 	"disconnected: WebSocket was aborted",
+	// Output gate is broken during Durable Object (incl. Workflow) instance disposal at test
+	// teardown — this is normal workerd behaviour and not actionable by the user
```
Comment (penalosa) [inline packages/vitest-pool-workers/src/pool/index.ts]:
```suggestion
```

**Comment by workers-devprod** [comment]
Codeowners approval required for this PR:
- ✅ @cloudflare/wrangler

<details><summary>Show detailed file reviewers</summary>


</details>
