### PR TITLE
Service bindings in Pages

### LINKED ISSUE #3053: 🐛 BUG: `--service` options missing in `wrangler pages dev`
### Which Cloudflare product(s) does this pertain to?

Pages

### What version of `Wrangler` are you using?

2.15.1

### What operating system are you using?

Mac

### Describe the Bug

The documentation https://developers.cloudflare.com/pages/platform/functions/bindings/#interact-with-your-service-binding-locally tells to interact with a service you have to use the `--service` option in `wrangler pages dev`:

image

This option does not exist:

image

### PR DESCRIPTION
**Pull request by WalshyDev**
fixes #3053

### CODE REVIEW

File: packages/wrangler/src/pages/dev.tsx [hunk 1]
```diff
@@ -24,6 +24,10 @@ const DURABLE_OBJECTS_BINDING_REGEXP = new RegExp(
 	/^(?<binding>[^=]+)=(?<className>[^@\s]+)(@(?<scriptName>.*)$)?$/
 );
 
+const SERVICE_BINDING_REGEXP = new RegExp(
+	/^(?<binding>[^=]+)=(?<service>[^@\s]+)(@(?<environment>.*)$)?$/
```
Comment (GregBrimble) [inline packages/wrangler/src/pages/dev.tsx:28]: I'd double-check the environments bit here. Might be totally fine, but I wouldn't be surprised if there's weirdness where I need to do something like:

```
--service MyBinding=my-worker--local
```

instead of

```
--service MyBinding=my-worker@local
```

If there is anything funky, I'd suggest dropping support for passing in an environment right now, just until we can think over how we want them to work (esp. given environments v2).

`wrangler pages dev --do` Durable Objects don't support environments today because of this. Let's just make sure the solution works across the board.

**Comment by GregBrimble** [comment]
We have a fixture used for DOs which you could copy: https://github.com/cloudflare/wrangler2/tree/main/fixtures/external-durable-objects-app

File: packages/wrangler/src/pages/dev.tsx (hunk 1 above)
Comment (WalshyDev) [reply packages/wrangler/src/pages/dev.tsx:28]: Yep you're right, the environment gets appended onto the end
> "service-test-dev"
`wrangler dev --local --persist --env dev`

Should be easy to support, i'll do a quick try and if it fails I'll just leave it for now.

**Comment by rfire12** [comment]
@WalshyDev Will this be released any time soon? 

The documentation has been out of date for a while: 
- https://developers.cloudflare.com/pages/platform/functions/bindings/#interact-with-your-service-binding-locally
- https://github.com/cloudflare/cloudflare-docs/pull/5015

**Comment by JorritSalverda** [comment]
Would be brilliant if this gets released. Any ETA?

**Comment by code-poel** [comment]
Is there any quick work-around for being able to bind a worker to a page application locally in the mean time?

**Comment by petebacondarwin** [comment]
> Is there any quick work-around for being able to bind a worker to a page application locally in the mean time?

Could you move the shared logic that you want to service bind to into a separate Worker of its own, then service bind to it from the Pages project and from any other Workers where it is needed?

File: fixtures/external-service-bindings-app/package.json [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+	"private": true,
+	"description": "A test for external service bindings",
+	"scripts": {
+		"mod-a-dev": "wrangler dev module-worker-a/index.ts --local --port 8500",
+		"mod-b-dev": "wrangler dev module-worker-b/index.ts --local --port 8501",
+		"ser-a-dev": "wrangler dev service-worker-a/index.ts --local --port 8502",
+		"mod-c-dev": "wrangler dev module-worker-c/index.ts --local --port 8503 --env staging",
+		"mod-d-dev": "wrangler dev module-worker-d/index.ts --local --port 8504 --env production",
+		"pages-dev": "cd pages-functions-app && npx wrangler pages dev public --port 8505 --service MODULE_A_SERVICE=module-worker-a MODULE_B_SERVICE=module-worker-b SERVICE_A_SERVICE=service-worker-a STAGING_MODULE_C_SERVICE=module-worker-c@staging STAGING_MODULE_D_SERVICE=module-worker-d@staging",
+		"dev": "npx concurrently -s first -k 'npm run mod-a-dev' 'npm run mod-b-dev' 'npm run ser-a-dev' 'npm run mod-c-dev' 'npm run mod-c-dev' 'npm run pages-dev'",
```
Comment (GregBrimble) [inline fixtures/external-service-bindings-app/package.json:12]:
```suggestion
		"dev": "npx concurrently -s first -k 'npm run mod-a-dev' 'npm run mod-b-dev' 'npm run ser-a-dev' 'npm run mod-c-dev' 'npm run mod-d-dev' 'npm run pages-dev'",
```

File: .changeset/three-dolphins-float.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"wrangler": minor
+---
+
+add support for service bindings in `wrangler pages dev`
```
Comment (GregBrimble) [inline .changeset/three-dolphins-float.md:5]: Can we flesh this out a little with an example of `--service MY_BINDING=my-script`?

File: fixtures/external-service-bindings-app/package.json (hunk 2 above)
Comment (dario-piotrowicz) [reply fixtures/external-service-bindings-app/package.json]: 🤦 👍

File: packages/wrangler/src/pages/dev.ts [hunk 4]
```diff
@@ -144,6 +148,11 @@ export function Options(yargs: CommonYargsArgv) {
 				type: "array",
 				description: "R2 bucket to bind (--r2 R2_BINDING)",
 			},
+			service: {
+				type: "array",
+				description: "Service to bind (--service SERVICE=WORKER_NAME[ENVIRONMENT])",
```
Comment (GregBrimble) [inline packages/wrangler/src/pages/dev.ts:153]:
```suggestion
				description: "Service to bind (--service SERVICE=SCRIPT_NAME)",
```

I'd like to avoid calling out the environment bit until we figure out something a bit more holistic here. For example, how can I bind to a DO in another script which is using a different environment?

File: packages/wrangler/src/pages/dev.ts [hunk 5]
```diff
@@ -557,6 +567,32 @@ export const Handler = async ({
...
+						"Could not parse Service binding:",
+						serviceBinding.toString()
+					);
+					return;
+				}
+
+				// Envs get appended to the end of the name
+				let serviceName = service;
+				if (environment) {
+					serviceName = `${service}-${environment}`;
```
Comment (GregBrimble) [inline packages/wrangler/src/pages/dev.ts:586]: Might be worth logging a "environments are weird and not officially supported" message here until we nail this down.

**Review by GregBrimble — COMMENTED** [review]
Quick skim looks good, but need to go over it in a bit more detail later.

File: .changeset/three-dolphins-float.md (hunk 3 above)
Comment (dario-piotrowicz) [reply .changeset/three-dolphins-float.md:5]: sure 🙂👍

File: packages/wrangler/src/pages/dev.ts (hunk 4 above)
Comment (dario-piotrowicz) [reply packages/wrangler/src/pages/dev.ts:153]: I see... ok let's remove it

also `SCRIPT_NAME` feels very awkward to me here... but yeah I guess for consistency with the other args we can use that 😓

File: packages/wrangler/src/pages/dev.ts (hunk 5 above)
Comment (dario-piotrowicz) [reply packages/wrangler/src/pages/dev.ts]: I've added this warning:
Screenshot 2023-10-11 at 22 35 53

let me know if you think it's sufficient/appropriate 🙂

File: fixtures/external-service-bindings-app/package.json [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+				"esbuild-jest",
+				{
+					"sourcemap": true
+				}
+			]
+		},
+		"transformIgnorePatterns": [
+			"node_modules/(?!find-up|locate-path|p-locate|p-limit|yocto-queue|path-exists|execa|strip-final-newline|npm-run-path|path-key|onetime|mimic-fn|human-signals|is-stream)"
+		]
+	},
```
Comment (GregBrimble) [inline fixtures/external-service-bindings-app/package.json:33]: Is this actually used?

**Review by GregBrimble — APPROVED** [review]
Looks good, thanks for being patient and making all those refinements!

File: fixtures/external-service-bindings-app/package.json (hunk 6 above)
Comment (dario-piotrowicz) [reply fixtures/external-service-bindings-app/package.json]: no I don't think so, good catch, thanks! 😄

**Review by petebacondarwin — APPROVED** [review]
