### PR TITLE
fix: ensure `miniflare`/`wrangler` can source map in the same process

### LINKED ISSUE #4715: 🐛 BUG: Always see strange internal assertion error in debugger when I encounter an exception.
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.22.3

### What version of Node are you using?

20.9.0

### What operating system are you using?

Windows

### Describe the Bug

Whenever I'm running the debugger and I encounter an error I see the following output:

```
[wrangler:err] AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, import_assert5.default)(prepareStackTrace !== void 0)

    at getSourceMapper (C:\Users\Tom\Downloads\webapp\winter-tree-e15e\node_modules\miniflare\dist\src\index.js:5747:30)
    at getSourceMappedStack (C:\Users\Tom\Downloads\webapp\winter-tree-e15e\node_modules\miniflare\dist\src\index.js:5820:10)
    at reviveError (C:\Users\Tom\Downloads\webapp\winter-tree-e15e\node_modules\miniflare\dist\src\index.js:5854:17)
    at handlePrettyErrorRequest (C:\Users\Tom\Downloads\webapp\winter-tree-e15e\node_modules\miniflare\dist\src\index.js:5859:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async #handleLoopback (C:\Users\Tom\Downloads\webapp\winter-tree-e15e\node_modules\miniflare\dist\src\index.js:8572:20)
```

It never shows me the correct stack trace so it makes debugging very annoying.

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by mrbbot**
Fixes #4715.

**What this PR solves / how to test:**

Previously, if in a `wrangler dev` session you called `console.log()` and threw an unhandled error you'd see an error like `[ERR_ASSERTION]: The expression evaluated to a falsy value`. This change ensures you can do both of these things in the same session.

This broke when we switched from `source-map-support` to `@cspotcode/source-map-support` as part of #4423. `@cspotcode/source-map-support` has some additional code to share state between different instances of the module. In particular, if the module was loaded once, future calls to any new instance's `install()` function wouldn't set `Error.prepareStackTrace`, leading to this assertion error in either Miniflare or Wrangler (depending on which one installed support first). We want each instance of the module to be completely isolated, so this PR overrides `Symbol.for()` while we're loading the module to ensure isolated "shared" data: https://github.com/cspotcode/node-source-map-support/blob/69baeb8ccbf9f2a342c8575f21ac81f5d711eb81/source-map-support.js#L45-L48. An assertion has been added to ensure this assumption holds when we upgrade the package.

**Author has addressed the following:**

- Tests
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [x] Not necessary because: fixing a regression

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

File: packages/miniflare/src/plugins/core/errors/sourcemap.ts [hunk 1]
```diff
@@ -2,6 +2,36 @@ import assert from "assert";
...
+	const resolvedSupportPath = require.resolve("@cspotcode/source-map-support");
+
+	const originalSymbolFor = Symbol.for;
+	const originalSupport = require.cache[resolvedSupportPath];
+	try {
+		Symbol.for = (key) => {
+			// Make sure we only override the expected symbol. If we upgrade this
+			// package, and new symbols are used, this assertion will fail in tests.
+			assert.strictEqual(key, "source-map-support/sharedData");
+			return Symbol();
```
Comment (RamIdeas) [inline packages/miniflare/src/plugins/core/errors/sourcemap.ts:25]:
```suggestion
			return Symbol(key);
```

File: packages/miniflare/src/plugins/core/errors/sourcemap.ts [hunk 2]
```diff
@@ -2,6 +2,36 @@ import assert from "assert";
...
+export function getFreshSourceMapSupport(): typeof import("@cspotcode/source-map-support") {
+	const resolvedSupportPath = require.resolve("@cspotcode/source-map-support");
+
+	const originalSymbolFor = Symbol.for;
+	const originalSupport = require.cache[resolvedSupportPath];
+	try {
+		Symbol.for = (key) => {
+			// Make sure we only override the expected symbol. If we upgrade this
+			// package, and new symbols are used, this assertion will fail in tests.
+			assert.strictEqual(key, "source-map-support/sharedData");
```
Comment (RamIdeas) [inline packages/miniflare/src/plugins/core/errors/sourcemap.ts:24]: Should probably use an if-statement rather than an assertion to allow for other usage of `Symbol.for`

**Review by RamIdeas — APPROVED** [review]

File: packages/miniflare/src/plugins/core/errors/sourcemap.ts (hunk 2 above)
Comment (mrbbot) [reply packages/miniflare/src/plugins/core/errors/sourcemap.ts:28]: Discussed offline, added some additional comments to more clearly cover the intention of this assertion, and what to do in the future if it start's failing.
