### PR TITLE
[miniflare] fix: remove `__STATIC_CONTENT_MANIFEST` from module worker `env`

### LINKED ISSUE #4374: [Miniflare] `__STATIC_CONTENT_MANIFEST` should not be available on the environment for Module Workers
These lines were written in 9ce44ba to supply `__STATIC_CONTENT_MANIFEST` for Workers Sites in Service Worker mode:

https://github.com/cloudflare/miniflare/blob/e3673a5df09c98e674932d01ec5c14b3ce5becec/packages/sites/src/plugin.ts#L116C1-L119

However, [when using ES Modules, `__STATIC_CONTENT_MANIFEST` must be imported](https://github.com/cloudflare/kv-asset-handler#es-module-1). It never appears on the environment.

This behaviour mismatch doesn’t break anything in particular, but it can lead people developing in local-only to make incorrect assumptions about deployed behaviour (ex. https://github.com/remix-run/remix/blob/3f0ba3780c748782c31df2d19392909765a28f5d/templates/cloudflare-workers/server.ts#L14-L17).

### PR DESCRIPTION
**Pull request by mrbbot**
Fixes #4374.

**What this PR solves / how to test:**

When using Workers Sites with a module worker, the asset manifest must be imported from the `__STATIC_CONTENT_MANIFEST` virtual module. Miniflare provided this module, but also erroneously added `__STATIC_CONTENT_MANIFEST` to the `env` object too. Whilst this didn't break anything locally, it could cause users to develop Workers that ran locally, but not when deployed. This change ensures `env` doesn't contain `__STATIC_CONTENT_MANIFEST`.

To test this, run `wrangler dev` in `fixtures/sites-app` and verify `__STATIC_CONTENT_MANIFEST` doesn't appear in the `env` object.

**Author has addressed the following:**

- Tests
  - [x] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [x] Included
  - [ ] Not necessary because:
- Associated docs
  - [ ] Issue(s)/PR(s):
  - [x] Not necessary because: this was erroneous local only behaviour

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

File: packages/miniflare/test/fixtures/sites/modules.ts [hunk 1]
```diff
@@ -2,8 +2,19 @@ import { getAssetFromKV } from "@cloudflare/kv-asset-handler";
...
 
-export default <ExportedHandler<{ __STATIC_CONTENT: KVNamespace }>>{
+export default <
+	ExportedHandler<{
+		__STATIC_CONTENT: KVNamespace;
+		__STATIC_CONTENT_MANIFEST?: undefined;
+	}>
+>{
 	async fetch(request, env, ctx) {
+		if (env.__STATIC_CONTENT_MANIFEST !== undefined) {
```
Comment (RamIdeas) [inline packages/miniflare/test/fixtures/sites/modules.ts:12]: Do we not only want to assert env.__STATIC_CONTENT_MANIFEST is undefined but also that it is not on the env object at all?
```suggestion
		if ("__STATIC_CONTENT_MANIFEST" in env) {
```

**Review by RamIdeas — APPROVED** [review]
