### PR TITLE
Prevent spaces in names

### LINKED ISSUE #4229: 🐛 BUG: websocket connection closed before connection established
### Which Cloudflare product(s) does this pertain to?

Wrangler core

### What version(s) of the tool(s) are you using?

3.13.2 [wrangler]

### What version of Node are you using?

v20.8.0

### What operating system are you using?

Mac

### Describe the Bug
1. Initialize project with create-cloudflare
2. Run `wrangler dev`

Expected: Dev server does not crash

Actual: 
```
❯ npx wrangler dev
 ⛅️ wrangler 3.13.2
-------------------
⎔ Starting local server...
[mf:inf] Ready on http://0.0.0.0:62093
[mf:inf] - http://127.0.0.1:62093
[mf:inf] - http://10.10.4.163:62093
Waiting for connection...
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                                                                                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:29374
            throw a;
            ^

Error: WebSocket was closed before the connection was established
    at WebSocket2.close (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:107657:18)
    at close (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:127798:14)
    at /Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:127859:7
    at jh (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:28430:15)
    at exports2.unstable_runWithPriority (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:24402:16)
    at Pc (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:25050:16)
    at Qg (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:28393:18)
    at /Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:28382:13
    at V (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:24327:22)
    at Timeout.w [as _onTimeout] (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:24162:13)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/Users/foo/bar/node_modules/wrangler/wrangler-dist/cli.js:108144:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.8.0
```
### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by penalosa**
## What this PR solves / how to test

Fixes #4229
## Author has addressed the following

- Tests
  - [ ] TODO (before merge)
  - [ ] Included
  - [ ] Not necessary because:
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
  - [ ] TODO (before merge)
  - [ ] Included
  - [ ] Not necessary because:
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): <https://github.com/cloudflare/cloudflare-docs/pull/>...
  - [ ] Not necessary because:

### CODE REVIEW

File: packages/wrangler/src/config/validation-helpers.ts [hunk 1]
```diff
@@ -236,7 +236,7 @@ export const isString: ValidatorFn = (diagnostics, field, value) => {
  */
 export const isValidName: ValidatorFn = (diagnostics, field, value) => {
 	if (
-		(typeof value === "string" && /^$|^[a-z0-9_ ][a-z0-9-_ ]*$/.test(value)) ||
+		(typeof value === "string" && /^$|^[a-z0-9_][a-z0-9-_]*$/.test(value)) ||
```
Comment (andyjessop) [inline packages/wrangler/src/config/validation-helpers.ts:239]: Change looks good. Maybe a good time to add some unit tests here?

Comment (penalosa) [reply packages/wrangler/src/config/validation-helpers.ts:239]: I've adapted the existing test to ensure it catches this case

**Review by andyjessop — APPROVED** [review]
