### PR TITLE
fix: better handler malformed paths

### LINKED ISSUE #7611: URI malformed error with Workers Assets and malformed paths
If you send a request to the Assets server with a malformed URL, it throws an error like `Error: URIError: URI malformed`

This currently makes it easy to cause errors on Assets sites, like `https://developers.cloudflare.com/%A0`, or `https://placeholders.dev/%A0`.

### PR DESCRIPTION
**Pull request by Cherry**
Fixes #7611

This more gracefully handles malformed URLs and simply throws a 404 on them instead of the entire Worker throwing an exception.

---

- Tests
  - [ ] TODO (before merge)
  - [x] Tests included
  - [ ] Tests not necessary because:
- E2E Tests CI Job required? (Use "e2e" label or ask maintainer to run separately)
  - [ ] I don't know
  - [ ] Required
  - [x] Not required because: no e2e tests for this
- Public documentation
  - [ ] TODO (before merge)
  - [ ] Cloudflare docs PR(s): 
  - [x] Documentation not necessary because: no user-facing changes

### CODE REVIEW

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
I am not sure how this can happen in practice - i.e. whether it is possible to access a real asset via a malformed URL segment.

But I feel like we should just be passing through these invalid segments rather than 404ing.
So instead of this fix we just change `decodePath()` so that it is resilient there: catching the error for each segment and just returning the original string instead of the decoded one.

If there is no such asset, then it would still 404 but at least we are not potentially hiding a real asset.

**Comment by Cherry** [comment]
Good call, that makes sense, thanks Pete. I've updated the changes and tests to account for this more gracefully.

File: packages/workers-shared/asset-worker/src/handler.ts [hunk 1]
```diff
@@ -692,6 +700,14 @@ export const decodePath = (pathname: string) => {
 const encodePath = (pathname: string) => {
 	return pathname
 		.split("/")
-		.map((x) => encodeURIComponent(x))
+		.map((x) => {
+			let encoded;
+			try {
+				encoded = encodeURIComponent(x);
```
Comment (petebacondarwin) [inline packages/workers-shared/asset-worker/src/handler.ts:706]: Can encodeURIComponent actually throw?

Comment (Cherry) [reply packages/workers-shared/asset-worker/src/handler.ts:706]: If given something like a lone surrogate, yes:

`encodeURIComponent("\uD800")`

How likely/possible this is to happen in a URL? Probably not, but I felt like it couldn't hurt to wrap both.

**Review by petebacondarwin — APPROVED** [review]
