### PR TITLE
[miniflare] Make temp directory cleanup best-effort in `dispose()`

### LINKED ISSUE #10511: Vitest-pool-workers: failed to remove cache objects
### What versions & operating system are you using?

System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 4.02 GB / 15.81 GB
Binaries:
    Node: 22.17.1 - C:\root\nvm\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.9.2 - C:\root\nvm\nodejs\npm.CMD
npmPackages:
    @cloudflare/vitest-pool-workers: ^0.8.68 => 0.8.68
    @cloudflare/workers-types: ^4.20250829.0 => 4.20250829.0
    wrangler: ^4.33.1 => 4.33.1

### Please provide a link to a minimal reproduction

_No response_

### Describe the Bug

When running `vitest` on my windows computer, I see many logs stating it failed to remove cache objects. These are repeated for many times making it impossible for me to see all test results sometimes. When running on GitHub actions (action runs on `ubuntu-latest`), I don't see these logs. Something to either disable or hide these logs would work for me.

### Please provide any relevant error logs

vitest-pool-worker: Unable to remove temporary directory: Error: EBUSY: resource busy or locked, rmdir 'C:\Users\user\AppData\Local\Temp\miniflare-4cdfc3adc1efdd36e9c4005f21fc0e38\cache\miniflare-CacheObject'

Failed for `Cache`, `D1`, `KV` and `R2` objects

### PR DESCRIPTION
**Pull request by penalosa**
Fixes #10511.

On Windows, `workerd` may not release file handles immediately after `Runtime#dispose()` returns. When `Miniflare#dispose()` then tries to remove the temp directory, `fs.promises.rm` fails with `EBUSY` — and because this isn't caught, the error propagates to the caller (e.g. `vitest-pool-workers`), producing noisy errors in test output.

The temp directory lives in `os.tmpdir()`, so the OS will clean it up eventually. This makes the async cleanup path best-effort — matching the pattern the synchronous exit hook already uses.

---

- Tests
  - [ ] Tests included/updated
  - [ ] Automated tests not possible - manual testing has been completed as follows:
  - [x] Additional testing not necessary because: this is a Windows-specific error handling change — the cleanup itself is unchanged, it just no longer throws on failure
- Public documentation
  - [ ] Cloudflare docs PR(s):
  - [x] Documentation not necessary because: internal behaviour change

---

<a href="https://app.devin.ai/review/cloudflare/workers-sdk/pull/13078" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

**Comment by workers-devprod** [comment]
Codeowners approval required for this PR:
- ✅ @cloudflare/wrangler

<details><summary>Show detailed file reviewers</summary>


</details>

File: packages/miniflare/src/index.ts [hunk 1]
```diff
@@ -2818,7 +2808,12 @@ export class Miniflare {
 			await this.#runtime?.dispose();
 
 			await this.#stopLoopbackServer();
-			await removeDir(this.#tmpPath);
+			// Best-effort cleanup: on Windows, workerd may not release file handles
+			// immediately after disposal, causing EBUSY errors. The temp directory
+			// lives in os.tmpdir() so the OS will clean it up eventually.
+			try {
+				await removeDir(this.#tmpPath);
+			} catch {}
```
Comment (petebacondarwin) [inline packages/miniflare/src/index.ts]: Should this not be:


```suggestion
			removeDir(this.#tmpPath, { fireAndForget: true });
```

Comment (penalosa) [reply packages/miniflare/src/index.ts]: https://github.com/cloudflare/workers-sdk/pull/13078/commits/2e0ee78257251d349811feffc62a7816db37a80f
