### PR TITLE
C3: Fixing double prompt for ts during hello world worker creation

### LINKED ISSUE #3979: 🐛 BUG: C3 - Typescript response label shown twice when creating workers (minor bug)
### Which Cloudflare product(s) does this pertain to?

C3

### What version(s) of the tool(s) are you using?

C3 2.2.3

### What version of Node are you using?

16

### What operating system are you using?

Mac

### Describe the Bug

When creating a worker using C3 the response label for typescript is displayed twice (note that it is correctly asked only once)

For example:

Screenshot 2023-09-19 at 11 20 33

Screenshot 2023-09-19 at 11 21 02

### Please provide a link to a minimal reproduction

_No response_

### Please provide any relevant error logs

_No response_

### PR DESCRIPTION
**Pull request by jculvey**
Fixes #3979.

**What this PR solves / how to test:**

Fixes an issue in the "Hello World" worker creation workflow where the user is prompted for typescript twice:

268923065-fa36007c-7bc9-4e95-ba7b-330b40387a79

**Associated docs issue(s)/PR(s):**

- [insert associated docs issue(s)/PR(s)]

**Author has included the following, where applicable:**

- [ ] Tests
- [ x ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

**Reviewer is to perform the following, as applicable:**

- Checked for inclusion of relevant tests
- Checked for inclusion of a relevant changeset
- Checked for creation of associated docs updates
- Manually pulled down the changes and spot-tested

**Note for PR author:**

We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn from it.

### CODE REVIEW

File: packages/create-cloudflare/src/workers.ts [hunk 1]
```diff
@@ -34,6 +34,13 @@ export const runWorkersGenerator = async (args: C3Args) => {
 		args,
 	};
 
+	ctx.args.ts = await processArgument<boolean>(ctx.args, "ts", {
```
Comment (RamIdeas) [inline packages/create-cloudflare/src/workers.ts:37]: either `processArgument` should handle assigning the `args.x` value, ie:
```suggestion
	await processArgument<boolean>(ctx.args, "ts", {
```

or the pattern should be to call it with `??=`, ie:
```suggestion
	ctx.args.ts ??= await processArgument<boolean>(ctx.args, "ts", {
```

**Review by RamIdeas — APPROVED** [review]

File: packages/create-cloudflare/src/workers.ts (hunk 1 above)
Comment (jculvey) [reply packages/create-cloudflare/src/workers.ts:37]: Yeah, agreed this feels a little unwieldy still.

One of the important things `processArgument` does is render the `submit` state of the prompt for the question, so a user would see `yes Typescript` even if they passed the `--ts` flag. That's why `ctx.args.ts ??= await processArgument<boolean>(ctx.args, "ts", {` wouldn't work, since we do need it to evaluate.

I like the first alternative though. I'll make a separate PR to refactor this into an in-place operation instead of returning a value that we re-assign to the same object.
